### PR TITLE
Fixed tests for python 3.7

### PR DESCRIPTION
**Pull request by schlunma**
## Description

#1408 broke the tests for python 3.7, which are only tested for `main`. This should fix it.

@ESMValGroup/esmvaltool-coreteam would it maybe be possible to also run these tests on the feature branches so we immediately see that those fail and not only after the merge to `main`?

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
> would it maybe be possible to also run these tests on the feature branches so we immediately see that those fail and not only after the merge to main?

It would be possible, but a waste of computational resources and bad for the environment. It's quite rare for changes to break compatibility with older Python versions, I think this happens once or twice a year.

**Comment by schlunma** [comment]
Yeah, makes sense!

The 3.7 tests ran fine, I reverted the change in the workflow config file. Ready to merge from my side!

**Review by valeriupredoi — APPROVED** [review]
many thanks for fixing these, and thanks for looking at the Github Actions to find the actual fails - somebody is looking at the GA :partying_face:

**Comment by schlunma** [comment]
> many thanks for fixing these, and thanks for looking at the Github Actions to find the actual fails - somebody is looking at the GA partying_face

You can thank the mail that was sent to me by GitHub :smile:

**Pull request merged**
