### PR TITLE
Run fgco2 fix for all CESM2 models

### LINKED ISSUE #1107: Dataset problem: run fgco2 fix for all CESM2 models
**Describe the dataset issue**
A clear and concise description of what the problem with the data is is. Here are some guidelines that you can use
right out the box by filling in the blanks (note that, if needed we will assist you with writing a fix; also note that
if the problem is with a CMIP6 dataset, we will alert the ESGF and/or the model developers for them to fix the problem
in the long run; fixes for CMIP5 by the model developers are no longer possible):

- Project: CMIP6
- Full dataset description (fill out as many as you know, please):
  - dataset: `cesm2_fv2`, `cesm2_waccm`, `cesm2_waccm_fv2`
  - experiment: historical
  - mip: Omon
  - grid: gn
  - variable used: fgco2
- Problems encountered (please describe what the actual problems are: e.g. wrong standard name, issue with dimensions):
```
esmvalcore.cmor.check.CMORCheckError: There were errors in variable fgco2:
depth0m: does not exist
```
- Pointer to existing copy of data on ESGF node (it would be very useful if you could provide a physical
fullpath to the file(s) that are causing the problem, e.g. on CEDA Jasmin or DKRZ): 
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2-FV2/historical/r1i1p1f1/Omon/fgco2/gn/v20191120/fgco2_Omon_CESM2-FV2_historical_r1i1p1f1_gn_195001-199912.nc
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r1i1p1f1/Omon/fgco2/gn/v20190808/fgco2_Omon_CESM2-WACCM_historical_r1i1p1f1_gn_185001-201412.nc
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/NCAR/CESM2-WACCM-FV2/historical/r1i1p1f1/Omon/fgco2/gn/v20191120/fgco2_Omon_CESM2-WACCM-FV2_historical_r1i1p1f1_gn_195001-199912.nc
- Other notes and mentions:

**Assign the right people**
If you are already a member of the ESMValTool GitHub project, please assign Valeriu Predoi (valeriupredoi) and
Klaus Zimmermann (zklaus) to the issue. They will then check the issue raised and propagate it further to the
data model developers.

### PR DESCRIPTION
**Pull request by LisaBock**
## Description

Closes #1107. Adds 0m-depth coordinate for fgco2 in CESM2 models.

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by remi-kazeroni** [comment]
Tests added so this PR is now ready for review

**Review by bettina-gier — APPROVED** [review]
No scientific changes, but runs fine and output looks plausible.

**Comment by zklaus** [comment]
@LisaBock, could you please add a very brief description, make sure that all applicable boxes in the checklist are ticked, and all not-applicable boxes are removed or struck out?

**Comment by remi-kazeroni** [comment]
> 
> 
> @LisaBock, could you please add a very brief description, make sure that all applicable boxes in the checklist are ticked, and all not-applicable boxes are removed or struck out?

Are we fine to merge this PR or is there something still missing @zklaus?

**Review by zklaus — APPROVED** [review]

**Comment by zklaus** [comment]
Looks fine.

**Pull request merged**
