### PR TITLE
Machine-specific directories for auxiliary data in the `config-user.yml` file

### LINKED ISSUE #1266: Add paths to auxiliary data directories on Mistral and Jasmin to `config_user.yml`
**Is your feature request related to a problem? Please describe.**
A shared directory where auxiliary data are stored (shape files, ...) is available on Mistral. Its working is similar to the OBS and RAWOBS directories. This shared directory is also mirrored to Jasmin.
It would be great if the developers use these directories when adding new auxiliary data so that we avoid duplication and missing data to run recipes. 

**Would you be able to help out?**
To make people aware of this possibility, we could add the Mistral and Jasmin paths to auxiliary data to the `config_user.yml`.

### PR DESCRIPTION
**Pull request by remi-kazeroni**
## Description
This PR adds a path for the `auxiliary_data_dir` on Jasmin and Mistral. These are included in the "lines to uncomment" for each of the two machines. Not sure if these paths would be better placed below 
```yaml
# Auxiliary data directory (used for some additional datasets)
auxiliary_data_dir: ./auxiliary_data
```

Closes #1266 

Link to documentation: [https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html?highlight=auxiliary#user-configuration-file](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html?highlight=auxiliary#user-configuration-file)

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- ~~[ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added~~
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- ~~[ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~~
- ~~[ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date~~
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by remi-kazeroni** [comment]
Would it be useful to add something to the doc: [https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html?highlight=auxiliary#user-configuration-file](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html?highlight=auxiliary#user-configuration-file)?

**Review by axel-lauer — APPROVED** [review]
Look good. Thanks for adding!

**Comment by bouweandela** [comment]
> Would it be useful to add something to the doc: https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html?highlight=auxiliary#user-configuration-file?

Yes, that would be great! The documentation that is there now is not very clear, unfortunately.

**Review by valeriupredoi — APPROVED** [review]
cheers Remi, I have added some jabber about these dirs in the docs :grin:

**Comment by bouweandela** [comment]
I think it's fine like this, users will hopefully be smart enough to figure it out.

**Comment by remi-kazeroni** [comment]
> 
> 
> I think it's fine like this, users will hopefully be smart enough to figure it out.

Agreed. Then I think this is good be merged.

**Pull request merged**
