### PR TITLE
Python311-klaus

### PR DESCRIPTION
**Pull request by zklaus**
## Description

Closes #issue_number

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
Thanks, @valeriupredoi. To be honest, I am not sure the `conda run pip` does the right thing, because I think the `${CONDA_DEFAULT_ENV}` might not be set (correctly?) at that point. But anyway, the main thing is the setting of those env vars in the `conf.py`. It is a bit ugly, since I am basically guessing everything, but I have checked in the readthedocs sources that this is indeed the scheme they use, at least for now.

**Comment by valeriupredoi** [comment]
look at that! Docs build - awesome work, Klaus! That RTD env and its handling is "complicated" to say the least. You OK if I merge this in `python311` then close it - just so that we focus on fixing all stuff there, in one place

**Review by valeriupredoi — APPROVED** [review]
many thanks, Klaus!

**Comment by zklaus** [comment]
> look at that! Docs build - awesome work, Klaus! That RTD env and its handling is "complicated" to say the least. You OK if I merge this in `python311` then close it - just so that we focus on fixing all stuff there, in one place

Well, of course the intention was for this to go into that, but IMHO the closing of the PR was a bit premature. Now we are removing `CheckLevels` from the API documentation and the issue of `conda run` is unresolved. I guess I'll have to do new PRs to work on those. Perhaps a selective merge or cherry-picking for the features we consider ready is better in such a case?

**Comment by valeriupredoi** [comment]
no that's true - after the merge I went a bit like "yip, this should not have been merged with squash and branch deletion" - but I see you reopened and revived the branch which is what I was about to do, bud

**Pull request merged**
