### PR TITLE
Run tests in parallel and when building conda package

### LINKED ISSUE #663: python setup.py test is deprecated
So our documentation on running tests as well as the test scripts that run on CircleCi need to be updated.

### PR DESCRIPTION
**Pull request by bouweandela**
Run tests in parallel and when building conda package.

Also changes the test command to `pytest`, closes #663.

**Tasks**

-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.

### CODE REVIEW

**Comment by valeriupredoi** [comment]
but what in the world is going on with the install tests? Are we asking for too many threads?

**Comment by bouweandela** [comment]
Looks like the CircleCI docker containers actually report the number of cores available on their host machine.

**Comment by bouweandela** [comment]
@valeriupredoi I fixed the problem with too many test runners on CircleCI and changed the way we run tests in the process. Could you please have another look?

**Comment by valeriupredoi** [comment]
@bouweandela all good for me with the pinning done in https://github.com/ESMValGroup/ESMValTool/pull/1804 - do you want to set the pinning here too or I can do it :beer:

**Comment by valeriupredoi** [comment]
awesome! roll out @bouweandela :medal_military:

**Comment by bouweandela** [comment]
Thanks for reviewing @valeriupredoi!

**Pull request merged**
