### PR TITLE
Pin `flake8<4` to keep getting relevant error traces when tests fail with FLAKE8 issues

### LINKED ISSUE #1405: Pin `flake8<4` - running `pytest` tests with `--flake8` turned on may mask print statements that are necessary if test fails
A bunch of native Python errors - like undefined name/variable - are now picked up by Flake8 when running a pytest test - if those errors can be debugged via print statements that the test developer has purposefully put in the test for debugging, those print statements don't get flushed to stdout even if you change the `--capture` value when running pytest, because flake8 runs right at the very beginning and once it fails it discards every other call that follows in the test. I'd like to change this somehow, without having to turn off the `--flake8` flag, but I don't know how - any ideas?

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

@bouweandela and I have decided to pin flake8, so we stop getting garbage instead of actual FLAKE8 issues when tests fail with FLAKE8 issues

Closes #1405 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
This PR adds flake8 in places where it was not present before. That is surprising since we have been using it for a long time. Could you please double-check that there are no other places to add it and explain how it is being pulled in at the moment?

**Comment by valeriupredoi** [comment]
> This PR adds flake8 in places where it was not present before. That is surprising since we have been using it for a long time. Could you please double-check that there are no other places to add it and explain how it is being pulled in at the moment?

looking at this right now, man, am a bit confused but I'll figure my way round in a jiffy :+1:

**Comment by valeriupredoi** [comment]
OK Ive tested the syntax 'pytest-flake8>=1.0.6;flake8<4' and that don't work, now it's pinned in the test section, I think it's all fine now :+1:

**Comment by schlunma** [comment]
We already have a 2.5 milestone, right? I don't think we need a dedicated project for that.

**Comment by valeriupredoi** [comment]
ah gut then, no not a project, used the wrong term :grin:

**Comment by valeriupredoi** [comment]
we should get this in the sooner the better, that `_io.String` error instead of the actual flake8 problem is starting to get me :rage:

**Review by zklaus — APPROVED** [review]
Thanks, looking good. Could you please also:
- Check ESMValTool for the same requirement
- Read https://conda-forge.org/docs/maintainer/adding_pkgs.html#constraining-packages-at-runtime and let me know what you think how we should proceed on the feedstock
- Possibly open an issue and/or PR at the feedstock?

Thanks! :beers:

**Comment by valeriupredoi** [comment]
ace @zklaus :beer: The Tool PR for this is here https://github.com/ESMValGroup/ESMValTool/pull/2492 - I'll have a look at the feedstock situation now :+1:

**Comment by valeriupredoi** [comment]
this https://conda-forge.org/docs/maintainer/adding_pkgs.html#constraining-packages-at-runtime returns a Unable to connect in FF, in fact https://conda-forge.org/ seems to be down - even their Status is not loading, hope it be back :grin:

**Comment by valeriupredoi** [comment]
OK so the question is: do we want to restrict `flake8` in the conda-forge package - do we distribute the tests with the package and if so, do they actually get run? I'd say we should, and for that I think we just have to add the pin in the `test: requires:` section or maybe just add the recommended `run_constraint:` section in `test:` - I am not entirely sure what the difference would be - do you know, Klaus?

**Comment by valeriupredoi** [comment]
anyway I took the discussion here https://github.com/conda-forge/esmvalcore-feedstock/issues/15

**Pull request merged**
