### PR TITLE
Fix diagnostic filter

### LINKED ISSUE #712: --diagnostics option in CLI fails
**Describe the bug**
While testing another PR (ESMValGroup/ESMValTool#1585) for ESMValTool I noticed that the `--diagnostics` option in the new CLI does not seem to work. I tried

```
esmvaltool run ~/ESMValTool/esmvaltool/recipes/recipe_ecs_constraints.yml --diagnostics diag_x_volodin_cmip5 --config-file ~/config/mymodels.yml
```

and 

```
esmvaltool run ~/ESMValTool/esmvaltool/recipes/recipe_ecs_constraints.yml --config-file ~/config/mymodels.yml --diagnostics diag_x_volodin_cmip5
```

for [this](https://github.com/ESMValGroup/ESMValTool/blob/add_ecs_constraints/esmvaltool/recipes/recipe_ecs_constraints.yml) recipe.

**Output**

```
...
2020-07-14 08:55:48,077 UTC [17726] INFO    Creating diagnostic task diag_x_su_hur_cmip5/ecs_predictor
2020-07-14 08:55:48,077 UTC [17726] INFO    Creating diagnostic task diag_x_su_hur_cmip5/emergent_constraint
2020-07-14 08:55:48,094 UTC [17726] INFO    These tasks will be executed: 
2020-07-14 08:55:48,099 UTC [17726] INFO    Running 0 tasks using 0 processes
2020-07-14 08:55:48,277 UTC [17726] INFO    Maximum memory used (estimate): 0.2 GB
2020-07-14 08:55:48,277 UTC [17726] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2020-07-14 08:55:48,279 UTC [17726] ERROR   Program terminated abnormally, see stack trace below for more information
Traceback (most recent call last):
  File "/ESMValCore/esmvalcore/_main.py", line 428, in run
    fire.Fire(ESMValTool())
  File "/miniconda3/envs/mlr/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/miniconda3/envs/mlr/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/miniconda3/envs/mlr/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/ESMValCore/esmvalcore/_main.py", line 405, in run
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/ESMValCore/esmvalcore/_main.py", line 98, in process_recipe
    recipe.run()
  File "/ESMValCore/esmvalcore/_recipe.py", line 1358, in run
    run_tasks(self.tasks,
  File "/ESMValCore/esmvalcore/_task.py", line 643, in run_tasks
    _run_tasks_parallel(tasks, max_parallel_tasks)
  File "/ESMValCore/esmvalcore/_task.py", line 674, in _run_tasks_parallel
    with Pool(processes=max_parallel_tasks) as pool:
  File "/miniconda3/envs/mlr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/miniconda3/envs/mlr/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
2020-07-14 08:55:48,285 UTC [17726] INFO    If you suspect this is a bug or need help, please open an issue on https://github.com/ESMValGroup/ESMValTool/issues and attach the run/recipe_*.yml and run/main_log_debug.txt files from the output directory.
```

Please note this line: **`Running 0 tasks using 0 processes`**

Am I doing something wrong here? If not this needs to be fixed before the release of v2.0.0

### PR DESCRIPTION
**Pull request by jvegasbsc**
There is an issue with the diagnostics filter if you try to filter only one diagnostic (see #712 )

This pull request fixes it

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [ ] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [ ] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #712

### CODE REVIEW

**Comment by schlunma** [comment]
Tested successfully, thanks for the quick fix! :tada: I think you should merge this in `master` and not `v2.0.0`, Bouwe will cherry-pick this from master once this is merged.

**Comment by bouweandela** [comment]
I tried to test this, but how do I select two tasks?

I ran
```
$ esmvaltool run examples/recipe_python.yml --diagnostics diagnostic1/pr diagnostic1/script1
```
and the output was:
```
ERROR: Config file /home/bandela/src/esmvalgroup/esmvalcore/diagnostic1/script1 does not exist
ERROR:esmvalcore._main:Program terminated abnormally, see stack trace below for more information
Traceback (most recent call last):
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/_main.py", line 430, in run
    fire.Fire(ESMValTool())
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/bandela/conda/envs/esmvaltool/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/_main.py", line 366, in run
    cfg = read_config_user_file(config_file, recipe_name, kwargs)
  File "/home/bandela/src/esmvalgroup/esmvalcore/esmvalcore/_config.py", line 42, in read_config_user_file
    with open(config_file, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bandela/src/esmvalgroup/esmvalcore/diagnostic1/script1'
```

It looks like the second task is somehow interpreted as the config-user file?

**Comment by jvegasbsc** [comment]
>  how do I select two tasks?

Like this,

```bash
$ esmvaltool run examples/recipe_python.yml --diagnostics '("diagnostic1/pr", "diagnostic1/script")'
```
but I am going to modify it a bit so it also accepts
```bash
$ esmvaltool run examples/recipe_python.yml --diagnostics 'diagnostic1/pr diagnostic1/script'
```

**Comment by bouweandela** [comment]
Thanks! Could you also document that syntax somewhere?

**Comment by jvegasbsc** [comment]
> Thanks! Could you also document that syntax somewhere?

Yes.

Can you please test the branch locally? The tests run fine on my computer but fail in CircleCI, and I do not understand why

**Comment by bouweandela** [comment]
I think it's an old Python issue  #719

**Comment by bouweandela** [comment]
Merging this now, because I want to make the release today. Can you please make a new pull request to document how to use the feature?

**Pull request merged**
