### PR TITLE
Extension of ERA5 CMORizer (variable cl)

### PR DESCRIPTION
**Pull request by axel-lauer**
## Description

This PR adds variable cl (3-dim cloud fraction) to the ERA5 CMORizer. This variable is needed for the updated cloud diagnostics (PR https://github.com/ESMValGroup/ESMValTool/pull/2750).

The ESMValTool documentation and recipe_check_obs.yml are updated in the accompanying PR https://github.com/ESMValGroup/ESMValTool/pull/2952.

Docs: https://esmvaltool--1850.org.readthedocs.build/projects/ESMValCore/en/1850/quickstart/find_data.html#era5

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

### CODE REVIEW

**Review by remi-kazeroni — CHANGES_REQUESTED** [review]
Thanks for your contribution @axel-lauer! The code and fixes look good to me. I tested the code locally and it works as expected. I'm just realizing now that our ERA5 documentation is spread across the Core and the Tool... So we would need to add `cl` also here: https://github.com/ESMValGroup/ESMValCore/blob/main/doc/quickstart/find_data.rst#era5 Could you please add that?

**Comment by axel-lauer** [comment]
> Thanks for your contribution @axel-lauer! The code and fixes look good to me. I tested the code locally and it works as expected. I'm just realizing now that our ERA5 documentation is spread across the Core and the Tool... So we would need to add `cl` also here: https://github.com/ESMValGroup/ESMValCore/blob/main/doc/quickstart/find_data.rst#era5 Could you please add that?

Good point, I added "cl" to the documentation.

**Review by remi-kazeroni — APPROVED** [review]
Thanks Axel!

**Comment by schlunma** [comment]
Thanks both! :rocket:

**Pull request merged**
