### PR TITLE
Pin Python to 3.9 in environment.yml on CircleCI and skip mypy tests in conda build

### LINKED ISSUE #1166: Nightly tests on CircleCI are failing
The `install`, `develop`, and `conda_build` test [failed on CircleCI last night](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/4985/workflows/92577489-0597-4286-9bc7-3e6a0637ebbf). There appear to be two problems:
1) timeouts when creating the conda environment
2) Newer version of mypy with extra dependencies

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

This pull request fixes the problems with the nightly build on CircleCI.

- Use Python 3.9 to run the installation (from source installation and development installation) tests on CircleCI
- Skip mypy tests in conda build

Closes #1166

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
cheers @bouweandela - I was just about to do this but you beat me to the goal (3-2 haha :netherlands: ). But why hard pin for Python?

**Comment by bouweandela** [comment]
Because it takes forever to solve the environment, even with a 30 minute time limit the build takes too long: https://app.circleci.com/pipelines/github/ESMValGroup/ESMValTool/5004/workflows/fab7221e-8abd-4262-a7c6-006103ea9f63/jobs/46393

**Comment by valeriupredoi** [comment]
OK I know that's happening but we should not pin it everywhere for all the jobs (GA tests will struggle and we will lose the actual testing capability for anything lower than 3.9, virtually losing testing for supported versions, so might as well not even support them anymore). What happens if you just pin it in the `meta.yml/[build]` section?

**Comment by zklaus** [comment]
Is the pinning intended also only for the conda-build then? Perhaps in that case it would be better to change it in the meta.yaml?

**Comment by bouweandela** [comment]
No, the pinning is needed to do a development installation within a reasonable time. @valeriupredoi is right that doing it like this breaks the GitHub actions tests though.

**Comment by valeriupredoi** [comment]
it doesn't break them since the GA conda gets updated from the `envronment.yml`, so in effect it will update to a set of deps for python 3.9 across all tests, but we lose the testing capability for the lower Python we toot we support

**Comment by bouweandela** [comment]
I tried changing the build so it only pins Python to 3.9 for CircleCI, so at least the GitHub Actions tests continue to work. The problem remains though that a user doing a development installation of just the core will have to wait forever.

**Comment by valeriupredoi** [comment]
looking the [nightly](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore?branch=main) it seems to me that all goes fine apart from the conda build test and last night's test that indeed took more than 30min but two nights ago it took only 23min. Let's not pin Python, since we can start using the new lock file for these tests very soon anyway

**Comment by valeriupredoi** [comment]
> I tried changing the build so it only pins Python to 3.9 for CircleCI, so at least the GitHub Actions tests continue to work. The problem remains though that a user doing a development installation of just the core will have to wait forever.

we'll prompt the user to use the lock file if they experience delays, and we can plug that into Circle too :+1:

**Comment by valeriupredoi** [comment]
thanks Bouwe, I'm happy with this for now, can we merge so @zklaus can release the beast? (is it today?)

**Review by zklaus — APPROVED** [review]

**Pull request merged**
