### PR TITLE
Update filename template for obs4MIPs to better match filenames

### LINKED ISSUE #1859: obs4MIPs filename templates in config-developer.yml are wrong
The filename templates currently in config-developer.yml for the obs4MIPs project are
https://github.com/ESMValGroup/ESMValCore/blob/2e657fedb2a203acc406acded79b3f9028a6506f/esmvalcore/config-developer.yml#L112-L114

According to the [specification of the obs4MIPs DRS](https://esgf-node.llnl.gov/site_media/projects/obs4mips/ODSv2p1.pdf), the filename template is either
```
<variable_id>_<frequency>_<source_id>_<variant_label>_<grid_label>[_<time_range>].nc
```
or (legacy)
```
<variable>_<instrument>_<processing_level>_<processing version>_<start_date>-<end_date>.nc
```
so our template looks like the legacy template.

However, in the wild it looks like something like `{short_name}_*.nc` would be more appropriate. 
[Here is a list of all obs4MIPs files I found on ESGF](https://github.com/ESMValGroup/ESMValCore/files/10194227/obs4MIPs_files.txt)

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Closes #1859

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility) - issue in ESMValTool describing the incompatibility https://github.com/ESMValGroup/ESMValTool/issues/2974
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
@yukosaka @LisaBock This update will create an issue with the default RCAST configuration which stores everything in the same directory. Is that configuration still current?

**Review by valeriupredoi — APPROVED** [review]
looks very reasonable to me but I've not tested it, Do we not have a test case that downloads some 1-2 years of data in a temp dir?

**Comment by bouweandela** [comment]
You could try running any recipe that uses obs4MIPs data that you don't have on your computer

**Comment by bouweandela** [comment]
Thanks for checking @remi-kazeroni! It looks like there are two issues here. When I search ESGF for `pr` from the project `obs4MIPs` with this code:
```python
from esmvalcore.esgf import find_files
find_files(project='obs4MIPs', short_name='pr', dataset='*')
```
the following results are found:
```
[ESGFFile:obs4MIPs/GPCP-V1/2/v20180518/pr_GPCP-1DD_L3_v1.2_19961001-20110630.nc on hosts ['dpesgf03.nccs.nasa.gov'],
 ESGFFile:obs4MIPs/GPCP-V1/3/v20180519/pr_GPCP-1DD_L3_v1.3_19961001-20161231.nc on hosts ['dpesgf03.nccs.nasa.gov'],
 ESGFFile:obs4MIPs/GPCP-V2/2/v20180518/pr_GPCP-SG_L3_v2.2_197901-201312.nc on hosts ['dpesgf03.nccs.nasa.gov'],
 ESGFFile:obs4MIPs/GPCP-V2/3/v20180519/pr_GPCP-SG_L3_v2.3_197901-201710.nc on hosts ['dpesgf03.nccs.nasa.gov'],
 ESGFFile:obs4MIPs/TRMM/v20160613/pr_TRMM-L3_v7-7A_199801-201312.nc on hosts ['dpesgf03.nccs.nasa.gov'],
 ESGFFile:obs4MIPs/TRMM/v20160613/pr_TRMM-L3_v7A_200001010130-200001312230.nc on hosts ['dpesgf03.nccs.nasa.gov'],
 ESGFFile:obs4MIPs/TRMM/v20160613/pr_TRMM-L3_v7A_200002010130-200002292230.nc on hosts ['dpesgf03.nccs.nasa.gov'],
 ESGFFile:obs4MIPs/TRMM/v20160613/pr_TRMM-L3_v7A_200003010130-200003312230.nc on hosts ['dpesgf03.nccs.nasa.gov'],
 ...
```

So it looks like the dataset name in the recipe should be `'GPCP-V2.2'` or `'GPCP-V2.3'` instead of the [`'GPCP-SG'`](https://github.com/ESMValGroup/ESMValTool/blob/966b0a6a6c083b7c961747f0b878a49cb0def3cb/esmvaltool/recipes/recipe_quantilebias.yml#L24).

The other issue is that the dataset name contains a `.` and that is not handled correctly by the current code, so the data will be saved to the wrong path (note that the `.` in the dataset name `GPCP-V2.3` turns into directory `GPCP-V2/3`).

**Comment by remi-kazeroni** [comment]
Thanks for clarifying @bouweandela, makes sense to me. The PR is a good step in improving the support for `obs4MIPs` data. But I am not sure if ESMValTool users would be able to download many `obs4MIPs` datasets from ESGF during recipe runs. The reason is that many of the `obs4MIPs` dataset entries in our recipes do not follow the ESGF way of organizing the data. In particular, nearly all `obs4MIPs` datasets use a `version` that corresponds to a data version (from a publication, file metadata, data filename, ...) that is different from the ESGF version `vYYYYMMDD`. For example, the code:
```python
from esmvalcore.esgf import find_files
find_files(project='obs4MIPs', short_name='rsdt', dataset='*')
```

returns: 

```python
[ESGFFile:obs4MIPs/CERES-EBAF/v20160610/rsdt_CERES-EBAF_L3B_Ed2-8_200003-201404.nc on hosts ['dpesgf03.nccs.nasa.gov']]
```

But that is not downloaded since the version number in the [recipe](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/recipe_cmug_h2o.yml#L72) is set to `Ed2-8`:
```bash
FileNotFoundError: Requested versions Ed2-8 of file not found. Available files: [ESGFFile:obs4MIPs/CERES-EBAF/v20160610/rsdt_CERES-EBAF_L3B_Ed2-8_200003-201404.nc on hosts ['dpesgf03.nccs.nasa.gov']\
]
```

I am not sure if we should revise the handling of the `obs4MIPs` version numbers in the Core (here or in another PR) or if this is a task for recipe maintainers to update their recipes according to what's available on ESGF. Do you have an idea what we should do to further improve the Tool's capability to download `obs4MIPs` data?

**Comment by bouweandela** [comment]
I could make a pull request to update the dataset names and remove the invalid version numbers from the affected recipes. The [obs4MIPs specification](https://esgf-node.llnl.gov/site_media/projects/obs4mips/ODSv2p1.pdf) is from 2017, so the naming scheme in those recipes is considered "legacy" for over 5 years now. I think it's time we update those recipes so they are in line with the current specification. I created an issue to report this #2974.

**Review by remi-kazeroni — APPROVED** [review]
Thanks @bouweandela! Let's follow-up on this in the issue that you've just started in the Tool 👍

**Comment by bouweandela** [comment]
@ESMValGroup/technical-lead-development-team Could someone please do a final check and merge?

**Comment by valeriupredoi** [comment]
excellent work @bouweandela and @remi-kazeroni (especially since testing automagically happened w/o me lifting a single file haha)

**Comment by valeriupredoi** [comment]
guys I am getting this when running with the latest Core (the recipe is `recipe_validation.py`):
```
ESGFFile:obs4MIPs/CERES-EBAF/v20160610/rsdt_CERES-EBAF_L3B_Ed2-8_200003-201404.nc on hosts ['dpesgf03.nccs.nasa.gov']
2023-01-10 14:39:43,140 UTC [12009] INFO    Maximum memory used (estimate): 0.3 GB
2023-01-10 14:39:43,141 UTC [12009] INFO    Sampled every second. It may be inaccurate if short but high spikes in memory consumption occur.
2023-01-10 14:39:43,141 UTC [12009] ERROR   Program terminated abnormally, see stack trace below for more information:
Traceback (most recent call last):
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe.py", line 597, in _get_input_files
    check.data_availability(
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe_checks.py", line 143, in data_availability
    raise InputFilesNotFound(
esmvalcore.exceptions.InputFilesNotFound: Missing data for obs4MIPs: rsdt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/valeriu/ESMValCore/esmvalcore/_main.py", line 486, in run
    fire.Fire(ESMValTool())
  File "/home/valeriu/miniconda3/envs/esmvaltool-27/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/valeriu/miniconda3/envs/esmvaltool-27/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/valeriu/miniconda3/envs/esmvaltool-27/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/valeriu/ESMValCore/esmvalcore/_main.py", line 393, in run
    self._run(recipe, session)
  File "/home/valeriu/ESMValCore/esmvalcore/_main.py", line 433, in _run
    process_recipe(recipe_file=recipe, session=session)
  File "/home/valeriu/ESMValCore/esmvalcore/_main.py", line 124, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe.py", line 73, in read_recipe_file
    return Recipe(raw_recipe,
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe.py", line 1283, in __init__
    self.tasks = self.initialize_tasks() if initialize_tasks else None
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe.py", line 1892, in initialize_tasks
    tasks = self._create_tasks()
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe.py", line 1867, in _create_tasks
    new_tasks, failed = self._create_preprocessor_tasks(
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe.py", line 1827, in _create_preprocessor_tasks
    task = _get_preprocessor_task(
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe.py", line 1226, in _get_preprocessor_task
    derive_input = _get_derive_input_variables(variables, config_user)
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe.py", line 1188, in _get_derive_input_variables
    files = _get_input_files(var, config_user)[0]
  File "/home/valeriu/ESMValCore/esmvalcore/_recipe.py", line 606, in _get_input_files
    search_result = esgf.find_files(**variable)
  File "/home/valeriu/ESMValCore/esmvalcore/esgf/_search.py", line 346, in find_files
    return cached_search(**facets)
  File "/home/valeriu/ESMValCore/esmvalcore/esgf/_search.py", line 360, in cached_search
    files = select_latest_versions(files, facets.get('version'))
  File "/home/valeriu/ESMValCore/esmvalcore/esgf/_search.py", line 67, in select_latest_versions
    raise FileNotFoundError(
FileNotFoundError: Requested versions Ed2-7 of file not found. Available files: [ESGFFile:obs4MIPs/CERES-EBAF/v20160610/rsdt_CERES-EBAF_L3B_Ed2-8_200003-201404.nc on hosts ['dpesgf03.nccs.nasa.gov']]
```

whereas while running with core=2.7 it goes about and downloads all I need it to download from obs4mips places. Is this an effect of this PR?

**Comment by bouweandela** [comment]
No, it's an affect of another pr. You're requesting a version that doesn't exist on ESGF. Could you try removing the version facet or setting it to v20160610 instead of Ed2-7?

**Comment by valeriupredoi** [comment]
but why does it work with the older core=2.7.1 (released package) then - was the version not checked before?

**Comment by valeriupredoi** [comment]
setting that version in the recipe makes the show run indeed :partying_face:

**Comment by bouweandela** [comment]
> was the version not checked before?

Indeed it was not used when searching ESGF (and not locally either when the version tag in config-developer.yml was set to `{latestversion}`, you would just get the latest version regardless of what you asked for.

**Pull request merged**
