### PR TITLE
Adapt tests to new version of cf-units

### LINKED ISSUE #1655: Test failure due to change in cf-units
For a couple of days now, we have seen our tests fail. The problem stems from a change in the latest cf-units release where the handling of the `gregorian` and `standard` calendars was changed, namely SciTools/cf-units#205. This creates the failure in our tests where they find now the calendar to be `standard` instead of `gregorian`. The quick fix is to just change the tests to expect `standard`, but I have a lingering concern that other places like diag scripts may be surprised to find `standard` now.

This is similar to ESMValGroup/ESMValTool#2705.

### PR DESCRIPTION
**Pull request by zklaus**
## Description

This is a bugfix to address recent test failures due to a change in cf-units.

Closes #1655 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
This is a start to address recent test failures for the core similar to those in the tool that arise from the changes in cf-units.

I need help with two things: How to convert the `unittest.TestCase` derived classes in the cmip5 fix tests, and how to deal with the inevitable regression. @bouweandela or @schlunma, any ideas?

**Comment by schlunma** [comment]
Why do you want to get rid of `unittest.Testcase`? As an alternative for setup and teardown I would use [`fixtures`](https://docs.pytest.org/en/latest/explanation/fixtures.html#about-fixtures).

**Comment by schlunma** [comment]
Ah I see.

I think you could just define the fixture outside of the class and then use it inside the class like you would normally do. In addition you could add a [`scope='class'`](https://docs.pytest.org/en/latest/how-to/fixtures.html#scope-sharing-fixtures-across-classes-modules-packages-or-session) parameter to the fixture, but I don't think that's useful here. To mimic the behavior of `setUp` the default scope (fixture is destroyed after every test) should be the one to go.

**Comment by sloosvel** [comment]
Is this worth another release candidate?

**Comment by zklaus** [comment]
I would say so, yes. But it's your call. I am also not fully aware of other changes that may have happened since the last release candidate, but generally speaking, the release is expected to be identical to the last release candidate.

**Comment by valeriupredoi** [comment]
I think this needs to be included in the RC rather than straight into the release since all this calendars business is a source of major pain in the rear and can lead to some unwanted changes in the actual diagnostics' results. @zklaus would you have some time to polish this a bit more? If not I can take over from here, no problemo :beer:

**Comment by sloosvel** [comment]
No worries, I got a new branch to work on this. I will close this one.

**Comment by bouweandela** [comment]
For the upcoming relaese and to avoid a lot of last minute work, would it be an option to just pin cf-units to the version that we know works and that @sloosvel already ran all the tests with?

**Comment by valeriupredoi** [comment]
@bouweandela I think that's a very good idea indeed!

**Comment by zklaus** [comment]
> > Alright, I'm stepping off here. Release managers, feel free to continue with this branch or to start your own fixes.
> 
> And what is is that is left to be finished in here? It's quite surprising to see these kind of answers considering the kind of comments that I usually have to hear about my own "unfinished work".

It's the responsibility of the release managers to take care of the nightly tests. They have been broken for a week now, so I did the digging for the cause and how to fix it. I'm sorry if this came across as anything but helpful.

**Comment by sloosvel** [comment]
>It's the responsibility of the release managers to take care of the nightly tests. They have been broken for a week now, so I did the digging for the cause and how to fix it. I'm sorry if this came across as anything but helpful.

I know, but I had to finish running recipes for a release candidate that could have been avoided. In any case, everyone in favour of pinning then?

**Comment by valeriupredoi** [comment]
@sloosvel am pinning it as we speak :beer:

**Comment by valeriupredoi** [comment]
about the tests - we should think of a stricter policy while we're working on a RC or stable release, something like "thou shall not pass" if the tests fail

**Comment by zklaus** [comment]
@valeriupredoi, I am not sure what you mean, but perhaps that's a new issue/discussion?

**Comment by valeriupredoi** [comment]
> @valeriupredoi, I am not sure what you mean, but perhaps that's a new issue/discussion?

what I mean is to have a clause in the push to pypi that all GA tests have passed - ok maybe too strict - have the tests open an issue automatically if one test fails, and maybe turn that feature on only during release periods so we don't overkill?

**Comment by bouweandela** [comment]
> have the tests open an issue automatically if one test fails

I like that, there is probably a github action for that

**Comment by valeriupredoi** [comment]
@bouweandela there's a github action even for when you forget to turn on that github action :rofl:

**Pull request closed without merging**
