### PR TITLE
Consistently use dimension/coordinate names in VariableInfo.coordinates

### LINKED ISSUE #412: Coordinates of VariableInfo inconsistent
The `coordinates` attribute of the `esmvalcore.cmor.table.VariableInfo` class is a dictionary with for CMIP6 tables coordinate axis as keys and for CMIP5 tables coordinate names as keys. This is inconsistent and confusing.

This issue was reported by @bascrezee in https://github.com/ESMValGroup/ESMValTool/pull/1338#discussion_r345899097

### PR DESCRIPTION
**Pull request by bouweandela**
Closes #412

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) to fix the ERA-Interim CMORizer and add the link below

Related to https://github.com/ESMValGroup/ESMValTool/pull/1338

### CODE REVIEW

**Comment by bascrezee** [comment]
Thanks @bouweandela. Testing this now in combination with https://github.com/ESMValGroup/ESMValTool/pull/1338/ Looking good so far.

**Comment by mattiarighi** [comment]
Any other recipe/cmorizer that could be affected?

**Comment by bouweandela** [comment]
Yes, I'll make the associated pull request.

**Comment by bouweandela** [comment]
It looks like only the ERA-Interim CMORizer was affected, I adjusted https://github.com/ESMValGroup/ESMValTool/pull/1338 so it works both with and without this pull request.

**Pull request merged**
