### PR TITLE
Include `-` in allowed characters for bibtex references

### LINKED ISSUE #2092: Reference bibtex filenames can only contain the characters that match `\w` regex
Issue reported by @alistairsellar

> Could you have a look at the following warnings from [`main_log.txt`](https://esmvaltool.dkrz.de/shared/esmvaltool/esmvalbot-output/autoassess_soilmoisture_obs_fly-litxq94v/recipe_autoassess_landsurface_soilmoisture_20230613_071633/run/main_log.txt)?
> 
> > WARNING [20879] The reference file /mnt/esmvaltool_disk2/esmvalbot-work/esmvalbotwork-autoassess_soilmoisture_obs_fly-litxq94v/ESMValTool/esmvaltool/references/soilmoisture.bibtex does not exist, citation information incomplete.
> > WARNING [20879] The reference file /mnt/esmvaltool_disk2/esmvalbot-work/esmvalbotwork-autoassess_soilmoisture_obs_fly-litxq94v/ESMValTool/esmvaltool/references/esacci.bibtex does not exist, citation information incomplete.
> > WARNING [20879] No provenance information was written to /mnt/esmvaltool_disk2/shared/esmvaltool/esmvalbot-output/autoassess_soilmoisture_obs_fly-litxq94v/recipe_autoassess_landsurface_soilmoisture_20230613_071633/run/plot_standard/plot_landsurf_soilmoisture/diagnostic_provenance.yml. Unable to record provenance for files created by diagnostic script

I believe that there is a parsing error somewhere. I'm referencing `esacci-soilmoisture` in my diag_script and recipe for consistency with file names and bibtex label: `esmvaltool/references/esacci-soilmoisture.bibtex`, but it is looking for separate references for `esacci` and `soilmoisture` implying that it has been split on `-` into separate ids. I can get rid of the warnings by remving the `-` from file name and references, but then it would be inconsistent with the other `references/esacci-*.bibtex` files. What do you reckon?

_Originally posted by @alistairsellar in https://github.com/ESMValGroup/ESMValTool/issues/3197#issuecomment-1589813326_

### PR DESCRIPTION
**Pull request by alistairsellar**
## Description

Very small change that correctly handles bibtex references that include `-`, as is the case for many bibtex files in `esmvaltool/references`.
Closes #2092 
Required to fix warnings arising from https://github.com/ESMValGroup/ESMValTool/pull/3197#issuecomment-1589813326

Link to documentation: https://esmvaltool--2097.org.readthedocs.build/projects/ESMValCore/en/2097/ (no change)

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] ~~Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~~
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by alistairsellar** [comment]
Hi @bouweandela here is the PR for the parsing bug #2092. Please could you review?

I've marked as 2.9 but appreciate the Core deadline for that has passed, so understand if it gets bumped to 2.10.

**Comment by bouweandela** [comment]
Thanks @alistairsellar! I've added a unit test for you. It looks like there were no unit tests for the module yet, so I started it in a new file.

**Comment by alistairsellar** [comment]
> Thanks @alistairsellar! I've added a unit test for you. It looks like there were no unit tests for the module yet, so I started it in a new file.

Thanks @bouweandela! Nice to see how a unit test can be added for such a simple change - this had not occurred to me as something that was even applicable for this change, but of course it is.

**Comment by alistairsellar** [comment]
Thanks @schlunma and @bouweandela!

**Pull request merged**
