### PR TITLE
Find various fx files for OBS projects for preprocessor masking

### PR DESCRIPTION
**Pull request by valeriupredoi**
Should solve #296

### CODE REVIEW

**Comment by valeriupredoi** [comment]
OK tested with ERA-Interim files, works fine! Can someone pls test :beer:

**Comment by valeriupredoi** [comment]
tested with #210 (ie with stock OBS fx file names and all the rest of that PR) and it works a-ok :beer:

**Comment by valeriupredoi** [comment]
@mattiarighi since you are at https://github.com/ESMValGroup/ESMValTool/pull/1310 maybe you can test this one real quick in conjunction with those tests and approve pls? :heart:

**Comment by mattiarighi** [comment]
That's what I'm doing right now :beer:

**Comment by valeriupredoi** [comment]
> That's what I'm doing right now beer

you are a sweeatpea :1st_place_medal:

**Comment by mattiarighi** [comment]
Tested as part of [#1310](https://github.com/ESMValGroup/ESMValTool/pull/1310), seems to work as expected.

**Comment by mattiarighi** [comment]
I can do that with `NSIDC` and `PIOMAS`.
Will do once done with the branch by Ruth.

**Comment by valeriupredoi** [comment]
You the bestest :beer:

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom

**Comment by mattiarighi** [comment]
This should be tested together with [#1272](https://github.com/ESMValGroup/ESMValTool/pull/1272), which itself needs #210. Right?

**Comment by valeriupredoi** [comment]
Yes, I tested it with an hoc merge of #210, works fine, it is idependent of
that PR so merging can happen at any time, no conflicts either

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom

**Comment by mattiarighi** [comment]
Actually if you use the `default` drs for `OBS` that PR is quite important.

**Comment by valeriupredoi** [comment]
Hmmm, yes, but who uses that :grin:

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom

**Comment by mattiarighi** [comment]
Tested successfully within [#1272](https://github.com/ESMValGroup/ESMValTool/pull/1272) (see details [here](https://github.com/ESMValGroup/ESMValTool/pull/1272#issuecomment-540642047)).

**Comment by valeriupredoi** [comment]
push, push, push :baby_symbol:

**Comment by mattiarighi** [comment]
@bascrezee did you already test this?

**Comment by bascrezee** [comment]
Yes, I just tested and it works.

**Pull request merged**
