### PR TITLE
Fix DRS for IPSLCM : split attribute 'freq' into : 'out' and 'freq'

### PR DESCRIPTION
**Pull request by senesis**
## Description

    For datasets using project ISLCM, instead of writing e.g. :
      `out: Analyse/TS_MO'`
    one should now write :
      `out: Analyse, freq: TS_MO`

    This is mainly in order to avoid side effects when creating output
    directories based on attributes value

Link to documentation: https://esmvaltool--1304.org.readthedocs.build/projects/ESMValCore/en/1304/develop/fixing_data.html#ipsl-cm6

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do : Not done because assume interested individuals are very few

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance). 
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available : Yes,, applies to technical doc only, see https://esmvaltool--1304.org.readthedocs.build/projects/ESMValCore/en/1304/develop/fixing_data.html#ipsl-cm6
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added. No
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility). No (recipes have to be modified if they use project IPSLCM), but user base for this feature is still small and limited to IPSL, and the information will be forwarded 
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly. N/A
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
cheers @senesis - I have no way to test this though, but it's probably better to replace the nondescript `out` key with `outdir` or something like that (`out-type` maybe?) - it's a bit better for readability :+1:

**Comment by valeriupredoi** [comment]
oh and it would also need a test before merging

**Comment by senesis** [comment]
> ... it's probably better to replace the nondescript `out` key with `outdir` or something like that (`out-type` maybe?) - it's a bit better for readability +1

Actually, label `out` is coined at IPSL , even if it is far from self-explaining ...

**Comment by senesis** [comment]
> oh and it would also need a test before merging

Such a test, using the actual project description, would mean adding a test data file in a directory such as 

> /thredds/tgcc/store/p86caub/IPSLCM6/PROD/historical/CM61-LR-hist-03.1950/ATM/Output/MO/CM61-LR-hist-03.1950_18500101_18591231_1M_histmth.nc

Would it be OK ?

**Comment by valeriupredoi** [comment]
@senesis my apologies, I should have been more explicit when I menationed the test - a dummy file with that correct specific path is enough to be added in the [data finder test set](https://github.com/ESMValGroup/ESMValCore/blob/main/tests/integration/data_finder.yml) and then an actual test that finds that file should be added in the[data finder integration test](https://github.com/ESMValGroup/ESMValCore/blob/main/tests/integration/test_data_finder.py) - no actual data, just monkey patches :monkey:

**Comment by valeriupredoi** [comment]
@senesis tell you what, I just checked the test facility for different drs's in config-developer and it looks like we are missing a bunch of test cases (for native6, obs4MIPs etc) so let's get this in without a test and I'll create an issue for those other drs's (including this one). @zklaus we can get this in for 2.4 after all :beer:

**Pull request merged**
