### PR TITLE
Added fixes for hybrid level coordinates of CESM2 models

### PR DESCRIPTION
**Pull request by schlunma**
This PR adds fixes for `cl`, `cli` and `clw` for the CESM2 models.

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes ESMValGroup/ESMValTool#1903.

### CODE REVIEW

**Comment by zklaus** [comment]
I don't think the diagnosis is correct. I explained this in some detail [in the issue](https://github.com/ESMValGroup/ESMValCore/issues/883#issuecomment-734214000). The gist is: Thanks to the `formula_terms` attribute `lev` **is** `a` and thus is absolutely used for the calculation.

**Comment by schlunma** [comment]
Yes @zklaus, for the datasets shown in #883 (with hybrid height) you're absolutely right, apologies for that.

I jumped to conclusions here: I only analyzed datasets with **hybrid pressure** coordinates, which show the behavior I explain in the description of this PR: for example, CESM2 fails with

```
esmvalcore.cmor.check.CMORCheckError: There were errors in variable cl:
lev: units should be 1, not hPa
 lev: has values < valid_min = 0.0
```

The dataset looks like this:

```
netcdf cl_Amon_CESM2_historical_r10i1p1f1_gn_185001-189912 {
dimensions:
        lat = 192 ;
        nbnd = 2 ;
        lon = 288 ;
        lev = 32 ;
        time = UNLIMITED ; // (600 currently)
variables:
        float cl(time, lev, lat, lon) ;
                cl:_FillValue = 1.e+20f ;
                cl:cell_measures = "area: areacella" ;
                cl:cell_methods = "area: time: mean" ;
                cl:comment = "Includes both large-scale and convective cloud." ;
                cl:coordinates = "time lev lat lon" ;
                cl:description = "Includes both large-scale and convective cloud." ;
                cl:frequency = "mon" ;
                cl:id = "cl" ;
                cl:long_name = "Percentage Cloud Cover" ;
                cl:mipTable = "Amon" ;
                cl:missing_value = 1.e+20 ;
                cl:out_name = "cl" ;
                cl:prov = "Amon ((isd.003))" ;
                cl:realm = "atmos" ;
                cl:standard_name = "cloud_area_fraction_in_atmosphere_layer" ;
                cl:time = "time" ;
                cl:time_label = "time-mean" ;
                cl:time_title = "Temporal mean" ;
                cl:title = "Percentage Cloud Cover" ;
                cl:type = "real" ;
                cl:units = "%" ;
                cl:variable_id = "cl" ;
        float ps(time, lat, lon) ;
                ps:long_name = "surface_air_pressure" ;
                ps:units = "Pa" ;
        float p0 ;
                p0:long_name = "vertical coordinate formula term: reference pressure" ;
                p0:units = "Pa" ;
        double a(lev) ;
                a:bounds = "a_bnds" ;
                a:long_name = "vertical coordinate formula term: a(k)" ;
        double b(lev) ;
                b:bounds = "b_bnds" ;
                b:long_name = "vertical coordinate formula term: b(k)" ;
        double lat(lat) ;
                lat:axis = "Y" ;
                lat:bounds = "lat_bnds" ;
                lat:standard_name = "latitude" ;
                lat:title = "Latitude" ;
                lat:type = "double" ;
                lat:units = "degrees_north" ;
                lat:valid_max = 90. ;
                lat:valid_min = -90. ;
        double lev(lev) ;
                lev:axis = "Z" ;
                lev:bounds = "lev_bnds" ;
                lev:positive = "up" ;
                lev:standard_name = "alevel" ;
                lev:title = "atmospheric model level" ;
                lev:type = "double" ;
                lev:units = "hPa" ;
        double lon(lon) ;
                lon:axis = "X" ;
                lon:bounds = "lon_bnds" ;
                lon:standard_name = "longitude" ;
                lon:title = "Longitude" ;
                lon:type = "double" ;
                lon:units = "degrees_east" ;
                lon:valid_max = 360. ;
                lon:valid_min = 0. ;
        double time(time) ;
                time:axis = "T" ;
                time:bounds = "time_bnds" ;
                time:standard_name = "time" ;
                time:title = "time" ;
                time:type = "double" ;
                time:units = "days since 0001-01-01 00:00:00" ;
                time:calendar = "noleap" ;
        double time_bnds(time, nbnd) ;
                time_bnds:calendar = "noleap" ;
                time_bnds:units = "days since 0001-01-01 00:00:00" ;
        double b_bnds(lev, nbnd) ;
                b_bnds:long_name = "vertical coordinate formula term: b(k+1/2)" ;
        double lat_bnds(lat, nbnd) ;
                lat_bnds:units = "degrees_north" ;
        double lon_bnds(lon, nbnd) ;
                lon_bnds:units = "degrees_east" ;
        double lev_bnds(lev, nbnd) ;
                lev_bnds:formula = "p = a*p0 + b*ps" ;
                lev_bnds:formula_terms = "p0: p0 a: a_bnds b: b_bnds ps: ps" ;
                lev_bnds:standard_name = "atmosphere_hybrid_sigma_pressure_coordinate" ;
                lev_bnds:units = "hPa" ;
        double a_bnds(lev, nbnd) ;
                a_bnds:long_name = "vertical coordinate formula term: a(k+1/2)" ;
```

Please note that the `formula_terms` attribute is missing for `lev`, which we add through a fix. However, for the bounds it reads: `p0: p0 a: a_bnds b: b_bnds ps: ps`, so `lev` is **not** used.

So I think the issue I describe here only applies for the the hybrid pressure coordinate, not for the hybrid height coordinate, so I will remove this from the PR here. However, as described in #883 there is still an issue with these hybrid height coordinates, since the recipe describe there works when only a single dataset is used, but **may** fail when 5 of them are used together.

(Sorry for the slow response, since mistral is down today I had to download the corresponding datasets to my local machine).

**Comment by schlunma** [comment]
When #883 is solved then maybe we can solve this with a fix after all, because I think only the 4 CESM models are really suffering from this issue (due to #883 I saw this for 4 additional models, which were apparently false positives).

Let's wait for @sloosvel to fix #883. After that I will have a look which datasets are really affected.

**Comment by valeriupredoi** [comment]
OK adding #859 and its sister #515 to this to be closed - can I confirm we **do need** fixes for those CESM2 olevs in cm? :beer:

**Comment by schlunma** [comment]
> OK adding #859 and its sister #515 to this to be closed - can I confirm we **do need** fixes for those CESM2 olevs in cm? beer

I only found theses issues I mentioned here in the atmosphere coordinate, but I would not at all be surprised if the ocean coordinates are messed up, too :smile:

**Comment by valeriupredoi** [comment]
aye, what's the worst it can happen if I write a fix - make the fishes and ocean people happy :+1:

**Comment by schlunma** [comment]
Okay, with @sloosvel's fix (#886) I can now confirm that at least 5 CMIP6 models suffer from the issue described here:

- CAS-ESM2-0 (`/mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP6_DKRZ/CMIP/CAS/CAS-ESM2-0/historical/r1i1p1f1/Amon/cl/gn/v20200302/cl_Amon_CAS-ESM2-0_historical_r1i1p1f1_gn_185001-201412.nc`)
- CESM2 (`/mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP6_DKRZ/CMIP/NCAR/CESM2/historical/r1i1p1f1/Amon/cl/gn/v20190308/cl_Amon_CESM2_historical_r1i1p1f1_gn_185001-201412.nc`)
- CESM2-FV2 (`/mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP6_DKRZ/CMIP/NCAR/CESM2-FV2/historical/r1i1p1f1/Amon/cl/gn/v20191120/cl_Amon_CESM2-FV2_historical_r1i1p1f1_gn_200001-201412.nc`)
- CESM2-WACCM (`/mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP6_DKRZ/CMIP/NCAR/CESM2-WACCM/historical/r1i1p1f1/Amon/cl/gn/v20190415/cl_Amon_CESM2-WACCM_historical_r1i1p1f1_gn_185001-201412.nc`)
- CESM2-WACCM-FV2 (`/mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP6_DKRZ/CMIP/NCAR/CESM2-WACCM-FV2/historical/r1i1p1f1/Amon/cl/gn/v20191120/cl_Amon_CESM2-WACCM-FV2_historical_r1i1p1f1_gn_200001-201412.nc`)

I can confirm that the `lev` coordinate values are not used in any of these datasets (`lev:formula_terms = "p0: p0 a: a b: b ps: ps"`) and take values from -1000 to 1000 hPa (but they should be between 0 and 1 and have units of 1).

How should we proceed here? Since I still have no idea how to fix these datasets correctly, I propose to do it similarly to the changes I made in this PR. I think it is safe to exclude the values of coordinate `atmosphere_hybrid_sigma_pressure_coordinate` from the checks. Additional support for that is given by the CMOR table, in which `lev` is not used for the creation of `air_pressure`:

https://github.com/ESMValGroup/ESMValCore/blob/c07e280274ef00aba2ad12969e22ca43660d5d5d/esmvalcore/cmor/tables/cmip6/Tables/CMIP6_coordinate.json#L2019

In contrast, for `atmosphere_hybrid_height_coordinate`, `lev` is explicitely used:

https://github.com/ESMValGroup/ESMValCore/blob/c07e280274ef00aba2ad12969e22ca43660d5d5d/esmvalcore/cmor/tables/cmip6/Tables/CMIP6_coordinate.json#L722

**Review by axel-lauer — APPROVED** [review]
Looks fine to me. This is a good approach to be able to work with the affected model datasets as we are not able to provide "fixes" for this issue for the affected models. Without this fix, some variables from these models could not be processed.

**Review by zklaus — CHANGES_REQUESTED** [review]
I am still in the process of evaluation. My findings so far: The data from the CESM models are all broken. The `lev` coordinate has an invalid standard name that does not refer to a parametric coordinate, the `lev` bounds use a different coordinate system from the `lev` coordinate itself.

As such, those models need to be fixed independently from any action suggested in this PR.

That leaves us with only the CAS model. I have not finished looking into that.

As such, at the moment it is unclear if this PR will address an actual problem.

**Comment by axel-lauer** [comment]
@zklaus In addition to the CESM models and CAS mentioned here, I also encountered this problem with the following models when processing variable clw: UKESM1-0-LL, KACE-1-0-G, ACCESS-ESM1-5, ACCESS-CM2, HadGEM3-GC31-LL. All of these models (including the CESM models and CAS) could be processed correctly before introducing the "lev check".

**Comment by schlunma** [comment]
@axel-lauer These models have hybrid height coordinates and should work now after the merge of #886.

However, I do not agree with you here @zklaus. This PR addresses a problem that does not allow the processing of datasets anymore that have been successfully used before. We are aware the the CESM2 models need fixes (we already implemented them) and successfully used `cl` data from CAS-ESM2-0, CESM2, CESM2-FV2 and CESM2-WACCM for an accepted publication.

Since the `lev` coord is not used in the final datasets, see

https://github.com/ESMValGroup/ESMValCore/blob/c07e280274ef00aba2ad12969e22ca43660d5d5d/esmvalcore/cmor/tables/cmip6/Tables/CMIP6_coordinate.json#L2019

we did not address it in the fixes.

I could of course provide a "fix" for this coordinate by simply linearly mapping the values `[-999, 0]` to the range `[0, 1]`, but would this be more correct than before? What's the point of fixing something that is not used on the final output and we also don't know how to fix?

**Comment by zklaus** [comment]
Following @schlunma's comment, I assume that only CESM and CAS are open. If this is not correct, please mention any other models that remain problematic here.

The point is not to fix something that isn't used. The point is that we have two potential sources of height information and we seem not to be able to reconcile them with one another. If that is true, we don't know if they have been used successfully before. We only know that they have been used before and that the tests have done exactly what they are supposed to do: Uncover problematic data. If it is not true, and we can reconcile the two sources of information, then we can write a simple fix. For the CESM models, there is nothing in the files that ties the parametric coordinates to the data field and several of the coordinate variables are defective.

So whatever the correct resolution of these problems is (and it may well be that you used the correct height information in the end), this seems to be a problem with this specific data and as such, I don't think we should deactivate the check generally.

**Comment by ruthlorenz** [comment]
If this is an issue with the data which could (potentially) be solved by the modelling group it should be reported to them. We have done this in the past and the modelling groups are generally happy to be informed and try to fix things if they can. They then also add the information here [https://errata.es-doc.org/static/index.html](url) so other people have a chance of knowing these issues.

**Comment by schlunma** [comment]
I think I found a solution to this problem:

As stated in [Appendix D](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#parametric-v-coord) of the CF conventions, "the hybrid sigma-pressure coordinate for level k is defined as a(k)+b(k) or ap(k)/p0+b(k), as appropriate".

I checked this, and it is true for most CMIP6 models (the ones differing are the CESM2 models, the CAS model and 1 other model where there are numerical inconsistencies). This should allow us to calculate the correct values for the `atmosphere_hybrid_sigma_pressure_coordinate` for CESM2 and CAS in a fix, which will solve this problem. I will open a PR on Monday.

However, I really think that in some very specific cases it might not be useful or user-friendly to check all nitty gritty aspects of the CMOR table when there is a scientific justification. In this specific case, the height information was always given (by the formula which does **NOT** depend on `atmosphere_hybrid_sigma_pressure_coordinate`) and **unique**, so checking the values of the `atmosphere_hybrid_sigma_pressure_coordinate` is really not useful. It probably took me now a day now to get an idea how to "fix" a dataset that is not wrong from a scientific point of view, which is kind of annoying.

**Comment by sloosvel** [comment]
>As stated in Appendix D of the CF conventions, "the hybrid sigma-pressure coordinate for level k is defined as a(k)+b(k) or ap(k)/p0+b(k), as appropriate".

That was pointed out in #840. Back in the day I tried summing a+b and I got coordinate values that match those of other models, so if that works for you, we can add this type of fix instead of skipping them. Copying the values from a model with the right coordinate as a fix would not be that bad either.

**Comment by schlunma** [comment]
Will re-open soon, this was automatically closed by force-pushing the current master to it (so I can have a fresh start on this branch).

**Comment by schlunma** [comment]
I added the fix for the CESM2 models according to the link that @sloosvel (I didn't see that back then, sorry). Unfortunately the CAS model is not available on mistral anymore, so I cannot test this.

@sloosvel can you do a technical review, please?

@axel-lauer can you do a scientific review, please? I used this recipe for testing:

[recipe_test_cl_cli_clw.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/6063010/recipe_test_cl_cli_clw.yml.txt)

**Review by sloosvel — APPROVED** [review]
I could only run the CESM2 dataset, as the others are missing on jasmin, but the fix looks good to me.

**Review by axel-lauer — CHANGES_REQUESTED** [review]
I have tried this fix and it produces results that look good when using no preprocessor. When using e.g. the following preprocessor to convert the data to altitude levels (same happens for pressure levels), only the lowermost level contains valid values while all other levels contain only missing values:
```  ppa40:
    extract_levels:
      levels: {cmor_table: CMIP6, coordinate: alt40}
      coordinate: altitude
      scheme: linear
```
This behavior differs from the results obtained using the current master branch (with `--check_level=ignore` to get the tool to process cl, cli or clw from CESM2). With the master branch, all altitude / pressure levels contain valid values.

I currently do not understand why this happens, but I think this might need some more investigation before this fix can be merged.

**Comment by schlunma** [comment]
That is really strange....having a look at this right now!

**Review by axel-lauer — APPROVED** [review]
After talking to @schlunma I redid the tests with a clean version of this branch (fix_hybrid_lev_coords). This solved the problem, the results now look good and as expected. It seems the problem I reported yesterday was caused by a somewhat screwed up version of my local repository copy. Sorry about that. This fix can be merged now!

**Comment by schlunma** [comment]
@zklaus can you either approve the changes or dismiss you review? Merging is blocked because you requested changes on the original version of this PR which is completely outdated now.

**Comment by axel-lauer** [comment]
We have positive reviews and we need this PR now for further work. Since the PR changed in a way that the changes requested by @zklaus for an earlier version do not apply any more, I think merging this now is fine.

**Pull request merged**
