### PR TITLE
Version2 preprocessor convert units

### PR DESCRIPTION
**Pull request by zklaus**
Port of ESMValGroup/ESMValTool#976

### CODE REVIEW

**Comment by bouweandela** [comment]
Could you fix the merge conflict? i also think there should be a reference to this new function in the recipe documentation.

**Comment by zklaus** [comment]
@mattiarighi am I right that the correct place for the documentation now would be in `ESMValCore/doc/sphinx/source/esmvalcore/preprocessor.inc` and if so, is there a particular order or place where this should be added?

**Comment by mattiarighi** [comment]
I created a table of contents for the preprocessor in [#1135](https://github.com/ESMValGroup/ESMValTool/pull/1135) and I put unit conversion at the end.
But the PR is not yet merged.

**Comment by zklaus** [comment]
I think this is ready. @bouweandela , could you have a look please?

**Comment by mattiarighi** [comment]
This should be merged before the beta release, if possible.

**Pull request merged**
