### PR TITLE
Fixes for sos and siconc of BCC models

### LINKED ISSUE #1089: Dataset problem: Issues with latitude and longitude for sos and siconc of BCCs CMIP6 models
**Describe the dataset issue**
This is the same as #537 or #748 but for the variables `sos` and `siconc` (model `BCC-ESM1` for the latter only).

- Pointer to existing copy of data on ESGF node (it would be very useful if you could provide a physical
fullpath to the file(s) that are causing the problem, e.g. on CEDA Jasmin or DKRZ):
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/BCC/BCC-CSM2-MR/historical/r1i1p1f1/Omon/sos/gn/v20181126/sos_Omon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/BCC/BCC-CSM2-MR/historical/r1i1p1f1/SImon/siconc/gn/v20200218/siconc_SImon_BCC-CSM2-MR_historical_r1i1p1f1_gn_185001-201412.nc
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/BCC/BCC-ESM1/historical/r1i1p1f1/Omon/sos/gn/v20181129/sos_Omon_BCC-ESM1_historical_r1i1p1f1_gn_185001-201412.nc
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/BCC/BCC-ESM1/historical/r1i1p1f1/SImon/siconc/gn/v20200218/siconc_SImon_BCC-ESM1_historical_r1i1p1f1_gn_185001-201412.nc

### PR DESCRIPTION
**Pull request by remi-kazeroni**
## Description

Fixes for `sos` and `siconc` of `BCC-ESM1` model and `sos` of `BCC-CSM2` model. 

Closes #1089 

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
Hi @remi-kazeroni, I just opened a PR that fixes the fix that is used here (#1092). Once this is merged the fixes you introduce here are as simple as 

```py
Sos = OceanFixGrid
Siconc = OceanFixGrid
```

Would it be okay for you to wait with this PR until #1092 is merged? I will review it as soon as possible.

If this is really urgent I can have a look at it right now and adapt #1092 accordingly, but I think the other way round is easier :smile:

**Comment by remi-kazeroni** [comment]
> Hi @remi-kazeroni, I just opened a PR that fixes the fix that is used here (#1092). Once this is merged the fixes you introduce here are as simple as
> 
> ```python
> Sos = OceanFixGrid
> Siconc = OceanFixGrid
> ```
> 
> Would it be okay for you to wait with this PR until #1092 is merged? I will review it as soon as possible.
> 
> If this is really urgent I can have a look at it right now and adapt #1092 accordingly, but I think the other way round is easier 😄

Hi @schlunma, thanks for offering to review this PR. I agree it makes totally sense to wait until #1092 is merged and then adapt this PR by using the `OceanFixGrid` for the variables needed here. This PR is not super urgent but the sooner, the better 👍

**Comment by schlunma** [comment]
Hi @remi-kazeroni, #1092 has been merged, so you can proceed with this PR :+1:

As I said, I think the fixes can be covered with

```py
Sos = OceanFixGrid
```

and the tests similar to this:

https://github.com/ESMValGroup/ESMValCore/blob/66dd7bd2e5750c193b73056e430cd9577660e5fe/tests/integration/cmor/_fixes/cmip6/test_bcc_esm1.py#L43-L51

**Review by valeriupredoi — APPROVED** [review]
nice work @remi-kazeroni and @schlunma :beer:

**Review by schlunma — APPROVED** [review]

**Pull request merged**
