### PR TITLE
Use smarter (units-aware) weights

### LINKED ISSUE #708: Global total air sea flux of CO2 removed
The derived variable  Global total air sera flux of CO2,  `gtfgco2`, is a CRUCIAL measurement of the earth system, and was mistakenly removed in PR #418 during the Christmas break. The changes in pr #418 were pushed without testing their actual functionality. 

This functionality is now missing and can't be reproduced using the previously suggested `area_statistics` and `convert_units` preprocessors. This is because `area_statistics` miscalculates the units, and iris's `convert_units` can't be used to change units with different dimensions. 

This field is also included in the second v2 paper, so this problem really needs to be fixed. 

**Describe the bug**
A clear and concise description of what the bug is. If you are developing a new diagnostic script, please provide a link to the code/branch on GitHub that you are working in.

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory

### LINKED ISSUE #1613: Smarter area weighted sum
Follows comment made [here](https://github.com/ESMValGroup/ESMValCore/pull/1574#issuecomment-1123428679) (other issues could also be spun out of that comment). 

**Is your feature request related to a problem? Please describe.**

Currently, when doing an area-weighted sum, the units are not changed. They should be multiplied with area ** 2.

**Would you be able to help out?**

Yes, but this would not be a backwards compatible change so I would need guidance.

### PR DESCRIPTION
**Pull request by schlunma**
## Description

Since [version 3.5.0](https://scitools-iris.readthedocs.io/en/latest/whatsnew/3.5.html#v3-5-27-apr-2023), iris allows the usage of cell measures (and a lot of other objects) as weights. This has the great benefit that units in statistical calculations are handled properly, e.g., for an area-weighted sum, resulting units are multiplied by `m2`.

In addition, this PR adds type hints for all functions of the affected modules.

Closes #1613
Closes #708

Link to documentation:
- https://esmvaltool--2139.org.readthedocs.build/projects/ESMValCore/en/2139/recipe/preprocessor.html#area-statistics
- https://esmvaltool--2139.org.readthedocs.build/projects/ESMValCore/en/2139/recipe/preprocessor.html#climate-statistics
- https://esmvaltool--2139.org.readthedocs.build/projects/ESMValCore/en/2139/recipe/preprocessor.html#axis-statistics
- https://esmvaltool--2139.org.readthedocs.build/projects/ESMValCore/en/2139/recipe/preprocessor.html#depth-integration

## Backwards-compatibility

The changes of these PR are **NOT** backwards-compatible. Since this PR fixes calculations that have been scientifically wrong in previous versions, no deprecation cycle is used. The following preprocessors are affected:

|Preprocessor|Affected option|Old behavior|New behavior|Affected recipe(s)|
|---|---|---|---|---|
|`area_statistics`|`operator='sum'`|Cube units remained, e.g., `kg m-2 s-1`|Cube units are multiplied by `m2`, e.g., `kg s-1`|[recipe_wenzel16nat](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/recipe_wenzel16nat.yml), [recipe_wenzel14jgr](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/recipe_wenzel14jgr.yml)|
|`climate_statistics`|`period='full'` and `operator='sum'`|Cube units remained, e.g., `kg m-2 s-1`|Cube units are multiplied by time units, e.g., `kg m-2`|-|
|`axis_statistics`|`operator='sum'`|Cube units remained, e.g., `kg m-2 s-1`|Cube units are multiplied by coordinate units, e.g., `kg m-1 s-1`|-|
|`depth_integration`|all|Cube units remained, e.g., `kg m-2 s-1`|Cube units are multiplied by coordinate units, e.g., `kg m-1 s-1`|[recipe_ocean_example](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/recipe_ocean_example.yml)|

In addition, there has been a bug in `climate_statistics`, which lead to a wrong calculation of weighted sums if the weights are equal for all time points. These are the relevant lines of code: 

https://github.com/ESMValGroup/ESMValCore/blob/1abaf8effe007250382c3fa9ee5f60160f1d4e95/esmvalcore/preprocessor/_time.py#L740-L746

While this simplification is correct for calculating means and RMSE, the weighted sum actually differs in both cases. Thus, we need to always consider the weights here, regardless if they are equal or not. This PR fixes that.

~I will test all affected recipes and open corresponding PR in ESMValTool if any changes are necessary.~

EDIT: I tested all affected recipes; they run fine with minimal changes (https://github.com/ESMValGroup/ESMValTool/pull/3300).

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] ~Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)~ (see note above)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] ~All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful~ (I think `assert` in production code is [fine ](https://stackoverflow.com/questions/17732/when-should-assertions-stay-in-production-code) to make other developers aware of something; this is not intended to catch errors by users)

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
this is a very nice PR and introduced functionality, very cool, @schlunma :beer: Proper testing too :medal_military: (I don't see any reason) but do we expect any changes in results for recipes that use this set of preprocessors? Also, were there any distinct changes in performance you might have noticed? Cheers!

**Comment by valeriupredoi** [comment]
PS: I meant actual result changes, not if the recipes just run. I guess we could find that out at v2.10 release time - which reminds me, maybe we should curate a list of PRs that may lead to changes in results and have that at hand when testing for a release

**Comment by schlunma** [comment]
Good point!

- [recipe_wenzel16nat](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/recipe_wenzel16nat.yml): no change (needs https://github.com/ESMValGroup/ESMValTool/pull/3300).
- [recipe_wenzel14jgr](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/recipe_wenzel14jgr.yml): no change (needs https://github.com/ESMValGroup/ESMValTool/pull/3300).
- [recipe_ocean_example](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/recipe_ocean_example.yml): the units of the plots of `diag_depthInt_1` change from `K` `K m`, but I think these new units are correct (@ledm please correct me if I am wrong here). Does **not** need any changes in ESMValTool to run.

Old version:

grafik

New version:

diag_CMIP5_HadGEM2-CC_Omon_historical_r1i1p1__prep_depth_integration_1_diag_depthInt_1_2001_2004_map_0

**Comment by valeriupredoi** [comment]
awesome you doing testing, Manu! About those K -> m.K units change - it's a bit fishy (excuse the pun) at first glance since the numbers are the same, only units changed? You wanna do more testing before we merge this? :beer:

**Comment by schlunma** [comment]
No, nothing fishy at all, that's exactly what was to be expected: In this preprocessor (`depth_integration`), a weighted sum of potential temperature along the depth coordinate is taken;, i.e., potential temperature (units `K`) is multiplied by the depth layer thickness (units `m`) and then summed up, which results in the units `K m`. 🐟 This PR just fixes the units handling; the actual calculation was correct before (hence the numbers didn't change).

This has also been expected by the author of `depth_integration`; see the following comment I removed now:

https://github.com/ESMValGroup/ESMValCore/blob/4c2578b58cc581715fbfe877418b2bc2e1296667/esmvalcore/preprocessor/_volume.py#L256-L258

**Comment by valeriupredoi** [comment]
excellent! I'll take my :fish: back then :grin:

**Pull request merged**
