### PR TITLE
Use consistent precision in multi-model statistics calculation and update reference data for tests

### LINKED ISSUE #940: Multimodel stats computes with artificially high precision.
>     * Issue 1: Data are different. It is accurate to 7 digits, but not to 8. Could be similar to what's [discussed above](https://github.com/ESMValGroup/ESMValCore/pull/685#issuecomment-698253145). Changing the statistic from 'mean' to 'median' as suggested by Mattia solves the issue on the data.

I also found out where this difference comes from: in the current master branch, the data is passed over from the original cubes into a new array here: https://github.com/ESMValGroup/ESMValCore/blob/4d52e4ac50483a98e946353a630427831da44f3a/esmvalcore/preprocessor/_multimodel.py#L331

The incoming data is `float32`, whereas the new data type is `float64`. Consequently, the statistics are calculated on the `float64` data, introducing an unrealistically high precision. Later on the dtype is converted again to float32, but at that point, the damage is already done. 

I've created a new PR to correct this change and to update the reference data. That way we can confirm that this PR doesn't break the preprocessor.

_Originally posted by @Peter9192 in https://github.com/ESMValGroup/ESMValCore/issues/685#issuecomment-758783758_

### PR DESCRIPTION
**Pull request by Peter9192**
This PR forces the precision in the multi-model statistics calculation for `span=full` to `float32`. Also the reference data for the sample-data tests are updated. This is needed to verify that no (other) unwarranted changes to the multi-model statistics functionality are introduced in #685

closes #940
## Checklist

-   [x] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [x] N/A [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality 
-   [x] N/A YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [x] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   [x] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:

-   [x] N/A Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Review by stefsmeets — APPROVED** [review]
Looks good to me, because we already change the dtype here anyway:
https://github.com/ESMValGroup/ESMValCore/blob/4d52e4ac50483a98e946353a630427831da44f3a/esmvalcore/preprocessor/_multimodel.py#L439

Is that what you mean? Is there a reason we do not keep the type of the incoming data?

**Comment by Peter9192** [comment]
>  Is there a reason we do not keep the type of the incoming data?

New numpy arrays default to `float64`, so I think it's just gone unnoticed. There is an argument to be made for calculating on higher precision, but it doesn't seem to be the reason here, because for `span='overlap'` it just calculates on `float32`.

**Comment by Peter9192** [comment]
@nielsdrost could you merge this please?

**Comment by Peter9192** [comment]
I created an issue #943 to discuss whether it would be desirable to intentionally enforce high precision calculations.

**Pull request merged**
