### PR TITLE
Add support for Python=3.12

### LINKED ISSUE #2227: Support Python=3.12 :snake:
It's stable, with a solid ABI etc - we should start supporting it :snake: @zklaus @bouweandela I can fire up PRs to get it in before 2.10 is out if you guys consider we should do this, there may be problems when releasing Tool though (dunno!), or I can move the work to 2.11 -> up to you :beer: 

EDIT #2228 is still very young, so no way jose we can get anything done by 2.10 :+1:

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Closes #2227 

Link to documentation: not yet available, to be posted

## As of 28 May 2024

The prospector-related issue vs flake8 dependencies solved/workarounded in https://github.com/ESMValGroup/ESMValCore/pull/2437 by @bouweandela (merged that branch here to have the full support)

## Historical info

Only incompatibility is `prospector` - needs https://github.com/landscapeio/prospector/pull/645 that, in turn, needs a fix/workaround of `master` proposed in https://github.com/landscapeio/prospector/pull/658

Things are clear now: `flake8==7.0.0` is not barfing at all - all clear (bar one actual PEP8 error that fixed in https://github.com/ESMValGroup/ESMValCore/pull/2228/commits/57fcea4777803f16611b61ae4abf3a4f43c7ab2a ) - but, prospector is not happy to have latest flake8, am trying to push updated prospector pins in https://github.com/landscapeio/prospector/pull/645 - once that's merged, we will wait for a new prospector release, then I'll build a new prospector conda package myself. That should fix it all :+1:

**Incompatible packages**

- none (as of 31 October 2023)

But `flake8` is barfing! -> according to @zklaus @bouweandela and myself, the flake8 issue is a bug that I will report

**EDIT on flake8** (as of 7 November 2023): thanks to tests done by @ehogan we now see `flake8=6.1.0` almost not barfing at all (just a couple of errors, unlike `flake8=5` that completely poops the bed, as seen from the GA tests linked); problem is, `flake8=6.1.0` (latest version) is currently rejected by prospector; I'll have to go chase Carl at prospector get us a new version (probably with support for `pylint >=3`), then I'll rebuild it on feedstock.

**Tests failing**

- `flake8` (see above) https://github.com/ESMValGroup/ESMValCore/actions/runs/6708774145/job/18230325803
- ~`tests/unit/esgf/test_logon.py` due to `SafeConfigParser` being removed completely from new Python (via `esgf-pyclient` via `MyProxyClient`); once https://github.com/cedadev/MyProxyClient/pull/20 is merged, and a new vesrion of MyProxyClient is on conda-forge, things will be a-ok (I tested with the dev branch in that PR)~ This has now been fixed with a new version of MyProxyClient and a rebuild of `esgf-pyclient` for Python 3.12 (both by yours truly)

**Historical incompatible packages (resolved)**

- [cartopy](https://anaconda.org/conda-forge/cartopy) (incompatibility tested on: 11 October 2023)
- [cf-units](https://anaconda.org/conda-forge/cf-units) (incompatibility tested on: 11 October 2023)
 - iris via cf-units
 - iris-esmf-regrid via cf-units
 - [fiona](https://anaconda.org/conda-forge/fiona) via gdal/pillow. even if fiona=1.9.4 has a py312 build (incompatibility tested on: 11 October 2023)
 
 These seem to be the only ones - env solves fine with these out of the picture! Fiona plan on a 1.9.5 in a day or two anyway https://github.com/Toblerity/Fiona/issues/1301 - gonna take up the Python=3.12 with the MO folk then :+1: 
 
 **Work started elsewhere**
 
 - https://github.com/conda-forge/cf_units-feedstock/pull/56

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
The Flake8 errors seem to be a Flake8 bug, where that tool checks f-strings and complains about missing space after `:` for example in `f'http://something.org/ABC/v1/{filename}'`.

**Comment by valeriupredoi** [comment]
indeed @zklaus - next hurdle `A mistake in the recipe` https://github.com/ESMValGroup/ESMValCore/actions/runs/6719725575/job/18261890333?pr=2228 - I do wonder who wrote that terse error message :rofl:

**Comment by valeriupredoi** [comment]
> indeed @zklaus - next hurdle `A mistake in the recipe` https://github.com/ESMValGroup/ESMValCore/actions/runs/6719725575/job/18261890333?pr=2228 - I do wonder who wrote that terse error message 🤣

fixed! Now on to the next hurdle...

**Comment by valeriupredoi** [comment]
the `myproxy` import error masks the real problem:
```
raceback (most recent call last):
  File "/home/valeriu/ESMValCore/testimp.py", line 1, in <module>
    from myproxy.client import MyProxyClient
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/myproxy/client/__init__.py", line 44, in <module>
    from myproxy.client.utils.openssl import OpenSSLConfig
  File "/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/site-packages/myproxy/client/utils/__init__.py", line 11, in <module>
    from six.moves.configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/home/valeriu/miniconda3/envs/esmvaltool-fromlock/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
```

**Comment by valeriupredoi** [comment]
OK `SafeConfigParser` -> `ConfigParser` and complete retirement in Python 3.12: https://github.com/philipkershaw/MyProxyClient/issues/9

**Comment by valeriupredoi** [comment]
followup on the flake/prospector matter: I fixed Prospector's environment in the feedstock https://github.com/conda-forge/prospector-feedstock/pull/44 and opened a PR upstream too - all seems to be fine so far, big catch is that flake8>=6 will need the retirement of their (Prospector's) support for Python 3.7 so let's see how they approach it. I hope there'll be a decision soon, so I can push through that PR; there ill also be a separate push to get pylint>=3 supported in Prospector, and I guess that'll mean a new version out. For now we're stuck with no support for Python 3.12 unless we deactivate prospector and install flake8>=6, so still a bit of a :turkey:

**Comment by valeriupredoi** [comment]
@bouweandela `prospector` should be excluded of `setup.py` since it conflicts with the already installed `flake8` see https://github.com/ESMValGroup/ESMValCore/actions/runs/9268331024/job/25496728780?pr=2228

**Comment by valeriupredoi** [comment]
OK I'll revoke that too - `prospector` needs altogether removed from `setup.py` since the development installation grabs a very very old version on top of the already existing conda-forge one https://github.com/ESMValGroup/ESMValCore/actions/runs/9268407947/job/25496971870?pr=2228

**Comment by valeriupredoi** [comment]
OK final env: prospector==1.10.3 from conda-forge, flake8==7 from pypi :partying_face:

**Comment by bouweandela** [comment]
@valeriupredoi Do you want to run the actions again? Or do you think it's ok?

**Review by bouweandela — APPROVED** [review]

**Comment by chrisbillowsMO** [comment]
> @chrisbillowsMO We would like to include these changes in the upcoming release if possible. We can still keep the pin on Python <3.12 for the ESMValTool v2.11 package, but this will allow us to start switch the development version of ESMValTool v2.12 with Python 3.12 once all dependencies are up to date.

Hi @bouweandela - have added to our checklist here: https://github.com/ESMValGroup/ESMValCore/discussions/2389#discussioncomment-9460058

**Comment by valeriupredoi** [comment]
many thanks @chrisbillowsMO :beer:

**Pull request merged**
