### PR TITLE
Relocate `pytest-monitor` outputted database `.pymon` so `.pymon-journal` file should not be looked for by `pytest`

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Sister PR to https://github.com/ESMValGroup/ESMValTool/pull/2501

Second attempt at fixing the issue of missing `.pymon-journal` file during a pytest monitored session: this time around we moving the output database one dir up. The reason for passing in explicitly the log level for pytest-logging is in https://github.com/ESMValGroup/ESMValCore/pull/1441#issuecomment-1028014970

Github Actions tests finally [pass](https://github.com/ESMValGroup/ESMValCore/runs/5038429116?check_suite_focus=true) fully :disappointed_relieved: 

Closed already https://github.com/ESMValGroup/ESMValTool/issues/2489

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by zklaus — APPROVED** [review]
Thanks, @valeriupredoi! Usual caveat applies: Please don't forget to remove the branch from the trigger before merging. (Might as well fix the indentation of `-main` while at it.)

**Comment by valeriupredoi** [comment]
cheers @zklaus - I will, it looks like some tasks-related stuff hit the proverbial fan in the tests, am having a look what the deuce

**Comment by valeriupredoi** [comment]
OK tests are dying because of this https://github.com/ESMValGroup/ESMValCore/issues/1443

**Comment by valeriupredoi** [comment]
OK I have now narrowed down the test fails due to those missing ancestors being caused by running pytest with `--db ../.pymon` flag, the Julia path issue is separate and valid too

**Comment by valeriupredoi** [comment]
@bouweandela could you maybe have a look at the failing tests plss and possibly tell me why running pytest with a `--db ../.pymon` flag would mess up the ancestors generation? Is pytest being distracted about where to put files with that flag on? The flag is for the pytest-monitor to know where to put the output database for test monitoring

**Comment by zklaus** [comment]
The issue seems to be that there are more messages captured in the capture log (see [the log, ll 151ff](https://github.com/ESMValGroup/ESMValCore/runs/5022359285?check_suite_focus=true#step:9:151)). These are additional debug messages for provenance collection and I am not 100% sure they occur because of the pymon moving or just coincidentally with it here.

In any case, I don't see anything wrong with the log, so I suggest adjusting the test. More information can be found in the pytest documentation. Perhaps [a `with caplog.at_level`](https://docs.pytest.org/en/6.2.x/logging.html?highlight=at_level#caplog-fixture) approach would be the easiest to exclude the `DEBUG` level additional entries? Alternatively, we might just check for presence of the desired entries and ignore anything else.

**Comment by valeriupredoi** [comment]
@zklaus that's exactly what the problem is! But funnily enough the test is not failing locally on me laptop - am trying to figure out if the `pytest-monitor` package is the problem or the extra command line flag - I don't think it's the package since we run this test stock and green in our normal GA tests, but just doing a quick inspection now...

**Comment by valeriupredoi** [comment]
right! so it's the `--db` flag that's introducing the extra DEBUG crappe - I'm gonna try your suggestion with setting the log level at caplog level

**Comment by valeriupredoi** [comment]
man, whichever I go those blithering 3 tests still die, am thinking of binning this anyway, the pymon crappe almost never happens in Core, what you reckon @zklaus ?

**Comment by zklaus** [comment]
@valeriupredoi, I think you are kind of barking up the wrong tree: You are changing the log-level after the logging has happened. Try moving the change of level to the beginning of the testing routine, not just in the function that examines the log.

**Comment by valeriupredoi** [comment]
@zklaus of course, I am being a complete dummer :man_facepalming:

**Comment by valeriupredoi** [comment]
OK some progress finally! I have managed to reproduce the issues reported in the GA test as test failures, but as warnings with:

```bash
pytest tests/unit/task/test_diagnostic_task.py --db ../.pymon --log-cli-level=info
```

outputs 

```
tests/unit/task/test_diagnostic_task.py::test_collect_provenance_no_ancestors 
------------------------------------------------------ live log call -------------------------------------------------------
WARNING  esmvalcore._task:_task.py:629 No ancestor files specified for recording provenance of test.png, created by diagnostic script test.py in task some-diagnostic-task
WARNING  esmvalcore._task:_task.py:664 Valid ancestor files for diagnostic script test.py in task some-diagnostic-task are:

PASSED                                                                                                               [ 90%]
tests/unit/task/test_diagnostic_task.py::test_collect_provenance_invalid_ancestors 
------------------------------------------------------ live log call -------------------------------------------------------
WARNING  esmvalcore._task:_task.py:647 Invalid ancestor file xyz.nc specified for recording provenance of test.png, created by diagnostic script test.py in task some-diagnostic-task
WARNING  esmvalcore._task:_task.py:664 Valid ancestor files for diagnostic script test.py in task some-diagnostic-task are:

PASSED                                                                                                               [ 95%]
tests/unit/task/test_diagnostic_task.py::test_collect_provenance_ancestor_hint 
------------------------------------------------------ live log call -------------------------------------------------------
WARNING  esmvalcore._task:_task.py:647 Invalid ancestor file abc.nc specified for recording provenance of test.nc, created by diagnostic script test.py in task some-diagnostic-task
WARNING  esmvalcore._task:_task.py:664 Valid ancestor files for diagnostic script test.py in task some-diagnostic-task are:
xyz.nc
PASSED                                                                                                               [100%]

=====================
```

it seems that somehow the live log output gets ingested in the caplog when using the `--db` cmd line opt, rather than the more minimal stdout/stderr when not using that flag. We can set whatever `INFO` we want to in the test or outside it, it's the live vs not live log problem. So it takes warning crap as error output.

Now, looking at `--log-level` - the pytest-logging plugin documentation says that it depends on the machine where it runs, by default it's WARNING but it may vary, so on my machine, running with `--log-level=debug` it finally makes those 3 tests fail as on the GA machine, so on the GA machine the darn thing is set to `debug` by default arghhh

**Comment by valeriupredoi** [comment]
IT PASS!! :partying_face: :bomb:

**Comment by valeriupredoi** [comment]
@zklaus - fixed the logging issue eventually - you wanna have another look before I merges? :beer:

**Comment by zklaus** [comment]
I tried to suggest this approach. What do you think? Like this, we don't have to mess up everyone's logging levels globally.

**Comment by valeriupredoi** [comment]
man, am stumped, I tried exactly that earlier today and it didn't work (well just for one of the tests, just to see it pass, and it didnt) see https://github.com/ESMValGroup/ESMValCore/pull/1441/commits/bbbf06ed0fdc3285275292459a2391a50c3b7fde - I am a bit apprehensive now, since it's possible we've set the global level to `info` by doing the cmd line set before and now it keeps it the right way, only to flip back on a different branch...

**Comment by valeriupredoi** [comment]
I'll be a monkey's uncle, your implementation works beautifully even if on a different branch in a separate run https://github.com/ESMValGroup/ESMValCore/runs/5049938139?check_suite_focus=true - I got no idea why it didn't work for me when I tested it yesterday but am not gonna dwell on it - cheers a lot, Klaus, I'll remove the GA branch and merge this very painful PR :laughing:

**Comment by zklaus** [comment]
Well, you always set the level after the actual logging. Have a :eyes: at the code :smile:

**Comment by valeriupredoi** [comment]
no more, am done with this, it works now, and it might break even if I look at it :rofl:

**Pull request merged**
