### PR TITLE
Allow more recent version of `scipy`

### LINKED ISSUE #927: Test failure for tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1.py
I am noticing this test failure on multiple platforms including my laptop, Github Actions (see [GA](https://github.com/ESMValGroup/ESMValCore/runs/1651548703?check_suite_focus=true) output for both Python 3.8 and 3.9):
```
______________________________________________________ test_tos_fix_data _______________________________________________________
[gw1] linux -- Python 3.9.1 /home/valeriu/miniconda3/envs/esmvalcore39/bin/python3.9

    def test_tos_fix_data():
        """Test ``fix_data`` for ``tos``."""
        grid_lat = iris.coords.DimCoord(
            [20.0, 40.0],
            bounds=[[10.0, 30.0], [30.0, 50.0]],
            var_name='rlat',
            standard_name='grid_latitude',
        )
        grid_lon = iris.coords.DimCoord(
            [10.0, 20.0, 30.0],
            bounds=[[5.0, 15.0], [15.0, 25.0], [25.0, 35.0]],
            var_name='rlon',
            standard_name='grid_longitude',
        )
        latitude = iris.coords.AuxCoord(
            [[-40.0, -20.0, 0.0], [-20.0, 0.0, 20.0]],
            var_name='lat',
            standard_name='latitude',
            units='degrees_north',
        )
        longitude = iris.coords.AuxCoord(
            [[100.0, 140.0, 180.0], [80.0, 100.0, 120.0]],
            var_name='lon',
            standard_name='longitude',
            units='degrees_east',
        )
    
        # Create cube without bounds
        cube = iris.cube.Cube(
            np.full((2, 3), 300.0),
            var_name='tos',
            units='K',
            dim_coords_and_dims=[(grid_lat, 0), (grid_lon, 1)],
            aux_coords_and_dims=[(latitude, (0, 1)), (longitude, (0, 1))],
        )
        assert cube.coord('latitude').bounds is None
        assert cube.coord('longitude').bounds is None
    
        # Apply fix
        fix = Tos(None)
        fixed_cube = fix.fix_data(cube)
        assert fixed_cube is cube
        assert fixed_cube.coord('latitude').bounds is not None
        assert fixed_cube.coord('longitude').bounds is not None
        latitude_bounds = np.array([[[-40, -33.75, -23.75, -30.0],
                                     [-33.75, -6.25, 3.75, -23.75],
                                     [-6.25, -1.02418074021670e-14, 10.0, 3.75]],
                                    [[-30.0, -23.75, -13.75, -20.0],
                                     [-23.75, 3.75, 13.75, -13.75],
                                     [3.75, 10.0, 20.0, 13.75]]])
>       np.testing.assert_allclose(fixed_cube.coord('latitude').bounds,
                                   latitude_bounds)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=0
E       
E       Mismatched elements: 24 / 24 (100%)
E       Max absolute difference: 3.75
E       Max relative difference: 5.25762448e+13
E        x: array([[[-43.480762, -34.019238, -22.009619, -31.471143],
E               [-34.019238, -10.      ,   2.009619, -22.009619],
E               [-10.      ,  -0.538476,  11.471143,   2.009619]],...
E        y: array([[[-4.000000e+01, -3.375000e+01, -2.375000e+01, -3.000000e+01],
E               [-3.375000e+01, -6.250000e+00,  3.750000e+00, -2.375000e+01],
E               [-6.250000e+00, -1.024181e-14,  1.000000e+01,  3.750000e+00]],...

tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1.py:82: AssertionError
```
I can fix this asap by throttling the `rtol` value, but it looks to me as the differences are pretty darn big (O(1e1)) so a functional fix may be needed - any ideas @jvegasbsc ? :confused:

### PR DESCRIPTION
**Pull request by schlunma**
This PR fixes a test that fails in a more recent version of `scipy` (>1.6). Note that now the pin is `scipy>=1.6` instead of `scipy<1.6` to make sure that the newer version is picked up. Without the pin, I still got version 1.5.3 from `conda env create`.

Closes #927.

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
cheers muchly @schlunma :beer: I'll be running a full GA test suite on this PR too (will plug the call tomorrow, if all goes fine Ill remove the test branch immediately) and will try run the env creation manually too (conda is stubborn and if it plops 1.5.3 in curr env, it might be farting in my face with the new pin in). Out of curiosity, why are the numerical results change so much just by changing the scipy version?

**Comment by zklaus** [comment]
This was discussed in some detail in the issue, see e.g. https://github.com/ESMValGroup/ESMValCore/issues/927#issuecomment-809365488. Basically, scipy's interpolation routine got a bit better and changed a default, leading to a different treatment of boundary values.

**Comment by schlunma** [comment]
Yeah, I had the same issue - also got version 1.5.3 when I didn't pin `scipy` in `environment.yml`. Maybe we need to additionally pin it in `setup.py`?

**Comment by valeriupredoi** [comment]
cheers @schlunma - the env builds well and tests pass fine (both on my local machine and on AG machine) **except** for Python=3.6, seems that's a tad too old for conda to figure out the environment with the new scipy. I reckon we have two options: not support Python=3.6 anymore or condition scipy to <1.6 and the test too (but this seems to be a lot of faff IMHO)

**Comment by zklaus** [comment]
Incidentally, perhaps interesting: [Scipy's toolchain roadmap](https://docs.scipy.org/doc/scipy/reference/toolchain.html). From this, we see that Numpy has already dropped support for Python 3.6 in version 1.20.0 (released in January 2021).

**Comment by valeriupredoi** [comment]
good find @zklaus - that explains a **lot** :grin: - we should too then, methinks

**Comment by zklaus** [comment]
Would tend to agree. But perhaps we should have a separate issue/discussion about that?

**Comment by valeriupredoi** [comment]
have opened a PR where I drop Python 3.6 like a hot potato https://github.com/ESMValGroup/ESMValCore/pull/1200

**Comment by valeriupredoi** [comment]
link to [Github Actions tests](https://github.com/ESMValGroup/ESMValCore/actions/runs/942402528) that ran fine on this branch, except Python 3.6 :+1:

**Review by valeriupredoi — APPROVED** [review]
many thanks @schlunma :beer: I'll be very happy to merge as soon as we decide to drop Py3.6 and get #1200 in

**Pull request merged**
