### PR TITLE
Update _volume.py

### PR DESCRIPTION
**Pull request by ledm**
A minor edit to extract_trajectory, where the latitude and longitude interface was backwards.

## Description

Partially addresses #1137.

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
good catch! isn't there a test as well that will need to be changed? or you used identical lat and lon points in the test :grin:

**Comment by ledm** [comment]
The test is:
```
    def test_extract_trajectory(self):
        """Test to extract a trajectory from a (3, 2, 2) cube."""
        result = extract_trajectory(self.grid_3d, [1.5, 2.5], [2., 2.], 2)
        expected = np.ones((3, 2))
        self.assert_array_equal(result.data, expected)
```

So it shouldn't fail as it's only effectively comparing the shape of the outputs. Whether that is a good enough unit test should like be another issue/PR!

**Comment by valeriupredoi** [comment]
OK, it's a decent test, given that the numerical data parameters are tested for (cows vs bulls or bulls vs cows is a different matter, the test is happy as long as they're of the same shape then). I'm merging this if you don't need to get more stuff done to it :+1:

**Comment by ledm** [comment]
Thanks V. Randomly, while I uncovered this bug in my local version of the code, I did all the editing and merging for this PR in github without ever having a local copy of this branch. It is a great method to quickly correct bugs.

**Comment by valeriupredoi** [comment]
yes but be careful that some tests don't run on the pure github edited branch and only get run when merged onto main so it's good to do the bugfixes locally so you can run all the tests and see if there are issues before merging into main

**Comment by bouweandela** [comment]
@ledm @valeriupredoi I'm just reviewing our changelog for v2.3 and I'm a bit disappointed by what you came up with as a title for this change. From our [contribution guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label):
>The titles and labels of pull requests are used to compile the Changelog, therefore it is important that they are easy to understand for people who are not familiar with the code or people in the project. Descriptive pull request titles also makes it easier to find back what was changed when, which is useful in case a bug was introduced.

Could you please put in a bit more effort next time? :pray:

**Comment by ledm** [comment]
Sorry, that was the title github generated. I'll change it now, post hoc.

**Pull request merged**
