### PR TITLE
Fix areacello in CMIP5 EC-Earth

### PR DESCRIPTION
**Pull request by jvegasbsc**
Before you start, please read [CONTRIBUTING.md](https://github.com/ESMValGroup/ESMValCore/blob/master/CONTRIBUTING.md).

**Tasks**

-   [ ] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

### CODE REVIEW

**Comment by jvegasbsc** [comment]
Required for ESMValGroup/ESMValTool#1299

**Comment by zklaus** [comment]
Is there an issue for this PR?

**Comment by jvegasbsc** [comment]
> Is there an issue for this PR?

No, just found that Iris can not read latitudes and longitudes for areacello in ESMValGroup/ESMValTool#1299

**Comment by valeriupredoi** [comment]
@jvegasbsc Javi man, it'd be good to stick to what @bouweandela has been preaching for a while now: descriptive title for the PR, tick the boxes in the PR template, link and give a nice description in the original https://github.com/ESMValGroup/ESMValTool/pull/1299 (open an issue here before a PR too) - you know, the boring stuff, but albeit very useful for later :beer:

**Comment by zklaus** [comment]
The actual issue with the original file is that the `areacello` variable in it is missing the `coordinates` attribute. Hence, imho, the correct fix is to use `fix_file` to add `areacello:coordinates = "lat lon"`.

**Comment by jvegasbsc** [comment]
>  Hence, imho, the correct fix is to use fix_file to add areacello:coordinates = "lat lon".

That way is much slower, as we don't modify the files but create a new copy. Fix file must be used only if Iris can not read the cubes.

**Comment by zklaus** [comment]
I thought about that, but since this is an fx file the difference should be very small.

**Comment by valeriupredoi** [comment]
In #439 we use the output file as input for fx preproc steps so the file needs to be fixed proper via `fix_file`

**Comment by bouweandela** [comment]
I think that we might want to consider removing fix_file altogether at some point, because so far we have not encountered a single dataset on ESGF that needs it.

**Comment by schlunma** [comment]
> I think that we might want to consider removing fix_file altogether at some point, because so far we have not encountered a single dataset on ESGF that needs it.

I found a lot of them, but the fixes are not merged (regarding `cl` of almost all CMIP5 and CMIP6 datesets):

https://github.com/ESMValGroup/ESMValCore/blob/97a242cd0ccc544d16ca9c083bafdf1164f78a7d/esmvalcore/cmor/_fixes/cmip5/canesm2.py#L12-L58

Note that setting the attribute `formula_terms` is not allowed in `iris`, thus we definitely need to use another package for that. Without that attribute, `iris` is not able to read the derived coordinate correctly.

**Comment by jvegasbsc** [comment]
> Note that setting the attribute formula_terms is not allowed in iris, thus we definitely need to use another package for that. Without that attribute, iris is not able to read the derived coordinate correctly.

Can't you overcome that using any of this, at least for a few datasets? 
https://scitools.org.uk/iris/docs/latest/iris/iris/aux_factory.html

**Comment by zklaus** [comment]
One alternative might be to rethink the `fix_file` in terms of iris' callback mechanism.

**Comment by jvegasbsc** [comment]
> One alternative might be to rethink the fix_file in terms of iris' callback mechanism.

I had open a new issue to discuss the future of the fix_file

**Comment by zklaus** [comment]
And the issue is #463. Thanks, good idea to separate that discussion.

**Comment by jvegasbsc** [comment]
> And the issue is #463. Thanks, good idea to separate that discussion.

Ups, I forgot the link. Thanks!

**Comment by bouweandela** [comment]
@mattiarighi I think this can be merged, considering that the discussion is on a different topic. Right?

**Comment by zklaus** [comment]
I still think this is the wrong fix, but I guess we'll have to revisit the whole `cell_measures` complex after some iris improvements anyway.

**Comment by zklaus** [comment]
Actually, philosophical differences aside, V [seems to hint](https://github.com/ESMValGroup/ESMValCore/pull/457#issuecomment-582975979) above that the file needs to be fixed. @valeriupredoi, can you please elaborate and tell us whether this fix works or not?

**Comment by valeriupredoi** [comment]
> Actually, philosophical differences aside, V [seems to hint](https://github.com/ESMValGroup/ESMValCore/pull/457#issuecomment-582975979) above that the file needs to be fixed. @valeriupredoi, can you please elaborate and tell us whether this fix works or not?

dont mind me, I was walking in the desert, the fx file will have gone through the full fix metadata/fx data/all needed preproc steps before being used - that's the whole point of #439

**Comment by zklaus** [comment]
Alright, hope you found some water :). Then this is closed for good.

**Pull request merged**
