### PR TITLE
Added test for check of data availability and fixed some checks for _recipe.py

### PR DESCRIPTION
**Pull request by schlunma**
This adds missing tests for #98 (where @valeriupredoi was too quick in merging :wink:).

I also fixed some syntactic errors in the tests for `_recipe.py` which prevented them to work correctly (e.g. this explains why a test didn't fail after #432 even though it should have failed). This revealed some errors in the old tests. I couldn't fix two of them since I'm not quite sure how. Can you have a look at them, @bouweandela please? I think you wrote them (`test_extract_shape_raises` in `tests.integration.test_recipe`).

This PR only affects tests, so I think we can quickly merge it.

### CODE REVIEW

**Comment by valeriupredoi** [comment]
In principle approved, but then I saw the failed tests (not the ones fixed by #452 ) - can you check them out pls :beer:

**Comment by schlunma** [comment]
> In principle approved, but then I saw the failed tests (not the ones fixed by #452 ) - can you check them out pls beer

These are the ones where @bouweandela needs to step in since I'm not sure about them (I don't know if the test itself is wrong or the function).

**Comment by valeriupredoi** [comment]
Right on, Ill have a closer look too, after coffee :coffee:

**Comment by valeriupredoi** [comment]
that test is badly written in `master` and you have actually uncovered the badness - the recipe fails with `RecipeError(In preprocessor function `extract_shape`: Unable to find 'shapefile: ')` at all times irrespective of the functional argument passed - so it should fail exactly 3 times as you see it fail

**Comment by valeriupredoi** [comment]
ie if the `extract_shape` is run without `shapefile: test.shp` it'll always fail first coz the shapefile is not found due to `extract_shape(settings)` from `_recipe_checks.py` - @bouweandela or @JaroCamphuijsen please fix this catch22 :beer:

**Comment by valeriupredoi** [comment]
> ie if the `extract_shape` is run without `shapefile: test.shp` it'll always fail first coz the shapefile is not found due to `extract_shape(settings)` from `_recipe_checks.py` - @bouweandela or @JaroCamphuijsen please fix this catch22 beer

any chance @bouweandela or @JaroCamphuijsen had a look at this pls :beer:

**Comment by bouweandela** [comment]
The goal of the check function is to check that the arguments are within valid range and the goal of the test is to check that an RecipeError is raised if an invalid argument is provided. We should probably use a schema for this kind of checking at some point though.

**Comment by valeriupredoi** [comment]
Ah biutiful, cheers monsieur @bouweandela :beer:

**Pull request merged**
