### PR TITLE
[Github Actions] Update environment with latest mamba

### LINKED ISSUE #2138: [Github Actions] old conda and mamba versions
As they come shipped with the setup-miniconda@v2 and immune to a conda update -n base conda, they are fairly old, and we could start seeing issues (we already saw that in the case of conda-lock). The solution is to force update mamba that'll in turn update conda. I'll try work on this, also pinging the action devs needs be done.

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

In #2138 I raised the issue that our standard action setup-miniconda@v2 has not been updated in a while and is now starting to install fairly old conda and mamba versions - we are not yet hitting the issue we are face in Readthedocs builds (where the standards conda/mamba are really old) but I am adding an update to mamba and subsequently of the env for two of our more important Github Actions. We'll have to keep an eye on https://github.com/conda-incubator/setup-miniconda/issues/288 where I asked the folks upstream to update the Mambaforge version.

The two new steps added don't impact the time tests run (adding about 2 minutes); there is, however, a warning at mamba update stage: it's been debated in https://github.com/conda/conda-libmamba-solver/issues/145 and it doesn't seem to impact our env

Closes #2138 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
this is not urgent at all, but if any yous @bouweandela or @zklaus had a wee bit of time, I'd appreciate a reviewe here plss :beer:

**Review by bouweandela — CHANGES_REQUESTED** [review]
In our installation instructions we recommend installing a recent version of mamba and then creating the environment. To make sure that these instructions work, we replicate those steps in the tests. However, these changes here take a different approach: 1 install old mamba 2 create environment 3 update mamba 4 update environment.yml. Could you please make sure you do a single mamba installation and then create the environment from environment.yml?

**Comment by valeriupredoi** [comment]
> In our installation instructions we recommend installing a recent version of mamba and then creating the environment. To make sure that these instructions work, we replicate those steps in the tests. However, these changes here take a different approach: 1 install old mamba 2 create environment 3 update mamba 4 update environment.yml. Could you please make sure you do a single mamba installation and then create the environment from environment.yml?

absolutely valid point, and I wish I did that - unfortunately it is impossible to update the conda/mamba that comes shipped with the GA action, since it already builds the environment in the initial step, unless we change the workflow fundamentally I don't have any other "correct" ways to do it, apart from going this way, which I know it's fairly dodgy. The good thing is we've not yet started seeing issues from the GA action using an old mamba/conda, so I think we can park this until we start seeing problem, or, ideally, until they update the GA action :+1:

**Comment by valeriupredoi** [comment]
closed but keeping the branch just in case we decide to revive it and hack it to pieces :+1:

**Pull request closed without merging**
