### PR TITLE
Xfail esgf search tests if they fail with HTTP error from requests

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

The ESGF node at CEDA has been down for a few good hours now, and our tests are [failing](https://github.com/ESMValGroup/ESMValCore/actions/runs/3560815574/jobs/5988323814) and rightly so! But this is the last thing we'd want to see when, say, we make a release and the package fails to build due to an annoying, and independent of us issue. I marked those tests as xfailed only when the exception occurs; most of the time it doesn't so we  are still testing correctly - this id done like this:

- if test fails with requests HTTP error then it's marked as xfailed
- if test fails with any other exception then it's marked as red failed
- if test passes (normal behaviour) then it's marked as xpassed

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
Good idea to fix this, but shall we fix the code instead of the tests? I was doing a tutorial on the tool today with some people and we had to modify everyone's [~/.esmvaltool/esgf-pyclient.yml](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/quickstart/configure.html#search) file so it uses a different order of the index nodes.

**Comment by bouweandela** [comment]
Created an issue to report the problem: #1833

**Comment by valeriupredoi** [comment]
> Good idea to fix this, but shall we fix the code instead of the tests? I was doing a tutorial on the tool today with some people and we had to modify everyone's [~/.esmvaltool/esgf-pyclient.yml](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/quickstart/configure.html#search) file so it uses a different order of the index nodes.

Indeed, a code fix is better, but I think we should have a failsafe in place in testing too. Xpassed is better than failed 😁

**Comment by valeriupredoi** [comment]
> Created an issue to report the problem: #1833

Cool! I also reported the index node issue to CEDA 👍

**Comment by bouweandela** [comment]
Just created a pull request to fix the issue: 1834

**Comment by bouweandela** [comment]
> we should have a failsafe in place in testing too. Xpassed is better than failed grin

Every user of ESMValCore with the default configuration is affected by this problem, so to me it seems really good that our unit test picked this up.

**Pull request closed without merging**
