### PR TITLE
Options arg in read_config_user_file now optional (#709)

### PR DESCRIPTION
**Pull request by jvegasbsc**
As requested by @schlunma

### CODE REVIEW

**Comment by schlunma** [comment]
Perfect, thanks @jvegasbsc! In #709 there are 9 files changed, here it is only 1. Are these changes already in included in `master`? I think every `v2.0.0` should be a subset of `master`, so every change in `v2.0.0` should also be in `master`.

**Comment by jvegasbsc** [comment]
Those changes are already on master. I cherry picked the commit

**Comment by schlunma** [comment]
All right, but doesn't that mean that there are changes in `v2.0.0` which should not be there?

**Comment by bouweandela** [comment]
> Those changes are already on master. I cherry picked the commit

@jvegasbsc @mattiarighi Sorry if this was not clear. Commits should be cherry picked from the master branch into the v2.0.0 release branch, not the other way around. The way to get something in the release is to make a pull request to `master` and then ask me or @mattiarighi to cherry-pick that particular commit into the `v2.0.0` release branch. Now the branches have a different history and every pull request that has been merged since the `v2.0.0` release branch forked off the `master` branch has also been included in it when #709 was merged.

**Comment by mattiarighi** [comment]
Sorry @bouweandela, hope this does not cause too much trouble...

Is there a way to revert this?
I think we only had 2 PR merged in the last week: #709 and #716

**Comment by bouweandela** [comment]
It's a few more, but nothing big. I think it's fine to leave it like this for now. Let's be more careful next time.

**Pull request merged**
