### PR TITLE
Cmip6 lon bnds fixes

### PR DESCRIPTION
**Pull request by mwjury**
**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom) see #806 
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [ ] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [ ] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #issue_number

### CODE REVIEW

**Comment by mwjury** [comment]
Fix bad longitude bounds of:
- NorESM-LM: lon=[0, 2.5, ..., 355, 357.5], lon_bnds=[[0, 1.25], ..., [356.25, 360]] into lon_bnds=[[-1,25, 1.25], ..., [356.25, 358.75]]. Discrepancy is between historical (wrong) and ssp585 (maybe more) and produces errors when concatenating. Tested for TAS and PR.
- MCM-UA-1-0: lons=[0, ..., 356.25]; lon_bnds=[[-1.875, 1.875], ..., [354.375, 360]] into lon_bnds=[[-1.875, 1.875], ..., [354.375, 358.125]]. Discrepancy was found in historical and ssp585 (maybe more) and leads to errors when doing area_statistics ("iris/cube.py", line 2572, in _intersect_modulus: ValueError("coordinate's range greater than coordinate's"). Tested for TAS and PR.

**Comment by valeriupredoi** [comment]
cheers muchly @mwjury :beer: - could you please fix the test that's failing (the coord has no bounds there) and also write two tests to test the fixes? Let me know if you need help with the tests, glad to assist!

**Comment by mwjury** [comment]
@valeriupredoi done

**Review by valeriupredoi — APPROVED** [review]
awesome, cheers very much @mwjury :beer:

**Pull request merged**
