### PR TITLE
Do not realise coordinates in `check.py`

### LINKED ISSUE #1906: Make `check.py` lazy
**Is your feature request related to a problem? Please describe.**
There are several parts of the CMOR checker that call `coord.points`, which realise the auxiliary coordinates. If those coordinates are 2 dimensional, it can end up loading pretty big arrays. Changing that to `coord.core_points()` should solve the issue.

**Would you be able to help out?**
Yes

### PR DESCRIPTION
**Pull request by sloosvel**
## Description

This PR changes `check.py` so that it calls `coord.core_points()` and `coord.core_bounds()` when checking the coordinates , in order to not realise 2D latitudes and longitudes. 

Closes #1906 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
~- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
what a cute little, yet very useful PR, cheers @sloosvel :beer: Do you want to tidy up the PR description boxes, please? Then tut-tut about the PR so it can be merged :+1:

**Comment by sloosvel** [comment]
Sure, done!

**Comment by valeriupredoi** [comment]
@ESMValGroup/technical-lead-development-team can one of you peeps have a glance at this, and merge, please? :beer:

**Comment by schlunma** [comment]
Thanks!!

**Pull request merged**
