### PR TITLE
Add David Hohn to contributors' list

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Adding @dhohn to the CITATION file - David, do you mind adding your affiliation and ORCID no (if you have one, if not, just remove the line) please here, mate? Then approve the PR pls :beer: 

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by dhohn — APPROVED** [review]
Thats me :)

**Comment by dhohn** [comment]
Thanks @valeriupredoi. All good! :)

**Comment by valeriupredoi** [comment]
brilliant, thanks very much, David! :beer: @axel-lauer @zklaus would you guys be OK to add David as a collaborator - he's been working with me on the Amoc derivation for CMIP6 - in fact, he's done the whole scientific work towards that derivation, I only improved testing, see https://github.com/ESMValGroup/ESMValCore/pull/1577 Cheers, fellas :beer:

**Comment by zklaus** [comment]
I'm in favor! @axel-lauer?

**Comment by axel-lauer** [comment]
Sounds also good to me.

**Pull request merged**
