### PR TITLE
Update yamale to version 3

### LINKED ISSUE #717: Update yamale to v3
A new version of Yamele has been released (v3), but our schemas are not compatible with it.

### PR DESCRIPTION
**Pull request by zklaus**
## Description

This adds `strict=False` to the call to `yamale.validate`. This option has been supported already in yamale 2.x, but there the default was `False`. This default has been changed to `True` in yamale 3.x, but we need `strict=False` because we have a number of recipes that contain bits and pieces that are extra to the parts defined in the schema.

Updating to yamale 3 will allow us to drop one of the two external conda packages we are keeping in our own channel, thus moving us closer to abandoning the channel in favor of conda-forge.

-   Closes #717 

***

## Before you get started

-   [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [x] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Labels are assigned so they can be used in the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [x] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs

***

To help with the number of pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Review by bouweandela — CHANGES_REQUESTED** [review]
Nice work! The file yamale_meta.yaml can also be removed and could you please do a `grep` for all occurrences of the esmvalgroup conda channel? I think it can be removed in most places (think documentation, github actions, maybe more?).

**Comment by zklaus** [comment]
I removed the yamale recipe. As for the conda channel as a whole, I agree that it should be removed, but right now it still hosts our own packages and in any case also touches on the other package, so maybe that should be done in a separate PR?

**Comment by bouweandela** [comment]
It only hosts the `esmvalcore` package now, right? That means it's no longer needed for the conda build command

**Comment by zklaus** [comment]
Done.

**Review by bouweandela — APPROVED** [review]

**Pull request merged**
