### PR TITLE
Pin esmpy<8.4

### PR DESCRIPTION
**Pull request by zklaus**
## Description

Affects #1870 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
Is there reason to believe that esmpy >= 8.4 is not compatible apart from the import statement? Otherwise we could just try importing `esmpy` and if that fails fall back to the old import statement.

**Comment by zklaus** [comment]
@bouweandela, you mean something like this?
```python
try:
    import ESMF
except ImportError:
    import esmpy as ESMF
```

That maybe workable, but I would prefer the inverse, i.e.
```python
try:
    import esmpy
except ImportError:
    warnings.warning("Update esmpy")
    import ESMF as esmpy
```

with a pin now and the full conversion to esmpy along with the import fix then.
How does that sound?

**Comment by valeriupredoi** [comment]
I am with @zklaus :arrow_up:

**Comment by bouweandela** [comment]
If you think that's faster, then let's pin, but if all it takes is the bit of code above then we might as well do that straightaway.

**Comment by bouweandela** [comment]
Let's pin it for now because https://github.com/SciTools-incubator/iris-esmf-regrid/issues/227 will also need to be updated before we can unpin.

**Comment by bouweandela** [comment]
Here is a pull request to update the imports so it works with both versions: #1876.

**Comment by bouweandela** [comment]
@zklaus Is this ready to be taken out of draft or did you plan to do additional work on it?

**Review by bouweandela — APPROVED** [review]

**Review by valeriupredoi — APPROVED** [review]
thanks gents, we gonna get some green :christmas_tree: over Xmas then :grin:

**Pull request merged**
