### PR TITLE
Avoid side effects in extract_season

### LINKED ISSUE #1013: extract_season is broken
PR https://github.com/ESMValGroup/ESMValCore/pull/247 broke the basic functionality of `extract_season()` - it may have introduced the functionality for custom seasons but it broke the basic functionality for extracting a simple meteorological season like `"MAM"`; the problem is reported in this [comment](https://github.com/ESMValGroup/ESMValTool/issues/2028#issuecomment-783246327) and my investigations show that by running a simple functional extraction with:
```python
    seasons = ['DJF', 'MAM', 'JJA', 'SON']
    season_cubes = [extract_season(data_cube, season) for season in seasons]
```
the code returns only the `DJF` cube and `None` for the others because the `clim_season` coord looks malformed:
```
AuxCoord(array(['DJF', 'DJF', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'DJF', 'DJF', 'DJF', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'DJF', 'DJF', 'DJF', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'DJF', 'DJF', 'DJF', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'DJF', 'DJF', 'DJF',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON',
       'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'MAMJJASON', 'DJF'],
      dtype='<U64'), standard_name=None, units=Unit('no_unit'), long_name='clim_season')
```

I unfortunately don't know what you want to achieve with the custom seasons functional integration so I can't fix the code myself, but please fix it **asap** and add a test for the basic seasonal extraction too please.
Cheers :beer:

### PR DESCRIPTION
**Pull request by jvegasbsc**
Extract season was having side efefcts in the form of extra aux coords left in the original cube. This PR fixes it

-   Closes #1013

## Before you get started

-   [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [ ] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] Labels are assigned so they can be used in the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [ ] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   [ ] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:

-   [ ] Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Comment by jvegasbsc** [comment]
Better than still having side effects that are more civil and predictable is to remove them completely. We may be paying a bit in performance for some cases, like extracting the four usual seasons, but it will not be much and we are safer in the weirder cases

**Comment by valeriupredoi** [comment]
cheers for the fix @jvegasbsc - but I am quite confused as to how this fix works: you add the malformed seasons types `["DJF", "MAMJJASON"]` to the cube, then extract the `"DJF"` season from it and return it as `result`, then remove the coord clim_season from `cube` - why isn't a simple one-liner `result = cube.extract(iris.Constraint(clim_season=season))` and return `result` not enough? Note that after you instantiate `result`, `cube` is no longer needed and is an obsolete variable that gets deleted from memory

**Comment by jvegasbsc** [comment]
> cheers for the fix @jvegasbsc - but I am quite confused as to how this fix works: you add the malformed seasons types eg ["DJF", "MAMJJASON"] to the cube, then extract the "DJF" season from it and return it as result, then remove the coord clim_season from cube - why isn't a simple one-liner result = cube.extract(iris.Constraint(clim_season=season)) and return result not enough? Note that after you instantiate result, cube is no longer needed and is an obsolete variable that gets deleted from memory

Cube is the original instance. When we use the preprocessor it is discarded, yes, but it may not be discarded in a diagnostic. This was the source of the problem for @remi-kazeroni: it passed the original cube several times but it only worked fine the first one because in the other ones it has extra stuff from the first one.

Bear in mind that the coordinate is not malformed, it is working at expected: it divides the cube between the season we want to extract and all the rest we don't care, but that coordinate should only live inside this function

**Comment by valeriupredoi** [comment]
regardless of my comment above, I just tested this with an extension of the unit test and it works nicely as I would expect it to work for regular meteorological seasons for multiple extractions in one go :+1:

**Comment by valeriupredoi** [comment]
> Bear in mind that the coordinate is not malformed, it is working at expected: it divides the cube between the season we want to extract and all the rest we don't care, but that coordinate should only live inside this function

Now it does, previously it was `cube`'s new coordinate that was preserved all along the way; now that `result` is returned it's all fine. But note that `cube` is lost inside this function, the new pointer is now `result`, which is fine and well constructed, but I am still thinking we have a couple extra operations that are not needed since `cube` is destroyed after this function and reinstatiated with `result`

**Comment by valeriupredoi** [comment]
ah I see what you mean - inside a diagnostic where the `cube` instance is preserved as pointer and not overwritten as eg `cube = esmvalcore.presprocessor._time.extract_season(cube, season="DJF")`

**Review by valeriupredoi — APPROVED** [review]

**Comment by valeriupredoi** [comment]
OK Javi, I added a test that tests the very case that was broken in the validation diagnostic that was failing for @remi-kazeroni and I am more than fine with this to go in now, cheers mate :beer:

**Review by schlunma — APPROVED** [review]
Tested with the the validation recipe, works fine :+1: 

@valeriupredoi Even in the old version the weird coordinate (it is not malformed as @jvegasbsc said) did not appear in the resulting cube, but was added to the source cube. The main issue is that `iris.coord_categorisation.add_season` alters the original cube in-place, which poses a problem if you re-use the cube several time like it is done in the validation recipe.

**Pull request merged**
