### PR TITLE
Create Github Actions workflow to build and deploy on Test PyPi and PyPi

### PR DESCRIPTION
**Pull request by valeriupredoi**
Automate the deployment to PyPi 🐍📦

See  #814

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@bouweandela do you have a `pyproject.toml` hanging around from previous PyPi builds? I am a bit lazy and not 100% sure of creating one around; do we need to use pep517 to create the wheel or we just use the usual `python3 setup.py sdist bdist_wheel`?

**Comment by bouweandela** [comment]
It would probably be good to use that, since it looks like that's the future of Python packaging, see also this blog: https://snarky.ca/what-the-heck-is-pyproject-toml/

From the blog, it looks like the following content would be enough:
```
[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"
```

**Comment by valeriupredoi** [comment]
I'll try that in a jiffy, cheers dude :beer:

**Comment by valeriupredoi** [comment]
OK good news! I got the darn thing to build the wheel automatically (cheers for the pyproject file suggestion, @bouweandela ) but it looks like I have no permission to upload to Test PyPi - see [test](https://github.com/ESMValGroup/ESMValCore/runs/1230941927?check_suite_focus=true) - this means that either @bouweandela hasnt added me as collaborator on Test PyPi or the Secrets have not been set correctly on ESMValCore/Settings @mattiarighi - can you guys check this by running the test yourselves pls? To trigger the test just do a dummy push to this branch

**Comment by valeriupredoi** [comment]
> OK good news! I got the darn thing to build the wheel automatically (cheers for the pyproject file suggestion, @bouweandela ) but it looks like I have no permission to upload to Test PyPi - see [test](https://github.com/ESMValGroup/ESMValCore/runs/1230941927?check_suite_focus=true) - this means that either @bouweandela hasnt added me as collaborator on Test PyPi or the Secrets have not been set correctly on ESMValCore/Settings @mattiarighi - can you guys check this by running the test yourselves pls? To trigger the test just do a dummy push to this branch

problem solved by @bouweandela adding me to PyPi/Test PyPi :beer:

**Comment by valeriupredoi** [comment]
here is a (most probable) explanation for the failed circleCI test: https://github.com/pypa/pip/issues/8437

**Comment by bouweandela** [comment]
From the blog:

> which is why the current directory is not put on sys.path automatically; you will need sys.path.insert(0, os.path.dirname(__file__)) or equivalent if you're importing local files

So you'll probably need to insert that before trying to import esmvalcore._version in setup.py. Alternatively, I think you could just write a small function to read the version number from the file without importing it.

**Comment by valeriupredoi** [comment]
@bouweandela you Dutch genius! How did I miss that? Yeh, does the job, but two things: the package already being on Test PyPi the upload fails (should I remove it from Test PyPi? - am scared) and PEP8 complains about the module import not being at top of file - bs if you ask me but hey, it's PEP8

**Comment by bouweandela** [comment]
You can't remove packages from (test) PyPI, because that's just a really bad idea. Just use a new version number for the next try, e.g. `2.1.0.post0`, `2.1.0.post1` etc.

**Review by bouweandela — APPROVED** [review]
Nice job!

**Pull request merged**
