### PR TITLE
Make preprocessors mask_above/below_threshold, mask_inside/outside_range lazy 

### PR DESCRIPTION
**Pull request by joergbenke**
## Description

   - addresses parts of https://github.com/ESMValGroup/ESMValCore/issues/674
   - the functions mask_above_threshold, mask_below_threshold, mask_inside_range and
mask_outside_range have been daskified (substituting numpy with dask.array)
   - they were tested against the recipe "recipe_mask_landsea.yml" 
   - the reduction of memory consumption was in this case on Levante (login nodes) from approx 20 GiB to 12 GiB, runtime improvement was about 20% (distributed.LocalCluster)
   - I've added my name to the CITATION.cff and .zenode.json files 

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
~~[ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available~~
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
~~[ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~~
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
hi @joergbenke many thanks for contributing! Could you please tell us what this PR does, by adding a description to it (the title could use with a bit more info too please), and also if there is any issue that this contributes towards or closes; also please make sure the boxes in the PR description are ticked - the ones that are relevant to this PR, otherwise the others that are not, should either be strike-thru-ed, or removed. Then I'll be happy to review it :beers:

**Comment by joergbenke** [comment]
I've adapted my pull request and did some minor corrections:
- I've adapted manually the .zenode file,  
- checked the topics of the checklist, etc.,
- wrote some aditional information (Indeed I posted it already with my last Pull Request but it was still commented out)

I hope everything is fine now.

**Review by remi-kazeroni — APPROVED** [review]
Thanks a lot for your contribution, @joergbenke! The changes look good to me. I also noticed the performance improvements by running test cases with `distributed.LocalCluster` which could be run successfully with this branch but not with current `main`. This PR follows our guidelines, it is ready to be merged 👍

**Comment by schlunma** [comment]
Thanks @joergbenke for your contribution and @remi-kazeroni for reviewing! This can be merged! I also checked the corresponding boxes in https://github.com/ESMValGroup/ESMValCore/issues/674, 4 more prepcessory lazy 🚀

**Pull request merged**
