### PR TITLE
Sorted output for `esmvaltool recipes list`

### PR DESCRIPTION
**Pull request by stefsmeets**
**Tasks**

-   [X] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [X] This pull request has a descriptive title that can be used in a changelog
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes https://github.com/ESMValGroup/ESMValTool/issues/1826

### CODE REVIEW

**Comment by stefsmeets** [comment]
CircleCI has an issue getting the image:
```
error pulling image configuration: unknown blob
```

**Comment by jvegasbsc** [comment]
I tried to update with master, to see if that was the problem, but it still fails.

I am rebuilding the development container

**Review by valeriupredoi — APPROVED** [review]
you can alway rerun the tests if you think they've failed with a transitory cause; looks good to me but could you pls give us a one-line explanation as to why this is needed? :beer:

**Comment by stefsmeets** [comment]
> you can always rerun the tests if you think they've failed with a transitory cause; looks good to me but could you pls give us a one-line explanation as to why this is needed? 🍺

This is based on a user-request in ESMValTool (https://github.com/ESMValGroup/ESMValTool/issues/1826). I was working on that part of the code anyway, and it seemed simple and sensible enough to add.

**Comment by valeriupredoi** [comment]
awesompossum :rat:

**Pull request merged**
