### PR TITLE
Produce a readable warning if ancestors are a string instead of a list.

### LINKED ISSUE #686: Warning for "Invalid ancestor" hard to read if ancestors is s string instead of a list
**Describe the bug**
In esmvalcore/_task.py a warning should be produced, if the ancestor file in attributes is not found. To identify the filename, attributes['ancestors'] should contain a list with the filename. If a string is found there instead of a list, the loop "for ancestor_file in ancestor_files:" runs over every character of this string and produces a cryptic warning, see below for an example. It would be better to warn if a string is in attributes['ancestors'].

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory

The diagnostics which issued these warnings have been fixed now, the main_log_debug.txt is attached for the non corrected version of the diagnostic  esmvaltool/diag_scripts/droughtindex/collect_drought_func.py used in esmvaltool/recipes/recipe_martin2018grl.yml
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/4844374/main_log_debug.txt)

See also  https://github.com/ESMValGroup/ESMValTool/pull/1689

### PR DESCRIPTION
**Pull request by katjaweigel**
Before you start, please read our [contribution guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html).

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [ ] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [ ] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

Tested with recipe_hyint.yml (how do I make a unit test?).

Documentation is not effected because it should just change a warning? 
* * *

Closes  #686 and helps to create better readable warnings for some of the warnings reported in e.g https://github.com/ESMValGroup/ESMValTool/issues/1716

### CODE REVIEW

**Comment by mattiarighi** [comment]
Can you remove the draft status?

**Comment by katjaweigel** [comment]
Yes, as soon as the test with the last small change runs through
 (should take about 10 mintutes).

**Comment by katjaweigel** [comment]
Did run successfully so I removed the draft

**Comment by koldunovn** [comment]
Hi @katjaweigel @mattiarighi 
It looks like the additional problem with this part of the code, might be that it assumes `ancestor_files` always exist. First there is a check `if not ancestor_files:` that will issue a warning, but later it still tries to do `for ancestor_file in ancestor_files:`.

I don't know if we whant to try to solve it here or in another PR. I would just probably do something like:

```python
            if not ancestor_files:
                logger.warning(
                    "No ancestor files specified for recording provenance of "
                    "%s, created by diagnostic script %s in task %s", filename,
                    self.script, self.name)
                valid = False
            ancestors = set()
            if isinstance(ancestor_files, str):
                logger.warning(
                    "Ancestor file(s) %s specified for recording provenance "
                    "of %s, created by diagnostic script %s in task %s is "
                    "a string instead of a list", ancestor_files, filename,
                    self.script, self.name)
                ancestor_files = [ancestor_files]
            if valid:
                for ancestor_file in ancestor_files:
                    if ancestor_file in ancestor_products:
                        ancestors.add(ancestor_products[ancestor_file])
                    else:
                        valid = False
                        logger.warning(
                            "Invalid ancestor file %s specified for recording "
                            "provenance of %s, created by diagnostic script %s "
                            "in task %s", ancestor_file, filename, self.script,
                            self.name)
```
But this adds another if :)

**Comment by bouweandela** [comment]
> It looks like the additional problem with this part of the code, might be that it assumes ancestor_files always exist. First there is a check if not ancestor_files: that will issue a warning, but later it still tries to do for ancestor_file in ancestor_files:

The only assumption is that the value associated with the `ancestors` key is of type `list`. If no `ancestors` key is present, an empty list will be used and the for loop will work as expected (nothing happens if you loop over an empty list). Unfortunately it turned out that even that was too strong an assumption.

For the next release I'm planning to add a check that the type is correct, see #124, but I wanted to start with just some warnings so not all recipes are suddenly broken.

**Comment by bouweandela** [comment]
cherry-picked this into v2.0.0 branch

**Pull request merged**
