### PR TITLE
Options arg in read_config_user_file now optional

### PR DESCRIPTION
**Pull request by jvegasbsc**
To fix and issue with the cmorizers

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #issue_number

### CODE REVIEW

**Comment by mattiarighi** [comment]
Can you check the failing test?

**Comment by bascrezee** [comment]
Doesn't work yet for me: 

``` 
$   cmorize_obs --config-file config-ETH-LANDCLIM.yml -o CDS-SATELLITE-SOIL-MOISTURE

Traceback (most recent call last):
  File "/conda/envs/esmvaltool-public/bin/cmorize_obs", line 11, in <module>
    load_entry_point('ESMValTool', 'console_scripts', 'cmorize_obs')()
  File "/ESMValTool/esmvaltool/cmorizers/obs/cmorize_obs.py", line 175, in main
    output=run_dir, console_log_level=config_user['log_level'])
TypeError: configure_logging() got an unexpected keyword argument 'output'
```

**Comment by mattiarighi** [comment]
I think is `config_file` wiht `_`

**Comment by bascrezee** [comment]
No, `config-file`  seems the correct one.

**Comment by mattiarighi** [comment]
It's an error at line 174 in `cmorize_obs.py`:
```
    log_files = configure_logging(
        output=run_dir, console_log_level=config_user['log_level'])
```

The argument `output` is not called `output_dir`. I will open a PR.

**Comment by schlunma** [comment]
Can we merge this branch into `master`? I think the Bouwe's plan was to cherry-pick the necessery changes for the release into `v2.0.0` after they have been merged into `master`.

**Comment by schlunma** [comment]
Right now `cmorizer_obs` does neither work in the `master` branch (`TypeError: read_config_user_file() missing 1 required positional argument: 'options'`) nor in the `v2.0.0` branch (`TypeError: configure_logging() got an unexpected keyword argument 'output'`).

**Comment by bascrezee** [comment]
Sounds like a good idea to me. I need the cmorization on a near-daily basis so would be glad if this is fixed again.

**Comment by schlunma** [comment]
All right, I will open a new PR.

**Comment by bouweandela** [comment]
> Can we merge this branch into master? I think the Bouwe's plan was to cherry-pick the necessery changes for the release into v2.0.0 after they have been merged into master.

Indeed, this was not the plan. Pull requests should only be merged to the master branch, never into the v2.0.0 release branch. This pull request has merged all other pull requests that were merged since the v2.0.0 feature freeze into the v2.0.0 branch. The changes were very minor, so I think it's OK to leave it as is for now, but we should be more careful about this next time.

**Pull request merged**
