### PR TITLE
Fix bug with matplotlib backend environmental variable

### LINKED ISSUE #549: "_tkinter.TclError: couldn't connect to display" and MPLBACKEND="Agg" missing in re-run command
**Describe the bug**
I'm actually not sure if this is a ESMValCore or an ESMValTool issue: I switched to the latest version of ESMValCore and ESMValTool yesterday and since then I get a error related to the x-server, if I try to run a diagnostic in the queue on Mistral in the log file of the diagnostic:
"self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "localhost:40.0""
at the same time I saw, that "MPLBACKEND="Agg"" is missing in the "re-run" command in main_log.txt 
Also including:
`
import matplotlib 
`
`matplotlib.use('Agg')`
in the diagnostic helped to run it in the queue again, but I thought this was not the way we should solve it?
I don't think it is related to the recipe/diagnostic I used, I'll try another soon. If I do the re-run including  "MPLBACKEND="Agg"" it works (possibly also without, I have to try, on mistralpp it has access to the x-server, but not in the queue).
I don't really know where to start searching for the reason of this issue?
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValTool/files/4286401/main_log_debug.txt)

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
Github refuses to upload *.yml, see:
https://github.com/ESMValGroup/ESMValTool/tree/linatcc_for_gmdpart4/esmvaltool/recipes/recipe_li17natcc.yml
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory

### PR DESCRIPTION
**Pull request by bouweandela**
Before you start, please read [CONTRIBUTING.md](https://github.com/ESMValGroup/ESMValCore/blob/master/CONTRIBUTING.md).

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #549

### CODE REVIEW

**Comment by valeriupredoi** [comment]
so here's a funny thing - my diag went through no problemo (rerun too) even if `MPLBACKEND` is not declared in my environment :beer:

**Comment by bouweandela** [comment]
You're probably running an X-server then. You only need this e.g. on a cluster.

**Comment by valeriupredoi** [comment]
I am not and I am on a cluster (Jasmin) :grin:

**Comment by valeriupredoi** [comment]
am blabbering -> `xset q` tells me Jasmin is actually running an X-server since I forgot about my ssh alias to always login with `-X` on :rofl:

**Pull request merged**
