### PR TITLE
Added CESM2 CMORizer

### PR DESCRIPTION
**Pull request by schlunma**
## Description

This PR implements a prototype of the on-the-fly CMORizer for the CESM2 model.

Link to documentation: https://esmvaltool--1678.org.readthedocs.build/projects/ESMValCore/en/1678/quickstart/find_data.html#cesm

Depends on #1718 

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by remi-kazeroni — COMMENTED** [review]
Thanks for your contribution @schlunma, nice to have another model supported! This PR looks fine to me. Reusing shared fixes for native model output significantly reduces the number of code lines. I have a couple of minor suggestions, feel free to have a look. In particular, I would suggest to slightly expand the documentation to clarify which variables are currently supported and maybe how support could be added in the future for other cases.

**Comment by schlunma** [comment]
Thanks for the review @remi-kazeroni! I expanded the doc and addressed all your comments. Let me know if you need anything else! :+1:

**Review by remi-kazeroni — APPROVED** [review]
Thanks for the changes @schlunma! This looks good to me as it is 👍

**Comment by valeriupredoi** [comment]
fellas @schlunma @remi-kazeroni I am ready to merge this if there are no major objections so I can include it in the 2.7 freezer :snowman_with_snow: Please yell at me if otherwise, if not I will merge it by the end of day today :+1:

**Comment by valeriupredoi** [comment]
OK fellas, she's going in :ship:

**Comment by schlunma** [comment]
Thanks V! Sorry for the late reply, we had a public holiday yesterday 😄

**Pull request merged**
