### PR TITLE
Use precommit flake8 instead of pytest-flake8

### LINKED ISSUE #1699: Consider dropping `pytest-flake8` plugin
It seems there's not much love between `flake8` and `pytest-flake8` (see eg https://github.com/tholo/pytest-flake8/issues/87#issuecomment-1216704377 ) and if you look up that issue there are people saying `pytest-flake8` is going its own way proper, and it's not condoned by the Pytest community - we've already had issues before and even now, and asking the `flake8` devs to fix stuff only worsens the situation, since they are not communicating with the plugin devs. Can we suggest alternatives for the plugin plss @ESMValGroup/technical-lead-development-team

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Loads of issues between `pytest-flake8` and `flake8` - they diverged proper, and it appears they started doing so since last year. We are currently pinning `flake8<5` to address an inherent issue in `pytest-flake8` but this is not a long term solution. This PR starts the case to run `flake8` as a pre-commit hook. See #1699 and refs inside it - loads other projects are dropping flake8 from the pytest env.

Closes #1699 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
OK @ESMValGroup/technical-lead-development-team I need your opinion here - this nifty Github Precommit tool works well and does a whole lot of things automatically (see the number of files it corrected) in here, it runs flake8 tests and all the style jazz before the push, and runs the Precommit CI (activation in https://github.com/organizations/ESMValGroup/settings/installations/28337967 ) BUT - do we want such an invasive tool? Also, do we want a tool that runs stuff for users that might get a bit uncomfortable with stuff running on their screens when committing, and they may not know what's going on? Can discuss this on the next Tech call, which I should send a Doodle for imminently. In the meantime I'll temporarily deactivate the Precommit tool (and CI) from the repo's Settings :beer:

**Comment by schlunma** [comment]
I like the idea of having a common code format across the entire code base! I also like that the formatting (and other hooks) are applied to every commit automatically.

What kind of formatter is used at the moment? `yapf`? I also like [`black`](https://pypi.org/project/black/) as it feels 100% uncompromising, but that's just my personal preference :smile:

**Comment by valeriupredoi** [comment]
@schlunma it is yapf indeed - @bouweandela introduced it to ESMVal many many moons ago, we're sticking with it looks like. I heard about black - never used it tho - maybe we can talk about all this extremely nerdy stuff on our next tech call? (I am producing a Dioodle for that as we speak, I promise :grin: )

**Comment by bouweandela** [comment]
I'm not too keen on using pre-commit.ci because
1) Some of our contributors are already confused by the many different services (readthedocs, circleci, codacy, github actions), so adding one more will increase confusion
2) If you do not use pre-commit locally and pre-commit.ci makes a commit on your branch and you forget to pull the branch before making your next commit, you often end up with a merge conflict. This makes it more difficult to work with the code for those of us who are not too git savvy.

**Comment by valeriupredoi** [comment]
absolutely agreed @bouweandela :100: Gonna close this since I am very uneasy with it - please reopen if decisins are made to use it after all :+1:

**Pull request closed without merging**
