### PR TITLE
added RMS iris analysis operator

### PR DESCRIPTION
**Pull request by pcosbsc**
Adding RMS iris analysis operator (which allow Area Weighting) to the preprocessor. This allows computing root mean squares in the _area.py and _time.py preprocessors.

**Tasks**
-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.

* * *

closes https://github.com/ESMValGroup/ESMValCore/issues/739

### CODE REVIEW

**Comment by bouweandela** [comment]
Thanks for the pull request! Could you please have a look at the failing test on CircleCI? Just click the `commit` link below, it looks like there is something wrong with the formatting of one of the docstrings. You can build the documentation on your own computer by following these instructions: https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#how-to-build-the-documentation-locally

**Comment by bouweandela** [comment]
Would you also be able to add some unit tests, e.g. similar to:
https://github.com/ESMValGroup/ESMValCore/blob/8e41213af7211328ca2ebc64502b6c9e4d48c29f/tests/unit/preprocessor/_time/test_time.py#L364-L373
and
https://github.com/ESMValGroup/ESMValCore/blob/8e41213af7211328ca2ebc64502b6c9e4d48c29f/tests/unit/preprocessor/_area/test_area.py#L79-L83
?

**Comment by pcosbsc** [comment]
Hi @bouweandela 

I've never done unit testing so correct me if I'm wrong: Should I add a couple of functions to test_area.py and test_time.py in order to check that rms works fine?

Thanks!

**Comment by bouweandela** [comment]
Yes, that's the idea. You can just copy/paste the code of the examples mentioned above, replace 'median' by 'rms' and make sure the expected numbers match the computed result. To run the tests in a particular file, you can run `pytest tests/unit/preprocessor/_time/test_time.py`, see also

**Comment by pcosbsc** [comment]
Thanks for checking @bouweandela !

@sloosvel coould you have a look at it? Thanks.

**Comment by sloosvel** [comment]
Looks fine to me, good job @pcosbsc .

**Comment by bouweandela** [comment]
@sloosvel or @jvegasbsc Would you have time to run a few recipes using the new functionality for testing, so we can still include this in v2.1?

**Comment by sloosvel** [comment]
Works fine in both the area and time preprocessors.

**Pull request merged**
