### PR TITLE
Remove derived variable gtfgco2

### PR DESCRIPTION
**Pull request by bouweandela**
Because it can be computed from fgco2 with the area_statistics preprocessor, see https://github.com/ESMValGroup/ESMValCore/pull/83#issuecomment-551676316

Before you start, please read [CONTRIBUTING.md](https://github.com/ESMValGroup/ESMValCore/blob/master/CONTRIBUTING.md).

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html) -> I don't think this is documented anywhere
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below -> The only recipe where this derived variable is mentioned is [recipe_ocean_bgc.yml](https://github.com/ESMValGroup/ESMValTool/blob/19262286ef14fa84acf3a0dc09ac0bc739d9c464/esmvaltool/recipes/recipe_ocean_bgc.yml#L225), but it is commented out.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Partially addresses https://github.com/ESMValGroup/ESMValCore/issues/42

### CODE REVIEW

**Comment by ledm** [comment]
I'm just in the process of preparing a PR for the GMD paper (https://github.com/ESMValGroup/ESMValTool/pull/1621) and I need to re-open this issue (sorry). I  realise that I'm a bit late to the party here, but it's still not strictly possible to fully replace this derived variable with a preprocessor at the moment.  (Similarly for the global total integrated primary production derived variable, which is not mentioned here but also needed for this publication.)

The `area_statistics` preprocessor sum operator multiplies and sums the data and the area, and this process change the units. In this case, the units change from from `kg m-2 s-1` in fgco2 to `kg s-1` for the global total dervied variable gtfgco2, which is then converted into `Pg/year`.

Even now, it's not clear that there's a solution where preprocessors can change the dimensions of the output units. @valeriupredoi like to bring up Iris's `cube.convert_units(new_units)` function, but this function will be able to change the dimensionality of the units, and it is not sensible for it to do so either.  Also the preprocessed version may only use the units listed in the CMOR tables, but the  derived output netcdf can have any units.

Can we annul this PR and re-instate the global total fgco2?

**Comment by ledm** [comment]
Instead of annulling this PR, is there a solution where area_statistics sum can change the cube's units?

**Comment by valeriupredoi** [comment]
no, I don't think it's a good idea to revert this PR. Instead, maybe you can create a preprocessor that calculates a flux like in the derivation script that got deleted but rather using dask arrays for laziness (that may be useful for other variables and being a preprocessing function preserves a good degree of generality)? :beer:

**Comment by ledm** [comment]
@valeriupredoi, I think that you're missing the point here. The `area_statistics` sum operation calculates the area-weighted sum. This means that it multiplies the value, either a concentration [per cubic meter] or a flux [per square meter] by the area [square meters]. This changes the units, which isn't reflected by the preprocessor at the moment.  

This means that every preprocessor that uses the `area_statistics` sum operation with fx files is scientifically incorrect. However, if you attempt to change the units in a preprocessor, the netCDF is no longer CMOR compliant. This is why we needed a global total air sea flux of CO2 derived variable.

**Comment by bouweandela** [comment]
@ledm Changing the units shouldn't be that big of a problem, so long as you do it after the cmor checks are performed, so I guess you could work around issues #212 and #505 by using a custom order for now. Would that be an option? See also discussion in #212.

**Pull request merged**
