### PR TITLE
Adding standard names to the custom tables of the `rlns` and `rsns` variables

### PR DESCRIPTION
**Pull request by remi-kazeroni**
## Description

This PR adds `standard_name` to the custom tables for the variables `rlns` and `rsns`. This is necessary for the derivation of the `rlus` and `rsus` variables in ERA5 otherwise a wrong standard name containing "upward" is used and the derivation fails (see [comment](https://github.com/ESMValGroup/ESMValTool/issues/2396#issuecomment-960826885)).

Related to https://github.com/ESMValGroup/ESMValTool/issues/2396

Link to documentation:
- https://github.com/ESMValGroup/ESMValCore/blob/main/esmvalcore/cmor/tables/custom/CMOR_rlns.dat
- https://github.com/ESMValGroup/ESMValCore/blob/main/esmvalcore/cmor/tables/custom/CMOR_rsns.dat

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- ~~[ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added~~
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- ~~[ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~~
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]

**Review by zklaus — CHANGES_REQUESTED** [review]
Hold

**Review by zklaus — CHANGES_REQUESTED** [review]
Looks  good. I like how you actually chose a standard name, unlike some of the others as I just discovered.

However, this seems a good opportunity to fix the comment as well. It is speaking of the top of the atmosphere (aka TOA), but this quantity is actually about the surface. Could you fix that? Perhaps be inspired by the standard name description or the ERA5 documentation.

**Comment by valeriupredoi** [comment]
the old functionality was not using the `standard_name` from the custom files (back in the distant past, 2017-2018 AD) that's why most of the custom vars don't have a standard name

**Comment by zklaus** [comment]
Not having a standard_name is one thing (acceptable), having a "standard_name" that actually isn't a standard_name is another thing. But anyway that's for a different ticket. Here I'd just like to align the comment with the quantity.

**Review by lukasbrunner — APPROVED** [review]

**Comment by remi-kazeroni** [comment]
> 
> 
> Looks good. I like how you actually chose a standard name, unlike some of the others as I just discovered.
> 
> However, this seems a good opportunity to fix the comment as well. It is speaking of the top of the atmosphere (aka TOA), but this quantity is actually about the surface. Could you fix that? Perhaps be inspired by the standard name description or the ERA5 documentation.

Thanks for the feedback. It makes sense to update the comments accordgliny to the documentation. After this is merged, I'll make a quick fix PR for the recipe_check_obs to account for these changes.

**Review by zklaus — APPROVED** [review]

**Comment by zklaus** [comment]
@remi-kazeroni, perfect, thanks. Could you perhaps also open an issue here that reminds us to review the existing custom table entries? In checking this one, I saw missing standard names, wrong standard names, and wrong comments. But that, we can take later. It would only be good to have an issue about it, perhaps with the 2.5.0 milestone assigned.

**Pull request merged**
