### PR TITLE
Extended fix for cl-like variables of CESM2 models

### PR DESCRIPTION
**Pull request by schlunma**
This PR extends the fixes for `cl`, `cli` and `clw` for the CESM2 models (the original fix only flips the vertical coords, but not the data itself).

I also had to move the function `var_name_constraint` to a new module (`iris_helpers`) because of circular dependencies in `esmvaltool.cmor._fixes.shared` and `esmvaltool.preprocessor.shared`. I'm happy to rename that module if anybody knows a better name.

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [ ] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Related to #538 and #539.

### CODE REVIEW

**Comment by schlunma** [comment]
Are the failing tests related to #189? @bouweandela @valeriupredoi

**Comment by valeriupredoi** [comment]
can you merge the latest `master` in this one pls @schlunma :beer:

**Comment by schlunma** [comment]
I did (one hour ago).

**Comment by valeriupredoi** [comment]
`flake8=1.0.5` is being superflaky

**Comment by schlunma** [comment]
Ready to merge from my side

**Comment by bouweandela** [comment]
@mattiarighi Could you please test?

@schlunma Is there no other way to fix the formula terms than changing the file? Because this is really inefficient and I was hoping to get rid of that function at some point..

**Comment by axel-lauer** [comment]
@mattiarighi I'll rerun the tests and merge this PR in case the tests are successful.

**Comment by schlunma** [comment]
> @schlunma Is there no other way to fix the formula terms than changing the file? Because this is really inefficient and I was hoping to get rid of that function at some point..

I invested quite some time in this and came to the following conclusion: It is possible without modifying the file, but the code necessary for this is considerably longer (it involves adding all coordinates, their bounds and manually adding the coordinate factory). Since the attribute `formula_term` is simply wrong, fixing this also feels like the "natural" way to fix this file.

**Comment by bouweandela** [comment]
> it involves adding all coordinates, their bounds and manually adding the coordinate factory

Maybe there is some code in iris that you could copy/paste? It would be a lot faster, since file fixes copy the entire file before starting to do anything. If you don't have the time right now, maybe keep it as an idea for the future?

**Comment by schlunma** [comment]
Yes, I agree that this is slower. I will keep it in mind, but as I already said, it's way more complicated and also doesn't feel like the right fix.

**Comment by axel-lauer** [comment]
Tests were successful, PR is read to be merged...

**Pull request merged**
