### PR TITLE
[v2.7.1 bugfix release] Finalize v2.7.1 bugfix: add changelog for v2.7.1 bugfix release

### PR DESCRIPTION
**Pull request by valeriupredoi**
Add Changelog for v2.7.1 (V's own creation) and semantic versioning from PR #1854 

Added [changelog](https://esmvaltool--1858.org.readthedocs.build/projects/ESMValCore/en/1858/changelog.html)

### CODE REVIEW

**Comment by bouweandela** [comment]
Sorry, I acccidentally merged `main` into this branch because I clicked the update button and the target branch is set to `main` instead of `v2.7.x`. Is that on purpose?

It would be nice to separate updating the version numbering from adding the changelog.

**Comment by valeriupredoi** [comment]
> It would be nice to separate updating the version numbering from adding the changelog

OK, the PR torture continues then :laughing:

**Comment by bouweandela** [comment]
Could you also add the changes from #1864 to the log?

**Comment by valeriupredoi** [comment]
Yis, was just about to holler at you not to merge this just yet coz I need to add that - but will add it as #1838 rather than #1864 :+1:

**Pull request merged**
