### PR TITLE
Disable automatically detecting the use of frameworks in Prospector

### LINKED ISSUE #1703: Codacy issue `Django was not configured` keeps popping up in pull requests
Recently, we saw the Codacy issue

```
Django was not configured. For more information run pylint --load-plugins=pylint_django --help-msg=django-not-configured 
```

popping up in some PRs (e.g., [here](https://app.codacy.com/gh/ESMValGroup/ESMValCore/pullRequest?prid=10002238&bid=30646651)).

@ESMValGroup/esmvaltool-coreteam do we use Django anywhere in the code? I couldn't find a reference to it. Running the suggested command above gives

```bash
$ pylint --load-plugins=pylint_django --help-msg=django-not-configured
:django-not-configured (E5110): *Django was not configured. For more information run pylint --load-plugins=pylint_django --help-msg=django-not-configured*
  Finding foreign-key relationships from strings in pylint-django requires
  configuring Django. This can be done via the DJANGO_SETTINGS_MODULE
  environment variable or the pylint option django-settings-module, eg: `pylint
  --load-plugins=pylint_django --django-settings-module=myproject.settings` .
  This can also be set as an option in a .pylintrc configuration file. Some
  basic default settings were used, however this will lead to less accurate
  linting. Consider passing in an explicit Django configuration file to match
  your project to improve accuracy. This message belongs to the django foreign
  keys referenced by strings checker.
```

So I guess we are using the `pylint-django` plugin? Could we disable this?

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Disable automatically detecting prospector plugins that we do not use.

Link to documentation: https://prospector.landscape.io/en/master/profiles.html#libraries-used-and-autodetect

Closes #1703

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label) -> What label do I use for this?
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by schlunma — APPROVED** [review]
Looking good! Please make sure to add a label before merging :rocket:

**Comment by valeriupredoi** [comment]
one sec, I want to run a GA testy-test on it

**Comment by bouweandela** [comment]
:smile: Do you have a suggestion for a label? I couldn't find any that matches.

**Comment by valeriupredoi** [comment]
#bearatadinnerparty :bear:

**Comment by schlunma** [comment]
> 😄 Do you have a suggestion for a label? I couldn't find any that matches.

Not really, also thought of the good old bear 🐻 😃

**Comment by valeriupredoi** [comment]
awesome job @bouweandela - ran a set of GA [tests](https://github.com/ESMValGroup/ESMValCore/actions/runs/3038599861/jobs/4892506664) just to make sure Django is unchained (doesn't get picked up, +1 if you get the movie reference haha) :beer:

**Review by valeriupredoi — APPROVED** [review]

**Comment by schlunma** [comment]
Wait...The GH test you showed lists `pylint-django`:

```
Run conda list django
# packages in environment at /usr/share/miniconda3/envs/esmvalcore:
#
# Name                    Version                   Build  Channel
pylint-django             2.5.3                    pypi_0    pypi
```

Shouldn't this PR prevent this?

**Comment by valeriupredoi** [comment]
indeed `pylint-django` is still there, but not `django` itself as `prospector` doesn't bring it in anymore. Not 100% sure who brings in `pylint-django` but at least it's not the hefty Django package (whoever brings it in it's after pip install, so maybe even prospector?)

**Comment by schlunma** [comment]
But was `django` itself ever pulled in? It does not appear in [latest GH action tests](https://github.com/ESMValGroup/ESMValCore/actions/runs/3041679141)...

**Comment by valeriupredoi** [comment]
yes, big hefty Django comes in brought in by prospector (cheers @zklaus for pointing that out, I thought Django was brought in by pylint-django)

**Comment by valeriupredoi** [comment]
alas, having said all that, reading the [documentation](https://prospector.landscape.io/en/master/profiles.html#libraries-used-and-autodetect) that Bouwe linked from the PR description, it *seems* that now prospector shouldn't bring in the `plugin-django` either so now I'm starting to get confusado

**Comment by schlunma** [comment]
But why does it not appear in the GH action tests? And if `pylint-django` is still there, isn't there the chance that we still get these wrong Codacy issues?

**Comment by valeriupredoi** [comment]
> But why does it not appear in the GH action tests? And if `pylint-django` is still there, isn't there the chance that we still get these wrong Codacy issues?

it does, but only after pip installing, when prospector gets installed; and yes, those issues were from the plugin complaining Django wasn't properly installed right? Well, now it's not at all installed anymore so I wonder if it'll complain anymore :rofl:

**Comment by valeriupredoi** [comment]
so now `Django was not configured.` will probably turn into `Looking for Django, seems to be chained still.` :laughing:

**Comment by valeriupredoi** [comment]
so here's the thing - I'm not sure we can get rid of that `pylint-django` dep brought in by `prospector`. I did an experiment whereby I didn't install `prospector` while pip installing it (removed it from our PyPi setup), and am trying to install it from conda-forge instead: it brings in all this crap:
```
  Install:
───────────────────────────────────────────────────────────────────────────────────────

  + asgiref                   3.5.2  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + astroid                  2.12.9  py310hff52083_0  conda-forge/linux-64     Cached
  + colorama                  0.4.5  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + dill                    0.3.5.1  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + django                    4.1.1  py310hff52083_0  conda-forge/linux-64     Cached
  + dodgy                     0.2.1  py_0             conda-forge/noarch       Cached
  + flake8                    3.8.4  py_0             conda-forge/noarch       Cached
  + flake8-polyfill           1.0.2  py_0             conda-forge/noarch       Cached
  + importlib-metadata       4.11.4  py310hff52083_0  conda-forge/linux-64     Cached
  + isort                    5.10.1  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + lazy-object-proxy         1.7.1  py310h5764c6d_1  conda-forge/linux-64     Cached
  + logilab-common            1.7.3  py_0             conda-forge/noarch       Cached
  + mccabe                    0.6.1  py_1             conda-forge/noarch       Cached
  + mypy_extensions           0.4.3  py310hff52083_5  conda-forge/linux-64     Cached
  + pep8-naming              0.10.0  pyh9f0ad1d_0     conda-forge/noarch       Cached
  + platformdirs              2.5.2  pyhd8ed1ab_1     conda-forge/noarch       Cached
  + prospector              1.4.1.1  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + pycodestyle               2.6.0  pyh9f0ad1d_0     conda-forge/noarch       Cached
  + pydocstyle                6.1.1  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + pyflakes                  2.2.0  pyh9f0ad1d_0     conda-forge/noarch       Cached
  + pylint                   2.15.2  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + pylint-celery               0.3  py_1             conda-forge/noarch       Cached
  + pylint-django            2.0.11  py_0             conda-forge/noarch       Cached
  + pylint-flask                0.6  py_0             conda-forge/noarch       Cached
  + pylint-plugin-utils         0.7  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + requirements-detector       0.7  py310hff52083_3  conda-forge/linux-64     Cached
  + setoptconf                0.3.0  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + snowballstemmer           2.2.0  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + sqlparse                  0.4.2  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + tomli                     2.0.1  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + tomlkit                  0.11.4  pyha770c72_0     conda-forge/noarch       Cached
  + typing                 3.10.0.0  pyhd8ed1ab_0     conda-forge/noarch       Cached
  + typing_extensions         4.3.0  pyha770c72_0     conda-forge/noarch       Cached
  + wrapt                    1.14.1  py310h5764c6d_0  conda-forge/linux-64     Cached
  + zipp                      3.8.1  pyhd8ed1ab_0     conda-forge/noarch       Cached
```
On the other hand, it's possible the Django from conda be correctly configured?

**Comment by valeriupredoi** [comment]
Ok - the crux of this PR is not really working: prospector still installs all the pylint plugins that nobody needs:
```
pylint-celery             0.3                      pypi_0    pypi
pylint-django             2.5.3                    pypi_0    pypi
pylint-flask              0.6                      pypi_0    pypi
```

I suggest we open an issue on the prospector GH, prob more on the pylint side actually and tell them it's not quite working out what they thought the `--no-autodetect` should do. I am trying to not get myself into the PyCQA GH area, so anyone else? :grin:

**Comment by schlunma** [comment]
Maybe we should merge this and test if the Codacy problem disappears? E.g., [here](https://github.com/ESMValGroup/ESMValCore/pull/1678)?

Maybe the installation of the plugin cannot be disabled, but the the actual use of it can...

**Comment by zklaus** [comment]
I am afraid this will not help. What this PR should achieve is that Prospector doesn't *run* pylint-django, but it is still installed as a dependency. If it is installed via conda-forge, that will also pull in django because of [this](https://github.com/conda-forge/pylint-django-feedstock/blob/71591243e3d13b2276f805f649ee808318599cde/recipe/meta.yaml#L22).

The problem is that the Codacy problem did not come from the Prospector tool, but directly from the Pylint tool, so we need to prevent Pylint from running pylint-django, not only Prospector. I was surprised though that Pylint did run it, since the Codacy configuration defers to our Pylint config file which makes no mention of the plugin and I could also not find anything about autodetection in Pylint itself, though I didn't look very thoroughly yet.

**Comment by valeriupredoi** [comment]
@zklaus good points! There is this old PR https://github.com/PyCQA/pylint-django/pull/137 that decoupled Django from Pylint, but it seems they're still chained somehow

**Comment by zklaus** [comment]
Good find, @valeriupredoi. It seems conda-forge is overdepending. I added an issue at conda-forge/pylint-django-feedstock#39.

However, that doesn't solve our issue with Pylint running the plugin outside of Prospector.

**Comment by bouweandela** [comment]
Plugins are indeed disabled in the pylint configuration file: https://github.com/ESMValGroup/ESMValCore/blob/55d630cd9de0642fcffac146337ae1adb379d34f/.pylintrc#L23, so I'm not sure Codacy is still running pylint-django.

**Comment by bouweandela** [comment]
I will close this now because it seems unlikely to solve our problem.

**Comment by valeriupredoi** [comment]
@bouweandela I think this would have been useful after all - in theory, this should have done the job, so it's solid implementation from you (us as a package), so I would merge this, and flag the issue at `prospector`'s end?

**Comment by bouweandela** [comment]
This is really not needed. If you look at the error message on Codacy carefully, like I didn't do and @zklaus did, then you'll see that they are generated by pylint and not prospector.

**Pull request closed without merging**
