### PR TITLE
Add institute name used on ESGF for CMIP5 CanAM4, CanCM4, and CanESM2

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

This adds the institute name `CCCMA` used on ESGF for the CMIP5 datasets CanAM4, CanCM4, and CanESM2. Without this institute name, the tool is not able to find the files for these datasets on ESGF.

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
Thanks for opening this PR @bouweandela! I am currently testing #1609 again and I am getting lots of errors due to this. Can you make this ready for review? I tested it and it worked fine :+1: 

Question on this: Why did this only occur now? Could this also happen for other CMIP5 datasets or are we sure that these models are the only case?

**Comment by bouweandela** [comment]
> Why did this only occur now?

Prior to #1920 the value for `institute` was ignored when searching ESGF. When I originally implemented ESGF search, I ran into issues like this (i.e. files with wrong facet values), so I only selected a rather minimal set of facets to use. However, that doesn't play nice with the automatic finding of datasets.

> Could this also happen for other CMIP5 datasets or are we sure that these models are the only case?

Yes, there are quite a few files on ESGF that have wrong facet values. However, this was the most obvious case. A simple way to check this is to use `Dataset.from_files()` with an `*` for as many facets as possible (e.g. only define `project`, `mip`, and `short_name` as not wildcard) and then checking if the tool can find the files for each of the datasets that come out.

**Comment by bouweandela** [comment]
> I am currently testing https://github.com/ESMValGroup/ESMValCore/pull/1609 again and I am getting lots of errors due to this. Can you make this ready for review? I tested it and it worked fine :+1: 

There are several tests failing because they use this dataset as an example. Those tests may have been changed in #1609, so I was planning to fix them only once #1609 is merged to avoid fixing outdated stuff. Would it work for you to just merge this into your testing branch for #1609 for now?

**Comment by schlunma** [comment]
I see, that makes sense. How exactly does the tool handle lists as additional facets? Is it simply checking for all possible combinations and is happy when it finds at least one file?

> Would it work for you to just merge this into your testing branch for https://github.com/ESMValGroup/ESMValCore/pull/1609 for now?

Yeah, that's what I already did.

**Comment by bouweandela** [comment]
> How exactly does the tool handle lists as additional facets? 

It will try to [concatenate the data](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/overview.html#recipe-section-datasets). In this case the institute `CCCMA` is used on ESGF and the institute `CCCma` is used on the local file system, so this shouldn't be an issue.

**Comment by valeriupredoi** [comment]
thanks lots @bouweandela - as directly affected via Tool's #2994 and scratching my head interminably before you told me it was the blithering CanESM2, I fully embrace this arms open. Can I fix the tests for you so we get this ready-ready?

**Comment by bouweandela** [comment]
That's a great offer, thanks! Could you do if after #1609 is merged, to avoid fixing outdated things and creating merge conflicts?

**Comment by valeriupredoi** [comment]
> That's a great offer, thanks! Could you do if after #1609 is merged, to avoid fixing outdated things and creating merge conflicts?

sounds like a plan Batman :bat:

**Comment by bouweandela** [comment]
> Can I fix the tests for you so we get this ready-ready?

Just fixed it myself, there was only one test remaining that failed.

**Comment by valeriupredoi** [comment]
> > Can I fix the tests for you so we get this ready-ready?
> 
> Just fixed it myself, there was only one test remaining that failed.

there goes my chance for fame and glory then :grin:

**Review by valeriupredoi — APPROVED** [review]
cheers @bouweandela - but do we still have tests with `CCCma` and `CCCMA`?

**Comment by bouweandela** [comment]
No, and I don't think we need those. We have tests that adding extra facets works correctly. Hopefully, we can just get this issue corrected on ESGF (did not receive a reply to my email asking how to go about that so far) and then we no longer need the extra value in all uppercase.

**Comment by valeriupredoi** [comment]
sounds good to me, man! OK - I can merge this now if you all good :+1: Let me go do make some noise myself towards ESGF after a few more days have passed

**Pull request merged**
