### PR TITLE
Update iris pin

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

`iris=3.5` is out and has a bunch of nice features and bugfixes; I think we should update our pin

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by remi-kazeroni** [comment]
@valeriupredoi, what about waiting for [iris 3.6.0](https://github.com/SciTools/iris/discussions/5106) scheduled for Wednesday? And would such change of pin require a new release as for Python3.11?

**Comment by valeriupredoi** [comment]
hmm I was thinking we'd pin on 3.5 and obv can grab 3.6 once it's out - my idea was to grab the various bugfixes from 3.5. No need to release anything, just yet - this would be used only by the dev installations :+1:

**Comment by valeriupredoi** [comment]
@bouweandela they already have to upgrade quite a few bits in the env from the changes we made in the pins for supporting Python 3.11. I reckon we can slip this one through too. I am not ready to give up my dog for this so if you guys consider it unnecessary, am OK to close, but I do like my updated deps :grin:

**Comment by valeriupredoi** [comment]
> Because only recent versions of that dependency package support Python 3.11, this upper bound rules out all versions of that package on conda-forge that support Python 3.11.

Indeed. It's actually a combination of releasing the upper bound on esmpy (was <8.4) and placing a lower bound on prospector (now >=1.9, the only one that supports Py311)

**Comment by remi-kazeroni** [comment]
@valeriupredoi - is this still needed because the Dask distributed PR (#2049) put an lower pin to `iris>3.6.0`?

**Pull request closed without merging**
