### PR TITLE
Rechunk between preprocessor steps

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Many preprocessor function reduce the data in size, resulting in chunks that are too small. This pull request addresses the issue by rechunking between preprocessor functions. This results in smaller task graphs, reducing the risk of overloading the scheduler.

This helps with issue #2184.

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — COMMENTED** [review]
heh speaking of chunking and rechunking :grin:

**Comment by valeriupredoi** [comment]
I am curious how efficient `rechunk` is - obv not on a wee bit of data, but rather, on some hefty datasets

**Comment by bouweandela** [comment]
This pull request reduces the number of chunks on a fairly large recipe in https://github.com/ESMValGroup/ESMValTool/pull/3356 from 1.2 million to about 700 thousand, making it possible to run the recipe. That's still not great, but at least it works. See https://github.com/ESMValGroup/ESMValCore/issues/2184 for more details.

**Review by zklaus — APPROVED** [review]
I think this is a step in the right direction. In the future, improving pre-processors and possibly including targeted rechunking as a first step in the preprocessor could lead to even better performance, but it is big step forward.

**Comment by valeriupredoi** [comment]
I am a fan (of optimal chunks) so good to go :beers:

**Pull request merged**
