### PR TITLE
Refactored native model fixes by adding common base class `NativeDatasetFix`

### LINKED ISSUE #1690: Refactor native model fixes
The different native model fixes re-use the same code over and over. I will refactor this by introducing a base class `NativeDatasetFix`.

### PR DESCRIPTION
**Pull request by schlunma**
## Description

This PR simplifies native model fixes by adding a base class `NativeDatasetFix` with common operations necessary for almost all datasets. This will dramatically simplify https://github.com/ESMValGroup/ESMValCore/pull/1678.

Closes #1690

Link to documentation: https://esmvaltool--1694.org.readthedocs.build/projects/ESMValCore/en/1694/develop/fixing_data.html#fix-native-data

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
I have no idea why that Codacy error (`Django was not configured. For more information run pylint --load-plugins=pylint_django --help-msg=django-not-configured`) appears here. I think we can simply ignore it...

**Review by remi-kazeroni — APPROVED** [review]
Thanks for your contribution @schlunma! The code looks good to me. This should help lowering the bar to add support for native model output in the future. This is also a good step towards reducing code duplication w.r.t. model fixes. The CMORization of models related to this PR gives identical results to that of the main branch and other models are not affected (different classes) so I think this is ready to be merged 👍

**Comment by remi-kazeroni** [comment]
> I have no idea why that Codacy error (`Django was not configured. For more information run pylint --load-plugins=pylint_django --help-msg=django-not-configured`) appears here. I think we can simply ignore it...

I have seen that in some other unrelated PRs as well, so I would agree...

**Comment by schlunma** [comment]
Awesome, thanks for the review @remi-kazeroni ! :rocket:

**Pull request merged**
