### PR TITLE
Supported `mip`-level fixes

### LINKED ISSUE #1094: Introduce `mip` level fixes
As proposed by @tomaslovato in #1069, it would be nice to have fixes at `mip` level for each dataset. For example, this fix

```py
class Amon(Fix):
    """Fixes for all `Amon` variables."""
```

would be applied to all `Amon` variables of the given dataset. This would probably avoid lots of code duplication.

The implementation should be fairly easy as pointed out by @tomaslovato [here](https://github.com/ESMValGroup/ESMValCore/issues/1069#issuecomment-822432524).

I really like this idea! What say you @valeriupredoi @zklaus @jvegasbsc? We could discuss this in the general discussion of the workshop if necessary.

### PR DESCRIPTION
**Pull request by schlunma**
This PR adds the support for `mip`-level fixes, i.e. a fix for all variables of a MIP table for a single dataset. As test case, a fix for CESM2 is included, which supersedes #888.

@tomaslovato Can you briefly do a test if this works for CESM's `thetao` for the scientific review?
@jvegasbsc  Could you please do a brief technical review?

Thanks!!

Closes #1094.

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by tomaslovato** [comment]
@schlunma a couple of quick comments:
1) I think the test code for ocean variables Z axis 
https://github.com/ESMValGroup/ESMValCore/blob/b08d3d1b28c2bd9cb6801280305c26ff7877f16b/tests/integration/cmor/_fixes/test_shared.py#L508-L509
should better refer to the `lev` coordinate as in the following 
```python
 z_coord = iris.coords.DimCoord(0.0, var_name='lev', 
                                attributes={'positive': 'down'}) 
```

2) Did you tested already the new fix? As I remember that this comparison
https://github.com/ESMValGroup/ESMValCore/blob/65dc7d0f1449ed34eb20e7cab48dc4aec14ac761/esmvalcore/cmor/_fixes/cmip6/cesm2.py#L270
was not working until I changed to the `Units` instance of `cf_units` like in 
https://github.com/ESMValGroup/ESMValCore/blob/8b4a790557a3808711e7c25add7b6ec40150bfd5/esmvalcore/cmor/_fixes/cmip6/cesm2.py#L271

**Comment by schlunma** [comment]
1. I did that on purpose, so that we really make sure that also the `var_name` and the `positive` attribute get fixed. As you can see further down the line, they do :smile:
2. Hmm...for me that works just fine. I tested it with real data and it looks good. Maybe it was a bug in an old version of `cf_units`?

```py
>>> import iris
>>> path = '/mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP6_DKRZ/CMIP/NCAR/CESM2/historical/r1i1p1f1/Omon/thetao/gn/v20190308/thetao_Omon_CESM2_historical_r1i1p1f1_gn_185001-201412.nc'
>>> cube = iris.load_cube(path)
>>> lev_coord = cube.coord('lev')
>>> lev_coord.units == 'cm'
True
```

**Comment by tomaslovato** [comment]
@schlunma do you think that it might be ok to import also the ocean depth coordinate fixes for the other datasets I mentioned in #1069 ? If so I could also test the whole ce2coast recipe ...

**Comment by schlunma** [comment]
I think for this PR it's better to include only the actual support of `mip`-level fixes and one example of it for testing purposes. This way we keep the PR small and easier to review.

Once this is merged I'm happy to assist you with the remaining fixes. I noticed that there are some tests missing in the `ce2coast` branch. Could you maybe already include the to the `ce2coast` so we open the PR right after this is merged? If not, no problem, I can also add them later :+1:

**Comment by tomaslovato** [comment]
@schlunma I see your point about the missing tests ..  so probably it would be better to do as you said by first closing this PR.
After this one has been merged, I'll open a new PR to collect the fixes for the other 3 datasets reported in #1069 and add the related tests.
At this point it will be probably better to solve also #1018 in a separated PR.

**Comment by schlunma** [comment]
Perfect, sounds great :+1:

**Comment by tomaslovato** [comment]
@schlunma I was trying to run a recipe to process CESM2 dataset ([recipe_ocean_ce2coast_test.txt](https://github.com/ESMValGroup/ESMValCore/files/6425968/recipe_ocean_ce2coast_test.txt)) to get a 'working test' of the whole machinery, but I got swamped in the 'area statistics' computation with a message generated from here 
https://github.com/ESMValGroup/ESMValCore/blob/65dc7d0f1449ed34eb20e7cab48dc4aec14ac761/esmvalcore/preprocessor/_area.py#L211-L214
as the `area` cell_measure is not available from the cube core_data, although the fx_file is correctly read in the previous step.

**Comment by jvegasbsc** [comment]
Ping @sloosvel, as she was the one that implemented the handling of fx variables. I doubt it is due to the changes in this PR, though

**Comment by tomaslovato** [comment]
@schlunma @jvegasbsc I remove the obs data from the recipe and reduce only to one variable analysis ... 
Looking into the [main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/6426034/main_log_debug.txt) I realized the `cell_measure` attribute added from the fx_file survives until it reaches the `climate_statistics` preprocessor (around line 744 in the log).
`cell_measure` property is removed from the cube when the time statistics is computed with the `aggregate_by()` method in https://github.com/ESMValGroup/ESMValCore/blob/65dc7d0f1449ed34eb20e7cab48dc4aec14ac761/esmvalcore/preprocessor/_time.py#L561



when it got removed

**Comment by sloosvel** [comment]
I checked the preprocessed files, and indeed after the `climate_statistics` step the cell measures are gone. I think it's a matter of modifying those functions so that they preserve the added variables.

**Comment by schlunma** [comment]
Thanks for looking into this @sloosvel. So this error is not caused by changes in this PR. Can you maybe try to run your recipe without using special preprocessor and diagnostic (by using `preprocessor: default` and `scripts: null`) and check if the depth coordinate of the dataset in the `preproc` is correct?

**Comment by sloosvel** [comment]
It does look fine to me!

**Comment by schlunma** [comment]
> It does look fine to me!

Awesome! Would you also have time to briefly check the code for the technical review @sloosvel? Thanks!!

**Review by tomaslovato — APPROVED** [review]

**Comment by schlunma** [comment]
@tomaslovato I think your recipe should work if you remove the `custom_order: true` from the preprocessor 👍

**Comment by tomaslovato** [comment]
@schlunma The implementation works fine for 3D data with simple recipe. LookinG forward to continue with remaining problematic datasets!

**Review by sloosvel — APPROVED** [review]

**Pull request merged**
