### PR TITLE
set implicit optional to true in mypy config to avert side effects and test fails from new mypy version

### LINKED ISSUE #1788: Tests failing left, right, and centre on Circle and Github Actions
The new pytest-mypy is causing phenomenal test fails - frankly I've no idea why, I can't understand the standards complaints, if anyone more literate in PEP can, please explain @ESMValGroup/technical-lead-development-team - this PR https://github.com/ESMValGroup/ESMValCore/pull/1787 uses the pin on pytest-mypy (at 0.10.0, 0.10.1 is causing the whole hubbub)

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Suggested by @zklaus in https://github.com/ESMValGroup/ESMValCore/pull/1787#pullrequestreview-1176952599 which this PR supersedes #1787 

Closes #1788 

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
OK it looks like that did the trick partially: from 9 to 1 failed mypy test, can I get some help from the standards experts @zklaus @bouweandela @schlunma please - am no good at these things, and wouldn't know what to fix now :beer:

**Comment by schlunma** [comment]
You could either try using the option `--check-untyped-defs` as suggested or remove the type hints here:

https://github.com/ESMValGroup/ESMValCore/blob/b880462a8de64b0636e987ab84f7c1fb5ae1aabc/esmvalcore/_task.py#L739

and add them to a comment maybe?

**Comment by valeriupredoi** [comment]
well that escalated real quick - I'll see about removing the `Type` from `_task.py` :man_facepalming:

**Comment by valeriupredoi** [comment]
OK so I eventually got this through the mypy hoops but am not sure of the functionality I hacked out - @bouweandela could you have a look please? :beer:

**Review by schlunma — APPROVED** [review]
Thanks V.! :rocket: 

Sorry, this change is exactly what I meant by "remove the type hints", could have been clearer!

**Comment by valeriupredoi** [comment]
cheers, Manu! Can I nominate @bouweandela to have a looksee at it and merge, please :beer:

**Pull request merged**
