### PR TITLE
Fix sithick derivation when units of siconc are %

### PR DESCRIPTION
**Pull request by jvegasbsc**
Fixed a couple of issues in sithick derivation

-   [ ] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

### CODE REVIEW

**Comment by jvegasbsc** [comment]
Please, don't merge yet. For some reason I am getting an Iris error in Jasmin but not locally. I am reconstructing my Jasmin environment to check if it was corrupted or something like that

**Comment by valeriupredoi** [comment]
whats the error? is it in testing?

**Comment by jvegasbsc** [comment]
> whats the error? is it in testing?

An iris operator being none in the division. I only have it with the real data.

**Comment by valeriupredoi** [comment]
if you point me to the recipe I can give it a try on Jasmine :grin:

**Comment by jvegasbsc** [comment]
Reconstructed and working!

**Comment by jvegasbsc** [comment]
Required for ESMValGroup/ESMValTool#1079

**Pull request merged**
