### PR TITLE
Fix wrong name of cmor_path that prevented obs4mips cmor tables from being used

### LINKED ISSUE #235: obs4mips CMOR table not used
At the moment, the obs4mips CMOR table is present but not used, the CMIP6 table is used instead to look up obs4mips variables.

### PR DESCRIPTION
**Pull request by bouweandela**
Closes #235

### CODE REVIEW

**Comment by bouweandela** [comment]
The tests require the OBS6 project introduced in #237.

**Comment by mattiarighi** [comment]
#237 is merged.

**Comment by mattiarighi** [comment]
`recipe_perfmetrics_CMIP5.yml` returns an error:
```
Traceback (most recent call last):
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_main.py", line 228, in run
    conf = main(args)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_main.py", line 156, in main
    process_recipe(recipe_file=recipe, config_user=cfg)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_main.py", line 202, in process_recipe
    recipe = read_recipe_file(recipe_file, config_user)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_recipe.py", line 70, in read_recipe_file
    raw_recipe, config_user, initialize_tasks, recipe_file=filename)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_recipe.py", line 801, in __init__
    self.tasks = self.initialize_tasks() if initialize_tasks else None
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_recipe.py", line 1136, in initialize_tasks
    task_name=task_name)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_recipe.py", line 747, in _get_preprocessor_task
    _add_cmor_info(variable)
  File "/mnt/lustre01/pf/b/b309057/ESMValTool/core/esmvalcore/_recipe.py", line 121, in _add_cmor_info
    format(cmor_table, short_name, mip))
esmvalcore._recipe_checks.RecipeError: Unable to load CMOR table 'obs4mips' for variable 'hus' with mip 'Amon'
2019-09-10 09:33:28,241 UTC [12067] INFO    If you suspect this is a bug or need help, please open an issue on https://github.com/ESMValGroup/ESMValTool/issues and attach the run/recipe_*.yml and run/main_log_debug.txt files from the output directory.
```

**Comment by jvegasbsc** [comment]
Table names in obs4mips have a prefix: in this case `obs4MIPs_Amon`

I think we should add a default prefix to simplify definitions. I can do it in this pull request

**Comment by mattiarighi** [comment]
Problem remains.

**Comment by jvegasbsc** [comment]
Fixed. Sorry!

**Comment by mattiarighi** [comment]
It works now, thanks!
Can you solve the Codacy issue before merging?

**Comment by bouweandela** [comment]
> @bouweandela can you solve the Codacy issue before merging?

Codacy is wrong here, the required documentation is already in the class docstring, this is allowed. See the first example here: https://www.sphinx-doc.org/en/1.6/ext/example_numpy.html#example-numpy

**Pull request merged**
