### PR TITLE
CITATION.cff fix and automatic validation of your citation metadata

### PR DESCRIPTION
**Pull request by abelsiqueira**
## Description

Hello!

We noticed that your CITATION.cff had a small issue and fixed it - possibly by just updating `cffversion` to 1.2.0.
In addition to the fix, this Pull Request automates validation of the CITATION.cff file using the [cffconvert GitHub Action](https://github.com/marketplace/actions/cffconvert). That way, it's a little bit easier to be robust against future changes to the `CITATION.cff` file.

BTW it's perfectly fine if you don't feel like accepting this Pull Request for whatever reason -- we just thought it might be helpful is all.

We found your repository using a partially automated workflow; if you have any questions about that, feel free to create an issue over at https://github.com/cffbots/filtering/issues/

On behalf of the cffbots team,
@abelsiqueira / @fdiblen / @jspaaks

Closes #issue_number

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@abelsiqueira many thanks for your contribution, much appreciated! I am a bit apprehensive to have a dedicated Github Action workflow to only check for this feature, maybe we can extend it to also check for other things that don't normally get picked up in regular nightly checks - what do you guys think @zklaus @bouweandela ?

**Comment by bouweandela** [comment]
Thanks @abelsiqueira! Indeed I think this workflow may be using rather too many computational resources for the kind of problems it avoids. Maybe we could run this once a day instead of on every commit.

Also, your tool appears to have a problem with the ORCID of one of our authors:
```
$ cffconvert --validate
validation.invalid
 --- All found errors ---
["Value 'https://orcid.org/0000-0003-2724-709X' does not match pattern 'https://orcid\\.org/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}'. Path: '/authors/16/orcid'", "Cannot find required key 'name'. Path: '/authors/16'", "Key 'affiliation' was not defined. Path: '/authors/16'", "Key 'family-names' was not defined. Path: '/authors/16'", "Key 'given-names' was not defined. Path: '/authors/16'", "Value 'https://orcid.org/0000-0003-2724-709X' does not match pattern 'https://orcid\\.org/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}'. Path: '/authors/16/orcid'"]
pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
 - Value 'https://orcid.org/0000-0003-2724-709X' does not match pattern 'https://orcid\.org/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}'. Path: '/authors/16/orcid'.
 - Cannot find required key 'name'. Path: '/authors/16'.
 - Key 'affiliation' was not defined. Path: '/authors/16'.
 - Key 'family-names' was not defined. Path: '/authors/16'.
 - Key 'given-names' was not defined. Path: '/authors/16'.
 - Value 'https://orcid.org/0000-0003-2724-709X' does not match pattern 'https://orcid\.org/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}'. Path: '/authors/16/orcid'.: Path: '/'>
```
but when I click the link https://orcid.org/0000-0003-2724-709X it seems to work just fine. Could you check? Also the error message could be a bit more clear.

**Comment by abelsiqueira** [comment]
Hi @valeriupredoi and @bouweandela, let me try to address your comments. I only recently started working with CFF, so @jspaaks might have to correct me.

The CFF schema 1.0.3 did not allow `X` at the end of the ORCID. This was fixed at the current version 1.2.0. `cffconvert` validates the CITATION.cff file according to the declared `cff-version` in the file, i.e., the schema version. Therefore, it still thinks there is a mistake in the CITATION.cff file.
In other words, the CITATION.cff is wrong according to its own defined schema version. That is why we made the commit [13bb1a1](https://github.com/ESMValGroup/ESMValCore/pull/1459/commits/13bb1a14d276074c859b6008c6d28e2da093faaf) in addition to adding the workflow.

About extra workload, we wrote the workflow in a way that it only runs when a commit **changing CITATION.cff** is pushed.

Let me know if you have any more doubts. Also, as we mentioned, feel free to close it for any reason, no justifications necessary.

**Comment by valeriupredoi** [comment]
@abelsiqueira cheers! By all means I believe this is a useful feature, so many thanks! I don't want to comment on the specific ORCID issue that @bouweandela pointed out since I'm not able to look into it at the moment, but it has to be fixed one way or another before merging. My suggestion would be to rename the GA workflow to e.g. `citation_file_validator`, add a cron job scheduling e.g. run every ten days or so, as well as your good idea to run on a push on the file (the reason for the scheduled run, be it even every 30 days or so, is to have this find issues that may creep up due to the action failing for some other reasons - obsolete action version etc), and please test this PR by running the GA here on a push ie adding `cffbots-cffconvert` branch so the GA test can run. Apart from that it should be all good for me, many thanks again! :beer:

**Comment by bouweandela** [comment]
Thanks for clarifying @abelsiqueira! I agree with @valeriupredoi that the name of the action could be a bit more specific, but otherwise I would be happy to merge this.

**Comment by abelsiqueira** [comment]
I have updated the workflow name and added a condition to run it monthly. I do not have permissions on this repo, so perhaps @bouweandela can push it to an internal branch?
Let me know it is all to your liking, and I can make a similar PR to ESMValTool.

**Comment by valeriupredoi** [comment]
cheers muchly @abelsiqueira - I'll take it from here, I'll make it an internal PR and run a quick GA test on the feature branch before merging. Just double checking @bouweandela - is the ORCID stuff resolved?

**Comment by valeriupredoi** [comment]
local PR linked from fork, and with minor adjustments https://github.com/ESMValGroup/ESMValCore/pull/1467

**Pull request closed without merging**
