### PR TITLE
Deprecate the function `esmvalcore.var_name_constraint`

### LINKED ISSUE #1536: API documentatin for `esmvalcore.iris_helpes` is missing
[`esmvalcore.iris_helpers`](https://github.com/ESMValGroup/ESMValCore/blob/main/esmvalcore/iris_helpers.py) is a public module, but there is no API documentation for it. See https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html.

### LINKED ISSUE #1537: Replace `esmvalcore.iris_helpers.var_name_constraint` with `iris.NameConstraint`
[`esmvalcore.iris_helpers.var_name_constraint`](https://github.com/ESMValGroup/ESMValCore/blob/main/esmvalcore/iris_helpers.py) can be replaced by [`iris.NameConstraint`](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris.html?highlight=Constraint#iris.NameConstraint) in our code.

### PR DESCRIPTION
**Pull request by schlunma**
## Description

This PR adds an API documentation for the module `esmvalcore.iris_helpers` deprecates the function `var_name_constraint` in it. It replaces it with iris' [`NameConstraint`](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris.html#iris.NameConstraint) class.

Note: I didn't remove the appearances of `var_name_constraint` in the ICON CMORizer on purpose since they are fixed in #1549 and I want to avoid merge conflicts.

Closes #1536
Closes #1537

Link to documentation: https://esmvaltool--1592.org.readthedocs.build/projects/ESMValCore/en/1592/api/esmvalcore.iris_helpers.html

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
Sorry, I can't add all these missing tests for the variable derivation here...

**Review by valeriupredoi — APPROVED** [review]
excellent enhancement, Manu! Two questions: is the class `NameConstraint` available for only yje latest iris, or - what's the minimum version of iris it is available in - since we must pin on that one? And the second question: do we have a list somewhere where we add all these deprecations, so we remember to remove them in said versions? :beer:

**Comment by valeriupredoi** [comment]
oh and don't worry about the coverage issue, we need tests for those to begin with, but we'll plop them in a future PR :+1:

**Comment by schlunma** [comment]
Cheers V, thanks for the review! :rocket: 

> is the class `NameConstraint` available for only the latest iris, or - what's the minimum version of iris it is available in - since we must pin on that one?

Apparently it [has been added in 2.4](https://scitools-iris.readthedocs.io/en/latest/whatsnew/2.4.html), so we should be fine here :laughing: 

> And the second question: do we have a list somewhere where we add all these deprecations, so we remember to remove them in said versions? beer

That's a very good idea! Afaik we don't have this list yet, but I will open an issue to create one.

**Comment by valeriupredoi** [comment]
great, cheers, Manu!

**Pull request merged**
