### PR TITLE
Added various fixes for hybrid height coordinates

### PR DESCRIPTION
**Pull request by schlunma**
This PR adds fixes for `cl`, `cli` and `clw` datasets with a hybrid height coordinate.

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Related to #537. (Note: Automatic closing of these issues is not desired; they should be closed when the issue is reported to the modelers).

### CODE REVIEW

**Comment by schlunma** [comment]
Please do not merge yet, I will refactor this similar to #529.

> Holy cheese, there are a **lot** of fixes here - well done, man! One comment: it would be very useful if we documented proper all funcs in ` esmvalcore/cmor/_fixes/shared.py` so that they can be used via the API - not necessarily here, but we should have that in mind (open an issue) for the future beer

Yes, definitely! I'll add proper docstrings for all public method

**Comment by schlunma** [comment]
I refactored all the code, now it's ready for another review.

Please note that I had to adapt some fixes introduce in #529 since they were not working properly (I didn't test this thoroughly, sorry!): By doing a simple `Cli = ClFixForHybridPressure`, the function [`Fix.get_cube_from_list`](https://github.com/ESMValGroup/ESMValCore/blob/e5827ad0f9121c5851c7686ff57bcd08f9e55664/esmvalcore/cmor/_fixes/fix.py#L70-L96) did not work anymore, since it relies on the name of the class to find the correct `cube` out of `cubes`. Since `Cli = ClFixForHybridPressure` simply adds a new reference for the class `ClFixForHybridPressure`, `Cli.__name__` still gives `'ClFixForHybridPressure'`, leading to an exception for the variables `cli` and `clw`.

I fixed this by introducing new classes

```python
Cli = CliFixHybridHeightCoord
```

with

```python
class CliFixHybridHeightCoord(ClFixHybridHeightCoord):
    """Fixes for ``cli`` regarding hybrid sigma height coordinates."""

    SHORT_NAME = 'cli'
```

with the static attribute `SHORT_NAME`, which is used as parameter for [`Fix.get_cube_from_list`](https://github.com/ESMValGroup/ESMValCore/blob/e5827ad0f9121c5851c7686ff57bcd08f9e55664/esmvalcore/cmor/_fixes/fix.py#L70-L96). I think without using metaclasses this is the most elegant solution.

I tested all affected models and variables (`cl`, `cli` and `clw`), everything works as expected now.

**Comment by schlunma** [comment]
Any comments on this @zklaus @valeriupredoi?

**Comment by valeriupredoi** [comment]
> I refactored all the code, now it's ready for another review.
Great! I am going to have a look in a jiffy, trying to sort out smth else right at the moment. You don't happen to know how to assign `dtype` to an iris cube so you change data type from float64 to 32 but keeping the data lazy? :beer:

**Comment by schlunma** [comment]
> > I refactored all the code, now it's ready for another review.
> 
> Great! I am going to have a look in a jiffy, trying to sort out smth else right at the moment. You don't happen to know how to assign `dtype` to an iris cube so you change data type from float64 to 32 but keeping the data lazy? beer

Great, thanks!!

I think something like this should work, just replace `coord.core_points` by `cube.core_data`.

https://github.com/ESMValGroup/ESMValTool/blob/322cc0b98e257113d6a6d6abb1e9a4ff1716dac9/esmvaltool/cmorizers/obs/utilities.py#L294-L312

**Comment by bouweandela** [comment]
The changes mentioned in this https://github.com/ESMValGroup/ESMValCore/pull/562#issuecomment-598723119 should not be needed.

There is a much simpler solution, which is to use the name from the CMOR table definition. I already added that here https://github.com/ESMValGroup/ESMValCore/pull/391/files#diff-dcd9100a443a7b362eceac557168cc7b, but unfortunately @jvegasbsc does not seem to have time fix the corresponding ESMValTool PR for that one, so it has become stale and it will probably take some time before it gets merged. Maybe you can simply copy the changes from that other pull request?

Alternatively, I guess you could simply inherit instead of assign, i.e. `class Cli(ClFixForHybridPressure): pass` instead of `Cli = ClFixForHybridPressure`?

**Comment by schlunma** [comment]
> Maybe you can simply copy the changes from that other pull request?

Sounds great!

**Comment by schlunma** [comment]
@bouweandela I implemented your suggestion and refactored the code again (hopefully for the last time now). Can you take another look at it? Thanks!

**Comment by schlunma** [comment]
> @bouweandela I implemented your suggestion and refactored the code again (hopefully for the last time now). Can you take another look at it? Thanks!

@bouweandela? Sorry for the hurry, but I really need this for a diagnostic used in Axel's paper :grimacing:

**Pull request merged**
