### PR TITLE
Pin `pytest-mypy` plugin to `>=0.10.3` comply with new `pytest==8`

### LINKED ISSUE #2314: [CI/pytest=8.0.0] `pytest-mypy==0.8.0` plugin at odds with latest `pytest=8.0.0`
see [test fails](https://github.com/ESMValGroup/ESMValCore/actions/runs/7719535181/job/21042934293) - pytest-mypy==0.10.3 works well, but is not yet picked up by the CI (slightly older mamba), I shall pin now

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Closes #2314 

Pretty self-explanatory :grin: 
NOTE: the `pytest-mypy` package from conda-forge is very old https://anaconda.org/conda-forge/pytest-mypy so I removed it altogether from the conda environment file and we should only install it from PyPI (unless one of us wants to go and update their pkg at the feedstock)

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by bouweandela — APPROVED** [review]
I volunteered to help with maintaining in https://github.com/conda-forge/pytest-mypy-feedstock/pull/12. But LGTM for now to fix our tests.

**Comment by valeriupredoi** [comment]
add me to the maintainers list there too, bud. Cheers :beer:

**Comment by bouweandela** [comment]
You can do that yourself really easily, just ask the bot: https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list

**Comment by valeriupredoi** [comment]
ha yes, but then again, if there is no maintainer, who gunna merge the maintainers' list update PR - :chicken: and :egg: problem

**Pull request merged**
