### PR TITLE
Add requests as a dependency

### LINKED ISSUE #851: Nightly 'install' test on CircleCI is failing
Since a few days, the nightly test that installation from source works is failing on CircleCI, see e.g. [here](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/3420/workflows/e63bbe2d-c55f-4328-8d57-3b3e42b65e0e/jobs/15254).

It looks like this happens because we make use of the `requests` library, but did not add it as a dependency.

### PR DESCRIPTION
**Pull request by bouweandela**
Add requests as a dependency, because it's missing from the list of dependencies and it's used:

https://github.com/ESMValGroup/ESMValCore/blob/02b8f668e89cabae656978b44faa1bb27f7158be/esmvalcore/_citation.py#L8

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes

* * *

Closes #851

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
what's it do?

**Comment by bouweandela** [comment]
It fixes the failing tests, see #851

**Comment by valeriupredoi** [comment]
yeah, sorry, I commented before I looked :grin: - but still, it seems that package should be installed automatically without us ever asking for it (the two envs I built today have it), I wonder why the CI env is ignoring it

**Comment by valeriupredoi** [comment]
we should try to avoid requesting deps manually, they may be not needed anymore in the future and we're left with conflicts from packages we don't actually need

**Comment by bouweandela** [comment]
> we should try to avoid requesting deps manually, they may be not needed anymore in the future and we're left with conflicts from packages we don't actually need

That's all fine, but we do need this package because we do use it, see the top post.

> I wonder why the CI env is ignoring it

Maybe some other package that we have as a dependency used to have it as a dependency, but doesn't anymore.

**Comment by valeriupredoi** [comment]
> Maybe some other package that we have as a dependency used to have it as a dependency, but doesn't anymore.

That can't be - I built two envs from scratch today, with the latest `environment.yml` - but with the latest conda 4.9.1 - so it might be worth keeping an eye. Whatevs, let's get this one in, but I'll think of a test (kind of a reverse test) to periodically test the dependncy list see if we have any unused deps

**Pull request merged**
