### PR TITLE
Changed latitude longitude fix from Tas to AllVars.

### PR DESCRIPTION
**Pull request by katjaweigel**
## Description

There is already a fix for the latitude and longitude bounds for the variable "tas" in esmvalcore/cmor/_fixes/cmip6/cesm2.py. Instead of only to "Tas" it should be applied to "AllVars". I found at least part of the same problem (bounds differ) the fix solves for "prw". It can be expected that it occurs also for other variables if e.g. different experiments from CESM2 are combined. The case I tested was combining historical and ssp585 for prw.

-   Closes/Fixes: #915
-   Link to documentation:

***

## Before you get started

-   \[ \] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   \[ \] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   \[ \] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   \[ \] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   \[ \] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   \[ \] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   \[ \] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   \[ \] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   \[ \] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:

-   \[ \] Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Comment by katjaweigel** [comment]
How to make a test for a model fix? (The link to the docu leads nowhere)

Somehow I cannot tick things in (neither chrome nor firefox)?

**Comment by katjaweigel** [comment]
Now ticking works if I tick and then refresh the page.

**Comment by jvegasbsc** [comment]
I am not a fan of doing an AllVars fix tested with only two, specially for coordinates like lat and lon that may be written differently in the ocean and atmosphere output. My suggestion will be, if you just need to apply the `tas` fix to `prw` just to add this two lines:

```python

class Prw(Tas):
    pass 
```
So this way you have two fixes that do exactly the same

**Comment by katjaweigel** [comment]
I would agree if it would be the same, but it is not: For tas also the 2m height is added, which should probably not be there for prw. How could that be solved without duplicating the whole code?

**Comment by jvegasbsc** [comment]
Sorry, I missed that. In that case, put all the code on `Prw` and then in `Tas`:

```python

class Tas(Prw):

    def fix_metadata(self, cubes):
        super().fix_metadata(cubes)
        # Specific code for tas
```

**Comment by katjaweigel** [comment]
Ok, thanks! I changed it and will test it now.

**Comment by katjaweigel** [comment]
Tests are working (I also run it for tas, but for my recipe so possible a different experiment combination and/or time period as originally tested for tas).

**Review by jvegasbsc — APPROVED** [review]

**Pull request merged**
