### PR TITLE
Update CMIP6 tables to 6.9.32

### LINKED ISSUE #704: Update CMIP6 CMOR tables
There have been new releases, so our copy is outdated: https://github.com/PCMDI/cmip6-cmor-tables/releases

@jvegasbsc Would you be able to take care of this?

### PR DESCRIPTION
**Pull request by jvegasbsc**
As request by @bouweandela  in #704 

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #704

### CODE REVIEW

**Comment by jvegasbsc** [comment]
The tests are failing because of an error of pytest. They run locally without issue

**Comment by bouweandela** [comment]
Thanks! I created a pull request to fix the failing tests:  #707.

**Comment by jvegasbsc** [comment]
Codacy analysis was not setup for this branch. I just did it

**Comment by mattiarighi** [comment]
I think we can test this once we make the final run of all recipes.

**Comment by bouweandela** [comment]
Just for clarity, do we want to have this included in v2.0.0? We've had problems in the past when updating the CMOR tables, because the format changed, so I'm not sure if it's safe to include an update this late.

**Comment by jvegasbsc** [comment]
> Just for clarity, do we want to have this included in v2.0.0? We've had problems in the past when updating the CMOR tables, because the format changed, so I'm not sure if it's safe to include an update this late.

My answer will be yes, but not as much as to block v2.0 release. I think we can manage to do it, as it will be tested thoroughly when running all the recipes. Also, if we detect non trivial issues, reverting this change is easy and safe, as no other commits will modify the affected files.

**Comment by bouweandela** [comment]
> I think we can manage to do it, as it will be tested thoroughly when running all the recipes.

The main question then is, when are we going to do this? After the ESMValCore v2.0.0 release on July 20 or before it? I have tried to run about 20 recipes on the esmvaltool VM, but have no time to continue that testing before the release. @mattiarighi What are your plans in this?

**Comment by mattiarighi** [comment]
Ideally all recipes should work with the released version.
If we share the effort, I think it's doable to test all of them before the release.

Concerning the tables, it's probably better to include this at a later stage.

**Comment by jvegasbsc** [comment]
> Concerning the tables, it's probably better to include this at a later stage.

Ok, just beware that some model names have changed between versions. It is possible that you find errors because of this in CMIP6 recipes if the data in DKRZ has been updated

**Comment by bouweandela** [comment]
Merging this now, so it will be included in the next release.

**Pull request merged**
