### PR TITLE
Fixes for MCM-UA-1-0 (CMIP6)

### LINKED ISSUE #425: Dataset problem: MCM-UA-1-0 (CMIP6) datasets have wrong coordinate names
**Describe the dataset issue**

- ~~Data file has been changed by you in any way (if you answer yes the issue will be void and closed, we are not
supporting custom-made datasets that present problems, it is your resposability to fix those problems)~~
- Project (CMIP5/CMIP6/OBS/obs4mips/etc): CMIP6
- Full dataset decription (fill out as many as you know, please):
  - dataset: MCM-UA-1-0
  - experiment: piControl, 1pctCO2
  - mip: Amon
  - grid: gn
  - type:
  - version: v20190731
  - tier:
  - variable used: `tas`, `ta` (probably all)
  - data_specs_version: 01.00.28
- Problems encountered (please describe what the actual problems are: e.g. wrong standard name, issue with dimensions):
  - For variable `tas`: `height` coordinate is not correctly marked as coordinate, so `iris` does not assign it correctly as `scalar coordinate`
  - `var_name` of `latitude` is `latitude`, not `lat`
  - `var_name` of `longitude` is `longitude`, not `lon`
  - `parent_time_units` has invalid format (ends with `... (noleap)`)
- Pointer to existing copy of data on ESGF node (it would be very useful if you could provide a physical fullpath to the file(s) that are causing the problem, e.g. on CEDA Jasmin or DKRZ): DKRZ: `/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/UA/MCM-UA-1-0/1pctCO2/r1i1p1f1/Amon/tas/gn/v20190731/tas_Amon_MCM-UA-1-0_1pctCO2_r1i1p1f1_gn_000101-010012.nc`
- Other notes and mentions: I will write a fix for it

### PR DESCRIPTION
**Pull request by schlunma**
Fixes issues for the MCM-UA-1-0 dataset.

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #425.

### CODE REVIEW

**Comment by zklaus** [comment]
The changes look fine at first glance (though I haven't checked everything in detail), so the merge per se is ok, but iirc the intention was also to send this kind of information to the modelers, right? @valeriupredoi did you do that? Should we somehow make sure that the issue stays open even after the merge until this is done?

**Comment by valeriupredoi** [comment]
you are absolutely correct @zklaus - cheers, I totally forgot about that! :beer: Yeah, let's put that machinery in motion. @schlunma can you pls start that by filling out the dataset issue template and create an issue with that? :beer: again

**Comment by schlunma** [comment]
#425

**Comment by valeriupredoi** [comment]
no need to reopen the PR if we have that issue out, we just need to mention in that issue that we've already implemented the fixes

**Pull request merged**
