### PR TITLE
Restore support for scalar cubes to time selection preprocessor functions

### LINKED ISSUE #1743: Check for scalar cubes in time operations and improve error handling/messaging in light of #1713
Leftover from #1713 as nicely asked by @schlunma in eg https://github.com/ESMValGroup/ESMValCore/pull/1713#discussion_r967121094 - the hurryup was from the release king (me) to get the beautiful speedup in main before rc1 gets rolled out

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Restore support for scalar cubes to time selection preprocessor functions.

Closes #1743

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by schlunma — APPROVED** [review]
Looks great, thanks @bouweandela! Tested successfully on real data with `resample_time`.

**Comment by valeriupredoi** [comment]
very cool! I am going to plug this in the next rc (which is probably gonna be the stable version) :partying_face:

**Comment by valeriupredoi** [comment]
@bouweandela you mind turning the GA just for a fleeing second pls so we don't run into the lower Pythons complaining again?

**Comment by bouweandela** [comment]
The problem was with type hints, using '|' instead of `typing.Union` is only supported since Python 3.10. Since this pull request does not introduce any type hints, it seems unlikely that there will be a problem.

Anyway, didn't you configure the GitHub actions such that you could trigger them with a comment or something?

**Comment by valeriupredoi** [comment]
cheers @bouweandela :beer:

**Pull request merged**
