### PR TITLE
New / updated model fixes

### PR DESCRIPTION
**Pull request by axel-lauer**
This PR updates the existing fixes for the CMIP6 models ACCESS-CM2 and ACCESS-ESM1-5 and adds fixes for the CMIP6 models CIESM and CESM2-WACCM-FV2 for 3-dim cloud variables (cl, clw, cli).

The existing fixes for ACCESS-CM2 and ACCESS-ESM1-5 produce wrong results when converting the hybrid-height coordinates to height or pressure levels because the coefficients "b" needed for calculating "z = a + b * orog" are wrongly defined in the input files. This fix replaces "b" with correct values.

The integration tests for both ACCESS models have been updated, tests for CIESM and CESM2-WACCM-FV2 have been added.

### CODE REVIEW

**Comment by schlunma** [comment]
Having a look at this now

**Comment by schlunma** [comment]
I'm getting this error now due to ESMValGroup/ESMValTool#1903:

```
esmvalcore.cmor.check.CMORCheckError: There were errors in variable cl:
lev: units should be 1, not hPa
 lev: has values < valid_min = 0.0
```

**Review by schlunma — APPROVED** [review]
Code and output looks fine, so I think we can merge this :+1: . Please note that due to ESMValGroup/ESMValTool#1903 the tests for the CESM model needs to be run with `--check_level=ignore`, all other models work with the default settings.

I also added support for the bounds, it would be nice if you can check this one last time before merging @axel-lauer.

**Comment by schlunma** [comment]
(The Codacy error can be ignored...)

**Review by jvegasbsc — APPROVED** [review]

**Pull request merged**
