### PR TITLE
Test module for _main.py with different run scenarios

### PR DESCRIPTION
**Pull request by valeriupredoi**
No issue, just improving the testing for `_main.py`

### CODE REVIEW

**Comment by valeriupredoi** [comment]
Yep, but the coverage is happening ok only if run in installation mode, that's why I wanted to add more testing even if run in just test mode. I mean, the ci machine runs the installation, but users and most developers won't. So unit tests will defo come in handy for this reason too - good call! what do you think - a set of unit tests for main.py that will perform imports of each of esmvalcore's components?

**Comment by bouweandela** [comment]
Yes, create tests for the functions in _main.py only, so mock the imports using e.g. [unittest.mock.create_autospec](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.create_autospec) or [unittest.mock.Mock](https://docs.python.org/3/library/unittest.mock.html#the-mock-class) and/or [monkeypatch](https://docs.pytest.org/en/latest/monkeypatch.html).

**Comment by valeriupredoi** [comment]
Monkey Patch :monkey: Will do on Monday, man :beer:

**Comment by valeriupredoi** [comment]
I'll close this - it is incredibly old and not adding too much to what we need, frankly, I think the the tests for main have improved massively in the past...four years :rofl:

**Pull request closed without merging**
