### PR TITLE
Fix CMOR table.

### PR DESCRIPTION
**Pull request by ledm**
PR associated with issue #284. 

Not sure that we want to merge this, just wanted to show the changes that were needed to get it running again.

### CODE REVIEW

**Comment by valeriupredoi** [comment]
let's not go about changing CMOR tables, especially the Controlled Vocabularies; instead, alert the CMOR folk. Also, you 100% sure the `activity_id` is not `["ScenarioMIP", "AerChemMIP"]` (ie both but correctly formatted? I tried looking for multiple activity_id's but couldn't really, so I might be totally blabbering, but double checking didnt kill anyone yet)

**Comment by ledm** [comment]
Created CMOR issue here: https://github.com/PCMDI/cmip6-cmor-tables/issues/264

**Comment by valeriupredoi** [comment]
great! I reckon it's safe to close this PR but keep the issue open until the CMOR issue gets fixed and we'll update the CMOR tables version (btw are we actually at the latest CMOR version?)

**Comment by ledm** [comment]
We're not at the most recent version, as the bug was on a different line in their recent version. 

Fine with me to close this PR.

**Pull request closed without merging**
