### PR TITLE
Remove numba dependendy

### LINKED ISSUE #869: Numba causing installation issues with python=3.9
conda=4.9.2 env builds well but installing doesn't:
```
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/valeriu/miniconda3/envs/esmvalcore-492/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-elou0qm8/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-elou0qm8/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-woct46sr/install-record.txt --single-version-externally-managed --compile --install-headers /home/valeriu/miniconda3/envs/esmvalcore-492/include/python3.9/llvmlite
         cwd: /tmp/pip-install-elou0qm8/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-elou0qm8/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /home/valeriu/miniconda3/envs/esmvalcore-492/bin/python3.9 /tmp/pip-install-elou0qm8/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-elou0qm8/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/home/valeriu/miniconda3/envs/esmvalcore-492/lib/python3.9/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/valeriu/miniconda3/envs/esmvalcore-492/lib/python3.9/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/valeriu/miniconda3/envs/esmvalcore-492/lib/python3.9/subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/valeriu/miniconda3/envs/esmvalcore-492/lib/python3.9/subprocess.py", line 1819, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-elou0qm8/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-elou0qm8/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-elou0qm8/llvmlite/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/home/valeriu/miniconda3/envs/esmvalcore-492/bin/python3.9' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/valeriu/miniconda3/envs/esmvalcore-492/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-elou0qm8/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-elou0qm8/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-woct46sr/install-record.txt --single-version-externally-managed --compile --install-headers /home/valeriu/miniconda3/envs/esmvalcore-492/include/python3.9/llvmlite Check the logs for full command output.
```

### PR DESCRIPTION
**Pull request by schlunma**
This PR accelerates the calculation of pressure level widths necessary for the derivation of `toz` by a factor of ~6 (for 100 years of monthly mean data, using 1 dataset) and removes the `numba` dependency. I also added some unit tests for the derivation of `toz`.

Please note that I could no make the calculation of `toz` lazy yet since it uses [`iris.util.broadcast_to_shape`](https://scitools.org.uk/iris/docs/latest/iris/iris/util.html#iris.util.broadcast_to_shape) that does not work on lazy data, and I think getting rid of `numba` is the main intention of this PR. 

@valeriupredoi can you do the technical review, please?

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #869

### CODE REVIEW

**Comment by valeriupredoi** [comment]
having a look right now! :beer:

**Review by valeriupredoi — APPROVED** [review]
very cool and quite a bit of code in one day, cheers @schlunma

**Comment by schlunma** [comment]
waaaaaait

**Comment by schlunma** [comment]
We need a scientific review for this, I'm not 100% sure if the `toz` calcualtion is correct. @hb326 can you maybe run a recipe that uses `toz` and check if the output is still correct? Now you can use the latest `master` branch of ESMValCore.

**Comment by bouweandela** [comment]
Is derivation of `toz` lazy after this? Because then #42 can also be closed.

**Comment by schlunma** [comment]
> Is derivation of `toz` lazy after this? Because then #42 can also be closed.

Unfortunately not, see description of this PR:

Please note that I could no make the calculation of toz lazy yet since it uses iris.util.broadcast_to_shape that does not work on lazy data, and I think getting rid of numba is the main intention of this PR.

**Comment by valeriupredoi** [comment]
for future reference, if a sci review is needed pls add a sci reviewer, I saw meself as the only reviewer so I didn't dillydoll around :grin:

**Comment by valeriupredoi** [comment]
> > Is derivation of `toz` lazy after this? Because then #42 can also be closed.
> 
> Unfortunately not, see description of this PR:
> 
> Please note that I could no make the calculation of toz lazy yet since it uses iris.util.broadcast_to_shape that does not work on lazy data, and I think getting rid of numba is the main intention of this PR.

that's perfectly fine, `numba` was the scope of this PR :+1:

**Comment by schlunma** [comment]
> for future reference, if a sci review is needed pls add a sci reviewer, I saw meself as the only reviewer so I didn't dillydoll around grin

Sorry, I thought we agreed yesterday that we only tag the scientific reviewer after the technical review is finished.

**Comment by valeriupredoi** [comment]
did we? not with me, man, am Fast Hand Luke, need to add one when you add me as well - OK I'll conform from next time :grin:

**Comment by hb326** [comment]
> 
> 
> We need a scientific review for this, I'm not 100% sure if the `toz` calcualtion is correct. @hb326 can you maybe run a recipe that uses `toz` and check if the output is still correct? Now you can use the latest `master` branch of ESMValCore.

Will do.

**Comment by axel-lauer** [comment]
I tested this with all CMIP5 models that are included in the perfmetrics recipe and it works well. There are, however, some small differences between this derivation method for toz and the old one. The differences ("old method" - "new method") are typically in the order of -0.05 to -0.15 DU (i.e. the new method gives slightly larger values) and vary with time and geographical location (see example below). Not sure where the differences are coming from and if that would be something to worry about. @hb326 are those differences significant?

Annual average differences between toz ("old method") and toz ("new method") for CMIP5 model MIROC-ESM-CHEM:

ncview_toz

**Comment by hb326** [comment]
@axel-lauer: which color indicates higher differences, and which lower differences?

**Comment by axel-lauer** [comment]
In the example above, blue (min) is about -0.13 DU and red (max) about -0.09.

**Comment by hb326** [comment]
Ok, I do not know for sure where the differences could come from. 
Normally global ozone ranges from about 200-250 DU to 350-450 DU (not looking at the ozone hole region here), so differences of -0.13 DU are pretty small. I looked at the global distribution of total column ozone (toz) to check if the new calculation is ok, and it seemed fine. 
I am not sure what exactly changed from the old to the new toz integration, but I can imagine that small changes in calculating the pressure levels would result in a small change in toz.

**Comment by axel-lauer** [comment]
So I guess we can then regard this as fine?

**Comment by hb326** [comment]
I would think yes, we can regard this as fine.

**Pull request merged**
