### PR TITLE
Increase version number for ESMValCore `v2.8.0`

### PR DESCRIPTION
**Pull request by remi-kazeroni**
## Description

Release candidate rc2 will be released tomorrow as stable Core `v2.8.0`. This PR update the version number to `v2.8.0`
***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
ha! Blithering location test decided to fail exactly when it hurts most :rofl:

**Review by valeriupredoi — APPROVED** [review]
:checkered_flag:

**Comment by valeriupredoi** [comment]
runs now, all good - many thanks for this titanic work @remi-kazeroni - let me know when you want me to merge :+1:

**Comment by remi-kazeroni** [comment]
Many thanks for all the support @valeriupredoi and answers to my questions! Let's merge it tomorrow when we're sure to launch the `v2.8.0` rocket.

**Pull request merged**
