### PR TITLE
Fix rounding of Pandas datetimes in ICON CMORizer

### LINKED ISSUE #2530: Tests failing with known Pandas rounding bug
[Tests](https://github.com/ESMValGroup/ESMValCore/actions/runs/10985987537/job/30498675477) are failing with a very well known rounding bug from Pandas, due to new pandas=2.2.3 released 24h ago. I finally have a permanent fix in #2529

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

We have been pinning Pandas since at least three minor versions ago, see https://github.com/ESMValGroup/ESMValCore/pull/2394 due to a bug in Pandas that they seem to be taking forever to fix issue https://github.com/pandas-dev/pandas/issues/57002 and now we are yet again faced with the same issue with the new version of Pandas 2.2.3 - see [failed nightly GA](https://github.com/ESMValGroup/ESMValCore/actions/runs/10985987537/job/30498675477). The problem is simple: Pandas are simply unable to round to the next minute eg 12H:12M:39S should be 12H:13M:00S (for daily data), so I got fed up and wrote our own rounding function (that took me surprisingly long to get it right - about an hour, rounded to the next minute :rofl:  I *think* this should not affect the result when Pandas finally fix their bug - but I'll let @schlunma decide :beer: 

Closes #2530 
***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful - YES, apart from *silly* pre-commit

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
ayay - check out the devel test with bleeding edge deps:
```
Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0:00:00.997120
 x: array([cftime.DatetimeProlepticGregorian(2004, 11, 4, 13, 30, 0, 997120, has_year_zero=True)],
      dtype=object)
 y: array([datetime.datetime(2004, 11, 4, 13, 30)], dtype=object)
 ```
 cftime plugging in some 0.997s out of thin air, they'd get absolutely destroyed if they worked in motorsports :grin:

**Comment by bouweandela** [comment]
Have you tried this suggestion to work around the issue? https://github.com/pandas-dev/pandas/issues/57002#issuecomment-1906866998

**Comment by valeriupredoi** [comment]
> Have you tried this suggestion to work around the issue? [pandas-dev/pandas#57002 (comment)](https://github.com/pandas-dev/pandas/issues/57002#issuecomment-1906866998)

Yes, it don't work, no Pd rounding works, including the one in the cmorizer 🍺

**Comment by schlunma** [comment]
This also doesn't sound like a workaround to me...

However, what DOES work is the hint in the description of that issue:

```py
# Round just date works
dates[0].round("30min")
# >Timestamp('2022-01-11 12:00:00')
```

See here:

```py
>>> datetimes = year_month_day + day_float
>>> print(datetimes)
0   2004-11-04 13:59:59.997120#
dtype: datetime64[ns]
>>> rounded_datetimes = pd.Series(dt.round('s') for dt in datetimes)
>>> print(rounded_datetimes)
0   2004-11-04 14:00:00
dtype: datetime64[ns]
```

**Comment by schlunma** [comment]
Ahh wait, I just realized that I have an old version of pandas, sorry, will update you again once that is updated...

**Comment by valeriupredoi** [comment]
You need to update ninja bear to 2.2.3 Nanu 😁

**Comment by schlunma** [comment]
Yes!! It does work with pandas v2.2.3:

```py
>>> import pandas as pd
>>> pd.__version__
'2.2.3'
>>> time_points = [20041104.5833333]
>>> time_str = pd.Series(time_points, dtype=str)
>>> year_month_day_str = time_str.str.extract(r'(\d*)\.?\d*', expand=False)
>>> year_month_day = pd.to_datetime(year_month_day_str, format='%Y%m%d')
>>> day_float_str = time_str.str.extract(
  r'\d*(\.\d*)',...             r'\d*(\.\d*)', expand=False
...         ).fillna('0.0')
>>> day_float = pd.to_timedelta(day_float_str.astype(float), unit='D')
>>> datetimes = year_month_day + day_float
>>> print(datetimes)
0   2004-11-04 13:59:59.997120
dtype: datetime64[ns]

>>> # Old version:
>>> rounded_datetimes = datetimes.round('s')
>>> print(rounded_datetimes)
0   2004-11-04 13:59:59.997120
dtype: datetime64[ns]

>>> # New version:
>>> rounded_datetimes = pd.Series(dt.round('s') for dt in datetimes)
>>> print(rounded_datetimes)
0   2004-11-04 14:00:00
dtype: datetime64[ns]
```

**Comment by schlunma** [comment]
You want to plug this in @valeriupredoi? You can simply replace the existing l.496 with

```py
rounded_datetimes = pd.Series(dt.round('s') for dt in datetimes)
```

and should work 😁 

I can also do it if you want, already got a local copy with this change.

**Comment by valeriupredoi** [comment]
So why is the rounding done in the ICON cmorizer don't work then, and all the attempts I tried two days ago? You mind plopping the correct syntax in this PR, and get rid of the peasant rounding then plss, bud 🍺

**Comment by valeriupredoi** [comment]
> I can also do it if you want, already got a local copy with this change.

That'd be fab, cheers, bud! :beer:

**Comment by schlunma** [comment]
In the [pandas issue](https://github.com/pandas-dev/pandas/issues/57002) they say that only rounding the `pd.Series` objects fail, i.e.,

```py
rounded_datetimes = datetimes.round('s')
```

This is what we currently have; hence, it fails.

However, rounding individual elements, i.e.,

```py
rounded_datetimes = pd.Series(dt.round('s') for dt in datetimes)
```

works. Please don't ask me why...

**Comment by bouweandela** [comment]
Did you time some representative test case @schlunma? Looping over every element of an array in Python and then doing something with it can be really slow.

**Comment by schlunma** [comment]
> Did you time some representative test case @schlunma? Looping over every element of an array in Python and then doing something with it can be really slow.

No, but I don't think it's critical here. All ICON output I've seen so far is scattered across many files with only very few time points (sometimes only one time step is stored). Even the high-res output (20 mins) we have only  has 72 time points per file.

However, I am open to any better solution. All solutions I could think of involved Python loops in one way or another.

**Comment by valeriupredoi** [comment]
we can always revert to the original implementation when Pandas finally fix their silly bug. Thanks a lot, Manu! @bouweandela would you be a trooper and merge this, pls :beer:

**Comment by schlunma** [comment]
> Well, my peasant approach didn't - it involved a list not an array 🤣

But you still had a `for` loop in there 😝

**Comment by valeriupredoi** [comment]
> > Well, my peasant approach didn't - it involved a list not an array 🤣
> 
> But you still had a `for` loop in there 😝

An even worse one too 🤣

**Comment by bouweandela** [comment]
I did some timings (with pandas 2.1.4) and for 100 points the time it takes is quite marginal, even if the new approach is more than 10 times slower:
```
In [0]: import pandas as pd
   ...: 
   ...: dates = pd.Series([pd.to_datetime("2022-01-11 12:10:01.123")] * 100)

In [1]: %timeit pd.Series(dt.round('s') for dt in dates)
906 μs ± 16 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [2]: %timeit dates.round("s")
67.3 μs ± 1.15 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```

**Pull request merged**
