### PR TITLE
_regrid.py: guess bounds before regridding if not available: iris regrid requires bounds

### PR DESCRIPTION
**Pull request by BenMGeo**
**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog

-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.

* * *

Closes {#422}

### CODE REVIEW

**Comment by BenMGeo** [comment]
Based on the tests, it does not look as simple as guessing bounds as there are some incompatibilities with unstructured data sets.

**Comment by zklaus** [comment]
CMIP6 data has to have bounds. I think this is the wrong place to address this issue; missing bounds should be considered a bug in the dataset and fixed with a fix file.

**Comment by BenMGeo** [comment]
> 
> 
> CMIP6 data has to have bounds. I think this is the wrong place to address this issue; missing bounds should be considered a bug in the dataset and fixed with a fix file.

Regridding should also be available for OBS, not? So do you prpose it is a cmorization issue?

**Comment by zklaus** [comment]
You raise a good point with the observations, but yeah, I think it should be considered a cmorization issue.

**Comment by mattiarighi** [comment]
> I think it should be considered a cmorization issue.

I agree.

Note that for the Python cmorizers, a function is available in `utilities.py` for setting the correct coordinate bounds:

https://github.com/ESMValGroup/ESMValTool/blob/b31cdd0039895b2c550b2903f9868d875740db3d/esmvaltool/cmorizers/obs/utilities.py#L231-L241

and also for the NCL cmorizers, in `utilities.ncl`:

https://github.com/ESMValGroup/ESMValTool/blob/b31cdd0039895b2c550b2903f9868d875740db3d/esmvaltool/cmorizers/obs/utilities.ncl#L1049-L1109

**Comment by BenMGeo** [comment]
> 
> 
> > I think it should be considered a cmorization issue.
> 
> I agree.
> 
> Note that for the Python cmorizers, a function is available in `utilities.py` for setting the correct coordinate bounds:
> 
> https://github.com/ESMValGroup/ESMValTool/blob/b31cdd0039895b2c550b2903f9868d875740db3d/esmvaltool/cmorizers/obs/utilities.py#L231-L241
> 
> and also for the NCL cmorizers, in `utilities.ncl`:
> 
> https://github.com/ESMValGroup/ESMValTool/blob/b31cdd0039895b2c550b2903f9868d875740db3d/esmvaltool/cmorizers/obs/utilities.ncl#L1049-L1109

OK, then we can close this. 

I did not write a cmorizer yet, as there was no other changes needed than renaming the variable. No checks raised issues.

**Comment by mattiarighi** [comment]
Please also delete the branch if no longer required.

**Comment by valeriupredoi** [comment]
right you say @zklaus but @BenMGeo cheers for thinking about this anyways! I noticed that the Python cmorizer bounds addition function needs a check on coordinate dimesnionality: `cube.coord(dim_coord).guess_bounds()` will fail with eg `iris.exceptions.CoordinateMultiDimError: Multi-dimensional coordinate not supported: 'latitude'` for 2+ dim coords. Maybe Ben can be a n9ce dude and add the check pls :beer:

**Comment by zklaus** [comment]
I'm not sure that's a good idea. Yeah, it will fail, but surely already for the author of the cmorizer so that he notices that the bounds have not been corrected and that he needs to think a bit more about it.

**Comment by BenMGeo** [comment]
I think so too. If "iris.exceptions.CoordinateMultiDimError: Multi-dimensional coordinate not supported: 'latitude'" is the returned error from the cmorizer, this is fully describing the issue that cannot be handled. Should not need additional checks.

**Comment by valeriupredoi** [comment]
no no, I meant let the exception be raised but add a nicer message via a check in the cmorizer script make the user aware where and how it happens. Iris final exceptions are nested in quite a bit of trace messages and sometimes it can be daunting to follow the paper trail

**Comment by BenMGeo** [comment]
I'll have a look when I rite the cmorizer.

**Pull request closed without merging**
