### PR TITLE
Update changelog and release date for v2.9.0 release

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Final updates for the release:
- update the release notes with latest changes
- update the version number and release date in CITATION.cff

Link to documentation: https://esmvaltool--2123.org.readthedocs.build/projects/ESMValCore/en/2123/changelog.html#v2-9-0

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by remi-kazeroni — COMMENTED** [review]
Thanks @bouweandela! Looks good to me. I see that PR #2119 is missing but maybe that is intended as this was fixed within a release cycle, right? Do you want to add this PR and maybe #2088 for the changes to the Changelog? You could make a "Release section" or make an entry in the "Documentation" section, as you like. Let me know what you think and I'll approve this PR.

**Comment by bouweandela** [comment]
> I see that PR https://github.com/ESMValGroup/ESMValCore/pull/2119 is missing but maybe that is intended as this was fixed within a release cycle, right?

Yes, the feature was added, but turned out to be too computationally expensive, so then taken out again.

**Comment by bouweandela** [comment]
> Do you want to add this PR and maybe https://github.com/ESMValGroup/ESMValCore/pull/2088 for the changes to the Changelog?

Done in 1311e4c

**Review by remi-kazeroni — APPROVED** [review]
Thanks!

**Pull request merged**
