### PR TITLE
Add tag `all_years: True`

### LINKED ISSUE #1120: Add option to load selected or all years available in an experiment
**Is your feature request related to a problem? Please describe.**
In #771 we tried to add the functionality to load all DCPP data without having to specify the `start_year` and the `end_year`, as the current time range handling is not ideal (#345). To do so, a new tag ` to load all the data available was introduced. @zklaus pointed out that it could work for all experiments. 

**Would you be able to help out?**
Yes

### PR DESCRIPTION
**Pull request by sloosvel**
## Description
This pull request adds the option to load all years in an experiment. To be merged after #771, as I started from a commit in there because the changes were already there. I will update the branch after the merge of #771  to make these changes more clear.

Closes #1120 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
I think a more user-friendly (and introducing less overhead with less optional arguments) is to leave out either `start_year` or `end_year` or both - no `start_year` means the code finds all the data before `end_year`, no `end_year` means it finds all the data after `start_year` and neither start nor end years meaning ALL the data available. Bit of a headache to implement but much nicer and with more scope IMHO :beer:

**Comment by sloosvel** [comment]
I think @zklaus idea is more in line with the work that is already done, because the pull request already finds all data available and it would just be a matter of subsetting it.

**Comment by valeriupredoi** [comment]
@zklaus @sloosvel sounds good to me! Sorry, I didn't realize this was urgent and don't want to sandbag it. The implicit configuration is useful (maybe not so implicit) since I've heard a lot of them scientists making noises they want to use all the available data on a particular site, they're not concerned how much it is available, but rather they just want to grab it all, and am honestly not a big fan of more configuration arguments/keys/definitions. But let's discuss this in the future, after this PR has been merged - Saskia, I can review it now if you ready!

**Comment by sloosvel** [comment]
Let me give it a go at the timeselection range, and if it's too much trouble maybe we can do with this?

**Comment by sloosvel** [comment]
I'm closing this and opening a new PR.

**Pull request closed without merging**
