### PR TITLE
Add custom table for vmrh2o

### PR DESCRIPTION
**Pull request by mattiarighi**
Custom variable required by the `HALOE` observational dataset.

### CODE REVIEW

**Comment by mattiarighi** [comment]
Any clue about the failing tests?

**Comment by schlunma** [comment]
No idea, but looks like it's not related to this PR. Can you merge the current `master` to restart the tests again?

**Comment by mattiarighi** [comment]
No changes.

**Comment by valeriupredoi** [comment]
There is a fixture instance that is calling `funcargs` as attribute and that is not supported, can you pls change it to `hasattr()` as in https://github.com/ionelmc/pytest-benchmark/commit/d1ab766220c564c8fb295f3cf68c133698fce5b0

**Comment by valeriupredoi** [comment]
@schlunma will know what I'm about :grin: - try rerunning the test container first, if it still fails then it's defo the issue above

**Comment by mattiarighi** [comment]
I'm not allowed to rerun the test (need write permissions ??).

Where is the line to be changed?

**Comment by schlunma** [comment]
> There is a fixture instance that is calling funcargs as attribute and that is not supported, can you pls change it to hasattr() as in ionelmc/pytest-benchmark@d1ab766

But it looks like it's an error in `pytest` itself, so how can we change the code of `pytest` on the CI machine? :grimacing: 

```
INTERNALERROR>   File "/test/.eggs/pytest_html-2.1.0-py3.8.egg/pytest_html/plugin.py", line 98, in pytest_runtest_makereport
INTERNALERROR>     fixture_extras = item.funcargs.get("extra", [])
INTERNALERROR> AttributeError: 'Flake8Item' object has no attribute 'funcargs'
```

Do local tests have the same issue @mattiarighi?

**Comment by jvegasbsc** [comment]
>But it looks like it's an error in pytest itself, so how can we change the code of pytest on the CI machine? 😬

We must pin the pytest version. Check your local version if its running fine and change the requirements accordingly

**Comment by valeriupredoi** [comment]
Yes, Javi beat me to it :+1:

**Comment by mattiarighi** [comment]
> Do local tests have the same issue @mattiarighi?

` 1060 passed, 3 skipped, 6 warnings in 296.51s (0:04:56)`

**Comment by valeriupredoi** [comment]
Will look into pinning pytest after the wrap-up session

**Comment by valeriupredoi** [comment]
I can not reproduce the error with `pytest==5.3.5`, will investigate moar

**Comment by valeriupredoi** [comment]
Ow wait, I was using python 3.7 d'oh!

**Comment by mattiarighi** [comment]
Given #568 can we merge this?

**Pull request merged**
