### PR TITLE
Moved and completed time preprocessors list (PR 439 child 1)

### PR DESCRIPTION
**Pull request by valeriupredoi**
Before you start, please read [CONTRIBUTING.md](https://github.com/ESMValGroup/ESMValCore/blob/master/CONTRIBUTING.md).

**Tasks**

-   [ ] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [ ] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

This alleviates some of the burden from PR #439 that will be now be broken into smaller bits - this is the first child

### CODE REVIEW

**Comment by valeriupredoi** [comment]
hey guys @bouweandela @schlunma @zklaus can I get a quick approval on this one so I can merge in master and go on producing #439 children pls? :beer:

**Comment by zklaus** [comment]
PS: It would have been helpful to have a sentence in the PR description on what this is trying to achieve. I was able to deduce it from the code only because it was so small and well-written.

**Comment by valeriupredoi** [comment]
cheers boss! :beer:

**Comment by valeriupredoi** [comment]
I will add plenty of info to the other ones, gimme a sec, merge this in the next now :tractor:

**Pull request merged**
