### PR TITLE
Increased ESMValCore version to 2.5.0rc1

### PR DESCRIPTION
**Pull request by schlunma**
## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
I think this can be merged now

**Review by remi-kazeroni — COMMENTED** [review]
Looks fine to me but @zklaus and @valeriupredoi are the experts here.

Question: is the next step to uncomment this [line](https://github.com/ESMValGroup/ESMValTool/blob/de40d87344fb47b2f10a9a6ac31304cf0167dba5/environment.yml#L7) in the environment file of the Tool?

**Comment by schlunma** [comment]
> Looks fine to me but @zklaus and @valeriupredoi are the experts here.
> 
> Question: is the next step to uncomment this [line](https://github.com/ESMValGroup/ESMValTool/blob/de40d87344fb47b2f10a9a6ac31304cf0167dba5/environment.yml#L7) in the environment file of the Tool?

Yes, I will do this after the release, but probably tomorrow (so hopefully the pip and conda package built successfully).

**Review by valeriupredoi — APPROVED** [review]
looking good, gents :+1: :beer:

**Comment by schlunma** [comment]
Thanks V.! :beers:

**Pull request merged**
