### PR TITLE
cat experiments first, then do the time based cat :black_cat: 

### LINKED ISSUE #2342: concatenate experiments handles time ordering incorrectly
I am analysing the 1pctCO2 and esm-1pct-brch-1000PgC experiments, where the latter branches from the former after about 70 years. The simulation time for 1pctCO2 is longer than 70 years, so there will be several years that are present in both experiments. When concatenating both experiments I need to take the first 70 years from 1pctCO2 and the remainder from esm-1pct-brch-1000PgC, essentially discarding the years in 1pctCO2 after year 70. 

Thats the default behaviour of ESMValTool and iris, except the above logic operates on a per-file basis rather than on per-experiment. So if the experiment datasets consist of multiple files (which they frequently do), we get nonsensical output that depends on how the files were chunked and saved.

Below is an MRE:

```python
import esmvalcore.dataset
import iris
import iris.quickplot as qplt

ds = esmvalcore.dataset.Dataset( **{
    "dataset": "CESM2",
    "project": "CMIP6", 
    "exp": ["1pctCO2", "esm-1pct-brch-1000PgC"], 
    "ensemble": "r1i1p1f1", 
    "grid": "gn", 
    "timerange": "0001/0217",
    "short_name":"tas",
    "mip":"Amon",
})

qplt.plot(ds.load().collapsed(['latitude', 'longitude'], iris.analysis.MEAN))
```

which gives the following plot:
image

One can see the discontinuity in the temperature value that is caused by taking some timeranges from the wrong experiment.

There is a single unambiguous way to concatenate 2 experiments with overlapping timestamps in the CMIP context and that is at the branching time. I have a local bugfix that first concatenates the experiments-wise and then concatenates the result of that, which I have pushed to https://github.com/ESMValGroup/ESMValCore/tree/experiments_first (will open a PR now)

There are several issues pertaining to concatenation, e.g. this one #1423 which considerable activity over the years. However the underlying issue persists.

### PR DESCRIPTION
**Pull request by dhohn**
## Description

Solves a bug where concatenation of multiple experiments consisting of datasets with multiple files leads wrong results, where timeranges are mixed randomly from the experiments.
Closes #2342 

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) #2342 

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
-  [x] [🛠][1] N/A: Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly.
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by dhohn** [comment]
I need help with adding tests.

**Comment by bouweandela** [comment]
@dhohn I simplified the code a bit and added a test for you. Could you please check if it still does what you expect?

**Comment by bouweandela** [comment]
It's a bit more tricky than I thought, I think the changes I made are not doing the job. Let me have another look.

**Comment by bouweandela** [comment]
@dhohn It should work now, could you please check?

**Comment by dhohn** [comment]
Dear @bouweandela 
Thanks for all these changes! Your code looks much better than mine. I tested this version it works as expected.

**Review by valeriupredoi — COMMENTED** [review]
very many thanks @dhohn and @bouweandela :beer: x2 - a very useful patch indeed!

**Review by valeriupredoi — APPROVED** [review]

**Pull request merged**
