### PR TITLE
Fix for FGOALS-f3-L clt

### LINKED ISSUE #1927: Dataset problem: FGOALS-f3-L clt in scenario simulation
**Describe the dataset issue**
FGOALS-f3-L clt has unit %, values are <= 1 in ssp585 simulation.

- Project : CMIP6
- Full dataset description (fill out as many as you know, please):
  - dataset: FGOALS-f3-L
  - experiment: ssp585
  - mip: Amon
  - grid: gr
  - variable used: clt

**Please attach**
[recipe_test_fgoals.txt](https://github.com/ESMValGroup/ESMValCore/files/10733564/recipe_test_fgoals.txt)

Cheers :beer:

### PR DESCRIPTION
**Pull request by LisaBock**
## Description

FGOALS-f3-L clt has unit %, values are <= 1 in ssp585 simulation.

Closes #1927 

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
~~- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~~
~~- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date~~
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
looking good, many thanks @LisaBock and @remi-kazeroni :beer:

**Comment by valeriupredoi** [comment]
@LisaBock do you mind cleaning up (removing or strikethru-ing) the PR description boxes, please? :beer:

**Comment by remi-kazeroni** [comment]
> @LisaBock do you mind cleaning up (removing or strikethru-ing) the PR description boxes, please? 🍺

Done! Thanks @valeriupredoi for the review 🍺

**Comment by LisaBock** [comment]
Thanks @remi-kazeroni for your support and @valeriupredoi for the review!

**Comment by valeriupredoi** [comment]
good work, guys! :beer:

**Pull request merged**
