### PR TITLE
Add timeout to requests.get in _citation.py

### LINKED ISSUE #1088: Slow `_get_response` in `citation.py`
**Is your feature request related to a problem? Please describe.**

The machine we use at BSC does not allow outgoing connections due to security reasons. This makes some recipes hang for some time after they finish computing diagnostics and they get to the citation module:

````
2021-04-27 10:10:45,598 UTC [14045] INFO    No network connection, unable to retrieve CMIP6 citation information
2021-04-27 10:13:55,038 UTC [14045] INFO    No network connection, unable to retrieve CMIP6 citation information
2021-04-27 10:17:05,502 UTC [14045] INFO    No network connection, unable to retrieve CMIP6 citation information
````

Would there be any way to get a quicker response?

### PR DESCRIPTION
**Pull request by SarahAlidoost**
## Description

Closes #1088

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
The requests documentation [here](https://docs.python-requests.org/en/master/user/quickstart/#timeouts) and [here](https://docs.python-requests.org/en/master/user/advanced/#timeouts) certainly seems to suggest using timeouts.

I feel like 1 second is a bit short, but looking around the intertubes that seems to be a feeling that is not widely shared.

Perhaps it would be nice to establish a universal network timeout as a configuration parameter?

**Comment by SarahAlidoost** [comment]
> The requests documentation [here](https://docs.python-requests.org/en/master/user/quickstart/#timeouts) and [here](https://docs.python-requests.org/en/master/user/advanced/#timeouts) certainly seems to suggest using timeouts.
> 
> I feel like 1 second is a bit short, but looking around the intertubes that seems to be a feeling that is not widely shared.
> 

Thank you. The timeout=1s was tested on my machine. However, it is now increased to 5s. 

> Perhaps it would be nice to establish a universal network timeout as a configuration parameter?

Do you mean as a parameter to [config-user-example.yml](https://github.com/ESMValGroup/ESMValTool/blob/master/config-user-example.yml)?

**Review by zklaus — APPROVED** [review]
LGTM

**Comment by zklaus** [comment]
> > Perhaps it would be nice to establish a universal network timeout as a configuration parameter? 
>
> Do you mean as a parameter to [config-user-example.yml](https://github.com/ESMValGroup/ESMValTool/blob/master/config-user-example.yml)?

Yes, something like that. However, grepping through the code, I didn't find another place where we directly make `requests`, so for now I think it might not be necessary.

**Comment by SarahAlidoost** [comment]
> LGTM

I cannot merge the PR, could you please do it?

**Pull request merged**
