### PR TITLE
[v2.7.1 bugfix release] Unpin cf-units and port changes from PR 1770 into v2.7.x

### PR DESCRIPTION
**Pull request by valeriupredoi**
These are changes (mostly) done in https://github.com/ESMValGroup/ESMValCore/pull/1770 that will be needed into the release branch for v2.7.1 bugfix release. The only major change is inside the sample data `test_multimodel.py` that contains a number of previous-to-1770 changes.

### CODE REVIEW

**Comment by bouweandela** [comment]
It's a bit surprising that the tests pass without the new netCDF files added in #1770. Do you understand why, since you didn't add them?

**Comment by valeriupredoi** [comment]
> It's a bit surprising that the tests pass without the new netCDF files added in #1770. Do you understand why, since you didn't add them?

I have seen this in the other PR too (the one with all the features in one basket), and I don't know why that is - let me have a look

**Comment by valeriupredoi** [comment]
Blast! The sample_data test is identical to the tests/unit/preprocessor/_multimodel/test_multimodel.py test, I must have conked up badly, let me figure that out

**Comment by valeriupredoi** [comment]
also @bouweandela note that we are git ignoring all `.nc` files from `.gitignore` so those files are not under git scrutiny unless we git commit -f changes

**Comment by valeriupredoi** [comment]
OK all back to normal and sane changes vs https://github.com/ESMValGroup/ESMValCore/pull/1770 :disappointed_relieved:

**Comment by bouweandela** [comment]
> also @bouweandela note that we are git ignoring all .nc files from .gitignore so those files are not under git scrutiny unless we git add -f ... changes

I know, we've had some issues with people accidentally committing huge netcdf files in the past

**Comment by valeriupredoi** [comment]
> > also @bouweandela note that we are git ignoring all .nc files from .gitignore so those files are not under git scrutiny unless we git add -f ... changes
> 
> I know, we've had some issues with people accidentally committing huge netcdf files in the past

I remember :rofl: It's good we have that block

**Pull request merged**
