### PR TITLE
Drop support for Python 3.6

### LINKED ISSUE #1199: Drop support for Python 3.6
it's very old, we don't support it in ESMValTool no more and some of the latest dependencies are not supporting it (eg `cf-units=3.0.0`)

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Closes #1199 
Related to full functionality of https://github.com/ESMValGroup/ESMValCore/pull/1182
Tests failing due to problem fixed in #1197 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful - **No, but see what I says above**

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@bouweandela @zklaus we should talk about this at the meeting tomorrow :+1:

**Comment by zklaus** [comment]
Agree with the idea, have not yet checked the implementation.

**Comment by zklaus** [comment]
Will do once we decide to go ahead with this. :beers:

**Comment by valeriupredoi** [comment]
OK if we do it in 2.4 then let's just get #1182 and #1197  in and I'll just take 3.6 out the Github Action tests, basically we will have no support for it via those two PRs but not saying it explicitly in our docs and environment file

**Review by bouweandela — APPROVED** [review]
The conda build is taking too long, but it looks unrelated to this pull request.

**Pull request merged**
