### PR TITLE
add support for percentile statistic to preprocessor

### LINKED ISSUE #1249: Add percentile stat for time statistics to pre processor
**Is your feature request related to a problem? Please describe.**
The preprocessor does not currently support the iris percentile aggregator for time based statistics. https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/analysis.html?highlight=percentile#iris.analysis.PERCENTILE

**Would you be able to help out?**
I've produced a PR #1250 that implements this for the climate statistics pre processor. If the approach is acceptable it could probably be extended fairly easily to the other statistics pre processors.

### PR DESCRIPTION
**Pull request by thomascrocker**
Closes #1249

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — CHANGES_REQUESTED** [review]
cheers muchly @thomascrocker :beer: It's good to have yet another group of builtin iris ops in, but could you please add a couple tests (expand the kwargs to actual values in the tests) and we'd also need documentation :+1:

**Review by znicholls — COMMENTED** [review]
@valeriupredoi @zklaus I should preface this by saying that I read through https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests so I think I'm reviewing in the intended way, but please let me know if not

From a scientific point of view this is obviously a helpful thing and relevant. Docs need to be added as pointed out by @valeriupredoi.

**Comment by znicholls** [comment]
@thomascrocker and @valeriupredoi what's the right next step here? I'm happy to a) create a new PR based on a rebased version of this branch b) rebase this branch and force push (although comes with risk of creating headaches for anyone else using this branch) or c) follow whatever standard ESMValTool practice is

**Comment by schlunma** [comment]
Hey @thomascrocker and @znicholls, sorry for this massive delay! I just finished https://github.com/ESMValGroup/ESMValCore/pull/2191, which is a more general PR that should fully include this PR. If you are still interested in this feature, please give it a try and let me know what you think!

P.S.: I will be on vacation the next two weeks and won't check GitHub. Afterwards I'll plan to finish this :+1:

**Comment by thomascrocker** [comment]
> Hey @thomascrocker and @znicholls, sorry for this massive delay! I just finished #2191, which is a more general PR that should fully include this PR. If you are still interested in this feature, please give it a try and let me know what you think!
> 
> P.S.: I will be on vacation the next two weeks and won't check GitHub. Afterwards I'll plan to finish this 👍

Great thank you. I will highlight to my team who I expect would find this functionality useful. 👍

**Comment by schlunma** [comment]
This is now fully supported, see https://esmvaltool--2387.org.readthedocs.build/projects/ESMValCore/en/2387/recipe/preprocessor.html#statistical-preprocessors. Feel free to reopen if necessary.

**Pull request closed without merging**
