### PR TITLE
Run a nightly test with the development version of dependencies

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Add a nightly test with development versions of upstream packages, to signal problems early. As agreed at the [tech lead team meeting on 2024-07-02](https://github.com/ESMValGroup/Community/blob/main/Tech%20Lead/Minutes/20240702.md).

Other changes in this pull request:
- update the orbs to the latest versions
- write logs also to the terminal for easier viewing

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
this is very nice, see the [output](https://circleci.com/api/v1.1/project/github/ESMValGroup/ESMValCore/47870/output/106/0?file=true&allocation-id=66966ff1283d4b62e6e1b50d-0-build%2FABCDEFGH) generated by running this new test. The only question I have is: I think we're bound to catch a few too many issues if we test against the dev versions of all those packages, and maybe we get lost in understanding what's going on, should we not just use it for iris, as @ehogan initially suggested in the TLT minutes?

**Comment by valeriupredoi** [comment]
ie what I meant by issues: both installation issues resulted from dependency conflicts (unevened environments yet to be evened at release times by all those guys); also scientific/numerical/deprecation troubles eg iris depends on cartopy, but cartopy decides to change something in their dev code, iris dev picks up the conda cartopy so all's fine, but when dev cartopy is installed, iris barfs, and we don't know who needs to fix what - we really don't want to start acting like the US Marines going everywhere to solve problems :grin:

**Comment by ehogan** [comment]
Thanks @bouweandela! 🥳 

> The only question I have is: I think we're bound to catch a few too many issues if we test against the dev versions of all those packages, and maybe we get lost in understanding what's going on, should we not just use it for iris, as @ehogan initially suggested in the TLT minutes?

I had this same question 😊 We could see how it goes testing all these packages and if it gets too noisy we could review? 🤔

**Comment by bouweandela** [comment]
> We could see how it goes testing all these packages and if it gets too noisy we could review? 🤔

That sounds like a great plan!

**Review by ehogan — APPROVED** [review]

**Pull request merged**
