### PR TITLE
allow contiguous representation of extracted regions

### LINKED ISSUE #2229: extract_region forces the region to be represented from 0-360 longitude
`extract_region` uses an iris cube `intersection`, and then applies another so that the cube is represented from 0-360 longitude. If the extracted region crosses 360 degrees, this forces the bounds to be discontiguous, and prevents future regrid-ing. I see that, in the default preprocessing order, regrid-ing is done before extracting a region. However I can see no obvious benefit to forcing the cube to be stored from 0-360 degrees, and it complicates analysis down the line outside of the preprocessor. I propose that this line be removed.

### PR DESCRIPTION
**Pull request by rebeccaherman1**
## Description

Remove automatic intersection with longitude=(0,360) from `extract_region` code

Closes #2229

Am I meant to fill out the checklist below? Still trying to understand the instructions for pull requests.

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

### CODE REVIEW

**Comment by rebeccaherman1** [comment]
Since I have not done pull requests before, it's a lot to take in and I do not fully understand what I'm looking at or how to figure it out regarding the unit tests etc. Guidance and feedback appreciated! (@valeriupredoi? :) )

**Comment by valeriupredoi** [comment]
@rebeccaherman1 welcome to the developers' bunch of ESMValCore! Cheers for the PR, let me know when you are happy with it (bar tests and other more advanced features) and I can come by here do a review and try help with the tests etc :+1: :beer:

**Comment by rebeccaherman1** [comment]
@valeriupredoi I do just want to remove that one line which I think is causing me problems with no obvious gain.
It is not a new feature, but rather a small adjustment to an existing feature, so I do not feel I need to add any unit tests or documentation.

The problem is that I do not know why that line was originally included -- there may have been a reason motivated by some future function which may have to be modified to respond to this -- I don't know. Or maybe it just seemed like a good idea at the time and is actually not important. 

I did not understand how to run tests on my own, so I tried just submitting the PR to see what would happen with the existing unit tests. But, of course, it is now failing one, and I don't understand how to figure out what test it is failing and why.

**Comment by valeriupredoi** [comment]
@zklaus would you, by any remote chance. have some time to run a few recipes with this, during your release tests, plsss? @schlunma (and myself, recently converted) believes this should work fine to avoid the non-contiguity issue that Rebecca raise in the linked issue :beer:

**Comment by bouweandela** [comment]
> Am I meant to fill out the checklist below? Still trying to understand the instructions for pull requests.

Yes. If you click the links you will find more information that explains what the checkbox is all about. A general introduction to contributing to ESMValCore is available here: https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html

**Comment by rebeccaherman1** [comment]
@bouweandela Thanks for the tip about running tests in the linked thread. 
It turns out that the one test that was failing was a test that targets the functionality I wished to change. 
@valeriupredoi Now that I've modified the expected output in that one tests, all tests pass. Would you be willing to do the review?
Are we still hoping for @zklaus to test some recipes?
I have not checked the "backwards compatible" checkbox above because this is a change in specs, but a good one.

**Comment by valeriupredoi** [comment]
@rebeccaherman1 good work! Shall do, in a jiffy :+1:

**Review by valeriupredoi — APPROVED** [review]
many thanks @rebeccherman1 - @schlunma would you be OK to merge pls (think we don't really have to run any more recipes, let's fix it when it breaks - to paraphrase Boeing) :beer:

**Comment by bouweandela** [comment]
Could you please check if other preprocessor functions rely on the behavior that is getting removed here?

**Comment by rebeccaherman1** [comment]
@bouweandela see no sign that any other preprocessor relies on this behavior.

**Comment by bouweandela** [comment]
Thanks for checking!

**Pull request merged**
