### PR TITLE
Set unit=1 if anomalies are standardized

### LINKED ISSUE #726: Standardized anomalies should be unitless.
**Describe the bug**
The title says it all. Found by @hb326 while testing https://github.com/ESMValGroup/ESMValTool/issues/1687.

### PR DESCRIPTION
**Pull request by bascrezee**
Closes #726. @hb326 Can you test in combination with the MPQB framework?

### CODE REVIEW

**Comment by bascrezee** [comment]
@hb326 Can you test?

**Comment by bascrezee** [comment]
@hb326 Did you test? I can already tell that we run into a few issues that have to be solved.

**Comment by hb326** [comment]
@bascrezee: I did test it just now. Does not work for the MPQB.
See the following error message:
`ValueError: Unable to convert from 'Unit('1')' to 'Unit('kg m-2 s-1')'.`
`2020-08-06 09:41:58,509 UTC [44220] INFO    If you suspect this is a bug or need help, please open an issue on https://github.com/ESMValGroup/ESMValTool/issues and attach the run/recipe_*.yml and run/main_log_debug.txt files from the output directory.`

Seems to me it is the same error as you reported in #741

**Comment by hb326** [comment]
I ran the MPQB recipe again, with the inlcuded changes to the preprocessor.
Good news: it ran through!
Not so good news: I am missing the units at the y-axis... Are there supposed to be units?
lineplot_pr_1983-2016

**Comment by bascrezee** [comment]
Can you check the units of the preprocessor file?  `ncdump -h ` I would expect them to be `1`.

**Comment by hb326** [comment]
> 
> 
> Can you check the units of the preprocessor output? `ncdump -h ` I would expect them to be `1`.

@bascrezee: yes, the unit is '1' in the preprocessor output.

**Comment by bascrezee** [comment]
Good. Than all is fine I would say, the units not being shown at the y-axis there is Iris behaviour (`iris.quickplot.plot`). Apparently it defaults to not showing in this case, which is fine. I am now working on the tests as requested by @jvegasbsc.

**Comment by bascrezee** [comment]
Can this be merged?

**Pull request merged**
