### PR TITLE
Bugfix for regional regridding when non-integer range is passed

### LINKED ISSUE #1230: New regional regrid option fails with float inputs for target grid
Trying to use the new regional regrid option from #1034 with the following spec

```yaml
    regrid:
      scheme: linear
      lon_offset: true
      lat_offset: true
      target_grid:
          start_longitude: 3.75
          end_longitude: 11.75
          start_latitude: 46.25
          end_latitude: 52.25
          step_longitude: 0.5
          step_latitude: 0.5
```
fails for me with 

```
  File "/home/peter/ESMValCore/esmvalcore/preprocessor/_regrid.py", line 257, in get_points
    num = int((stop - start) // Decimal(str(step)))
TypeError: unsupported operand type(s) for //: 'float' and 'decimal.Decimal'
```

Initial discussion in https://github.com/ESMValGroup/ESMValCore/pull/1034

### PR DESCRIPTION
**Pull request by stefsmeets**
## Description

Small bug fix for when a non-integer range is passed to the regional regridding preprocessor

Closes #1230

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by stefsmeets** [comment]
Hi @Peter9192 , this seems to work. I added your numbers as a failing test and adding the Decimal type fixes it. Can you have a test on your data?

**Comment by Peter9192** [comment]
Hey @stefsmeets thanks for responding so quickly with a fix! The recipe now runs, but it seems the latitude and longitude values now have an addition `0.001` added to them like so: 

```
lat = 52.251, 51.751, 51.251, 50.751, 50.251, 49.751, 49.251, 48.751,
    48.251, 47.751, 47.251, 46.751, 46.251
```

This leads to conflicts further on in my workflow...

**Comment by stefsmeets** [comment]
Hi @Peter9192 , I cannot reproduce that in the test. This exact case is tested for in `test_spec_to_latlonvals`, where it compares the output start value to the input start value. They must be the same: https://github.com/ESMValGroup/ESMValCore/blob/2a0bb11cb52df3ec4a485a16bf92356e04617b52/tests/unit/preprocessor/_regrid/test_extract_regional_grid.py#L82

Could it be something further downstream in your recipe? Feel free to hi-jack this PR if you find a solution.

**Comment by Peter9192** [comment]
You're right, the addition of that 0.001 happens further downstream (and it's intentional... 😅 ):

https://github.com/ESMValGroup/ESMValTool/blob/203fe50a861154f228b444000a5979c943d9768f/esmvaltool/diag_scripts/hydrology/pcrglobwb.py#L121-L125

Thanks again!

**Review by Peter9192 — APPROVED** [review]
Thanks for the quick action @stefsmeets.

**Comment by stefsmeets** [comment]
Glad we got this sorted then! 😅

@ESMValGroup/esmvaltool-coreteam This PR is ready to be merged!

**Pull request merged**
