### PR TITLE
Correctly use masked arrays after `unstructured_nearest` regridding

### LINKED ISSUE #1413: `unstructured_nearest` regridding does not return masked arrays
The `unstructured_nearest` regridding scheme does not return masked arrays (only regular `dask`/`numpy` arrays with explicit values of `1e20`). This can lead to problems further down the preprocessing chain and gets only fixed in the `save` step.

This is actually a problem of `iris`, but since they will improve their support for unstructured grids soon and we will also probably adapt the regridding preprocessor I don't think it is worth to report this upstream.

This can be solved with a single line, I will open a quick PR for that!

### PR DESCRIPTION
**Pull request by schlunma**
## Description

Right now, `unstructured_nearest` regridding does not return masked arrays. This PR fixes this.

Closes #1413

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
looks good! when iris will have fixed this it'd be good to remove the condition but leave the test - I'd argue an issue about this on GH scitools-iris would be good to have :+1:

**Comment by schlunma** [comment]
I found an issue with this, please do not merge yet :grimacing:

**Comment by valeriupredoi** [comment]
you merge at will, man, am off on baby Jesus holidays :christmas_tree: :santa:

**Comment by schlunma** [comment]
Cheers, happy hollidays!! :santa: :christmas_tree:

**Review by valeriupredoi — APPROVED** [review]

**Pull request merged**
