### PR TITLE
Update github PR template

### LINKED ISSUE #908: Update github PR template
**Is your feature request related to a problem? Please describe.**
Hi everyone, we recently updated the github PR template for ESMValTool: https://github.com/ESMValGroup/ESMValTool/pull/1924
It would be nice if the PR template for ESMValCore receives the same treatment.

**Would you be able to help out?**
👍

### PR DESCRIPTION
**Pull request by stefsmeets**
Hi everyone, this PR updates the github PR template to be more in line with ESMValCore, following up on https://github.com/ESMValGroup/ESMValTool/pull/1924.

The next PR template is shown in the comment below.

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #908

### CODE REVIEW

**Comment by stefsmeets** [comment]
## Description


- Closes/Fixes: #issue_number
- Link to documentation:

* * *

## Before you get started

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

- [ ] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
- [ ] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
- [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
- [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
- [ ] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
- [ ] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
- [ ] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
- [ ] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:
- [ ] Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description
 
***

To help with the number pull requests:

-  🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

**Comment by stefsmeets** [comment]
There are a bunch of issues from the markdown linter that I'm not sure I agree with. They seem to be super strict, and not something we normally do. Did something change recently here?

**Review by nielsdrost — COMMENTED** [review]
Nice work @stefsmeets!

No comments on the content, looking great :-)

Not sure what's going on with the markdown linter either. Did you run it through a local linter?

**Comment by nielsdrost** [comment]
I ran this trough markdownlint, it only gave a single error on how the top level header is not a "#" (which I do not agree with).

**Review by nielsdrost — APPROVED** [review]
Thanks @stefsmeets!

**Pull request merged**
