### PR TITLE
remove flag to use pip 2020 solver from Github Action pip install command on OSX

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

That flag will introduce an error in `pip=21.0` so let's just get rid of it (it is now the default solver, so all's safe and sound). See example [warning](https://github.com/ESMValGroup/ESMValCore/runs/3865183742?check_suite_focus=true)

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@schlunma you mind giving me a quick review here please mate? We need to get this in ideally for the release :beer:

**Comment by valeriupredoi** [comment]
@schlunma yis, good point! Pip introduced a more robust but different dependency resolver back when were were all working from home (sneaky! :grin: ), see [communication release](https://discuss.python.org/t/announcement-pip-20-2-release/4863) and that was breaking some stuffs back then, now it's the default resolver and the call to use the older resolver is deprecated and will introduce an error if used :+1: :beer:

**Review by schlunma — APPROVED** [review]
Cheers, thanks for the explanation!

**Comment by valeriupredoi** [comment]
cheers much for reviewing, Manu! :beer:

**Pull request merged**
