### PR TITLE
Custom user-defined location for custom CMOR tables

### LINKED ISSUE #1623: Custom user-defined location for custom CMOR tables
Currently, the location of custom CMOR tables is [hardcoded](https://github.com/ESMValGroup/ESMValCore/blob/933b37b225a89aeed84029d8c83105407ed7ae5f/esmvalcore/cmor/table.py#L820).

To facilitate the evaluation of new variables coming from native model output or new model components (e.g., ESM2025 project) that are not yet avaialble in the official CMOR tables, I think it would be good to allow the user the definition of a custom location for these custom CMOR tables in the `config-developer-yml` file. This can be implemented very easily [here](https://github.com/ESMValGroup/ESMValCore/blob/933b37b225a89aeed84029d8c83105407ed7ae5f/esmvalcore/cmor/table.py#L58).

The ultimate goal is of course to extend the CF standard names and/or CMOR tables, but since this process can take quite a while I think this feature would be great for users who want to have a quick look of newly defined variables. @zklaus what do you think? Would be great to get this into v2.6, I could open a PR today.

### PR DESCRIPTION
**Pull request by schlunma**
## Description

This PR allows the specification of a custom location for the custom CMOR tables in the `config-developer.yml` file (using the `custom` key).

Closes #1623 

Link to documentation:

- https://esmvaltool--1625.org.readthedocs.build/projects/ESMValCore/en/1625/quickstart/find_data.html#datasets-in-native-format
- https://esmvaltool--1625.org.readthedocs.build/projects/ESMValCore/en/1625/quickstart/configure.html#custom-cmor-tables
- https://esmvaltool--1625.org.readthedocs.build/projects/ESMValCore/en/1625/develop/fixing_data.html#add-support-for-new-native-datasets

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by sloosvel** [comment]
How is this going? Looks quite useful, but unfortunately now that all tests are passing,  I have to continue with the release procedure. So, apologies but this won't be included at the end.

**Comment by sloosvel** [comment]
How is this going? Looks quite useful, but unfortunately now that all tests are passing,  I have to continue with the release procedure. So, apologies but this won't be included at the end.

**Comment by schlunma** [comment]
The code is finished, just need to add some bits of doc and a tiny test. Would love to hear the opinion of @zklaus before I go on, though!

Don't worry, this doesn't need to go into `rc1`. If we need an `rc2` (which is more than likely given past experiences), we can still include this.

**Comment by schlunma** [comment]
Since there are no objections I will proceed with this PR now.

**Review by sloosvel — APPROVED** [review]
Tested for the following cases:
- Not setting the custom directory in config-developer
- Setting the custom directory as a relative path 
-  Setting the custom directory in a custom location

Works in all three cases as expected. Further comments and reviews are welcome, but I will merge on Monday if no one opposes.

**Pull request merged**
