### PR TITLE
Fix obs4MIPs capitalization

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

In #1217, the `obs4mips` project was renamed to `obs4MIPs`. However, #1032 added code that still used the old name and was not merged into #1217 before merging it. This pull request completes the rename.

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by zklaus — APPROVED** [review]

**Review by valeriupredoi — APPROVED** [review]
ran test locally (with adding `import iris.cube`) and it's biutiful :grin:

**Comment by valeriupredoi** [comment]
lesson for us to remember about the GH Actions tests if in doubt a Circle test has died of the dreaded SegFault or a valid fail (I forgot too, and ran the test locally instead) https://github.com/ESMValGroup/ESMValCore/actions/runs/1265911001

**Comment by valeriupredoi** [comment]
looks like we should give up Python 3.7 soon, man https://github.com/ESMValGroup/ESMValCore/runs/3687821651?check_suite_focus=true

**Comment by bouweandela** [comment]
Well spotted @valeriupredoi! See #1330.

**Pull request merged**
