### PR TITLE
update PyPI build `setup-python` action to latest v4 version

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

We are using a very old version of `setup-python` GA action, this latest one is also needed when we move to support the newly stabilized Python=3.12. v4 is the current version.

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] ~[☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do~

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
many thanks @zklaus - switched label to `testing` you reckon is a better one? It's a bit murky IMO but by me it could even be labelled `cowabunga` :grin:

**Comment by valeriupredoi** [comment]
@zklaus @bouweandela frenly ping, this would be nice to have in 2.10, py312 is just a PR around the corner :smiley:

**Comment by bouweandela** [comment]
Maybe use the `release` label?

**Comment by valeriupredoi** [comment]
@bouweandela @schlunma this is a breezy PR - could I pls get a looksee :beer:

**Comment by bouweandela** [comment]
Indeed, it seems to contain 0 changed files. Maybe these changes already made their way into `main` in some other pull request?

**Comment by valeriupredoi** [comment]
ha! That's a new one - cheers for noticing, bud, this will bite the dust then

**Pull request closed without merging**
