### PR TITLE
update conda lock file manually - test failed due to cf-units issue which is now fixed

### PR DESCRIPTION
**Pull request by valeriupredoi**

### CODE REVIEW

**Comment by valeriupredoi** [comment]
quick one for the reviewers - I wonder what happened to my admin rights - this was an easy merge w/o needing review :confused:

**Review by sloosvel — APPROVED** [review]

**Comment by zklaus** [comment]
I see nothing wrong with the lock file, but it doesn't actually touch cf-units. Is this still needed or how does it relate to the cf-units issue?

**Comment by sloosvel** [comment]
I would like to get the new release candidate out today, so if this could get sorted out it would be great!

**Comment by valeriupredoi** [comment]
it is now, thanks, Saskia!

**Comment by valeriupredoi** [comment]
oh shoot, completely missed that one, Klaus (too hot to scroll) - it's not changed coz we pinned it, the lock file uses the current `environment` file so it had initially failed its scheduled 10-daily re-creation run coz of cf-units, so I had to rebuild it manually just to stick to the schedule - no actual fix needed, just sticking to the scheduled rebuild

**Pull request merged**
