### PR TITLE
Fix alignment of daily data with inconsistent calendars in multimodel statistics

### LINKED ISSUE #1198: Multi-model mean fails for Core V2.3.0 because of difference in aux_coords
**Describe the bug**
A multi-model mean, which was running for the last core version now fails because:
> Encountered the following exception: failed to merge into a single cube.
> Coordinates in cube.aux_coords (scalar) differ by dtype or class (i.e. DimCoord vs AuxCoord).

Different to the case reported here: https://github.com/ESMValGroup/ESMValTool/issues/2198 
the recipe does not use "extract_level" but "extract_region" and "extract_season", could this be connected?

**Please attach**
  - The recipe is attached here, it belongs to the PR https://github.com/ESMValGroup/ESMValTool/pull/2153 There the multi-model mean is currently turned off.
[recipe_pv_capacity_factor.yml_coord_issue_multi_model_mean.txt](https://github.com/ESMValGroup/ESMValCore/files/6726402/recipe_pv_capacity_factor.yml_coord_issue_multi_model_mean.txt)

  - The `main_log_debug.txt` file:
[run_main_log_debug_coord_issue_multi_model_mean.txt](https://github.com/ESMValGroup/ESMValCore/files/6726397/run_main_log_debug_coord_issue_multi_model_mean.txt)

### LINKED ISSUE #1210: How should multi-model statistics handle daily data on different calendars?
More comprehensive metadata handling in the multi-model statistics recently turned up a conceptual issue for multi-model statistics on daily data with different calendars.

The issue is that in this case there are days, for which only a subset of models may provide data. This happens usually for datasets that contain leap days (gregorian or standard calendar, all_leap) vs those that don't (noleap), or with more unusual calendars (360_day, 30 days in every month); see [CF conventions 1.7, Sect. 4.4.1](http://cfconventions.org/cf-conventions/cf-conventions.html#calendar) for the full list of supported calendars).

The old version of the multi-model statistics has two modes (selected with the parameter `span`). In `overlap` mode, it discards all days that don't appear in all datasets, producing a result that leaves out those days. In `full` mode, 
However, [the documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/stable/recipe/preprocessor.html#multi-model-statistics) states that
> As the number of days in a year may vary between calendars, (sub-)daily data with different calendars are not supported.

The new version of the multi-model statistics follows the documentation by throwing an exception, albeit a cryptic one.

Alternative strategies could be
- Follow the existing `overlap`/`full` strategies
- Refuse daily data
- Introduce a calendar aligning pre-processor. It is fairly common to deal with this problem by repeating certain days to fill up the missing information, or leaving out superfluous days, for example from the all_leap calendar.

Some aspects of this have been discussed in #1201 and #1198.
This issue has previously been mentioned in #937, #744.
It is also connected to #781.

### PR DESCRIPTION
**Pull request by Peter9192**
## Description

Following #1210 this PR implements the following behavior for multimodel statistics, when the input data is a daily frequency with inconsistent calendars:

- `span='overlap'`: discard those days that occur only in certain calendars but not in others
- `span='full'`: use nearest-neighbour lookup to fill missing days. Missing dates outside the original date range are masked.

This is in contrast to the previous behavior, which was:
- `span='overlap'`: Find the first and last day that is present in all datasets; remove everything before the first and after the last day.
- `span='full'`: Find the very first and the very last day across all cubes; pad every cube with masked out data before and after its actual data to cover the full time range.

This only worked for data with the same number of days per year, raising an exception otherwise.

Closes #1198

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] ~[🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available~
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
Thanks @Peter9192, that's great. To aid in finishing this up, could you please "do" the checklist, i.e. tick done items and remove or strike out non-applicable items? Also, could you try to put a plainer description, i.e. distinguish between filling missing and removing superfluous days and make clear if and how this relates to the `overlap` and `full` options?

**Comment by katjaweigel** [comment]
@Peter9192 thanks a lot for the fix! For the version of recipe_pv_capacity_factor.yml including the multi-model mean using different calendars runs with it. But I wonder if it should without Warning? Or would if it would be even better to only allow this if an additional preprocessor like regrid_time is used?

**Comment by zklaus** [comment]
I think let's roll with it for now (i.e. the release) and revisit the issue of calendars afterward. I did a review of the code here and think it is an improvement, but it does not support 360 day calendars, for instance, just like the old multi-model code did not support it.

There are a few more quirks I'd like to talk about and probably go to handling on a day-of-year basis, but for now, let's get this in as a stable platform to base future improvements on.

**Comment by Peter9192** [comment]
> Or would if it would be even better to only allow this if an additional preprocessor like regrid_time is used?

I agree that would be good, also see #744.

**Comment by zklaus** [comment]
@katjaweigel, if you are nevertheless happy to move forward with this for now, could you please "Approve" the PR?

**Review by katjaweigel — CHANGES_REQUESTED** [review]
I like the method to regrid the calendar, but I would at least keep a warning and not replace the warning without note with def _map_to_new_time.
Maybe it would be better to only allow it, if regrid_time is used as preprocessor (in agreement with different horizontal grids, here the multi-model mean can also only be applied if everything is interpolated on a common grid.)?

**Comment by katjaweigel** [comment]
> @katjaweigel, if you are nevertheless happy to move forward with this for now, could you please "Approve" the PR?

@zklaus I rather agree that this one could wait, because since the multi-model mean is removed from recipe_pv_capacity_factor.yml I don't think there is any recipe affected by this issue.

**Comment by zklaus** [comment]
> I like the method to regrid the calendar, but I would at least keep a warning and not replace the warning without note with def _map_to_new_time.

The warning is not removed here; it remains in [lines 116ff of `_multimodel.py`](https://github.com/ESMValGroup/ESMValCore/blob/f068c0f61ace481eba23bbb40b2a49e6a79d2ec8/esmvalcore/preprocessor/_multimodel.py#L116).

> Maybe it would be better to only allow it, if regrid_time is used as preprocessor (in agreement with different horizontal grids, here the multi-model mean can also only be applied if everything is interpolated on a common grid.)?

Yes, but let's leave that to #744.

**Comment by katjaweigel** [comment]
> The warning is not removed here

@zklaus you are right, the warning is there. Sorry I checked the wrong log file!

**Review by katjaweigel — APPROVED** [review]

**Comment by zklaus** [comment]
I edited this so that #1210 stays open for a better long-term solution.

**Pull request merged**
