### PR TITLE
fix for thetao and so variables in BCC models

### LINKED ISSUE #748: Thetao and so in BCC models
**Describe the bug**
Variables `thetao` and `so` for BCC models (`BCC-CSM2-MR` and `BCC-ESM1`) were not passing cmip6 fixes. I will reuse fix that is available for `tos` and do the PR.

### PR DESCRIPTION
**Pull request by koldunovn**
Before you start, please read our [contribution guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html).

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [ ] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #748

### CODE REVIEW

**Comment by nielsdrost** [comment]
@koldunovn Could this be causing the problem with the BCC dataset in https://github.com/ESMValGroup/ESMValTool/pull/1391?

Anything that still needs to be done on this, or is it waiting for a review?

**Comment by koldunovn** [comment]
@nielsdrost This fix is only for two ocean variables that I can personally check (`so` and `thetao`). Looks like the problems @ValerioLembo having are for atmospheric variables (sorry, did not go through all conversation, it's super long now :))). 

I would consider the PR ready, but you might want to expand it with atmospheric variables. On the other hand I would do one thing at a time, makes it easier to handle :)

**Comment by valeriupredoi** [comment]
@koldunovn cheers mate, I think this one's good to go - but a test would be nice to have for the new functionality please :beer:

**Comment by valeriupredoi** [comment]
ping @koldunovn for a testy-test please :beer:

**Comment by schlunma** [comment]
Will have a look at this after #1092 is merged. It can probably be fixed with

```py
Thetato = OceanFixGrid
```

**Comment by zklaus** [comment]
I believe this has meanwhile been addressed in #1090 and #1092.

**Pull request closed without merging**
