### PR TITLE
added test for simple mask combination for a small threshold for mask_fillvalues

### PR DESCRIPTION
**Pull request by valeriupredoi**
Solves the no-need for #487

### CODE REVIEW

**Comment by valeriupredoi** [comment]
Good call, will replace it in this PR. About the dox - am not sure how to make it more spoonfeeding - maybe Bas can give some advice as you mention :beer:

**Comment by bascrezee** [comment]
Sure, I can give some feedback. For me at first sight it is not clear that this preprocessor is a multimodel function. The nice box in `ESMValCore Preprocessor` (docs) helps a lot, maybe it would be good to also add some info to the doc string, such that it becomes clear when browsing the `ESMValCore API Reference` as well. 

Also I find it confusing that it is called `mask_fillvalues`, when reading in data, the `fillvalues` are already masked thanks to Iris correctly interpreting the CF conventions. This function actually goes two steps further, it (1) masks a certain time window if number of values are below a certain threshold and (2) it applies the masks from each single model into one mask applied to each model. I expected a separate preprocessor for step (2) that would be named something like `mask_multimodel`.

Not sure what to recommend concrete. Renaming this preprocessor is not really an option I guess. Two possible suggestions: 

a) make as default the following values: 
```
    mask_fillvalues:
      threshold_fraction: 0.0     # keep all missing values
      min_value: None            # small enough not to alter the data 
```
such that a user can simply call this in one line (advantage: user who just wants to apply the same mask to all datasets does not need to think about setting the right thresholds)
```
my_masking:
  mask_fillvalues  # apply same mask to all datasets
```

b) create a new preprocessor named `mask_multiproduct`. (additional advantage: the preprocessor has a more intuitive name):
```
def mask_multiproduct():
    mask_fillvalues(threshold_fraction=0.0, min_value: -1e20)
```

@BenMGeo might have input on this as well.

**Comment by valeriupredoi** [comment]
Cheers @bascrezee - much appreciated :beer: Since you are such a nice dude wrt this issue, can I be cheeky and ask you to create a PR with the changes in the documentation that you regard as useful and making the use of the function more straightforward? You and @BenMGeo , if you guys do that, will receive a German :beer: each from me at the workshop :grin:

**Comment by valeriupredoi** [comment]
I will plug the changed defaults now...

**Comment by valeriupredoi** [comment]
also I defer the consideration to rename the function to @mattiarighi since I coded it up in his service back during the hedy times of ESMValTool v2.0SuperInitialWhenWeWereYoungIn2017 :grin:

**Comment by mattiarighi** [comment]
`mask_multimodel` could be misleading, e.g. that this preprocessor is only applied to the dataset created by `multimodel_stats`.

`mask_multiproduct` is also confusing, since we are not using the term `product` anywhere (and it is usually applied to satellite data, rather than models).

I think `fillvalues` should remain in the preprocessor name, maybe we could change `mask` to something like `propagate`, `uniform` or `homogenize`.

**Comment by BenMGeo** [comment]
what about `common_mask_all_fillvalues`. It's a bit lengthy, but may be describing the functionality at best.

**Comment by mattiarighi** [comment]
or just `common_fillvalues` to make it shorter.

**Comment by bascrezee** [comment]
> or just `common_fillvalues` to make it shorter.

Nice suggestions @BenMGeo and @mattiarighi, and how about `mask_common_fillvalues` ? 

I like it when the first part of the preprocessor describes the "action". Like `extract_levels`, `clip`, `fix_data`, etc.

**Comment by mattiarighi** [comment]
Nice!

**Comment by BenMGeo** [comment]
> 
> 
> > or just `common_fillvalues` to make it shorter.
> 
> Nice suggestions @BenMGeo and @mattiarighi, and how about `mask_common_fillvalues` ?
> 
> I like it when the first part of the preprocessor describes the "action". Like `extract_levels`, `clip`, `fix_data`, etc.

This can be misinterpreted. Why masking common fillvalues when they are already common?

**Comment by bascrezee** [comment]
> > > or just `common_fillvalues` to make it shorter.
> > 
> > 
> > Nice suggestions @BenMGeo and @mattiarighi, and how about `mask_common_fillvalues` ?
> > I like it when the first part of the preprocessor describes the "action". Like `extract_levels`, `clip`, `fix_data`, etc.
> 
> This can be misinterpreted. Why masking common fillvalues when they are already common?

That is a good point. Hmmmm... the search continues. Some more thoughts: 

a) we can use a more general verb e.g. `apply` or `set` 

My suggestion than would be `set_common_mask`. This new name suggestion would be solely for a new preprocessor which basically wraps the existing (not renamed) preprocessor `mask_fillvalues`, like this:

```
def set_common_mask(products):
    mask_fillvalues(products, threshold_fraction=0.0, min_value: -1e20)
```

**Comment by mattiarighi** [comment]
I think we should avoid wrappers: it would make recipes and documentation more confusing.

**Comment by bascrezee** [comment]
> I think we should avoid wrappers: it would make recipes and documentation more confusing.

Does that mean that you are in favour of renaming the function `mask_fillvalues` ?

**Comment by mattiarighi** [comment]
Yes, as I said [above](https://github.com/ESMValGroup/ESMValCore/pull/492#issuecomment-586213116).

**Comment by BenMGeo** [comment]
> I think we should avoid wrappers: it would make recipes and documentation more confusing.

The question is, if we want to provide functionality to different levels of user experience. The wrapped one is easier to use and understand for beginners. 

If no wrappers are wanted, just merge it as is. We try to extend the documentation examples then.

**Comment by bascrezee** [comment]
> If no wrappers are wanted, just merge it as is. 

Yes, I agree. I do not see a way of renaming `mask_fillvalues` in a way that reflects everything that can be done with this preprocessor. 

> We try to extend the documentation examples then.
Agree.

**Comment by valeriupredoi** [comment]
you guys had a name-the-baby party and I wasn't here :grin: Can we then accept this PR (mind you, just a wee test) and sail into the sunset :ocean:

**Comment by mattiarighi** [comment]
Waiting for @bouweandela's approval.

**Comment by valeriupredoi** [comment]
@bouweandela says:
> The test looks fine.
We can forget about the However... bit :grin:

**Comment by bouweandela** [comment]
>> We try to extend the documentation examples then.

>Agreed.

Who will do this? It would be good to get this done in this pull request, because the entire discussion lives here.

**Comment by valeriupredoi** [comment]
:eyes: :eyes:

**Comment by BenMGeo** [comment]
I just looked at the docs and I think it is already there. Maybe we should upgrade the information from a note to a section?!

**Comment by valeriupredoi** [comment]
Cheers @BenMGeo - proves out I can't remember what I wrote, a case of old age surely :grin: @bouweandela all good wrt your comment? :beer:

**Pull request merged**
