### PR TITLE
remove `with_mypy` or `with-mypy` extension/optional tool for prospector

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

~There is an issue with prospector=1.10.2 at the moment and installing it with `with_mypy` makes it not work at all, so I am removing this extra tool for now, so we have some functionality out of it, rather than a complete shutdown;~

~Nevermind, `prospectpr=1.10.2` needs `with-mypy` instead of `with_mypy` due to `poetry` changing version, and @carlio (the prospector main dev) tells me this may change in the future again, depending how poetry wakes up in the morning (what version it is one)~

@bouweandela suggested we remove the extra tool option altogether since we run the mypy tests separately anyway :+1: 

See https://github.com/landscapeio/prospector/issues/624

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
We can just drop the `with_mypy`/`with-mypy` extra because we're installing mypy separately already.

**Comment by valeriupredoi** [comment]
aha! Let me do that now - even better! :beer:

**Comment by bouweandela** [comment]
> @bouweandela suggested we remove the extra tool option altogether since we run the mypy tests separately anyway +1

What I actually meant is that we're installing `mypy` as a separate tool as well, so there is no need to pull it in through the prospector `with_mypy` extra. Because it is installed, it works fine with `prospector` too.

**Review by bouweandela — APPROVED** [review]

**Comment by valeriupredoi** [comment]
> > @bouweandela suggested we remove the extra tool option altogether since we run the mypy tests separately anyway +1
> 
> What I actually meant is that we're installing `mypy` as a separate tool as well, so there is no need to pull it in through the prospector `with_mypy` extra. Because it is installed, it works fine with `prospector` too.

indeed - mypy is a core dep for us here - may want to deouble check in Tool though

**Pull request merged**
