### PR TITLE
Pin esmpy <8.6.0

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

issues with iris-esmf-regrid mentioned by @schlunma in https://github.com/SciTools-incubator/iris-esmf-regrid/pull/342#issuecomment-2092921514 and confirmed by me in MO/ANCIL-ANTS, see https://github.com/valeriupredoi/ANTS_stuff/blob/main/ANTS_JASMIN.md - no issue raised at ESMF Github just yet though, so possibly just an iris-esmf-regrid issue, but pinning that instead is no bueno, since we'd better have their latest version up, and that works fine with older ESMF/Py's according to Manu.

~Also remove `esmpy` from `setup.py`~ -> `esmpy` is not on PyPI, they get their source for the package straight from Github packages https://github.com/conda-forge/esmpy-feedstock/blob/main/recipe/meta.yaml but we should still keep it for regulations

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by schlunma — APPROVED** [review]
Looks good to me, thanks V!

**Review by bouweandela — CHANGES_REQUESTED** [review]
From the contribution [guidelines on dependencies](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies):

> setup.py contains all Python dependencies, regardless of their installation source

Could you please explain why `esmpy` needs to be removed in this case?

**Comment by valeriupredoi** [comment]
@bouweandela as per our discussion at the TLT I have readded `esmpy` to `setup.py` in https://github.com/ESMValGroup/ESMValCore/pull/2402/commits/63e20c2b34e87567288b378f853e0d6f898fb83e - if you got a sec, pls re-review and merge :beer:

**Review by bouweandela — APPROVED** [review]

**Comment by valeriupredoi** [comment]
muchos bedankt, bud :beer:

**Pull request merged**
