### PR TITLE
Fix mistake in the documentation of `esmvalcore.esgf.find_files`

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

There is a mistake in the docstring of `esmvalcore.esgf.find_files`. The function is called `search` in the docstring, where it should be `find_files`. This pull request corrects the issue.

Link to documentation: https://esmvaltool--1784.org.readthedocs.build/projects/ESMValCore/en/1784/api/esmvalcore.esgf.html#esmvalcore.esgf.find_files

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by schlunma — APPROVED** [review]
Looks good, thanks Bouwe!

**Comment by bouweandela** [comment]
Thanks for the review @schlunma! @ESMValGroup/technical-lead-development-team Could one of you please do a final [check and then merge](https://docs.esmvaltool.org/en/latest/community/review.html#merge)?

**Comment by valeriupredoi** [comment]
I shallz!

**Review by valeriupredoi — APPROVED** [review]
noice, cheers guys!

**Pull request merged**
