### PR TITLE
Optimize time weights in time preprocessor for climate statistics

### PR DESCRIPTION
**Pull request by valeriupredoi**
Before you start, please read our [contribution guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html).

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #issue_number

No issue - just an email I got from @ledm earlier today telling me he ran into a memory assignment problem with a large cube.

### CODE REVIEW

**Comment by ledm** [comment]
This is a good opportunity to add the following chunk of code, which would make the `climate_statistics` operator much more efficient:
https://github.com/ESMValGroup/ESMValCore/blob/development_ar6_chap_3_ocean/esmvalcore/preprocessor/_time.py#L408
```
    if period in ('full', ):
        operator_method = get_iris_analysis_operation(operator)
        if operator_accept_weights(operator):
            time_weights = get_time_weights(cube)
            if time_weights.min() == time_weights.max():
                # No weighting needed.
                cube = cube.collapsed('time',
                                      operator_method)
            else:
               cube = cube.collapsed('time',
                                  operator_method,
                                  weights=time_weights)
        else:
            cube = cube.collapsed('time', operator_method)
        return cube

```
Basically, you only need to use weights when there's a difference in the weights. If they're all the same, a normal mean operation is far faster and efficient.

**Comment by valeriupredoi** [comment]
can you commit the change pls? :beer:

**Comment by valeriupredoi** [comment]
nay bother, am doing it now, need to add a test anyway

**Comment by valeriupredoi** [comment]
ok done, @ledm can you test with your used case that was chucking too much mem mate pls? :beer:

**Comment by valeriupredoi** [comment]
@jvegasbsc @bouweandela @ledm can you guys have a look and approve this PR please, it'd be good to have it in today so we have it for the release - the IPCC effort would benefit from it and it's kinda happening right now :beer:

**Comment by ledm** [comment]
So I can my code and it went well. However, I've only tested the  cause:
```
            if time_weights.min() == time_weights.max():
                # No weighting needed.
                cube = cube.collapsed('time',
                                      operator_method)
```
As I'm not yet running over a model with uneven time resolution. Happy to add one to my recipe though. Can anyone remember one I could test with?

**Comment by valeriupredoi** [comment]
cheers @jvegasbsc and @ledm :beer:

**Comment by ledm** [comment]
> So I can my code and it went well. However, I've only tested the cause:
> 
> ```
>             if time_weights.min() == time_weights.max():
>                 # No weighting needed.
>                 cube = cube.collapsed('time',
>                                       operator_method)
> ```
> 
> As I'm not yet running over a model with uneven time resolution. Happy to add one to my recipe though. Can anyone remember one I could test with?



I've now tested this code with another model dataset (UKESM1) and it fails.



```
"""
Traceback (most recent call last):
  File "/home/users/ldemora/anaconda3_20190821/envs/Vconda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/users/ldemora/workspace/ESMValTool_AR6/ESMValCore/esmvalcore/_task.py", line 723, in _run_task
    output_files = task.run()
  File "/home/users/ldemora/workspace/ESMValTool_AR6/ESMValCore/esmvalcore/_task.py", line 242, in run
    self.output_files = self._run(input_files)
  File "/home/users/ldemora/workspace/ESMValTool_AR6/ESMValCore/esmvalcore/preprocessor/__init__.py", line 428, in _run
    product.apply(step, self.debug)
  File "/home/users/ldemora/workspace/ESMValTool_AR6/ESMValCore/esmvalcore/preprocessor/__init__.py", line 296, in apply
    self.cubes = preprocess(self.cubes, step, **self.settings[step])
  File "/home/users/ldemora/workspace/ESMValTool_AR6/ESMValCore/esmvalcore/preprocessor/__init__.py", line 241, in preprocess
    result.append(_run_preproc_function(function, item, settings))
  File "/home/users/ldemora/workspace/ESMValTool_AR6/ESMValCore/esmvalcore/preprocessor/__init__.py", line 224, in _run_preproc_fun
ction
    return function(items, **kwargs)
  File "/home/users/ldemora/workspace/ESMValTool_AR6/ESMValCore/esmvalcore/preprocessor/_time.py", line 399, in climate_statistics
    time_weights = get_time_weights(cube)
  File "/home/users/ldemora/workspace/ESMValTool_AR6/ESMValCore/esmvalcore/preprocessor/_time.py", line 176, in get_time_weights
    time_weights = time_thickness * da.ones_like(cube.data)
  File "/home/users/ldemora/anaconda3_20190821/envs/Vconda/lib/python3.8/site-packages/dask/array/core.py", line 1221, in __array_u
func__
    return elemwise(numpy_ufunc, *inputs, **kwargs)
  File "/home/users/ldemora/anaconda3_20190821/envs/Vconda/lib/python3.8/site-packages/dask/array/core.py", line 3912, in elemwise
    broadcast_shapes(*shapes)
  File "/home/users/ldemora/anaconda3_20190821/envs/Vconda/lib/python3.8/site-packages/dask/array/core.py", line 3871, in broadcast
_shapes
    raise ValueError(
ValueError: operands could not be broadcast together with shapes (60,) (60, 75, 330, 360)
"""
```

**Comment by schlunma** [comment]
@ledm this is fixed in #695, we need to merge this soon.

**Pull request merged**
