### PR TITLE
Speed up ESGF search

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

This pull request speeds up searching for files on ESGF. This requires the latest version of esgf-pyclient (0.3.1), because it uses a feature that was broken in the previous release. See https://github.com/ESGF/esgf-pyclient/issues/75.

This pull request also takes into account that https://github.com/ESGF/esgf-pyclient/issues/71 and https://github.com/conda-forge/esgf-pyclient-feedstock/issues/12 have been solved now.

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
cheers much @bouweandela - I will trun on one GA action here then turn it off if all goes well, so please don't merge just yet (I'll turn it on in a few minutes, I just merged a PR and that's hogging a fair bit of GA nodes now); @schlunma heads up you guys will have to change the feedstock recipe with the new pins Bouwe put it, I think :+1:

**Comment by schlunma** [comment]
I will do a couple of tests of the download feature with this change :+1:

**Comment by valeriupredoi** [comment]
I don't feel like opening anew issue and since we have @bouweandela 's attention here I'll just ask: we had loads of coonectivity issues to llnl last night: `HTTPConnectionPool(host='esgf-node.llnl.gov', port=80): Read timed out. (read timeout=120)` - probably everyone was streaming the State of the Union speech, would it be an option to bypass these if it's just a connection hiccup and mark tests xfail or skip? I think there was an issue about this now that I think about it...meh, Bouwe, what you reckon?

**Review by schlunma — APPROVED** [review]
I tested 3 recipes with this and everything worked fine! From these 3 tests I cannot really tell if there is a speedup, but let's use the next round of recipe tests for that.

Thanks @bouweandela!!

@remi-kazeroni Please merge when you are happy with this :+1:

**Review by remi-kazeroni — APPROVED** [review]
Thanks a lot @bouweandela! It works fine for me as well. I have run several recipes and the ESGF search seemed rather fast. I can't tell the gain based on these runs. We'll have a better overview after the next round of recipe testing for the v2.5 release.

**Pull request merged**
