### PR TITLE
Update documentation on ESMValTool module at DKRZ

### PR DESCRIPTION
**Pull request by remi-kazeroni**
## Description

Similar to https://github.com/ESMValGroup/ESMValTool/issues/1888 but for the Core

Link to documentation: https://esmvaltool--1647.org.readthedocs.build/projects/ESMValCore/en/1647/quickstart/install.html#pre-installed-versions-on-hpc-clusters

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
~~- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added~~
~~- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)~~
~~- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~~
~~- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date~~
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by remi-kazeroni** [comment]
@sloosvel, would it be ok to merge this now or shall we rather wait until the release is finished?

**Comment by sloosvel** [comment]
I have a branch for 2.6, so I don't mind if this goes in main. I am not sure if another release candidate will be needed though, as rc2 was behaving quite well. However do you know how long it takes to get packages in conda forge? I still cannot see rc3...

**Comment by schlunma** [comment]
> However do you know how long it takes to get packages in conda forge? I still cannot see rc3...

This should be a matter of hours at most, no idea what is going on there...

**Comment by zklaus** [comment]
And just as I write this, the build succeeded, so we can expect rc3 on the repo in ~2hr.

**Comment by valeriupredoi** [comment]
> And just as I write this, the build succeeded, so we can expect rc3 on the repo in ~2hr.

that's great! Cheers, dude! Do you know why it ran the .4 test when the .3 (PR) test went well btw?

**Comment by valeriupredoi** [comment]
Gotcha! So that failed test was a ticking bomb, not some crazy fail due to conda not loving us then :grin:

**Comment by remi-kazeroni** [comment]
> I have a branch for 2.6, so I don't mind if this goes in main. I am not sure if another release candidate will be needed though, as rc2 was behaving quite well. However do you know how long it takes to get packages in conda forge? I still cannot see rc3...

Then I leave it up to you to press the merge button whenever you think it's best to do so. This is only minor documentation changes so the timing does not really matter.

**Pull request merged**
