### PR TITLE
updating changelog and CITATION in main to reflect files from 2.7.0 release

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

This is a bit of a departure from our usual way of updating the changelog, but I had to add a couple items to the Changelog in the [release branch](https://github.com/ESMValGroup/ESMValCore/tree/release_270stable) - the update of the changelog from #1746 and @schlunma 's very useful #1755 - I could have waited for a final final approval and only then moving it to the release branch, but given it's just two itty bitty changelog changes I'd rather get it done with the Core stable release :grin: 

This will be the first documentation entry for v2.8.0 yay!

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
not a worry, Manu! yeah, I will remove the Milestone, now that you pointed out that does sound a bit hacky after all :grin: Yes! Good call, I'll merge the release branch into main - actually here to reuse the PR

**Comment by valeriupredoi** [comment]
OK all is clean and placed in here, you wanna have another look @schlunma pls :beer:

**Comment by schlunma** [comment]
Awesome, cheers 🍺 

Let's merge https://github.com/ESMValGroup/ESMValCore/pull/1757 before this one here, so that everything aligns nicely.

**Comment by bouweandela** [comment]
@valeriupredoi You will also need update the changelog of the already released version v2.7 somehow: https://docs.esmvaltool.org/projects/ESMValCore/en/v2.7.0/changelog.html

For future releases, I would recommend making sure everything is included in the release before actually making the release.

**Comment by valeriupredoi** [comment]
No need to, guys, all that is in the release changelog, I took care of that
yesterday

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom

**Comment by valeriupredoi** [comment]
> No need to, guys, all that is in the release changelog, I took care of that yesterday beer

sorry, commented on the wrong PR (was supposed to be to #1757 - was on the bus, Reading buses are not optimal places to work on GitHub :grin: ) - thanks for the reviews, will merge now :beer:

**Pull request merged**
