### PR TITLE
Test Github Actions dashboard badge from meercode.io

### PR DESCRIPTION
**Pull request by valeriupredoi**
It's good to have CI Dashboard badges so we can have a bird's eye view of what our CI/CD is doing - @bouweandela pointed me to a dashboard from Circle, so I thought I'd have a go at a dash from Github Actions - proves out GA don't have a native dashboard so I found meercode.io offers a very decent integration (not only for GA) - can one of you @bouweandela @zklaus @schlunma please test if the badge is leading to the correct dashboard - it does for me, but I am registered with meercode, so not sure if that's working overall. Cheers :beer: 

**UPDATE at point of moving it to Ready for Review**

Folks see plots and stats and all manners of dashboard-y stuff if they click on the Meercode badge, and autheticate with GitHub. Do we need documentation for this? I think we're fine like this -

### CODE REVIEW

**Comment by zklaus** [comment]
Looks good. I got a badge that says "success rate 91%".

**Comment by schlunma** [comment]
> Looks good. I got a badge that says "success rate 91%".

Same here :+1:

**Comment by valeriupredoi** [comment]
> yeah cheers guys, but what do you get when you click on that badge? You should get a Dashboard with a lot of plots and info once you've logged in with yer GitHub credentials

any luck with this, fellas? :beer:

**Comment by bouweandela** [comment]
Clicking the badge does not work that well for me. I first need to authorize the app to use my github account or I see nothing. After authorization, I do see white blobs representing the various test runs, but no plots or anything.

**Comment by schlunma** [comment]
Yes, same here:

image

I think they're having some issues, as the Badge disappeared for me and the link of the badge (https://api.meercode.io/badge/ESMValGroup/ESMValCore?type=ci-success-rate&branch=main&lastDay=14) returns an `"Internal server error"`.

**Comment by valeriupredoi** [comment]
I can see this - complete with sidebar menu where I can select all manners of plots - did you guys activate your membership with Meercode?
meerCrap

**Comment by bouweandela** [comment]
@valeriupredoi That's what it looks like for me too, but note that not even the branch names are filled in: it looks like all actual data is missing from the cards.

**Comment by valeriupredoi** [comment]
OK plots are back for me, and I switched the dark mode on and they look super badass, can you fellas try again as well, please? I'll convert it to a RfR PR then :beers:

**Comment by valeriupredoi** [comment]
nasa-stuff

**Comment by schlunma** [comment]
Yes, I can see the same now :rocket:

**Review by zklaus — APPROVED** [review]
Looks fine. I am a bit weary since it's not super tied to the project but just invites everyone to join meercode and there may be other projects sprinkled in, but why not try it out for a bit. I like the idea of having a dashboard that collates GH Actions and CircleCI in one place.

**Comment by valeriupredoi** [comment]
cheers much @zklaus :beer: 

> I am a bit weary since it's not super tied to the project but just invites everyone to join meercode and there may be other projects sprinkled in

nay worry, I did the initial configuration for the ESMValGroup/ESMValCore being an admin of the project, I don't think anyone can willingly add bits and bobs if they're not admins

Circle is not yet added to the Meercode, do we want to add it? (not sure it's even possible tho)

**Comment by valeriupredoi** [comment]
ah yeah fair enough - got it now. Meh, I guess that's fine for us few that will want to look at these things, pretty sure 85% of our users will not want to see/add all manners of plots anyway :grin:

**Pull request merged**
