### PR TITLE
Pin lower bound for iris to 3.0.2

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

A bunch of bugfixes and improvements have been added in the 3.0.2 release of iris, including a fix to a nasty bounds behavior, see [last comment on the issue](https://github.com/ESMValGroup/ESMValCore/issues/799#issuecomment-872331326) - this is not make or break but it's good to make sure we don't pick up an older (3.0.1 actually) version. I suggest we have this in time for the imminent bugfix release 2.3.1 :grin: 

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful - no, conda build is failing, known issue, fixed in another PR

### CODE REVIEW

**Comment by zklaus** [comment]
I definitely like this! Would like to see it in our own bugfix release. Do you think you could finish this up asap?

**Comment by valeriupredoi** [comment]
the only two things that are still needed for it to be shipshape are merge #1197 that fixes the tests for Python 3.7-9 (and then I can remove the Github Actions test branch) and me tidying up the boxes above, all else should be fine I think

**Comment by zklaus** [comment]
Thanks, V! The merge is done, now you are on box duty ;)

**Comment by valeriupredoi** [comment]
Boss! Let me take care of it now :+1:

**Comment by zklaus** [comment]
Everything except for the conda-build worked, so once the checklist is done, I'll do the final review and we can get this in.

**Comment by valeriupredoi** [comment]
done, man :beer:

**Review by zklaus — APPROVED** [review]

**Comment by valeriupredoi** [comment]
cheers K-man :beers:

**Pull request merged**
