### PR TITLE
Fix tests to import explicitly `iris.fileformats` and remove `esmpy` from `setup.py` since not on PyPi

### LINKED ISSUE #1322: Tests failing on Circle CI and Github Actions
A number of tests fail - Circle is using iris 3.1.0 and is failing the tests that use `iris.fileformats` and GA tests fail with:
```
ERROR: Could not find a version that satisfies the requirement esmpy!=8.1.0 (from esmvalcore[develop]) (from versions: none)
ERROR: No matching distribution found for esmpy!=8.1.0
```

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Iris 3.1.0 needs you to explicitly import any of its submodules and don't use them as iris attributes in the code; also, I had to remove `esmpy` from `setup.py` since pip can't find it anymore - that's a bit of an odd one - has it gone off PyPi?

Closes #1322 

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
The fileformats stuff looks fine, but why do we remove the esmpy dependency?

**Comment by valeriupredoi** [comment]
> but why do we remove the esmpy dependency?

yesh that's an odd one - we still have it in the conda env file so we're installing it alright, but for some reason pip can't find the package at all, and I checked - it's not on PyPi (anymore) - am quite confused by that myself - do you you know if it was on PyPi and they have gotten off it by any chance?

**Comment by valeriupredoi** [comment]
ah wait - I have a clue what's happened to `esmpy` - pip thinks the conda-installed one is 8.1.0:
```
(esmvaltool-stock2) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ conda list esmpy
# packages in environment at /home/valeriu/miniconda3/envs/esmvaltool-stock2:
#
# Name                    Version                   Build  Channel
esmpy                     8.1.1           mpi_mpich_py39h8bb458d_100    conda-forge
(esmvaltool-stock2) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ pip install esmpy
Requirement already satisfied: esmpy in /home/valeriu/miniconda3/envs/esmvaltool-stock2/lib/python3.9/site-packages (8.1.0)
```
so when trying to (not)-install it and with the `!=8.1.0` pin, esmpy not being on PyPi, the pip installation of Core fails. Bugger me flat, why does pip read it as 8.1.0 when in fact it's 8.1.1?

**Comment by zklaus** [comment]
It is indeed not on PyPI, and likely never was. I don't love that, but that should IMHO not stop us from declaring the dependency (c.f. the last paragraph [here](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires)).

> Lastly, it’s important to understand that install_requires is a listing of “Abstract” requirements, i.e just names and version restrictions that don’t determine where the dependencies will be fulfilled from (i.e. from what index or source). The where (i.e. how they are to be made “Concrete”) is to be determined at install time using pip options.

Not sure what went wrong with the esmpy version. I'll look something up.

**Comment by valeriupredoi** [comment]
fairly sure it's coz pip reads it as 8.1.0 from the conda installed package see https://github.com/ESMValGroup/ESMValCore/pull/1323#issuecomment-924102003 - what that is, is beyond my paygrade :grin:

**Comment by zklaus** [comment]
Found it. The setup.py in the archive published by ESMF is wrong.

**Comment by valeriupredoi** [comment]
that was fast! awesome detective work, dude, how to fix it for us then?

**Comment by zklaus** [comment]
I'm fixing it upstream.

**Comment by zklaus** [comment]
For us, that means we should keep the dependency in here. Hopefully, this will be fixed in an hour or two.

**Comment by valeriupredoi** [comment]
Mega! I'll rea-add it once you give me the green lisght it's been fixed upstream :beer:

**Comment by zklaus** [comment]
For reference, the PR is conda-forge/esmpy-feedstock#49.

**Comment by zklaus** [comment]
@valeriupredoi, ok, it should work now.

**Comment by valeriupredoi** [comment]
@zklaus that fix you pushed upstream with esmpy works like a charm! I tested locally and we have it working on [GA actions](https://github.com/ESMValGroup/ESMValCore/runs/3670040472?check_suite_focus=true) - cheers much :beer: I've added it back to `setup.py` now, with the same pin as before, the Tool is hopefully gonna pick up 8.1.1 too so we'll want to remove that pin some time down the line

**Comment by valeriupredoi** [comment]
@bouweandela @zklaus this can be closed with unmerged changes too since the only test that actually fails proper is fixed in #1217 - given what we talked in #1324 this can probably be with the fishes too, you reckon? :fish:

**Comment by zklaus** [comment]
Yeah, agreed. We'll have it in mind if we run into problems in the future.

Oh, as an aside, I think I tracked the julia and general dependency problems with conda to the fact that the ncl feedstock is a bit neglected and didn't get its builds updated with newer versions of dependencies. I am trying to rectify that...

**Comment by valeriupredoi** [comment]
> I am trying to rectify that.

Awesome :beer: :medal_military:

**Pull request closed without merging**
