### PR TITLE
Relax the pin on iris to allow the use of older versions for performance reasons

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

During testing for the v2.9.0 release of ESMValTool, we noticed that the latest versions of iris are considerably less performant with the Dask default scheduler. Therefore it would be good to allow using older versions of iris, even if these do not support the distributed scheduler. Note that a new installation will still default to the latest version of iris, so this is only for users who really want to use the older version.

See discussion in https://github.com/ESMValGroup/ESMValTool/issues/3239#issuecomment-1613298587

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
if you don't relax it in environment.yml as well it will be most of the times forced to 3.6+ and some users won't know how to downgrade it in their envs, bud :+1:

**Comment by bouweandela** [comment]
If they ask in an issue we can explain it. This PR is just to allow those who really want it to use the older version, the default should be to use the latest version.

**Comment by valeriupredoi** [comment]
OKi, sounds like a plan - I'll approve then

**Review by valeriupredoi — APPROVED** [review]
so am guessing for the conda and PyPI packages we'll have the >=3.6 pin then. Cheers, bud!

**Pull request merged**
