### PR TITLE
Write settings.yml parameters in original order

### LINKED ISSUE #2339: Write settings.yml in original order
This is not a bug or a real feature but a minimal change for convenience.

As a user, I usually need to go to the `settings.yml` to make small changes and relaunch a diagnostic.

Currently, this file is written here:
https://github.com/ESMValGroup/ESMValCore/blob/bb7866e6a136f6e011bc6419c4e3ed9eec25721e/esmvalcore/_task.py#L425

which uses the default order by YAML and orders the entries alphabetically, and then also mixes user parameters with ESMValTool parameters (like workdir, plotdir, output_file_type...).

My experience as the user would prefer to write it in the original order. This will help to make changes and compare with the full recipe easily, in particular in the case that the arguments have been intentionally ordered somehow.

This should be easy to do with the argument `sort_keys=False` as it is done to save the full recipe.

Is a minor change, but I could make it if you agree with it. I know that is more of a preference than a bug or feature. However, after discussing with some colleagues, they also think that it would be better to keep the same order from the recipe in the `settings.yml` file.

### PR DESCRIPTION
**Pull request by enekomartinmartinez**
## Description

Small fix to write `settings.yml` without sorting the keys. This preserves the original order of the parameters as they were given in the recipe, keeps the order given by the user. It also will add all the ESMValTool written parameters at the end so the block can be easily identified, see the settings from an example I ran:

```yaml
c_my_argument1: whatever
a_my_argument2: null
z_my_argument3:
  c: 1
  b: 2
  a: 3
b_my_argument3: null
recipe: recipe_test_settings.yml
version: 2.10.0
script: test_settings_1
run_dir: /esarchive/scratch/emarti1/my-esmvaltool/testing/recipe_test_settings_20240227_140542/run/test_settings_diag/test_settings_1
plot_dir: /esarchive/scratch/emarti1/my-esmvaltool/testing/recipe_test_settings_20240227_140542/plots/test_settings_diag/test_settings_1
work_dir: /esarchive/scratch/emarti1/my-esmvaltool/testing/recipe_test_settings_20240227_140542/work/test_settings_diag/test_settings_1
output_file_type: png
log_level: debug
auxiliary_data_dir: /esarchive/scratch/emarti1/my-esmvaltool/auxiliary_data
input_files:
- /esarchive/scratch/emarti1/my-esmvaltool/testing/recipe_test_settings_20240227_140542/preproc/test_settings_diag/psl/metadata.yml
```

Closes #2339 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
Thanks for taking the time to contribute this feature! Could you please have a look at the checklist and do the things on it when you have the time? Then we can merge this.

**Comment by enekomartinmartinez** [comment]
Hi @bouweandela 

Sorry for the delay; I have been on a research visit since April and have not worked on priority topics related to my research.

The test failed because the method I modified was not covered by the original tests. I have added a small test to ensure the data is saved in order in the `settings.yml`. It is a really simple case, but I guess it is enough.

Let me know if you require a more specific example/test.

**Comment by enekomartinmartinez** [comment]
Something failed with the [Codacy Upload](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/11351/workflows/df545373-bc4a-4cc2-817b-4ab6ca39a46f/jobs/47712/parallel-runs/0/steps/0-117)

**Comment by bouweandela** [comment]
> Something failed with the [Codacy Upload](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/11351/workflows/df545373-bc4a-4cc2-817b-4ab6ca39a46f/jobs/47712/parallel-runs/0/steps/0-117)

Yes, it's a known issue with the Codacy Coverage uploader: https://github.com/codacy/codacy-coverage-reporter/issues/500.

**Review by bouweandela — APPROVED** [review]
Thanks, looking fine!

**Pull request merged**
