### PR TITLE
add conda build Github Actions workflow

### PR DESCRIPTION
**Pull request by valeriupredoi**
Tested off the `github-actions2` test branch, it builds the conda package nicely; we need to add an upload to channel option (hence installing `anaconda-client`) but maybe we do that later. test off test branch [here](https://github.com/ESMValGroup/ESMValCore/actions/runs/295505663)

Before you start, please read our [contribution guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html).

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [ ] This pull request has a descriptive title that can be used in a changelog
-   [ ] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

See #814

### CODE REVIEW

**Comment by valeriupredoi** [comment]
asked @fdiblen how to integrate his GA workflow with this one here in https://github.com/fdiblen/anaconda-action/issues/6 :beer:

**Comment by valeriupredoi** [comment]
@bouweandela we can probably close and forget about this one since now the conda building is done part of the [publishing test](https://github.com/ESMValGroup/ESMValCore/actions/runs/302599195) that runs on a push and stops before publishing - or do we want it to be done nightly too?

**Comment by bouweandela** [comment]
It would be nice to have it done nightly (even though we do this on CircleCI too), but then I would just add that to the schedule of the existing publish workflow.

I also noticed that this:
https://github.com/ESMValGroup/ESMValCore/blob/16f8a414314b769516a5231f03fab1955296a520/.github/workflows/action-conda-publish.yml#L55-L85
does the same as this:
https://github.com/ESMValGroup/ESMValCore/blob/16f8a414314b769516a5231f03fab1955296a520/.github/workflows/action-install-from-conda.yml#L35-L70
so it would be nice to merge the two workflows into a single file, called e.g. action-conda.yml, and remove any duplicate entries.

**Comment by valeriupredoi** [comment]
not quite, the `verify` step runs only on release triggers, I don't know how to write a bunch of steps in a function to be called in two or more places without explicitly writing the steps themselves - do you?

**Comment by valeriupredoi** [comment]
> It would be nice to have it done nightly (even though we do this on CircleCI too), but then I would just add that to the schedule of the existing publish workflow.

yeah, good call! :beer:

**Comment by valeriupredoi** [comment]
OK gents @bouweandela and @nielsdrost - I updated the conda hook and this thing runs nightly as well, can we give it a :+1: for merge pls?

**Comment by bouweandela** [comment]
> I don't know how to write a bunch of steps in a function to be called in two or more places without explicitly writing the steps themselves - do you?

You could try using yaml anchors, the files are yaml after all?

**Comment by valeriupredoi** [comment]
I think we don't need this no more now since we have it from Circle and both are using only the latest Python version - what do you think @bouweandela @nielsdrost @jvegasbsc

**Comment by jvegasbsc** [comment]
No need to have it duplicate. Anyway, do not remove the branch just in case we need to move it out from CircleCI

**Comment by bouweandela** [comment]
Probably not needed anymore, this PR is very similar to #825 (the only difference is that this adds a nightly cron job).

**Comment by valeriupredoi** [comment]
sounds like a decent plan, gent, am gonna close the PR but leave the branch hanging about just in case :+1:

**Pull request closed without merging**
