### PR TITLE
Add surface chlorophyll concentration as a derived variable

### LINKED ISSUE #715: Add derivation script for chlora
**Is your feature request related to a problem? Please describe.**
A derivation script should be added to compute variable `chlora` from model variables `chldiatos` and `chlmiscos`, as observational datasets provide `chlora` directly

**Would you be able to help out?**
yes

### PR DESCRIPTION
**Pull request by sloosvel**
Compute chlora as a derived variable from model output chlmiscos and chldiatos

Before you start, please read our [contribution guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html).

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [ ] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #715

### CODE REVIEW

**Comment by sloosvel** [comment]
Sorry for the spam, @ESMValGroup/esmvaltool-coreteam but it would be useful to some of our users to have this in the next release.  I would say this is ready.

**Comment by valeriupredoi** [comment]
@sloosvel in the future, it's probably best if you added more than one reviewer in the Reviewers section before polling the core team - eg me and/or @bouweandela and maybe someone else who might have the expertise, if you hear nada from these initial reviewers then ask the Core team :beer: I'll have a look at this in a jiffy!

**Comment by sloosvel** [comment]
Noted, thanks for the help!

**Review by valeriupredoi — APPROVED** [review]
cheers @sloosvel :beer:

**Pull request merged**
