### PR TITLE
make build and deploy to PyPI Github Action use PyPI's new trusted publishers authentication

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

This is us going forward and keeping up with the newest trends, and a big thank you to @bouweandela suggesting this to me for a different package. This is a simple, token-free, password-free secure method to upload the Python package to PyPI; it's described in https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/ and setup explained in https://docs.pypi.org/trusted-publishers/adding-a-publisher/ - but, in a nutshell, it goes like this:

- once the pkg has been built, the GA workflow uses a PyPA workflow that uploads it to PyPI, *if and only if*...
- an owner of the PyPI project enables Trusted Publishers on the PyPI project page (in settings etc)

This is the changed GA workflow at our end, for this to be enabled (note that the Python setup action has been upgraded to v4, the latest); I've not yet enabled Trusted Publishers at our PyPI project end, will do that only is this PR gets merged.

**TODO**

- enable TP at PyPI end if this is approved/merged
- have a look at the docs (we may have to change the description how we upload the PyPI package)

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
Looks good to me @valeriupredoi! To test that everything works as expected, could you do an upload to test pypi?

**Comment by valeriupredoi** [comment]
cheers @bouweandela! Yis, I'll do us one tomorrow :+1:

**Comment by valeriupredoi** [comment]
snap! Test (and subsequent actual) PyPI is complains about our development version:
```
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
         '2.11.0.dev5+gf1b1ecdc7' is an invalid value for Version. Error: Can't 
         use PEP 440 local versions. See                                        
         https://packaging.python.org/specifications/core-metadata for more     
         information.  
```
 @bouweandela do you know of a workaround without an actual release that'd have the version set correctly? Only thing I can think of it to plop a hardcoded version in setup.py

**Comment by valeriupredoi** [comment]
OK a frozen version in `setup.py` did the [trick and uploaded fine to Test PyPI](https://github.com/ESMValGroup/ESMValCore/actions/runs/7129002425/job/19412085415?pr=2269) :beer:

**Comment by valeriupredoi** [comment]
yay! Cheers, buds! Let me enable the script on PyPI main, then I'll merge, you and @zklaus will have a great time seeing how it uploads to PyPI when releasing next week, like a good movie :grin:

**Comment by valeriupredoi** [comment]
> yay! Cheers, buds! Let me enable the script on PyPI main, then I'll merge, you and @zklaus will have a great time seeing how it uploads to PyPI when releasing next week, like a good movie 😁

Done!

**Pull request merged**
