### PR TITLE
update CITATION.cff file with 2.7.0 release info

### PR DESCRIPTION
**Pull request by valeriupredoi**
The bogstandard update of CITATION.cff for 2.7.0 release, please :beer:

### CODE REVIEW

**Review by schlunma — APPROVED** [review]
🍺

**Comment by bouweandela** [comment]
It would have been nice to include this in the v2.7 release. Too late now I guess..

**Comment by schlunma** [comment]
It is there (as a [commit](https://github.com/ESMValGroup/ESMValCore/commit/8f384bd9a734406e43babdf1a3916d93f0a00cc4) to the release branch), but I agree that a PR to main would have been the better solution.

**Comment by valeriupredoi** [comment]
Yeah that was me in a bit of a hurry, only to be stood up by the regro bot
- while the bot was broken I'd had had time for three such PR's. But heyho
- all's working well, so am not too fussed :))

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom

**Comment by valeriupredoi** [comment]
cheers gents :beer:

**Pull request merged**
