### PR TITLE
Several minor fixes needed for marine BGC data.

### PR DESCRIPTION
**Pull request by ledm**
Here are some fairly straightforward fixes for various CMIP6 models. Several of these models are simply not receiving the "standard" OceanFixGrid fixes that they need. Could we instead just apply that to every model - or is that a bad idea?

PR is a draft as it's a work in progress.

### CODE REVIEW

**Comment by valeriupredoi** [comment]
cheers @ledm - could you pls fix the flake8 issues (line too long etc) :beer:

**Comment by chrisbillowsMO** [comment]
Hi @ledm - following on from the community call earlier, would you have time to complete this PR by the end of next week? If not would you be happy to move it to the next milestone [v2.12.0](https://github.com/ESMValGroup/ESMValCore/milestone/18) please?

**Comment by valeriupredoi** [comment]
OK flake8 issues fixed, so we have green tests now, please proceed with work, and let me know when you'd want a review, or please change the milestone to M2.12 and see about it afterwards - up to you @ledm :beer:

**Review by valeriupredoi — APPROVED** [review]
many thanks @ledm LGTM :beer: @schlunma would you be able to give this one a lookover when you got a minute, plss bud? We can then merge and make the 2.11 cut :scissors:

**Review by schlunma — CHANGES_REQUESTED** [review]
Would be great if you can add some (minimal) tests for this, e.g., https://github.com/ESMValGroup/ESMValCore/blob/99129212012a68ec44aef5083545a780cb1c30b9/tests/integration/cmor/_fixes/cmip6/test_bcc_esm1.py#L61-L69

**Comment by valeriupredoi** [comment]
good call, Manu! I shall, imminently :beer:

**Comment by valeriupredoi** [comment]
plopped tests in https://github.com/ESMValGroup/ESMValCore/pull/2110/commits/b7b3fc87b9ab61995d55348e08a5b8bd5598e84b and https://github.com/ESMValGroup/ESMValCore/pull/2110/commits/b9b286df8e0fc457ebea95327348f31812d2c33b bud :beer:

**Review by schlunma — APPROVED** [review]
Thanks @ledm @valeriupredoi 🚀

**Comment by valeriupredoi** [comment]
and danke Manu :beer:

**Pull request merged**
