### PR TITLE
Fixing unit for derived variable rsnstcsnorm to prevent overcorrection2

### PR DESCRIPTION
**Pull request by katjaweigel**
Fixing unit for derived variable rsnstcsnorm to prevent over correction caused by changes of #754. This time based on master. Sorry, the other branch (fix_derived_var_rsnstcsnorm) should be deleted.

Before you start, please read our [contribution guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html).

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Contributes to close ESMValTool issue ESMValGroup/ESMValTool#1875 for recipe recipe_deangelis15nat.yml

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
cheers @katjaweigel ! I added a unit test for good measure, @schlunma is on holidays, so @axel-lauer you wanna have a look, mate? Cheers

**Comment by axel-lauer** [comment]
Sure, I'll take a look.

**Comment by bouweandela** [comment]
> I added a unit test for good measure

Awesome! That way it won't get broken again in the future!

**Review by axel-lauer — APPROVED** [review]
I have tested this and it works nicely. This is ready for merging.

**Comment by valeriupredoi** [comment]
cheers for revieweing @axel-lauer and @bouweandela :+1: :beer:

**Comment by bouweandela** [comment]
Is this something we would want to make a bugfix release for? i.e. a version 2.1.1 of ESMValCore?

**Comment by valeriupredoi** [comment]
shall we wait until iris3 becomes mainstream?

**Comment by katjaweigel** [comment]
Not sure if it is important enough, maybe if there are also other issues?

**Comment by zklaus** [comment]
In principle, I think it is worth a bugfix release. Maybe collect the bugfix PRs somehow (~milestone? project?~ in the bugfix release branch) and cut the release when one of three conditions is met: A serious bug is fixed, some time has passed (this PR has been in for almost a month now), or the next release has come around?

@valeriupredoi I would (almost) never update an important dependency like Iris in a bugfix release, so I don't think that is a factor here.

**Pull request merged**
