### PR TITLE
Development dump preprocessor profile to metadata file

### PR DESCRIPTION
**Pull request by valeriupredoi**
This solves an issue raised by a bunch of yous @axel-lauer @ledm etc (can't remember the issue number). Now you get the preprocessor settings in the `metadata.yml` file a la:
```
preprocessing_profile:
  multi_model_statistics:
    span: overlap
    statistics:
    - mean
  regrid:
    target_grid: 1x1
    scheme: linear
```

### CODE REVIEW

**Comment by valeriupredoi** [comment]
ah found the issue, started by the ubiquitous @mattiarighi actually :grin: https://github.com/ESMValGroup/ESMValCore/issues/70

**Comment by valeriupredoi** [comment]
@mattiarighi @bouweandela this poor fella has been sitting here for ages, can we open the gates of `development` for him? :grin:

**Comment by valeriupredoi** [comment]
@bouweandela let's get this one in with no fuss bro :beer:

**Comment by valeriupredoi** [comment]
tit for tat: @schlunma you reckon you can give me an OK for this one pls? :beer:

**Comment by bouweandela** [comment]
Maybe you can link the corresponding issue? This is a feature I'm not too keen on (see discussion in the issue) and interest seems to be lacking too from the people who originally requested it.

Regarding review: from looking at the code I expect this pull request might break running NCL diagnostics for some of the preprocessor settings. This pull request also lacks documentation and unit tests.

**Comment by valeriupredoi** [comment]
aye, can remove if agreed, am not too fussed about it, much bigger fish to catch (ie more urgent PR's to be addressed) :beer:

**Comment by mattiarighi** [comment]
@valeriupredoi it looks like this is not needed anymore.
Can we close it without merging?

**Comment by valeriupredoi** [comment]
yeah gonzo now :grin:

**Pull request closed without merging**
