### PR TITLE
adding the ability to derive xch4 

### LINKED ISSUE #782: new xch4 derivation script
Some observational datasets are providing the variable xch4 (column-averaged dry air mole fractions of CH4).
This variable is not provided in the CMIP model simulations, so it needs to be derived to be able to compare CMIP simulations with the observations.

I started working on a derivation script in the branch "xch4_derivation_branch".

### PR DESCRIPTION
**Pull request by hb326**
-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes (not necessary)
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #782

Dependent on #880

### CODE REVIEW

**Review by axel-lauer — APPROVED** [review]
I tested the xch4 calculation script and it does what it is supposed to do. There is 1 codacy issue left, which I could not fix: codacy complains about a missing blank line after line 104 in esmvalcore/preprocessor/_derive/xch4.py even though there is one. The typical DOS/Unix problem LF vs CRLF does not seem to be the reason here. @bouweandela @schlunma do you have an idea?

Two general comments:
* This derivation script for xch4 is almost idential to the one for xco2 developed in other branches. Once there is a pull request for the xco2 derivation script, those two scripts should be slightly modified to allow for sharing as much code as possible in oder to avoid a lot of code duplication.
* Variable derivation fails if not all input variables are on the same grid (e.g. the CMIP6 model MRI-ESM2). We could therefore think about providing a meaningful error message or maybe even a regridding option for such cases.

**Comment by bouweandela** [comment]
>  There is 1 codacy issue left, which I could not fix: codacy complains about a missing blank line after line 104 in esmvalcore/preprocessor/_derive/xch4.py even though there is one. The typical DOS/Unix problem LF vs CRLF does not seem to be the reason here. @bouweandela @schlunma do you have an idea?

Running prospector locally gives more useful information:
```
$ prospector esmvalcore/preprocessor/_derive/xch4.py
```
gives:
```
Messages
========

esmvalcore/preprocessor/_derive/xch4.py
  Line: 104
    pep257: D410 / Missing blank line after section ('Parameters')
    pep257: D411 / Missing blank line before section ('Parameters')
    pep257: D417 / Missing argument descriptions in the docstring (argument(s) ch4_cube, ps_cube, top_limit are missing descriptions in '_pressure_level_widths' docstring)
    pep257: D411 / Missing blank line before section ('Returns')
```

But note that numpy style docstrings [are not required](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#what-should-be-documented) for code that is not part of the [public API](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html) (i.e. can be seen on docs.esmvaltool.org), so it would also be fine to not describe all parameters in detail.

Maybe you were already planning to do this, but I noticed that it looks like a lot of the code has been copy/pasted from the file `esmvalcore/preprocessor/_derive/toz.py`. It would be better to just import the function you need from there, i.e. `from .toz import _pressure_level_widths`.

**Comment by axel-lauer** [comment]
All "helper functions" are now imported from toz.py. This also solved the codacy issues. @bouweandela thanks for pointing this out! The tests failing now do not seem to be related to this PR but rather to tests/integration/cmor/_fixes/cmip6/test_cesm2.py and tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py. Not sure where this is coming from.

**Comment by bouweandela** [comment]
Thats probably #644, usually just re-running the tests by clicking the 'Re-run from failed' button on CircleCI works. I haven't had time to figure out why that is happening and I'm hoping that the problem will just go away by itself again. So far no users have reported encountering this issue while using the tool in real life, until that happens I don't really want to invest a lot of time in it.

**Comment by bettina-gier** [comment]
Any news on this? I'd like to do a pull request for xco2 soon, which should build on xch4, as it's almost the same computation.

**Comment by hb326** [comment]
> 
> 
> Any news on this? I'd like to do a pull request for xco2 soon, which should build on xch4, as it's almost the same computation.

@schlunma wanted to take a look at this. Not sure how far he got with it during the workshop. I think he changed some things in the calculation of the column and wanted that to be tested to go ahead with this pull request.

**Comment by schlunma** [comment]
Yes, the calculation of the pressure level width for `toz` needs to be tested, see [here](https://github.com/ESMValGroup/ESMValCore/pull/880#issuecomment-733671826) :grimacing:

**Comment by schlunma** [comment]
I added unit tests and cleaned the code so similar variables (e.g. `xco2`) can be derived easier. This is ready for review now.

@hb326 can you test it with real CMIP5 **and** CMIP6 data please? I noticed that `hus` has different units in CMIP5 (`1`) and CMIP6 (`%`) and adapted the code to account for this.

**Comment by axel-lauer** [comment]
@schlunma @hb326 Theoretically, `hus` should have units `1` in both cases, at least according to the CMOR tables. Maybe the tested model needs a fix?

**Comment by schlunma** [comment]
> @schlunma @hb326 Theoretically, `hus` should have units `1` in both cases, at least according to the CMOR tables. Maybe the tested model needs a fix?

Okay, then just ignore my previous comment, I must have read the entry for `hur` or something :smile: I will update this PR accordingly!

**Comment by hb326** [comment]
So no testing needed anymore?

**Comment by schlunma** [comment]
No, testing still necessary, I only used fake data and I have no idea how the real data should look like :smile:. It would be nice if you can still test CMIP5 and CMIP6 data, since the units of `ch4` differ and the units of `xch4` should be `1` in both cases. Thanks :blush: !

**Comment by hb326** [comment]
> 
> 
> No, testing still necessary, I only used fake data and I have no idea how the real data should look like 😄. It would be nice if you can still test CMIP5 and CMIP6 data, since the units of `ch4` differ and the units of `xch4` should be `1` in both cases. Thanks 😊 !

Ok, I'm testing.

**Comment by hb326** [comment]
I ran a recipe where observed xch4 values are compared to CMIP6 (CMIP5) simulations. The recipe worked for both, CMIP5 and CMIP6, and the data derived from the simulations look similar to the observations. So I think the derivation of xch4 works fine.
lineplot_xch4_2003-2005_CMIP5
lineplot_xch4_2003-2014_CMIP6

**Review by schlunma — APPROVED** [review]

**Pull request merged**
