### PR TITLE
Accept cubes as input in multimodel

### LINKED ISSUE #630: Make some functions in multimodel public
The multimodel_statistics function can't be called inside diagnostic scripts because it does not accept cubes, but rather products.

However functions _get_overlap, _assemble_overlap_data and _assemble_full_data do accept cubes and they are what computes the statistics anyway. Could they be made public and add in the documentation how to call them? Maybe it would be better to generalise the multimodel_statistics preproc to accept both products and cubes, but it would probably be more time consuming to implement.

### PR DESCRIPTION
**Pull request by sloosvel**
Generalise the multimodel preprocessor to accept both products and cubes as input. If using cubes as input, the current output is a dict with keys being the statistics, and items being the output cubes.

Pending to add tests.

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [ ] This pull request has a descriptive title that can be used in a changelog
-   [ ] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [ ] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #630

### CODE REVIEW

**Comment by valeriupredoi** [comment]
nice one! we should add documentation too so the users now know that they can plop the function in their diagnostics :beer:

**Comment by sloosvel** [comment]
I'm not sure how to fix the codacy error though

**Comment by valeriupredoi** [comment]
> I'm not sure how to fix the codacy error though

don't worry about it, it's fine :+1:

**Comment by mattiarighi** [comment]
@sloosvel can you have a look at the conflicts?

**Comment by sloosvel** [comment]
yes, done

**Pull request merged**
