### PR TITLE
Removed deprecated configuration option `offline`

### PR DESCRIPTION
**Pull request by schlunma**
## Description

This PR removes the deprecated configuration option `offline`.

Detailed upgrade instructions: https://github.com/ESMValGroup/ESMValCore/pull/1935

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] ~~Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)~~
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by bouweandela — CHANGES_REQUESTED** [review]
There is a bit of code left in `esmvalcore/_main.py` that is also part of this feature, could you have a look?
https://github.com/ESMValGroup/ESMValCore/blob/remove_offline/esmvalcore/_main.py#L368-L376

**Comment by schlunma** [comment]
Whoopsi, looks like I messed up the `git add` somehow. Should be fine now.

**Review by bouweandela — APPROVED** [review]

**Comment by bouweandela** [comment]
It looks like the feature is also used in the backward compatibility tests: https://github.com/ESMValGroup/ESMValTool/blob/main/.circleci/config.yml#L217

**Comment by schlunma** [comment]
Good catch, see https://github.com/ESMValGroup/ESMValTool/pull/3367.

**Review by valeriupredoi — APPROVED** [review]
gut work! Also approved Manu's Tool PR that removes it from there

**Pull request merged**
