### PR TITLE
Automatically fix small deviations in vertical levels

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

This pull request aims to make working with vertical levels that have tiny errors in the coordinate values easier. It does this by:

1) trying to automatically fix the problem
2) setting the levels equal to those requested in `extract_levels` when cube slicing is used instead of interpolation

This will make it easier to compute multi-model statististics, which now need exactly matching coordinates.

See https://github.com/ESMValGroup/ESMValCore/issues/956#issuecomment-768419704

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
this is cool! maybe we should make the tolerances a user tunable parameter? I can see uses for in a configuration file

**Comment by bouweandela** [comment]
I'm not sure. Do you think the values that I've chosen now make sense?

**Comment by zklaus** [comment]
I think in this case it's better if we control the tolerances. Note also that it might be tempting to do a similar thing for horizontal coordinates, where e.g. in CORDEX very small deviations can occur. The difference is that there is no "right" value in CORDEX, this is decided by the model, whereas here we have an authoritative value from the CMIP tables. This is also what allows us to decide on tolerances, imho.

**Comment by bouweandela** [comment]
> Note also that it might be tempting to do a similar thing for horizontal coordinates, where e.g. in CORDEX very small deviations can occur.

Indeed, this was implemented in #507 with the default tolerances. The default relative tolerance might be a bit lax (rtol 1e-5, atol 1e-8).

**Comment by bouweandela** [comment]
> I think in this case it's better if we control the tolerances.

I could add that for `extract_levels`. What would you propose as the default? The current values?

**Comment by zklaus** [comment]
I think the current values look fine to me, but let's have another look for the next release.

**Comment by bouweandela** [comment]
The remaining Codacy issue is about too many arguments for the `extract_levels` preprocessor function, so unfortunately it cannot be solved.

**Comment by bouweandela** [comment]
@zklaus I added the option to tweak the parameters as requested. Could you have another look, please?

**Comment by bouweandela** [comment]
Thank you for reviewing @valeriupredoi! @zklaus Do you have any further comments on this?

**Review by zklaus — APPROVED** [review]

**Pull request merged**
