### PR TITLE
regridding regular grids with similar coordinates 

### LINKED ISSUE #1551: Regridding very similar grids may result in lat/lon coordinates that are not exactly identical
Issue reported by @tomaslovato in https://github.com/ESMValGroup/ESMValCore/issues/485#issuecomment-1069230273: 

The grid coordinates comparison done in `_horizontal_grid_is_close` uses the function `np.allclose` which has default tolerance values set to `rtol=1e-05, atol=1e-08` that may not be always enough.
In particular, when lat/lon coordinates are not the same for all regridded datasets any following manipulation made between cubes will produce an `iris` error from the cube coordinates equality check.

I found this issue while working with CMIP6 ocean data on regular grid from `GFDL-CM4`and `GFDL-ESM4` datasets.

Here below a sample of the `latitude` field from `dissic_Omon_GFDL-CM4_historical_r1i1p1f1_gr_201001-201412.nc`
```
 lat = -89.5, -88.5, -87.5, -86.5, -85.5, -84.5, -83.5, -82.5, -81.5, -80.5,
    -79.5, -78.5, -77.5, -76.5, -75.5, -74.5, -73.5, -72.5, -71.5, -70.5,
    -69.5, -68.5, -67.5, -66.5, -65.5, -64.5, -63.500000000000007105,
    -62.500000000000007105, -61.500000000000007105, -60.5, -59.5, -58.5,
    ...
    63.500000000000007105, 64.5, 65.5, 66.5, 67.5, 68.5, 69.5, 70.5, 71.5,
    72.5, 73.5, 74.5, 75.5, 76.5, 77.5, 78.5, 79.5, 80.5, 81.5, 82.5, 83.5,
    84.5, 85.5, 86.5, 87.5, 88.5, 89.5 ;
```
I see a couple of possible fixes:
- force the lat/lon coordinates of the cube to be the same as the target_grid  at the end of the `_regrid` function
- in [_horizontal_grid_is_close](https://github.com/ESMValGroup/ESMValCore/blob/4dbac0492443cd209ed18ec7fbbebb6daa98304e/esmvalcore/preprocessor/_regrid.py#L646) replace the `np.allclose` with a more stringent iris equality check (as proposed by @valeriupredoi in the above discussion) and modify in here the lat/lon coordinates of the cube.

_Originally posted by @tomaslovato in https://github.com/ESMValGroup/ESMValCore/issues/485#issuecomment-1069230273_

### PR DESCRIPTION
**Pull request by tomaslovato**
## Description

Regridding regular grid needs to produce an exact matching of the source lat/lon coordinates with those of the target cube.

Closes #1551

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

### CODE REVIEW

**Comment by zklaus** [comment]
Thanks, @tomaslovato. Perhaps we should add a test for this functionality?

**Comment by tomaslovato** [comment]
@zklaus maybe something like this could do the job ...

```python 
diff --git a/tests/integration/preprocessor/_regrid/test_regrid.py b/tests/integration/preprocessor/_regrid/test_regrid.py
index 7a6b87e1a..a156bfb6f 100644
--- a/tests/integration/preprocessor/_regrid/test_regrid.py
+++ b/tests/integration/preprocessor/_regrid/test_regrid.py
@@ -92,6 +92,24 @@ class Test(tests.Test):
         expected = np.array([[[1.5]], [[5.5]], [[9.5]]])
         self.assert_array_equal(result.data, expected)

+    def test_regrid__regular_coordinates(self):
+        data = np.ones((1, 1))
+        lons = iris.coords.DimCoord([1.50000000000001],
+                                    standard_name='longitude',
+                                    bounds=[[1, 2]],
+                                    units='degrees_east',
+                                    coord_system=self.cs)
+        lats = iris.coords.DimCoord([1.50000000000001],
+                                    standard_name='latitude',
+                                    bounds=[[1, 2]],
+                                    units='degrees_north',
+                                    coord_system=self.cs)
+        coords_spec = [(lats, 0), (lons, 1)]
+        regular_grid = iris.cube.Cube(data, dim_coords_and_dims=coords_spec)
+        result = regrid(regular_grid, self.grid_for_linear, 'linear')
+        expected = np.array([[[1.5]], [[1.5]], [[1.]]])
+        self.assert_array_equal(result.data, expected)
+
     def test_regrid__linear_do_not_preserve_dtype(self):
         self.cube.data = self.cube.data.astype(int)
         result = regrid(self.cube, self.grid_for_linear, 'linear')
```

**Comment by tomaslovato** [comment]
@zklaus I added the test for the regular grid coordinate ... let me know if it works for you!

**Review by sloosvel — COMMENTED** [review]
I would say the changes are fine, but it would be good people from @ESMValGroup/esmvaltool-coreteam who have followed the issue closer double checked.

**Review by zklaus — APPROVED** [review]

**Pull request merged**
