### PR TITLE
[EMAC] Adjust commandline interface for quicklooks

### PR DESCRIPTION
**Pull request by bjoernbroetz**
This PR addresses the issue #145 by 
- adjusting the commandline interface of the esmvaltool command for running in quicklook-mode 
- adjusting the files formerly known as templates
- adjusting the `create_recipe` function to create a single quicklook recipe

The command works now as follows:
```
esmvaltool -c <CONFIG-USER.yml> --quicklook <SIMULATION-ID> --startyear 1990 --endyear 1992
```

### CODE REVIEW

**Comment by bjoernbroetz** [comment]
If there are corrupted netcdf files lurking in the persistent quicklook folder the tool crashes by running into [this](https://github.com/SciTools/iris/issues/3312) iris bug that will be fixed soon.

> Do we really need the command line option --quicklook? I thought the quicklook mode is turned on/off in  the user-config.yml: active: true/false. What if there is a conflict between the config file and the command line options?

As discussed with @axel-lauer off-line the name of this option should be changed but maybe in a different PR. We need the info whether we run in *quicklook mode* or not *before* we read the config-file. A possible conflict is caught.

**Comment by valeriupredoi** [comment]
infrastructure question: how come this PR doesn't need at least 1 approver for merging? @bjoernbroetz you ninja whizz :grin:

**Comment by valeriupredoi** [comment]
an nvmnd, it's not in `version2_development` :man_facepalming:

**Comment by mattiarighi** [comment]
Good idea.

**Comment by bjoernbroetz** [comment]
Full test at DKRZ for historical run from 1850-1970 in steps of 2 years currently on the way. Lets wait with this PR this it passes.

**Comment by schlunma** [comment]
I added an additional logger which just logs anomalies of the quicklook feature (especially errors in the concatenation). This log file can be specified in `config-user.yml`. New messages are appended to the end of it, that means the log file includes information from all running quicklook processes.

Unfortunately, testing this still failed because of the large numbers of threads. Using just one single diagnostic at the end of all variables works fine, so we should do that (right now, the quicklook features builds a recipe with 4 diagnostic blocks). However, I think this solution is also close to the thread limit (e.g. changing ancestors caused it to fail), so we should try to change this approach somehow to make it more stable.

**Comment by bjoernbroetz** [comment]
> Unfortunately, testing this still failed because of the large numbers of threads. Using just one single diagnostic at the end of all variables works fine, so we should do that (right now, the quicklook features builds a recipe with 4 diagnostic blocks). However, I think this solution is also close to the thread limit (e.g. changing ancestors caused it to fail), so we should try to change this approach somehow to make it more stable.

@schlunma : The test I ran on Friday (1850-1970 in steps of 2 years) with this branch worked fine for the first cycle but failed with:
```
KeyError: 'Provenance record for /work/XXX/XXX/esmvaltool_output/persistent/work/glob_timeseries_TN_GHG_CO2/glob_timeseries/AIRC_NO_s_historical_global_timeseries.nc already exists.'
```

I'm fixing this now but the thread problem was solved for me after rearranging the diagnostic-blocks. Do you run your tests interactive of do you submit it. I submit it to SLURM, maybe this is a difference as we saw on Friday there is a limit per node.

**Comment by bjoernbroetz** [comment]
Test is running fine with adjustment to the ESMValTool in https://github.com/ESMValGroup/ESMValTool/pull/1218
20 min WCT -> 15 years

**Comment by schlunma** [comment]
> > Unfortunately, testing this still failed because of the large numbers of threads. Using just one single diagnostic at the end of all variables works fine, so we should do that (right now, the quicklook features builds a recipe with 4 diagnostic blocks). However, I think this solution is also close to the thread limit (e.g. changing ancestors caused it to fail), so we should try to change this approach somehow to make it more stable.
> 
> @schlunma : The test I ran on Friday (1850-1970 in steps of 2 years) with this branch worked fine for the first cycle but failed with:
> 
> ```
> KeyError: 'Provenance record for /work/XXX/XXX/esmvaltool_output/persistent/work/glob_timeseries_TN_GHG_CO2/glob_timeseries/AIRC_NO_s_historical_global_timeseries.nc already exists.'
> ```
> 
> I'm fixing this now but the thread problem was solved for me after rearranging the diagnostic-blocks. Do you run your tests interactive of do you submit it. I submit it to SLURM, maybe this is a difference as we saw on Friday there is a limit per node.

The `KeyError` should not appear anymore with the changes I made to the core today, can you remove your changes to the provenance logger and try again? This error should not be ignored, as it occurs when similar data (identical `short_name` and `dataset`) is read by the diagnostic. This means that also only one plot (instead of multiple ones) is created.

I requested a node for interactive work for my test, but I will try again with a regular submitted job.

**Comment by bjoernbroetz** [comment]
> The `KeyError` should not appear anymore with the changes I made to the core today, can you remove your changes to the provenance logger and try again?

I reverted the changes and will check. Thanks for the logger feature! Particularly useful.

**Pull request merged**
