### PR TITLE
Add -i option in rerun message to ignore existing  output directories

### LINKED ISSUE #136: re-run diagnostic script stuck
After the successful execution of a recipe,  re-running the diagnostic script stop with the following message:

```
Script will abort to prevent accidentally overwriting your data in these directories
Use -f or --force to force emptying the output directories or use -i or --ignore-existing to ignore existing output directories.
Script will abort to prevent accidentally overwriting your data in these directories
```

This can be easily solved by adding  the suggested options `-f` or `-i`, but I fell like that the re-run message produced by code at the end of diagnostic function should more clear, e.g. by including at least `-i`.

In particular, `-i` can be added in `rerun_msg` variable within the following piece of code:
https://github.com/ESMValGroup/ESMValCore/blob/82178a9c593ce063baa10e8e883c9ba58491cb61/esmvalcore/_task.py#L409-L414
It could be also an idea to add in the log informations the need to specify `-f` or `-i` options.

### PR DESCRIPTION
**Pull request by tomaslovato**
In relation to the error described in issue #136 
I report here a small change to improve the usability of the tool when re-running diagnostics.

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

* * *

Closes #136

### CODE REVIEW

**Comment by valeriupredoi** [comment]
related to https://github.com/ESMValGroup/ESMValTool/issues/1271

The implementation from `ESMValTool/esmvaltool/diag_scripts/shared/_base.py` is up to the user's choice so I'd a line pointing the user to the documentation and tell them it's up to them to use it (there are repercussions!) :beer:

**Comment by tomaslovato** [comment]
@valeriupredoi So far the only repercussion I see is the overwriting of previous results, but it is a clear consequence of the fact that a user wants to re-run the diagnostic. This should simply make more easy to copy and paste the commands to re-run the code ... am I missing something else?

**Comment by valeriupredoi** [comment]
@tomaslovato yep that's it!

**Comment by valeriupredoi** [comment]
closed via https://github.com/ESMValGroup/ESMValTool/pull/1317

**Pull request closed without merging**
