### PR TITLE
Update sample data multimodel test module removing Runtime error and unused reference files 

### LINKED ISSUE #1203: Test multimodel for sample data fails with Runtime error
see [test](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/5161/workflows/4a7017f9-56a6-4e11-bb83-9c5b16491112/jobs/24577) - the problem is that re-adding the files is barred by `.gitignore` since that ignores any `.nc` files, one can always force that but I reckon this is not quite an elegant implement

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Run only the tests that are active and have only the reference data files that are needed for those, no extras; add to repo new files as tests are re-activated; do not fail with Runtime error just re-create and re-write files silently if they're not there

Closes #1203 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by stefsmeets — COMMENTED** [review]
This is a bad idea for the reasons I stated in here: https://github.com/ESMValGroup/ESMValCore/issues/1203#issuecomment-871451559

These tests will _always_ pass if the reference data are not available (because then reference data == test data), which defeats their purpose. The purpose of the reference is to lock in the desired output. If reference data are not available, this must result in a fail. Especially on the CI, where reference data are not available if they are not in git. The `RuntimeError` there to protect against this happening.

**Comment by valeriupredoi** [comment]
yeah I agree with that - that's why I propose we freeze the reference data and bolt to a release. An error in the CI because the data is not there will not make things smoother, it'll just make a maintainer scratch their head and simply rerun the test (if they are not aware of the situation), I propose we setup a git-controlled repo where data lives and that needs to be refreshed only when a release happens

**Comment by stefsmeets** [comment]
If you agree, then this PR can be closed 😅

**Comment by valeriupredoi** [comment]
no hold your horses for a bit :horse: I am thinking a bit, I might end up closing it tho :grin:

**Comment by valeriupredoi** [comment]
OK closing this since I am thinking about something (getting the reference data more strictly tied to a release or tag) but this is not doing it and I don't have time to elaborate on that in code right now, sorry for pestering you guys @stefsmeets @Peter9192 :beer:

**Pull request closed without merging**
