### PR TITLE
Remove deprecated configuration options

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Remove various deprecated configuration modules and methods:
- `esmvalcore.experimental.config` -> to upgrade, import the module from `esmvalcore.config`
- `esmvalcore._config` -> to upgrade, use `esmvalcore.config` instead
- `esmvalcore.config.Session.to_config_user` and `esmvalcore.config.from_config_user` -> to upgrade, use `esmvalcore.config.Session` to access the configuration values instead of a separate `dict`

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility) -> no
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
thanks bud, these slated to be removed in 2.9 right?

**Comment by valeriupredoi** [comment]
@schlunma maybe you got a couple seconds have a last look at this then merge, pls. bud :beer:

**Comment by schlunma** [comment]
Thanks @bouweandela for taking care of this!

It seems that one of these functions is still used in ESMValTool: https://github.com/ESMValGroup/ESMValTool/blob/main/tests/system/data_simulator.py#L10

Could you either open an issue or PR to address this, please? Thanks!!

**Comment by valeriupredoi** [comment]
done! Am on a roll today :grin: https://github.com/ESMValGroup/ESMValTool/issues/3195

**Comment by bouweandela** [comment]
> Could you either open an issue or PR to address this, please? Thanks!!

See https://github.com/ESMValGroup/ESMValTool/issues/3109

**Comment by valeriupredoi** [comment]
Bouwe needs to read comments more often and I need to check for existing issues :rofl:

**Pull request merged**
