### PR TITLE
Add `output2` to the `product` extra facet of CMIP5 data

### PR DESCRIPTION
**Pull request by remi-kazeroni**
## Description

As discussed in https://github.com/ESMValGroup/ESMValTool/issues/2408 we could reduce the "missing CMIP5 data" issue in recipe testing by allowing the tool to not only consider `product: output1` but also `product: output2`. There are cases where data is found on ESGF nodes but not downloaded because the tool is currently configured to only work with `product: output1` data. With this choice, recipe developers would not have to check the `product` value of the CMIP5 data used.

Related to https://github.com/ESMValGroup/ESMValTool/issues/2408

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
~~- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~~
~~- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date~~
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
Looks good; of course, the tests need fixing. Thanks, @remi-kazeroni !

**Comment by remi-kazeroni** [comment]
> cheers @remi-kazeroni - I can fix the tests and add another test case to cover the new facet if you want me to 👍

I think the existing tests, everything passes now. I'm not sure we need an extra test related to output2 but feel free to add a test case @valeriupredoi if you think that is needed 👍

**Review by zklaus — APPROVED** [review]
Thanks, @remi-kazeroni. I also don't think we need an extra test. @valeriupredoi, feel free to merge when you are happy.

**Comment by valeriupredoi** [comment]
the tests we have now are syntactic and don't test the actual functionality of the `output2` facet, I think we need a functional test that actually does the search and download off `output2` in `tests/integration/esgf/test_search_download.py` but given that the functionality of `output2` is exactly identical to `output1` which is tested thoroughly I'm inclined to let this through w/o a test :+1: Cheers guys, merging now!

**Pull request merged**
