### PR TITLE
Use nearest scheme to avoid interpolation errors with masked data in regression test

### PR DESCRIPTION
**Pull request by stefsmeets**
## Description

This PR changes the regridder from `Linear` to a `Nearest` scheme to avoid interpolation errors on masked arrays. It also updates the regression data. This fixes an issue with the regression test that makes it difficult to compare between branches.

For more info on why this happens, see also #593

- Closes: #1014 

***

## Before you get started

-   [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [x] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Labels are assigned so they can be used in the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [x] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [x] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [x] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   [x] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Comment by stefsmeets** [comment]
Hi @valeriupredoi , could you have a look at this one? 🚀

**Review by valeriupredoi — APPROVED** [review]
looks good, man :+1:

**Comment by valeriupredoi** [comment]
@stefsmeets could you please fix the failing multimodel test mate https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/4339/workflows/a42839e2-f294-4223-834b-0afec25fda4f/jobs/20245
Always remember to run the tests locally too, since our test CI is a bit en retard and builds only off master

**Comment by valeriupredoi** [comment]
friendly ping @stefsmeets :+1:

**Comment by valeriupredoi** [comment]
> friendly ping @stefsmeets +1

nevermind, that's happening coz the actual sample data has now changed, the Github Actions pass well, @bouweandela when is the sample data changed in the test container?

**Comment by stefsmeets** [comment]
Yeah, I noticed one test oddly failed in your PR. I just re-ran it before I did the review to see what happened. Not entirely sure why it magically got fixed, will keep an eye on it 👍

**Pull request merged**
