### PR TITLE
Tweak `extract_point` preprocessor: explain what it returns if one point coord outside cube and add explicit test 

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

I panicked a little bit while reviewing one of @sloosvel 's PRs dealing with yet another extraction scenario since I thought the extraction process can do extrapolation on top of the known interpolation and we'd end up extracting a point in Italy when the cube only contains Nigeria, in which case data would be absolutely bonkers. It proves out that in that case the code don't fail, but returns fully masked data of the extracted point cube - good - but this is mentioned nowhere! So here it is, mentioned here, and added a test for good measure - even though there was a test for outside points extraction, this one checks specifically for the mask to be full.

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
Yeah, the extrapolation options are hidden here:

https://github.com/ESMValGroup/ESMValCore/blob/b087bf37e727fbcb5a5d71bb93f014fa066c22f6/esmvalcore/preprocessor/_regrid.py#L56-L59

It might make sense at some point to allow custom kwargs for these, just like we did for `regrid` in https://github.com/ESMValGroup/ESMValCore/pull/1448. Sometimes it makes indeed sense to allow extrapolation. But this can be done in another PR, maybe open an issue?

**Comment by valeriupredoi** [comment]
I'd steer clear from that, Manu, or add a big Hazard sign - extrapolation can easily be misused by the user and their results could be absolutely mental, but valid numbers, and even not 1e20's - actual regular Joe data. At any rate, we can talk about that more in an issue, what you think of this PR for now?

**Comment by schlunma** [comment]
> I'd steer clear from that, Manu, or add a big Hazard sign - extrapolation can easily be misused by the user and their results could be absolutely mental, but valid numbers, and even not 1e20's - actual regular Joe data. At any rate, we can talk about that more in an issue, what you think of this PR for now?

This definitely shouldn't be the default option, but might actually be useful for experienced users. But yes, let's discuss this in another issue :+1:

**Review by schlunma — APPROVED** [review]

**Comment by valeriupredoi** [comment]
cheers, Manu! :beer:

**Pull request merged**
