### PR TITLE
Documentation updated for the new cmorizer framework

### PR DESCRIPTION
**Pull request by remi-kazeroni**
## Description
This PR simply aims at aligning the documentation with the new cmorizer framework from [#1657](https://github.com/ESMValGroup/ESMValTool/pull/1657). Since observation downloading and reformatting is handled by the tool, this is just a cosmetic change. To be merged only after [#1657](https://github.com/ESMValGroup/ESMValTool/pull/1657).

Related to https://github.com/ESMValGroup/ESMValTool/pull/1657

Link to documentation: https://docs.esmvaltool.org/projects/esmvalcore/en/latest/quickstart/find_data.html

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
@remi-kazeroni  do you have any intentions to further work on this for v2.5?

**Comment by remi-kazeroni** [comment]
> @remi-kazeroni do you have any intentions to further work on this for v2.5?

Yes, this PR is finished but it would only makes sense to mark it as RfR whenever [#1657](https://github.com/ESMValGroup/ESMValTool/pull/1657) is merged. For the sake of consistency, I would like to have [#1657](https://github.com/ESMValGroup/ESMValTool/pull/1657) and this PR in the same release. Will do my best for this to happen in v2.5 😃

**Comment by remi-kazeroni** [comment]
@schlunma since you already took a look at the documentation of the new cmorizer interface (https://github.com/ESMValGroup/ESMValTool/pull/1657), you may want to have a look here as well, whenever you have time. It would be great to merge this PR and the main PR simultaneously.

**Review by schlunma — APPROVED** [review]
Looks good, thanks @remi-kazeroni !

**Pull request merged**
