### PR TITLE
add changelog for latest released version v2.7.1

### LINKED ISSUE #1904: Adding v2.7.1 to the Changelog
We would need to add the bugfix release v2.7.1 to the Changelog (see here the [changelog for v2.7.1](https://github.com/ESMValGroup/ESMValCore/releases/tag/v2.7.1)) as discussed in https://github.com/ESMValGroup/ESMValTool/pull/3010. 🍻

Once the Changelog is updated, we would also need to update the release schedule in the docs of the Tool

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

I promised this to @remi-kazeroni but only got around to do it now :beer: 

Closes #1904 

Link to documentation: [for PR1905](https://esmvaltool--1905.org.readthedocs.build/projects/ESMValCore/en/1905/changelog.html)

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by remi-kazeroni — APPROVED** [review]
Thanks @valeriupredoi, looks good to me! 🍻

**Comment by zklaus** [comment]
Could you please also add it to the overview list in the release schedule document?

**Comment by valeriupredoi** [comment]
@zklaus a very good call indeed! Had completely forgotten that we include the bugfix release too in the [overview table](https://docs.esmvaltool.org/en/latest/community/release_strategy.html) - I shall do that in a jiffy. While we are at it, you mind final-checking and merging this plss :beer:

**Comment by valeriupredoi** [comment]
cheers for the review @remi-kazeroni :beer:

**Comment by zklaus** [comment]
Already checked this, will merge as soon as the overview table is in.

**Comment by valeriupredoi** [comment]
> Already checked this, will merge as soon as the overview table is in.

cheers, bud! Note that that's a PR in Tool docs, you want to see that first? :beer:

**Comment by valeriupredoi** [comment]
there we go https://github.com/ESMValGroup/ESMValTool/pull/3028

**Comment by zklaus** [comment]
Ah sorry, yes, that makes sense. Didn't realize that the overview is in the other repo.

**Review by zklaus — APPROVED** [review]

**Comment by valeriupredoi** [comment]
no worries, man - logistics is not really our forte :rofl:

**Pull request merged**
