### PR TITLE
Remove deprecated features scheduled for removal in v2.8.0 or earlier

### PR DESCRIPTION
**Pull request by schlunma**
## Description

This PR removes code that has been scheduled for removal in v2.8.0 or earlier versions.

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
The Codecov issue is something that wasn't previously tested - fixing this is out of scope of this PR.

**Review by valeriupredoi — APPROVED** [review]
cheers, Manu! Good catch about that shp mask deprecation - it didn't have an expry date, and I had just seen it a week ago when I was working on a mask preproc PR :+1:

**Comment by valeriupredoi** [comment]
> The Codecov issue is something that wasn't previously tested - fixing this is out of scope of this PR.

indeed, since the file changed Codecov thinks that line was newly added

**Comment by bouweandela** [comment]
It would be good to add separate entries for these changes into the changelog when the time comes to make the release. Maybe it would be good to do separate pull requests per removed feature next time, so they automatically end up as separate items in the changelog.

**Pull request merged**
