### PR TITLE
Upload coverage to codecov

### LINKED ISSUE #961: Add a coverage reporting service to increase test coverage
To make us all more aware of how well we are testing new code, it would be good to add a coverage reporting service that comments on a pull request and shows how well we are doing. An example of such a service is https://about.codecov.io/product/features/

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Closes #961 

Link to documentation: https://esmvaltool--1190.org.readthedocs.build/projects/ESMValCore/en/1190/contributing.html#tests

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
cheers @bouweandela - can you pls tell me why that Codecov page gives me a 404 and there are lots of question marks in the report? Is it that it only analyzes if on `main`?

**Comment by bouweandela** [comment]
It's because it tries to compare the coverage from this branch to that of `main`, but the coverage of `main` will only get uploaded once this gets merged.

**Comment by valeriupredoi** [comment]
aha, makes sense, robots are still dumb (fortunately) :grin:

**Review by valeriupredoi — APPROVED** [review]
cool shtuff! I like that colored plot, both surrealist and useful for our purposes :grin:

**Comment by valeriupredoi** [comment]
some documentation would be nice, even if it just points to the vendor's webpage

**Pull request merged**
