### PR TITLE
Optimize documentation about Earth mover distance in distance_metric preprocessor

### PR DESCRIPTION
**Pull request by schlunma**
## Description

The old docs are slightly misleading.

Link to documentation: https://esmvaltool--2423.org.readthedocs.build/projects/ESMValCore/en/2423/recipe/preprocessor.html#distance-metric

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
Looks good and math-y, though I got no idea what those Gamma vectors mean, they look like Christoffel symbols 🤣

**Comment by bouweandela** [comment]
Maybe this needs a review from someone who understands?

**Comment by valeriupredoi** [comment]
> Maybe this needs a review from someone who understands?

blog-9-banner-a6431d114beb300d12aa0ffc8af66f229b2010470b18873f7eb4e551fe1f6c46

**Comment by valeriupredoi** [comment]
> > Maybe this needs a review from someone who understands?
> 
> blog-9-banner-a6431d114beb300d12aa0ffc8af66f229b2010470b18873f7eb4e551fe1f6c46

as inspired as my comment was, I think Mr CAT is unavailable for a review, anyone else that's not busy building the new ECMWF building? :grin:

**Comment by valeriupredoi** [comment]
any knowledgeable earth movers in @ESMValGroup/technical-lead-development-team please have a look and merge? :construction:

**Comment by rbeucher** [comment]
Could be a quick one for @charles-turner-1?

**Comment by charles-turner-1** [comment]
I'm satisfied that this is correct, I don't have permission to merge though.

**Pull request merged**
