### PR TITLE
Dropped Python 3.7

### LINKED ISSUE #1528: OSX Test and Monitor Test GA tests are failing for all Pythons
same crappe as in https://github.com/ESMValGroup/ESMValTool/issues/2584

Looking at it now

### PR DESCRIPTION
**Pull request by schlunma**
## Description

See discussion here: https://github.com/ESMValGroup/ESMValTool/issues/2584. On OSX, Python 3.7 is no longer supported by conda-forge.

Closes #1528

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
@runGAtests

**Review by valeriupredoi — APPROVED** [review]
happy to drop the gramps Python, cheers, Manu!

**Review by zklaus — APPROVED** [review]
Yepp, that's the way to go.

**Comment by schlunma** [comment]
Cheers guys!

I will wait for a couple of hours (say until 4pm CET) if anyone from the @ESMValGroup/esmvaltool-coreteam has any objections, then will proceed with the merge :+1:

**Comment by valeriupredoi** [comment]
> Cheers guys!
> 
> I will wait for a couple of hours (say until 4pm CET) if anyone from the @ESMValGroup/esmvaltool-coreteam has any objections, then will proceed with the merge +1

nice of you :smiley:

**Comment by schlunma** [comment]
GitHub Actions ran successful (apart from the OSX 3.7 of course): https://github.com/ESMValGroup/ESMValCore/actions/runs/1962822315

I noticed that every comment in this PR triggers a GitHub action (e.g., https://github.com/ESMValGroup/ESMValCore/actions/runs/1962915977), is this on purpose?

**Comment by valeriupredoi** [comment]
if you are bit confused why there is a 3.7 OSX run [here](https://github.com/ESMValGroup/ESMValCore/actions/runs/1962822315) that is because the dumb GA bot is running the workflow that is on `main` rather the one in this PR. I am very confused as to what the crappe are those autofailed tests triggered by codecov tho

**Comment by schlunma** [comment]
> if you are bit confused why there is a 3.7 OSX run [here](https://github.com/ESMValGroup/ESMValCore/actions/runs/1962822315) that is because the dumb GA bot is running the workflow that is on `main` rather the one in this PR.

That's what I thought :smile:

**Comment by schlunma** [comment]
> I am very confused as to what the crappe are those autofailed tests triggered by codecov tho

They are not triggered by codecov, but by our comments:

grafik

**Comment by valeriupredoi** [comment]
aagh! I know what those are - not just codecov - but any comment - it tries to initiate the GA test but because there is no key string (am not gonna write it here coz I'd invoke the test) in the comment it stops, I need to figure out how to not have the initial phase of the test triggered - Github Actions documentation is blithering terrible

**Comment by schlunma** [comment]
Ahh, and it does that regardless if the keyword was mentioned in that PR or not (see #1308)...

**Comment by valeriupredoi** [comment]
seems like I have created a thing more verbose than my mum :rofl: Hang on lemme see what I can do about that

**Pull request merged**
