### PR TITLE
Refactor logging configuration

### PR DESCRIPTION
**Pull request by stefsmeets**
## Description

This code moves the logging out of the `_config.py` module into its own `_logging.py`, so that the logger can be imported without initializing `DIAGNOSTICS_PATH` / `CFG` / etc. I also did some refactoring and added some documentation based on my understanding of this module. No functionality has been added or changed.

I hope that this will make it easer to work with. This is also needed for #907 for I'm looking to see if I can merge logging from there with the logging config that already exists.

-   Addresses part of #889

***

## Before you get started

-   [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [x] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
~-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality~
~-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks~
-   [x] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
~-   [ ] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available~

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
nice one @stefsmeets - I think this is a cleaner more portable approack! One remark - would be able to write a couple tests for the new module, it's good to have it test-covered as a module even if (I think) there were minimal tests before :+1: :beer:

**Comment by stefsmeets** [comment]
Yeah, I could not find any tests so I did not bother but I can add a couple next week. 👍

**Comment by valeriupredoi** [comment]
cheers dude! Lemme know if you got time, if not I can do that, been doing a lot of maintenance and test stuff lately anyway :+1:

**Comment by stefsmeets** [comment]
Hi @valeriupredoi , I added a couple of tests to cover the functionality of module. Does this work for you?

**Comment by valeriupredoi** [comment]
very cool @stefsmeets - 100% coverage too :beer:

**Review by valeriupredoi — APPROVED** [review]

**Pull request merged**
