### PR TITLE
Support automatically closing issues

### PR DESCRIPTION
**Pull request by bouweandela**
When you fill the current pull request template, the associated issue will not be automatically closed. This pull request updates the template so issues are automatically closed by GitHub when the linked pull request is merged.

### CODE REVIEW

**Review by stefsmeets — APPROVED** [review]
👍

**Comment by stefsmeets** [comment]
Oddly tests are failing with some 2021 relates issues:

```
E       assert '<?xml versio.../>\n</cube>\n' == '<?xml versio.../>\n</cube>\n'
E         Skipping 300 identical leading characters in diff, use -v to show
E         Skipping 1413 identical trailing characters in diff, use -v to show
E         - mation 2020"/>
E         ?           ^
E         + mation 2021"/>
E         ?           ^
E             </a
```

**Comment by stefsmeets** [comment]
And ESMValTool may need a similar treatment, because it uses the same closes/fixes wording.

**Comment by jvegasbsc** [comment]
> Oddly tests are failing with some 2021 relates issues:

#925 fixes those tests

**Pull request merged**
