### PR TITLE
Fix type hints for Python versions < 3.10

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Python 3.8 and 3.9 do not support
```python
a = str | int
```
Python 3.8 does not support
```python
a = list[str]
```

even with `from __future__ import annotations`.

In function signatures, the syntax is supported though.

Credits to @schlunma for figuring this out.

This pull request updates the code so the older Python versions are type hinted correctly.

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
not sure this can be solved easily @bouweandela - have a look at this https://github.com/tiangolo/typer/issues/348 - am trying to pin typer see what's out of that, but until they fix it upstream I reckon we can't do much

**Comment by bouweandela** [comment]
I'm not sure if typer is related to this issue. What puzzles me is that [dask](https://github.com/dask/dask/) uses a very similar configuration, so why is it not working for us?

**Comment by valeriupredoi** [comment]
> I'm not sure if typer is related to this issue. What puzzles me is that [dask](https://github.com/dask/dask/) uses a very similar configuration, so why is it not working for us?

I thought typer was needed if we wanted to mess about with these type hints, I was wrong and I closed that PR - I am wondering though, maybe dask is using a different configuration of standards, or no mypy? Lemme have a look too

**Comment by schlunma** [comment]
I don't understand how pinning the Python version of mypy is supposed to solve this. Code like

```
MyType = list[int] | dict
```

is simply not valid code in Python<3.10 and will always raise these errors, no mypy involved whatsoever.

**Comment by schlunma** [comment]
But there is no `__future__` stuff in this PR, is there? On the other hand, dask uses that:

https://github.com/dask/dask/blob/81f771e05f57cab2838534c319a9b81f6e5a00cd/dask/highlevelgraph.py#L1

**Comment by valeriupredoi** [comment]
> But there is no `__future__` stuff in this PR, is there? On the other hand, dask uses that:
> 
> https://github.com/dask/dask/blob/81f771e05f57cab2838534c319a9b81f6e5a00cd/dask/highlevelgraph.py#L1

not in this PR, Manu, since this a fixer PR - Bouwe put those _futures shtuff already, look at `esmvalcore/dataset.py` or `typing.py`

**Comment by schlunma** [comment]
Ah, yes, that makes sense. Sorry, I didn't check that.

I think I know what the problem is: `from __future__ import annotations` [allows the usage of standard types in **variable and function definitions** ](https://peps.python.org/pep-0585/#implementation), i.e., something like:

```py
def f(x: list[int]) -> dict[str, float]:
    pass
```

is allowed and works with Python >= 3.7 when using `from __future__ import annotations`.

Example in our code: https://github.com/ESMValGroup/ESMValCore/blob/25e508adc14e9390fab81e412f035fe3ce607e35/esmvalcore/_recipe/from_datasets.py#L26

However, as far as I can tell, it is **not** possible to use this feature in code that is always executed (e.g., to define custom types) in Python < 3.10 like we do here:

https://github.com/ESMValGroup/ESMValCore/blob/25e508adc14e9390fab81e412f035fe3ce607e35/esmvalcore/_recipe/from_datasets.py#L20-L21

If you look at the error message we get, it's always those two lines. Other code that uses syntax like `dict[...]` in function and variable definitions does not raise errors.

**Comment by valeriupredoi** [comment]
> Ah, yes, that makes sense. Sorry, I didn't check that.
> 
> I think I know what the problem is: `from __future__ import annotations` [allows the usage of standard types in **variable and function definitions** ](https://peps.python.org/pep-0585/#implementation), i.e., something like:
> 
> ```python
> def f(x: list[int]) -> dict[str, float]:
>     pass
> ```
> 
> is allowed and works with Python >= 3.7 when using `from __future__ import annotations`.
> 
> Example in our code:
> 
> https://github.com/ESMValGroup/ESMValCore/blob/25e508adc14e9390fab81e412f035fe3ce607e35/esmvalcore/_recipe/from_datasets.py#L26
> 
> However, as far as I can tell, it is **not** possible to use this feature in code that is always executed (e.g., to define custom types) in Python < 3.10 like we do here:
> 
> https://github.com/ESMValGroup/ESMValCore/blob/25e508adc14e9390fab81e412f035fe3ce607e35/esmvalcore/_recipe/from_datasets.py#L20-L21
> 
> If you look at the error message we get, it's always those two lines. Other code that uses syntax like `dict[...]` in function and variable definitions does not raise errors.

@schlunma I think that's a bingo! Since it doesn't seem to be mypy's fault here - let me see if we get the same with a lower mypy pin, if that's the case then we got us a runner

**Comment by valeriupredoi** [comment]
yeah I reckon that's it - just figured it out it's not mypy that's at fault here, unless it's a dormant bug that's not been checked since a few versions ago - @schlunma you wanna make the changes you suggest directly in here and let's have us a test? I don't think @bouweandela would mind, since I've already hacked his PR quite a bit, before getting back to its original state :grin:

**Review by valeriupredoi — APPROVED** [review]
boom! Looking great, cheers, Manu! @bouweandela I took the liberty make this RfR and approve it while I'm at it too

**Comment by valeriupredoi** [comment]
@bouweandela got a bit of time to look at this, buds?

**Pull request merged**
