### PR TITLE
Added fix to convert "geopotential" to "geopotential height" for ERA5

### PR DESCRIPTION
**Pull request by egalytska**
Before you start, please read [CONTRIBUTING.md](https://github.com/ESMValGroup/ESMValCore/blob/master/CONTRIBUTING.md).

**Tasks**

-   [ ] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

This pull request is related to ESMValTool pull request https://github.com/ESMValGroup/ESMValTool/pull/1644.

### CODE REVIEW

**Comment by bouweandela** [comment]
@valeriupredoi Would you be able to test this?

**Comment by valeriupredoi** [comment]
I will add a unit test in a jiffy but can't test since we don't have any ERA5 data on Jasmin - @mattiarighi is the ERA5 landlord at DKRZ :grin:

**Comment by bouweandela** [comment]
> I will add a unit test in a jiffy but can't test since we don't have any ERA5 data on Jasmin

Here is a blog post [announcing the availability of ERA5 on Jasmin](https://www.ceda.ac.uk/blog/ceda-archive-support-for-era5-use/). It is stored in `/badc/ecmwf-era5` and `/badc/ecmwf-era5t`

**Comment by valeriupredoi** [comment]
dam right you are it's there, had no idea! But am gonna need a manual to be able to understand what's the data paths - do we have this location anywhere in the documentation and some instructions on how to grab files depending what one needs?

**Comment by bouweandela** [comment]
There is some documentation here: https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation#ERA5:datadocumentation-DataorganisationandhowtodownloadERA5, click `Data organisation in MARS` to expand the tab to have an explanation of the facets.

**Pull request merged**
