### PR TITLE
Run problematic cmor tests sequentially to avoid segmentation faults on CircleCI

### LINKED ISSUE #644: Segmentation fault when running tests on CircleCI
The unit tests are failing regularly due to a segmentation fault.

If this happens to your pull request, please go to CircleCI by clicking 'Details' behind the CircleCI 'commit' check below your pull request, and clicking on the failed test job. Once you're on CircleCI, click the 'Rerun' button in the top right corner and choose 'Rerun Workflow from Failed'. Usually, the test will succeed the second time, if not, try again. If you do not see the 'Rerun' button, you need to log in to CircleCI with your GitHub account first.

The problem seems to originate from the netcdf4 library.

Example crashed run: https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/2482/workflows/f8e73729-c4cf-408c-bdae-beec24238ac1/jobs/10300/steps

Example stack trace:
```
tests/integration/cmor/_fixes/cmip6/test_cnrm_cm6_1.py ..Fatal Python error: Segmentation fault
 
Thread 0x00007fc098ff9700 (most recent call first):
  File "/opt/conda/envs/esmvaltool/lib/python3.8/multiprocessing/pool.py", line 576 in _handle_results
  File "/opt/conda/envs/esmvaltool/lib/python3.8/threading.py", line 870 in run
  File "/opt/conda/envs/esmvaltool/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/conda/envs/esmvaltool/lib/python3.8/threading.py", line 890 in _bootstrap
 ... 

Thread 0x00007fc0b97fa700 (most recent call first):
 
  File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/iris/fileformats/netcdf.py", line 391 in __getitem__
  File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/array/core.py", line 98 in getter
  File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/core.py", line 121 in _execute_task
  File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/core.py", line 121 in <genexpr>
  File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/core.py", line 121 in _execute_task
  File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/local.py", line 222 in execute_task
  File "/opt/conda/envs/esmvaltool/lib/python3.8/multiprocessing/pool.py", line 125 in worker
  File "/opt/conda/envs/esmvaltool/lib/python3.8/threading.py", line 870 in run
  File "/opt/conda/envs/esmvaltool/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/conda/envs/esmvaltool/lib/python3.8/threading.py", line 890 in _bootstrap

...

Current thread 0x00007fc0fa7fc700 (most recent call first):
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/iris/fileformats/netcdf.py", line 391 in __getitem__
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/array/core.py", line 98 in getter
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/core.py", line 121 in _execute_task
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/core.py", line 121 in <genexpr>
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/core.py", line 121 in _execute_task
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/local.py", line 222 in execute_task
   File "/opt/conda/envs/esmvaltool/lib/python3.8/multiprocessing/pool.py", line 125 in worker
   File "/opt/conda/envs/esmvaltool/lib/python3.8/threading.py", line 870 in run
   File "/opt/conda/envs/esmvaltool/lib/python3.8/threading.py", line 932 in _bootstrap_inner
   File "/opt/conda/envs/esmvaltool/lib/python3.8/threading.py", line 890 in _bootstrap
  
...

 Thread 0x00007fc19193e740 (most recent call first):
   File "/opt/conda/envs/esmvaltool/lib/python3.8/threading.py", line 302 in wait
   File "/opt/conda/envs/esmvaltool/lib/python3.8/queue.py", line 170 in get
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/local.py", line 133 in queue_get
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/local.py", line 475 in get_async
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/threaded.py", line 76 in get
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/dask/base.py", line 444 in compute
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/iris/_lazy_data.py", line 226 in _co_realise_lazy_arrays
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/iris/_lazy_data.py", line 262 in as_concrete_data
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/iris/_data_manager.py", line 216 in data
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/iris/coords.py", line 640 in points
   File "/develop/tests/integration/cmor/_fixes/cmip6/test_cnrm_cm6_1.py", line 134 in test_cl_fix_metadata
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/python.py", line 182 in pytest_pyfunc_call
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/python.py", line 1477 in runtest
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/runner.py", line 135 in pytest_runtest_call
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/runner.py", line 217 in <lambda>
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/runner.py", line 244 in from_call
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/runner.py", line 216 in call_runtest_hook
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/runner.py", line 186 in call_and_report
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/runner.py", line 100 in runtestprotocol
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/runner.py", line 85 in pytest_runtest_protocol
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/main.py", line 272 in pytest_runtestloop
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/main.py", line 247 in _main
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/main.py", line 191 in wrap_session
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/main.py", line 240 in pytest_cmdline_main
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/_pytest/config/__init__.py", line 124 in main
   File "/develop/.eggs/pytest_runner-5.2-py3.8.egg/ptr.py", line 220 in run_tests
   File "/develop/.eggs/pytest_runner-5.2-py3.8.egg/ptr.py", line 209 in run
   File "/opt/conda/envs/esmvaltool/lib/python3.8/distutils/dist.py", line 985 in run_command
   File "/opt/conda/envs/esmvaltool/lib/python3.8/distutils/dist.py", line 966 in run_commands
   File "/opt/conda/envs/esmvaltool/lib/python3.8/distutils/core.py", line 148 in setup
   File "/opt/conda/envs/esmvaltool/lib/python3.8/site-packages/setuptools/__init__.py", line 144 in setup
   File "setup.py", line 159 in <module>
  
Received "segmentation fault" signal 
```

### PR DESCRIPTION
**Pull request by valeriupredoi**
Attempting to minimize the effects of random segmentation faults described in #644 and based on finding in this [comment](https://github.com/ESMValGroup/ESMValCore/issues/644#issuecomment-810276519) and using implementation suggestion by @stefsmeets (cheers, mate!)

EDIT: huzzah! This thing really works!
Closes #644

### CODE REVIEW

**Comment by valeriupredoi** [comment]
boom! first set of 9 test sets and no SegFault!

**Review by stefsmeets — APPROVED** [review]
Looks good to me! Nice to see that this solution worked 😁

As a side note, does this mean we can also use `pytest -n 4` for a small speed-up or is CircleCI limited to 2 threads?

**Review by schlunma — APPROVED** [review]
Looks good to me :tada:

**Comment by valeriupredoi** [comment]
cheers for the quick review, chaps! @stefsmeets cheers for changing the title, better one! Also, I am not 100% about the `-n 4` option, I *think* they are limited to 2, but we can try in a new PR :+1:

**Pull request merged**
