### PR TITLE
Pin cf-units to lower than 3.1.0 to temporarily avoid changes within new version related to calendars

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Temporarily fixes test failures noted in https://github.com/ESMValGroup/ESMValCore/issues/1655

Does not offer a long-term fix. That should be included after the 2.6.0 release.

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

### CODE REVIEW

**Comment by valeriupredoi** [comment]
why is the doc build test trying to build the `cf-units` wheel? It's there in the already created env! What the...

**Comment by valeriupredoi** [comment]
ok tests pass - let's get this kludge in! :beer:

**Review by sloosvel — APPROVED** [review]

**Comment by sloosvel** [comment]
>That should be included after the 2.6.0 release.

Wouldn't that break the final release candidate if this was included after 2.6?

**Comment by zklaus** [comment]
> > That should be included after the 2.6.0 release.
> Wouldn't that break the final release candidate if this was included after 2.6?

I am not sure I understand, but I think @valeriupredoi was referring to the long-term fix being put in place after the release, this short-term fix should go in asap. With this understanding, the sequence of events would be

1. Merge this PR to make sure the nightly tests pass and we don't get any (additional) calendar problems in the 2.6.0 release
2. Make any number of release candidates for ESMValCore
3. Release the last release candidate the official 2.6.0 release for ESMValCore and release together with the 2.6.0 release of ESMValTool
4. Put in the long-term fix. The proposal in #1656 works with both older and newer versions of cf-units.
5. Profit

In this, there is no breaking of the release candidate. Does that make sense and answer your question?

**Pull request merged**
