### PR TITLE
add `pandas` as dependency :panda_face: 

### LINKED ISSUE #1401: Our pandas left us: test failures due to missing module `pandas` since latest `iris` doesn't need any more `pandas`
[test fails eg](https://github.com/ESMValGroup/ESMValCore/runs/4348196555?check_suite_focus=true) - I am investigating

**CAUSE FOUND**: latest iris build:
```
(esmvalcore-stock-conda) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValCore$ conda list iris
# packages in environment at /home/valeriu/miniconda3/envs/esmvalcore-stock-conda:
#
# Name                    Version                   Build  Channel
iris                      3.1.0              pyhd8ed1ab_3    conda-forge
```
does not include `pandas` as dependency anymore - I opened an issue https://github.com/SciTools/iris/issues/4442 and asked, if they don't need it anymore we either include it ourselves or see about not using it anymore :+1:

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

`pandas` is no longer a required build dependency of `iris` so we should add it for our needs, since the package is actively used and imported in ESMValCore :panda_face: 

Closes #1401 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
It should be added to setup.py as well, probably, plus we might want to add a new build on conda-forge. Could you start a PR at https://github.com/conda-forge/esmvalcore-feedstock ?

**Comment by valeriupredoi** [comment]
@zklaus let's get this in :beer:

**Comment by zklaus** [comment]
It always takes some time for the new builds to appear on the CDN that serves the packages. As a rule of thumb, after the merge (here ~1hr ago) comes the build (yes, it is built again in the main branch, even though everything was already built in the PR CI, however, here the build took only ~10m), then the package is uploaded to the index and distributed to the CDN, which usually takes a couple of hours.

So, maybe we can wait another few hours and then test again?

**Comment by valeriupredoi** [comment]
sounds good, am good at playing the waiting game :grin:

**Comment by zklaus** [comment]
Alright, seems like the new build is now available (as verified by a local `mamba search esmvalcore`). Do you want to try again?

**Review by zklaus — APPROVED** [review]

**Comment by valeriupredoi** [comment]
huzzah! Build numero 2 installed all across the board :grinning: We have :panda_face: back again in the Zoo

**Pull request merged**
