### PR TITLE
Added fixes for various CMIP5 datasets, variable cl (3-dim cloud fraction)

### LINKED ISSUE #1016: Various CMIP5 datasets need fixes for variable cl
The following CMIP5 datasets erroneously report units of variable cl (3-dim cloud fraction) as percent (%) but units are actually given as fraction (0-1):

* BNU-ESM
* CCSM4
* CESM1-BGC
* CESM1-CAM5
* CESM1-FASTCHEM
* CESM1-WACCM
* FIO-ESM
* GFDL-CM2p1

### PR DESCRIPTION
**Pull request by axel-lauer**
This PR provides fixes for the CMIP5 datasets BNU-ESM, CCSM4, CESM1-BGC, CESM1-CAM5, CESM1-FASTCHEM, CESM1-WACCM, FIO-ESM, GFDL-CM2p1. Variable cl (3-dim cloud fraction) is erroneously reported in units percent (%) but units are actually given as fraction (0-1).

-   Closes #1016

## Checklist

-   [ ] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] Labels are assigned so they can be used in the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [ ] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   [ ] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:

-   [ ] Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
Do you have a recipe for testing?

**Comment by axel-lauer** [comment]
@schlunma Thanks for looking into this! Here is a recipe for testing: [recipe_test_cl_fixes.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/6028776/recipe_test_cl_fixes.yml.txt)

**Review by schlunma — COMMENTED** [review]
Output looks good, all data is in the range [0, 100] now.

Since all fixes are the same, I think you could implement every fix like the one you did for CESM1-WACCM, i.e. leave the fix for BNU-ESM as it is and replace all others with

```py
from .bnu_esm import Cl as BaseCl


Cl = BaseCl
```

For the tests you can do the same. Leave the BNU-ESM as is and replace the rest with

```py
"""Tests for the fixes of XXX."""
from esmvalcore.cmor._fixes.cmip5.bnu_esm import Cl as BaseCl
from esmvalcore.cmor._fixes.cmip5.xxx import Cl
from esmvalcore.cmor.fix import Fix


def test_get_cl_fix():
    """Test getting of fix."""
    fix = Fix.get_fixes('CMIP5', 'XXX', 'Amon', 'cl')
    assert fix == [Cl(None)]


def test_cl_fix():
    """Test fix for ``cl``."""
    assert Cl is BaseCl
```

**Review by schlunma — APPROVED** [review]
Code and output looks good :tada:

**Comment by axel-lauer** [comment]
@schlunma Thanks for reviewing!

**Pull request merged**
