### PR TITLE
Set the version number on the development branches to one minor version more than the previous release

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

This sets the version number on the `main` and feature branches so it starts with `v2.8.0.dev` (considering that the current release is `v2.7.0`). To make a release branch for a previous release, call it `v2.7.x` and the version number will be automatically correct (e.g. something starting with `v2.7.1-dev` if branched of the `v2.7.0` tag). This approach avoids the need to merge micro releases back into the `main` branch just to get the version number right.

@ESMValGroup/technical-lead-development-team 

See https://pypi.org/project/setuptools-scm/ for the details.

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by zklaus — APPROVED** [review]
LGTM. Should also be cherry-picked into the release branch, right?

**Comment by valeriupredoi** [comment]
cheers @bouweandela - do we have to pin setuptools_scm be with `toml` like [here](https://github.com/SciTools/iris/blob/dfbc5c2aef0c64918061a4e312f66d94b0beb525/pyproject.toml#L5) maybe?

**Review by valeriupredoi — APPROVED** [review]

**Comment by valeriupredoi** [comment]
also, if you turn on GA you can directly see the version after the test runs `pip install ...`

**Comment by bouweandela** [comment]
@ESMValGroup/tech-reviewers Could one of you please do a final check and merge?

**Pull request merged**
