### PR TITLE
Fixes of ocean variables in multiple CMIP6 datasets

### LINKED ISSUE #1539: Dataset problem: ocean variables for multiple CMIP6 datasets
**Describe the dataset issue**

A number of CMIP6 datasets requires fixes for different ocean variables to correct coordinates metadata and fix issues with depth definition.

Along with the dataset initially spotted in this issue (`cesm2_waccm`, `gfdl_cm4`, `gfdl_esm4`), it was decided to integrate and verify the changes reported in the sloppy PR #1395

Some of these fixes can be easily inherited from the models of the same family, where they have already been implemented.

### PR DESCRIPTION
**Pull request by tomaslovato**
## Description

Different CMIP6 datasets (see #1539 and #1395) require the inclusion of fixes for depth coordinates definition that are common to models from the same family.

Closes #1539 and sloppy PR #1395

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

### CODE REVIEW

**Review by valeriupredoi — CHANGES_REQUESTED** [review]
buon giorno, Tomaso, comme stai? I am not sure I understand the cesm2 fix - why are you fixing the `Omon` variable? Indeed, the test is failing since the fix has two members: cesm2.Fgco2 and cesm2.Omon:
```
fix = [<esmvalcore.cmor._fixes.cmip6.cesm2.Fgco2 object at 0x7f8d8d85f820>, <esmvalcore.cmor._fixes.cmip6.cesm2.Omon object at 0x7f8d8d85f7c0>]
```

**Comment by tomaslovato** [comment]
> buon giorno, Tomaso, comme stai? I am not sure I understand the cesm2 fix - why are you fixing the `Omon` mip variable? Indeed, the test is failing since the fix has two members: cesm2.Fgco2 and cesm2.Omon:
> 
> ```
> fix = [<esmvalcore.cmor._fixes.cmip6.cesm2.Fgco2 object at 0x7f8d8d85f820>, <esmvalcore.cmor._fixes.cmip6.cesm2.Omon object at 0x7f8d8d85f7c0>]
> ```
Grandissimo @valeriupredoi !!! tutto bbbene!
I think this one in on me ... I forgot to add `Omon` in  the `test_get_fgco2_fix` script of `cesm2_waccm`, similarly to what it is done for `cesm2`, 
https://github.com/ESMValGroup/ESMValCore/blob/42414577c5f708b433f3bb82a6380afc73ca7ba2/tests/integration/cmor/_fixes/cmip6/test_cesm2.py#L284-L287

**Comment by tomaslovato** [comment]
I included fixes for the following models:
`cesm2_fv2`, `cesm2_waccm`, `cesm2_waccm_fv2`, `cnrm_cm6_1`, `fgoals_f3_l`, 
`gfdl_cm4`, `gfdl_esm4`,` ipsl_cm5a2_inca`, `ipsl_cm6a_lr_inca`

I did not imported from PR #1395 the fixes for 
- ` ipsl_cm6a_inca` as I did not found this dataset on ESGF.
- `iitm_esm`,  the original data (e.g. for `thetao` and `uo`) does not require any fix to the coordinate
- `noresm2_lm` & `noresm2_mm`: the regular grid (`gr`) data of these dataset doesn't need fixes. If the original intent in #1395 was to fix the native grid data (`gn`) the proposed fixes were applied to vertical layers in that are in sigma coordinate, so the simple renaming of the depth would not help with this.

**Review by valeriupredoi — APPROVED** [review]
excellent, mille grazie @tomaslovato :beer: Could you please fix the issue description boxes too? Cheers muchly for the good work!

**Comment by tomaslovato** [comment]
> excellent, mille grazie @tomaslovato 🍺 Could you please fix the issue description boxes too? Cheers muchly for the good work!

I checked the boxes at the top of this PR ... there is still something missing?

**Comment by valeriupredoi** [comment]
> > excellent, mille grazie @tomaslovato beer Could you please fix the issue description boxes too? Cheers muchly for the good work!
> 
> I checked the boxes at the top of this PR ... there is still something missing?

all's nice and ready, man, thanks a lot!

**Pull request merged**
