### PR TITLE
Filter warnings about collapsing multi-model dimension in multimodel statistics preprocessor function

### LINKED ISSUE #1219: Multimodel statistics clutters the log with warnings
See here an example of the warnings generated by running `examplex/recipe_python.yml` from the ESMValTool: https://github.com/ESMValGroup/ESMValCore/files/6782756/log.txt

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Filter warnings about collapsing multi-model dimension in multimodel statistics preprocessor function. This is a dimension that by definition does not have bounds, so the warnings do not make sense.

Closes #1219

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
Given the many warnings that we have and the potential usefulness of this one (even if it is a bit hard to interpret) for other variables then tas (see @alistairsellar's comment: https://github.com/ESMValGroup/ESMValCore/issues/1204#issuecomment-872220725), I'd like to bump this to 2.4.0 for a final decision. Ok?

**Comment by bouweandela** [comment]
> potential usefulness of this one

The warning filtered by this pull request is very specific and completely useless.

The way the multimodel statistics preprocessor works is that it merges all input models into a single cube, adding a `multi-model` dimension. It then collapses this cube along that dimension to compute the statistic. This dimension does not have bounds because there is no meaningful order in the models. To keep memory use small, it does this for every single time point separately. That means that the warning is issued as many times as there are time points, so if you run a recipe with 150 years of monthly data you'll get 1800 warnings, making a big mess of your screen. Therefore I would prefer to include this in v2.3.1. It's a pretty minor change and I can add a unit test tomorrow morning.

**Comment by bouweandela** [comment]
To show you just how many warnings that is, attached are the messages that are displayed when I run `examples/recipe_python.yml`: [log.txt](https://github.com/ESMValGroup/ESMValCore/files/6782756/log.txt)

**Comment by zklaus** [comment]
Ah yes, now I agree. I thought this was about the same message for the `height` coordinate, but for the `multi-model` coordinate this makes perfect sense, of course.

**Review by zklaus — APPROVED** [review]

**Pull request merged**
