### PR TITLE
Added `dataset` and `alias` attributes to `multi_model_statistics` output

### LINKED ISSUE #1480: Output of `multi_model_statistics` does not have `dataset` and `alias` anymore
Changes in #673 (see [here](https://github.com/ESMValGroup/ESMValCore/pull/673/files#diff-b675431b6cf759c61f7867680472aabc0304475fd666ed514ca0365bb87c2a47L720)) cause many diagnostics to fail at the moment (e.g., the python example recipe) since the attributes `dataset` and `alias` are missing.

### PR DESCRIPTION
**Pull request by schlunma**
## Description

Re-adds the attributes `dataset` and `alias` (which many diagnostics rely on) to multi_model_statistics output.

Closes #1480

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
@sloosvel @valeriupredoi can you briefly take a look at this? This is the final piece that's missing for v2.5.0rc1 :smile: Thanks!!!

**Review by valeriupredoi — APPROVED** [review]
looks just perfect to me, man! Thank you!

**Comment by schlunma** [comment]
Awesome, thanks :heart:

**Comment by sloosvel** [comment]
Sorry for so many slipups in #673 !

**Comment by schlunma** [comment]
No worries at all, #673 is a great addition!! It must have been hell to fix all the merge conflicts that surfaced there...

**Pull request merged**
