### PR TITLE
test pull request statistics via Github Action

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Testing @bouweandela suggested GA action tool to inspect PR statistics - originally posted in https://github.com/ESMValGroup/ESMValTool/issues/2687

Closes #issue_number

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@schlunma is an Audi LMP1 at Le Mans - lots of laps and done super fast :rofl: I like this nifty thing - but isn't this a bit of a compettion-driven stats? I fear it may promote quantity over quality - thoughts please

**Comment by bouweandela** [comment]
Would it be possible to increase the timespan to the last 6 months?

**Comment by bouweandela** [comment]
It also says something about quality: 4 reviews but 0 comments @valeriupredoi?

**Comment by valeriupredoi** [comment]
> Would it be possible to increase the timespan to the last 6 months?

I'll look into that on Monday :+1: 

> It also says something about quality: 4 reviews but 0 comments @valeriupredoi?

Those were the ones I did for the condalock bot - if I talk to the bot **then** you should start getting concerned :laughing:

**Comment by bouweandela** [comment]
The numbers in the column 'Time to review' do not look very realistic and do not match those when you click the link to see the details. I wonder where those come from?

Would there be some way to share this information in a publicly visible place? E.g. in README.md?

**Comment by valeriupredoi** [comment]
> Would there be some way to share this information in a publicly visible place? E.g. in README.md?

Yes, we can create a badge of the GA test that'll show the most up to date result when it ran - we can run it nightly for example.

> The numbers in the column 'Time to review' do not look very realistic and do not match those when you click the link to see the details. I wonder where those come from?

They define it like this: Time to review: It is the median of the times to review of all Pull Requests reviewed by a person in the period. The plot shows time to first review in the lasts 180 days which is a different curry dish - a bit confusing if you asked me TBH

**Comment by zklaus** [comment]
Whether that is meaningful is a different question, of course, but, indeed, the time to review in the table is the median which is visualized as a constant orange line in the plot. If you click on the red box at the top with the stricken out ~average~, that too will be shown as a constant line, this time red, and you can deactivate any of the three elements.

**Comment by valeriupredoi** [comment]
spot on, Klaus! I just realized that graph is interactive so I turned on the thin red line (heh!) of the Average

**Comment by valeriupredoi** [comment]
guys, I opened this https://github.com/flowwer-dev/pull-request-stats/issues/40 ask the devs of the action about how we can get these results in a (nightly) updated stats table detached of any PR, just to have it in a badge and users click on it and see all the stats goodies

**Comment by valeriupredoi** [comment]
what do peeps think about this? Should we merge/change and merge, or we just keep it here and rerun when we feel oppressed by higher fora? :grin:

**Comment by bouweandela** [comment]
I think it is a good start, but the problem with this action as it is now is that the result can only be published as a pull request comment (which feels like the wrong place) or on slack (which we're not using). We would need the result in a file that is hosted somewhere (could be the result of a GitHub action so we can point to it from a badge in the README.md as you suggested, or an automated pull request to update our docs occasionally, or ..).

Maybe we can just close this for now and try again when the action is more mature?

**Comment by valeriupredoi** [comment]
@bouweandela I think I can make it run as a nightly action (not attached to a PR), gimme a few, I'll investigate

**Comment by valeriupredoi** [comment]
thanks bot! :angry:

**Comment by valeriupredoi** [comment]
@bouweandela I have to give this up - it's far too clunky to get anything streamlined, and I spent far too much time on it already :grimacing: I got an action to create an auto PR but that doesn't automatically run the PR stats action unless pushed to it since a PR open by a bot doesn't register as an open PR so it doesn't trigger the action - pushing on an auto PR is like a dog chasing its own tail since that'll trigger the auto PR opening, closing the initial auto PR, that will not run the PR stats again :laughing: ; the guys devving the PR stats thing will probably refine their output options, so we'll pick it up then :+1:

**Comment by bouweandela** [comment]
Thanks for trying!

**Pull request closed without merging**
