### PR TITLE
Fixed issue in irregular regridding regarding scalar coordinates

### LINKED ISSUE #1844: Error when regridding ocean variables
**Describe the bug**
I got an error when regridding ocean variables. But it is working with ESMValCore Tag v2.7.0.

Error message:
`ValueError: Duplicate coordinates are not permitted.`

When commenting out lines 299+300 in `esmvalcore/preprocessor/_regrid_esmpy.py` it is working again.
```
# Add scalar dimensions of source cube to target
for scalar_coord in src_rep.coords(dimensions=()):      
    aux_coords_and_dims.append((scalar_coord, ()))
```
These lines were included with the pull request #1811.

[recipe_test_regrid.txt](https://github.com/ESMValGroup/ESMValCore/files/10139178/recipe_test_regrid.txt)
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/10139179/main_log_debug.txt)

### PR DESCRIPTION
**Pull request by schlunma**
## Description

https://github.com/ESMValGroup/ESMValCore/pull/1811 introduced the addition of scalar coordinate to the output of the irregular regridding. However, by mistake, I read the scalar coordinates from the source **representant**, not the source cube itself. Since the **representant** is the result of slicing the source, it potentially contains many (unwanted) scalar coordinates and also leads to the bug described in https://github.com/ESMValGroup/ESMValCore/issues/1844.

This PR fixes that.

Closes #1844

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by schlunma** [comment]
Hi @LisaBock, I think this should fix your bug, could you please try your recipe with this change? Sorry for messing this up in the first place in #1811!

**Review by LisaBock — APPROVED** [review]
My recipes test was successfull.
Thanks @schlunma for the quick fix!

**Review by remi-kazeroni — APPROVED** [review]
LGTM, thanks @schlunma and @LisaBock!

**Comment by valeriupredoi** [comment]
cheers for this, you three (not an Xmas reference, I promise :christmas_tree: ) - @remi-kazeroni since Lisa approved as well, feel free to merge :+1:

**Pull request merged**
