### PR TITLE
Fix bounds after reversing coordinate values

### LINKED ISSUE #1060: Reversing coordinates using iris.util.reverse flips the bounds incorrectly
**Describe the bug**
During the checks for monotonicity and direction, if a coordinate has the wrong direction it gets flipped using `iris.util.reverse`. However, this also flips the bounds and makes them non-contigous. This can cause issues in later preprocessing steps, for instance, when computing area weighted operations.

### PR DESCRIPTION
**Pull request by sloosvel**
## Description
This pull request flips back the coordinate bounds if they have been reversed when checking the coordinate direction

-   Closes #1060 
-   Link to documentation:

***

## Before you get started

-   [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [x] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Labels are assigned so they can be used in the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [x] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   [x] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:

-   [ ] Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Comment by sloosvel** [comment]
Actually I am not sure if this is right, or if it's a weird issue with a specific dataset. I'll check and close it if that is the case.

**Comment by sloosvel** [comment]
So it is indeed a bug, but the implementation in the first commit was not quite right. This should do it.

**Review by valeriupredoi — APPROVED** [review]
nice one, cheers @sloosvel

**Comment by valeriupredoi** [comment]
> So it is indeed a bug, but the implementation in the first commit was not quite right. This should do it.

If this is a bug generalized to all datasets, then it's good to go :+1:

**Comment by sloosvel** [comment]
@jvegasbsc we need this for some obs data! And @valeriupredoi thinks it's good to go.

**Pull request merged**
