### PR TITLE
Use new conda environment for installing ESMValCore in Docker containers

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

Create a new conda environment to install ESMValCore in the docker containers, because updating the default conda environment leads to outdated dependencies as described in https://github.com/ESMValGroup/ESMValTool/issues/1980

-   Related to https://github.com/ESMValGroup/ESMValTool/issues/1980

***

## Before you get started

-   [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [x] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [x] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@bouweandela why is the test failing with "couldn't find esmvaltool environment"?

**Comment by bouweandela** [comment]
Because I forgot to rebuild the `esmvalgroup/esmvalcore:development` container. Building and uploading now...

**Comment by valeriupredoi** [comment]
you

> Because I forgot to rebuild the `esmvalgroup/esmvalcore:development` container. Building and uploading now...

3dc0a42e5e62bdbee40be3cd1b77f3d4

**Comment by bouweandela** [comment]
All fixed now

**Review by valeriupredoi — APPROVED** [review]
container has been found, tests have passed, am a happy camper, cheers Bouwe!

**Pull request merged**
