### PR TITLE
Support for 2D through conversion to 1D ocean coordinates for area weights DRAFT

### LINKED ISSUE #380: iris.analysis.cartography.area_weights() not working with 2D ocean coordinates
**Problem**

`iris.analysis.cartography.area_weights` calls it a day when `cube.coord("latitude")` and/or `cube.coord("longitude")` are 2D

When using `_volume.volume_statistics()` `area_weights` need to be computed that crashes when passed in ocean data with 2D coords

Specialists like @ledm @zklaus @bjlittle should chip in here plese :beer:

### PR DESCRIPTION
**Pull request by valeriupredoi**
**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [ ] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [ ] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #380 

This is what I changed for `thetao` and `volcello` to work for CMIP6

### CODE REVIEW

**Comment by zklaus** [comment]
This is completely wrong and must be rejected. I'll explain a bit why below. 

Fortunately, it is also unnecessary: the information of the area is available in areacello. 

The reason why iris does not provide this information is that it is ~~really hard~~ impossible to calculate in general. It becomes merely really hard when you accept the simplication of connecting points with arcs of great-circles. In that case, triangulation of cells with triangles on the surface of a sphere is possible, as done by cdo. This is, however, not a good approximation for some of the most common model grids.

This would be a problem with ideal model data. In reality, the problem is larger. Take as a case study the orca grids as used by nemo. They have two poles that come to lie at the top row of the data after unwrapping of the grid. But to ensure computational continuity, the two top rows are repeated and prepended to the data, this time mirrored left to right. Consequently, taking the coordinates just from that row for all rows is not merely dramatically wrong (as it would be if you took the, say, tenth row) but really in completely unrelated areas of the world.

**Comment by zklaus** [comment]
@valeriupredoi I see that you already had doubts. Good intuition :D

**Comment by valeriupredoi** [comment]
very cool expose @zklaus (if you read the issue text you will have seen I have serious doubts about this implementation too!)

But the question still stands - how can one compute area weights for ocean vars (as required by a certain preprocessor func) in the absence of `areacello`?

**Comment by valeriupredoi** [comment]
> @valeriupredoi I see that you already had doubts. Good intuition :D

indeed, my first PR that I really hate :grin:

**Comment by zklaus** [comment]
I would say one can not. This information is available for all modelers and there is no reason they couldn't provide it.

I personally would leave it at that.

Having said that, one alternative is the abovementioned triangulation. The area of triangles composed of great-circle arcs is well known and while not correct, particularly for large quadrilaterals, it at least will be an approximation. It is not trivial though because it has to take into account bounds and singly, doubly, and triply degenerate cells.

**Comment by valeriupredoi** [comment]
OKay cheers a mil @zklaus - let's do it this way then: I will reject my own PR but leave the issue #380 open since this is something myself and @ledm have just hit in our quest for obtaining IPCC Ar6 plots. The OHC diag for the said plots can not work w/o a certain implementation of some sort of 2D area weights (I ran it with this bad kludge). So @ledm will have to scratch his oceanic head to come up with a solution - I reckon those datasets do have `areacello`, no, Lee? In the meantime, I'll transfer your comments Klaus to the issue, they're pretty darn useful! :beer:

**Comment by zklaus** [comment]
Do that. I'll add a comment about areacello over there then.

**Comment by valeriupredoi** [comment]
closing since implementation is scientifically wrong

**Comment by ledm** [comment]
I think there is a problem though. Volume average needs to fail if the
volcello (or whatever the atmosphere version is) is not provided. We
can't expect ESMValTool to be able to calculate cell volume.

Unless the volume_statistic is a weightless sum, as this doesn't need
volume.

Please visit our new website at www.pml.ac.uk and follow us on Twitter @PlymouthMarine

We have updated our Privacy Notice which is available at http://www.pml.ac.uk/System-pages/Privacy_Notice

Plymouth Marine Laboratory (PML) is a company limited by guarantee registered in England & Wales, company number 4178503. Registered Charity No. 1091222. Registered Office: Prospect Place, The Hoe, Plymouth  PL1 3DH, UK. 

This message is private and confidential. If you have received this message in error, please notify the sender and remove it from your system. You are reminded that e-mail communications are not secure and may contain viruses; PML accepts no liability for any loss or damage which may be caused by viruses.

**Pull request closed without merging**
