### PR TITLE
Make _find_input_files public

### PR DESCRIPTION
**Pull request by znicholls**
## Description

Makes `_find_input_files` public. This is a super useful function and would be great if it was part of the 'public API' or at least well-documented and explicitly tested so that it can be used with confidence in other parts of the package (my particular interest is for #1572).

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] ~[☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do~

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by znicholls** [comment]
@sloosvel and @valeriupredoi it looks like you are the right ones to ask about this from my very basic git blame investigation. I just wanted to ask for your thoughts on a) the docstrings (suggestions of how to describe the `variable` argument would be super helpful) and b) how to test this, should I just basically copy `tests/integration/test_data_finder.py::test_get_input_filelist`, adapt for this slightly lower level function and then add other tests for my specific use cases?

**Comment by sloosvel** [comment]
I'm very sorry but I don't think I will be able to take a look at this right now, as I will be focusing on the PR that are open for the release!

**Comment by znicholls** [comment]
Totally fine, this should definitely wait until after the release

**Comment by bouweandela** [comment]
@znicholls I'm also trying to add a nicer version of this to the public API, but it's still work in progress: 1609.

**Comment by znicholls** [comment]
Super nice. Should I close this then? Fine by me but would be good to have
a rough expected timeline for #1609

**Comment by valeriupredoi** [comment]
@znicholls - cheers for this! Sorry for the radio silence, I just got back from holidays. I like the idea of making this public and importable/usable in the API - but I think we should have this integrated in a broader functionality e.g. a `dry-run` that tells the user how/where files are found, and if the files that are found are sufficient for a run etc, also optionally to have CMOR checks done on the data found, and logging issues found from there. By all means, this is a good start for that but I'd like to hear what @bouweandela thinks wrt #1609 before I come back here with more that thoughts&prayers :grin:

**Comment by znicholls** [comment]
@valeriupredoi all good, let's wait and see where #1609 lands before coming back to this. The dry run idea sounds awesome!

**Comment by znicholls** [comment]
(Feel free to close if you don't like having draft PRs floating around)

**Comment by valeriupredoi** [comment]
can help! Test fixing and/or reviewing, lemme know :beer:

**Comment by bouweandela** [comment]
#1609 grew into a very big change, so I'm breaking it up into smaller bits. Here is a pull request that adds the data finder functions to the public API: #1835

**Comment by bouweandela** [comment]
This is now available as the function [`esmvalcore.local.find_files`](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.local.html).

**Pull request closed without merging**
