### PR TITLE
Message for users when they use esmvaltool executable from esmvalcore only

### LINKED ISSUE #1729: Add relevant and parsable `--help` messages to sub-commands
This goes hand in hand with the issue that command line args are not checked and are ingested with silent defaulting - this one is about sub-commands like e.g. `esmvaltool data format`:
```bash
(netcdf4) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValTool$ esmvaltool data format
ERROR: Could not consume arg: data
Usage: esmvaltool <group|command>
  available groups:      config | recipes
  available commands:    run | version

For detailed information on this command, run:
  esmvaltool --help
(netcdf4) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValTool$ vim ~/merra_stuff/merra_command 
(netcdf4) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValTool$ esmvaltool data format
ERROR: Could not consume arg: data
Usage: esmvaltool <group|command>
  available groups:      config | recipes
  available commands:    run | version

For detailed information on this command, run:
  esmvaltool --help
(netcdf4) valeriu@valeriu-PORTEGE-Z30-C:~/ESMValTool$ esmvaltool data --help
[main help appears]
```

I reckon we should pipe relevant `--help` on-screen messages if one tries `esmvaltool data --help` or `esmvaltool data format --help` etc. just as we have for `esmvaltool run --help`.

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

I opened #1729 like a massive doofus not realizing that that env I was using contained an install of only esmvalcore - so I added a message to the main fire starter when no other entry point utility is available.

Closes #1729 

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
Nice idea to add this @valeriupredoi! I'm not 100% convinced about the location where the message is printed though. Wouldn't it be more clear to add this message to the `esmvaltool recipes` subcommand because that's where you might notice that there are no recipes listed? And to the `esmvaltool run` subcommand, add a message if the recipe is not found?

**Comment by valeriupredoi** [comment]
> Nice idea to add this @valeriupredoi! I'm not 100% convinced about the location where the message is printed though. Wouldn't it be more clear to add this message to the `esmvaltool recipes` subcommand because that's where you might notice that there are no recipes listed? And to the `esmvaltool run` subcommand, add a message if the recipe is not found?

that is a very good idea @bouweandela - lemme do it that way then! :beer:

**Review by bouweandela — APPROVED** [review]

**Comment by valeriupredoi** [comment]
@bouweandela great many thanks! @ESMValGroup/technical-lead-development-team can one of you eggheads please have a last looksee and merge, :beer:

**Comment by valeriupredoi** [comment]
@schlunma tit for tat - can you merge this pls :grin:

**Pull request merged**
