### PR TITLE
Add height for sfcWindmax in MPI HighRes models

### PR DESCRIPTION
**Pull request by malininae**
Following #2291 here's the fix for the missing coordinates for the sfcWindmax variable in MPI-ESM1-2-HR and MPI-ESM1-2-XR.

### CODE REVIEW

**Comment by Karen-A-Garcia** [comment]
Looks good from what I see :)

**Review by valeriupredoi — APPROVED** [review]
hey Liza, happy new year! Thanks a bunch for this - am approving, but I'd be very grateful if you added a couple tests for those fixes, please :beer:

**Comment by malininae** [comment]
> hey Liza, happy new year! Thanks a bunch for this - am approving, but I'd be very grateful if you added a couple tests for those fixes, please 🍺

Oops, sorry! Based on the other examples, I thought the ones which are re-using a class don't need tests. Will make tests in the next weeks!

**Comment by valeriupredoi** [comment]
ow I missed that those were re-used classes, my bad - no need then, those are tested already :+1: :beer:

**Pull request merged**
