### PR TITLE
Remove outdated cmor_table facet from data finder tests

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

This removes the `cmor_table` facet from the esmvalcore/_data_finder.py tests. A long time ago, the CMOR table could be different from the project. This is no longer the case, so it can be removed.

This also adds `hist` to the list of ignored spelling mistakes, because that raised incorrect warnigns with the pre-commit hook for codespell while trying to commit this change.

Part of #1609

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by valeriupredoi** [comment]
> the CMOR table could be different from the project

it still is, I don't understand this - CMIP5 CMOR tables are totally different from CMIP6 CMOR tables, it's just that the handling is done better on our side

**Comment by bouweandela** [comment]
Yes, they are function arguments to preprocessor functions

**Comment by sloosvel** [comment]
>A long time ago, the CMOR table could be different from the project. This is no longer the case, so it can be removed.

What do you mean by that? For convenience, internally we have a project that has a certain name but that follows a version of the CMIP6 tables. These changes only affect the tests, but is any further work going to affect the ability of having custom named projects that may follow tables that don't have the same name?

**Comment by bouweandela** [comment]
>> A long time ago, the CMOR table could be different from the project. This is no longer the case, so it can be removed.
>
> What do you mean by that? 

I mean that the `cmor_table` facet is not used anywhere in the code. All uses of it were removed in #358, but even then it was already the same as the `project` facet for quite some time. When we were just writing version 2, you could specify `{project: OBS, cmor_table: CMIP5}`, you could dig into the git history if you want to know more..

> is any further work going to affect the ability of having custom named projects that may follow tables that don't have the same name?

No. I need to make some changes to esmvalcore/_data_finder.py in #1609 to support wildcard searches, that's why I was looking at the tests and noticed this bit of ancient history and decided to remove it.

**Comment by sloosvel** [comment]
Great, thanks! I will merge now

**Pull request merged**
