### PR TITLE
Fix issue where data was not loaded and saved

### LINKED ISSUE #1962: Missing preprocessed OBS data when running `recipe_bock20jgr_fig_1-4`
**Describe the bug**
In https://github.com/ESMValGroup/ESMValTool/issues/3076, it was noticed that `recipe_bock20jgr_fig_1-4` fails because
`preproc/fig_1_cmip3/tas/OBS_HadCRUT4_ground_1_Amon_tas_1850-2017.nc not found or not a supported format`. The preprocessed data is actually not saved (fully preprocessed?). This error can also be reproduced with the `fig_1_cmip5` and `fig_1_cmip6` diagnostics, so it does not seem to be related to CMIP3 standards. 

@bouweandela and @schlunma would you have an idea what could go wrong in this run?  

**Please attach**
  - The recipe that you are trying to run: https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/bock20jgr/recipe_bock20jgr_fig_1-4.yml
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory: see https://esmvaltool.dkrz.de/shared/esmvaltool/v2.8.0rc1/recipe_bock20jgr_fig_1-4_20230306_210159/run/main_log_debug.txt

Attention: @LisaBock

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

This fixes an issue where data was not loaded and saved if no preprocessing was needed for that particular dataset, but it was part of a variable that also had other datasets that did need preprocessing. For example: a preprocessor

```yaml
    regrid:
      target_grid: CanESM2
      scheme: linear
    multi_model_statistics:
      span: full
      statistics: [mean]
      exclude: [CanESM2]
```
with datasets `CanESM2` and at least one other dataset.

This bug was introduced in #1609 and was not part of a release.

Closes #1962

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
@remi-kazeroni This works, but I'd like to add another test. I'm not working today, so if you're in a hurry you can merge this if it solves your issue and then I'll open another pull request next week to add the extra test.

**Comment by remi-kazeroni** [comment]
@bouweandela thanks for providing the fix. It's totally fine for me to wait that you add the test before this. I'll do a bit of recipe testing early next week. My plan would be to release rc2 towards the end of next week. Would be great to have this PR in there 👍

**Review by remi-kazeroni — APPROVED** [review]
Thanks @bouweandela! This looks good to me. I've several recipes including the 2 that were failing prior to this PR and all works fine now 👍 

@ESMValGroup/technical-lead-development-team could someone have a final look and merge, please?

**Comment by schlunma** [comment]
Awesome, thanks @bouweandela and @remi-kazeroni :rocket:

**Pull request merged**
