### PR TITLE
Pinned iris<3.2.0

### PR DESCRIPTION
**Pull request by schlunma**
## Description

Pin `iris>=3.1.0,<3.2.0`. See discussion in https://github.com/ESMValGroup/ESMValCore/issues/1509.

Closes https://github.com/ESMValGroup/ESMValCore/issues/1509

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
gut. Rolling out rc5 I guess :beer:

**Comment by schlunma** [comment]
Will merge this later today!

> Rolling out rc5 I guess :beer: 

Do we really need an rc5? The iris version we use didn't change compared to rc4. If we do an rc5 it will probably be identical to the final release since we probably won't change anything else. Given the state of https://github.com/ESMValGroup/ESMValTool/issues/2535 (111 out of 121 successful recipes) I propose to do the final release later this week :tada:

**Comment by valeriupredoi** [comment]
sounds like a solid plan to me, Manu! :beer:

**Comment by zklaus** [comment]
I have no problem either way. However, two remarks:

- I read somewhere that @remi-kazeroni did the last tests with a development version of the core due to a fix. Can't find it now though, so perhaps I am mixing things up.
- In general, the last rc is expected to be identical to the release.

**Comment by schlunma** [comment]
>     * In general, the last rc is expected to be identical to the release.

Sounds good. Then I will do an rc5 tomorrow :+1:

**Pull request merged**
