### PR TITLE
Add max, min and std operators to multimodel

### LINKED ISSUE #563: multi model statistics -- more statistics
@jvegasbsc How about adding standard deviation, min and max to the pool of available multi model statistics? It would be rather easy to implement. 
It would be nice to also have np.percentile in the mix, though this would require reforming the masked values to nans (numpy.nanpercentile), so idk if that's userful.

### PR DESCRIPTION
**Pull request by jvegasbsc**
Added several operators to the multimodel, as requested by @mwjury 

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *
Closes #563

### CODE REVIEW

**Comment by jvegasbsc** [comment]
If we add a comment about it, we should do it for every operator. All are local

**Comment by valeriupredoi** [comment]
yeah I think we should say that, lemme add it to the doc

**Comment by mattiarighi** [comment]
I have some installation issues at the moment (see #535) and cannot test.

**Comment by bouweandela** [comment]
@mattiarighi Did you manage to solve your installation issues?

**Comment by mattiarighi** [comment]
Yes, sorry for being absent lately, I'm very busy with other projects.
I'll try to test this and the other PRs this week.

**Comment by mattiarighi** [comment]
Seems to work as expected, thanks for adding this feature!

**Pull request merged**
