### PR TITLE
Add lazy 'engine' for multicube statistics

### PR DESCRIPTION
**Pull request by Peter9192**
## Description
This PR adds an alternative function for computing statistics across cubes. It relies on existing Iris functionality to concatenate cubes along a new auxiliary dimension, and then calculate the statistics across that new dimension. 

This function supports lazy evaluation. It is also less error prone since much of the work is passed on to Iris. It is less flexible when the input cubes are not homogeneous. Therefore, it cannot immediately replace the existing function. However, it is very well suited for the ensemble statistics function we are developing in #673. Anticipating #744 and follow-up actions in #781, we can gradually work towards this 'engine' for multi-model statistics as well. 

- Follows up on #949 
- Related to #781 
- Related to #673

***

## Before you get started

-   [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [x] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [x] N/A YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [x] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   [x] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:

-   [x] N/A Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Comment by Peter9192** [comment]
@stefsmeets I think it would be good if we could add some regressions tests for this function. Do you agree, and could you help me with that?

**Comment by stefsmeets** [comment]
> 
> 
> @stefsmeets I think it would be good if we could add some regressions tests for this function. Do you agree, and could you help me with that?

Might as well give this the same treatment as the other 'engine' :-)

**Comment by Peter9192** [comment]
The latest commit includes tests to check whether the new engine actually works for the sample data. This is not (yet) expected, and therefore the tests are implemented with the `xfail` mark. 

The tests fail because the cell_methods and coordinates (time and air_pressure) differ. The coord differences are mostly due to inconsistent attributes, but there are also a few inconsistencies in coordinates themselves.

I've played a bit with the iris development version, and it seems that the cell_methods and attribute errors will be solved by the new [lenient cube arithmetics](https://scitools-iris.readthedocs.io/en/latest/further_topics/lenient_maths.html) in iris3.

With respect to the error on mismatching coordinates, I'd like to keep those, for we are planning to make the time coordinates consistent in #744 and if some of the other coordinates are unexpectedly different, then I'd like to be notified about that. 

I've made an issue as to why the tests are not failing for the inconsistent plev with the 'normal' engine (#956).

**Comment by Peter9192** [comment]
PS tests are failing due to numpy not present !?

**Comment by stefsmeets** [comment]
> PS tests are failing due to numpy not present !?

I had the same. I think it is related to #951. Merging master should fix it.

**Comment by valeriupredoi** [comment]
cheers @Peter9192 !OK am seeing this fully includes https://github.com/ESMValGroup/ESMValCore/pull/949 so let's finalize that one first before revieweing this one, I've added a couple comments there :+1:

**Comment by Peter9192** [comment]
Abondoning this PR in favour of #968

**Pull request closed without merging**
