### PR TITLE
Landvariables

### PR DESCRIPTION
**Pull request by bascrezee**
Variable additions related to the following PRs: 

https://github.com/ESMValGroup/ESMValTool/pull/1200

https://github.com/ESMValGroup/ESMValTool/pull/1186

### CODE REVIEW

**Comment by jvegasbsc** [comment]
One question: the new definitions are not accompanied of new derivations? This is usually the case with observations.

Anyway, for me is ok to merge

**Comment by mattiarighi** [comment]
> One question: the new definitions are not accompanied of new derivations? This is usually the case with observations.

Should be [here](https://github.com/ESMValGroup/ESMValTool/pull/1186/files)

**Comment by jvegasbsc** [comment]
> Should be here

I was thinking about derived variables, not the cmorization of the observations.

**Comment by bascrezee** [comment]
> One question: the new definitions are not accompanied of new derivations? This is usually the case with observations.

[...]

> I was thinking about derived variables, not the cmorization of the observations.

No, these variables are not accompanied by any derivations at the moment.

**Comment by jvegasbsc** [comment]
OK. We can merge now

**Pull request merged**
