### PR TITLE
Documentation on how to use HPC central installations

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Suggested by @bouweandela - to be lifted from #1164 and dropped into a new stand-alone PR :+1: see https://github.com/ESMValGroup/ESMValCore/pull/1164#discussion_r765671097

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
Are you sure you want to duplicate the instructions instead of linking them? That will mean maintaining two copies of the same instructions.

**Comment by valeriupredoi** [comment]
it'd be nice to have something written rather than a pointer to another section, you reckon we should add the link as well? I am impartial about it, I just think it's nice to have something for those that only want to use Core, and not be thinking they'd need to use the whole Tool, what you reckon?

**Comment by bouweandela** [comment]
But the link was already there right? Anyway, I do not have a particularly strong opinion either

**Comment by valeriupredoi** [comment]
ya the link was there, I re-added it coz I intially took it out. Let's just get it in, it's not killing any polar bears :polar_bear:

**Review by bouweandela — APPROVED** [review]

**Comment by valeriupredoi** [comment]
cheers @bouweandela :polar_bear:

**Comment by remi-kazeroni** [comment]
Thanks V. I think it's worth mentioning that one could use esmvalcore on Mistral and Jasmin by doing `module load esmvaltool`. There is no proper esmvalcore module on Mistral (don't know about Jasmin). But for consistency with the rest of the page describing various ways to install esmvalcore, I guess I'd written "CEDA-JASMIN: esmvalcore is available...", just my 2 cents.

**Pull request merged**
