### PR TITLE
Added ocean fixes

### PR DESCRIPTION
**Pull request by ledm**
## A series of ocean fixes I've cobbled together in a rush

A lot of times, I'm the first person to look at a specific marine BGC dataset using ESMValTool. Unfortunately, with project deadlines looming, I've been so far unable to document all the problems I've encountered - it's almost every model! I don't want my changes to be lost, so I've set up this branch & PR. 

Please don't be angry with me, I really am trying to contribute! Better a sloppy PR than unfixed datasets!

Closes #issue_number

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by zklaus** [comment]
Please note that you can absolutely have a branch without a PR.

Is a sloppy PR better than unfixed datasets? Well, do the datasets stop being unfixed thanks to a sloppy PR? To me, this seems not to be the case. Indeed, it rather seems that they stay unfixed for longer, since the person having the "sloppy" PR has removed their pain without providing relief for anybody else. At the same time, other people coming across the same issue might see the existing work and (quite reasonably) conclude that the best way forward is to just wait until the work is finished. If this is then followed up by long periods of lingering, the issue very well might never be resolved.

The best thing, undoubtedly is to just finish some PRs sometimes.

**Comment by tomaslovato** [comment]
I just found this PR while looking for potential contributions and I realized that it partly overlaps with the open I just opened today #1566 ...
I think that can take care of including #1566  changes proposed in here by @ledm and try to close both ... 
what do you think @zklaus ?

**Comment by zklaus** [comment]
Thanks, @tomaslovato, that sounds good. Do move ahead with #1566 and take inspiration or code from here as needed.

**Comment by zklaus** [comment]
This has been addressed in #1566. Thanks, @tomaslovato.

**Pull request closed without merging**
