### PR TITLE
add newer Python versions in OSX to Github Actions

### PR DESCRIPTION
**Pull request by bvreede**
To make sure that recently fixed tests (and other issues) are run on OSX as well as Linux, newer versions of Python (3.8 and 3.9) are added to Github Actions.

Follows up on #1003

**NB: the Anaconda Publish action fails, which it does on Master too, [e.g.](https://github.com/ESMValGroup/ESMValCore/runs/2013956597?check_suite_focus=true) @ESMValGroup/esmvaltool-coreteam**

***

## Before you get started

-   [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [x] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Labels are assigned so they can be used in the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [ ] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   [ ] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:

-   [ ] Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
> NB: the Anaconda Publish action fails, which it does on Master too, e.g. @ESMValGroup/esmvaltool-coreteam

Reported it in #1036

**Review by valeriupredoi — CHANGES_REQUESTED** [review]
nice work @bvreede - could you please first test all the additional actions (for 3.9) in a test branch - like the ga_test one you've already added, then post the pass/fails here, and if all passes fine, remove that test branch from the triggers' list and then I will approve and it'll be ready to go. Sorry, am requesting changes now only for this technicality, the changes look perfect! :beer:

**Comment by bvreede** [comment]
Thanks very much @valeriupredoi! We did that already, if I understand you correctly. I just added the current branch as a trigger in the relevant actions, is that what you mean? In any case, the [actions were run on this branch](https://github.com/ESMValGroup/ESMValCore/actions) (though I see now that the last time this was done, the tests failed on Python OSX 3.7 — not one we added, and tests have been off and on failing on random systems, it must be the weather. Still, will double check).

I removed it in all but one (relevant) action [here](https://github.com/ESMValGroup/ESMValCore/pull/1035/commits/5143c7f0a73ac2c311b10c0b0b3fc4a02a34d66a).

All actions passed, except Anaconda Publish, as mentioned. I'm waiting for that one to function again on master before I confirm that this branch does not add failures (hence the draft status of this PR ;))

**Comment by valeriupredoi** [comment]
cheers @bvreede - good stuff! You can filter the actions on branch name - here the results filtered only on `ga_osx` https://github.com/ESMValGroup/ESMValCore/actions?query=branch%3Aga_osx (verbose link) which I should have looked at myself before asking you to instate such a test branch. Cool! They run fine - bar the segfault which is common and the circular import issue preventing conda build tests to pass (which I fixed in the other PR). Now, could you pls remove the `ga_osx` from the workflow files and after that we're good to go! Cheers :beer:

**Review by valeriupredoi — APPROVED** [review]

**Comment by bvreede** [comment]
OK done — perhaps best to merge this now & I'll keep a close eye on the Anaconda Publish action.

**Comment by valeriupredoi** [comment]
excellent work @bvreede cheers muchly! :beer:

**Pull request merged**
