### PR TITLE
remove duplicate implicit_optional = True line in setup.cfg

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Description

Thanks @zklaus for noticing this :beer: 

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by zklaus — APPROVED** [review]
I see we are keeping the reverse alphabetical ordering.

**Comment by valeriupredoi** [comment]
agh! @bouweandela how do you shut up cov - the line's complaining about is ye olde, and saw that in your PR that just got merged too, but thought it'd keep quiet after merge

**Comment by valeriupredoi** [comment]
> I see we are keeping the reverse alphabetical ordering.

that good or bad? :grin:

**Comment by bouweandela** [comment]
Alphabetical is nicer, but let's get this merged. I have no idea what codecov is thinking here..

**Comment by valeriupredoi** [comment]
I thought you were the cov whisperer Bouwe :laughing:

**Comment by bouweandela** [comment]
Thinking about it: the coverage change from #1769 is probably getting picked up because no coverage report was uploaded when that was merged into main because the tests failed on CircleCI.

**Comment by valeriupredoi** [comment]
bingo :bulb: That's it, man!

**Pull request merged**
