### PR TITLE
Dataset fixes for: ACCESS-ESM1-5, CanESM5, CanESM5 for carbon cycle

### LINKED ISSUE #946: Dataset problems: ACCESS-ESM1-5 air pressure coordinates rounding problem, CanESM5 & CanESM5-CanOE wrong units for co2, gpp incorrectly masked
**Describe the dataset issue**
**ACCESS-ESM1-5**:
Air pressure coordinates for zg and hus in esm-hist are rounded differently, leading to an error when trying to derive xco2 which uses both of these, as well as co2, which has the correct levels in the same version (20191128).
`ValueError: This operation cannot be performed as there are differing coordinates (air_pressure) remaining which cannot be ignored.
`
Also given by a warning for both variables:
```
WARNING There were warnings in variable hus/zg:
plev: does not contain 100000.0 Pa
 plev: does not contain 92500.0 Pa
 plev: does not contain 85000.0 Pa
 plev: does not contain 70000.0 Pa
 plev: does not contain 60000.0 Pa
 plev: does not contain 50000.0 Pa
 plev: does not contain 40000.0 Pa
 plev: does not contain 30000.0 Pa
 plev: does not contain 25000.0 Pa
 plev: does not contain 20000.0 Pa
 plev: does not contain 15000.0 Pa
 plev: does not contain 10000.0 Pa
 plev: does not contain 7000.0 Pa
 plev: does not contain 5000.0 Pa
 plev: does not contain 3000.0 Pa
 plev: does not contain 2000.0 Pa
 plev: does not contain 1000.0 Pa
 plev: does not contain 500.0 Pa
 plev: does not contain 100.0 Pa
```
Actual values in files:
```
 plev = 100000.00000001, 92500.00000001, 85000.00000001, 70000.00000001, 
    60000.00000001, 50000.00000001, 40000.00000001, 30000.00000001, 
    25000.00000001, 20000.00000001, 15000.00000001, 10000.00000001, 
    7000.00000001, 5000.00000001, 3000.00000001, 2000.00000001, 
    1000.00000001, 500.00000001, 100.00000001 ;
```

Files on mistral: 
e.g.
/work/ik1017/CMIP6/data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/esm-hist/r1i1p1f1/Amon/zg/gn/v20191128/zg_Amon_ACCESS-ESM1-5_esm-hist_r1i1p1f1_gn_185001-194912.nc
/work/ik1017/CMIP6/data/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/esm-hist/r1i1p1f1/Amon/hus/gn/v20191128/hus_Amon_ACCESS-ESM1-5_esm-hist_r1i1p1f1_gn_185001-194912.nc

- Full dataset description (fill out as many as you know, please):
  - project: CMIP6 
  - dataset: ACCESS-ESM1-5
  - experiment: esm-hist
  - realization: r1i1p1f1
  - mip: Amon
  - grid: gn
  - data version: v20191128
  - variable used: zg, hus, co2

Note: ps also has the weirdly rounded plev coordinates, but no warning form the ESMValTool and for me it works.

**Can-ESM5/CanESM5-CanOE**
CO2: wrong units, in CMIP6 the units [1] is expected, while they're giving it in ppmv, so data needs to be multiplied by a factor of 1e-6 - **Caveat:** Even though it's the same version as available data, co2 is not on mistral, but available on the ESGF download page and no known errata on ES-DOC.
Gpp: It's a carbon flux on LAND, but has ocean values set to 0 instead of masked, resulting in wrong averages

Files on mistral: 
/work/ik1017/CMIP6/data/CMIP6/CMIP/CCCma/CanESM5/esm-hist/r1i1p1f1/Lmon/gpp/gn/v20190429/gpp_Lmon_CanESM5_esm-hist_r1i1p1f1_gn_185001-201412.nc
/work/ik1017/CMIP6/data/CMIP6/CMIP/CCCma/CanESM5-CanOE/historical/r1i1p2f1/Lmon/gpp/gn/v20190429/gpp_Lmon_CanESM5-CanOE_historical_r1i1p2f1_gn_185001-201412.nc

- Full dataset description (fill out as many as you know, please):
  - project: CMIP6 
  - dataset: CanESM5 / CanOE
  - experiment: esm-hist/historical
  - mip: Amon / Lmon for gpp
  - grid: gn
  - data version: v20190429
  - variable used: co2, gpp

**Assign the right people**
If you are already a member of the ESMValTool GitHub project, please assign Valeriu Predoi (valeriupredoi) and
Klaus Zimmermann (zklaus) to the issue. They will then check the issue raised and propagate it further to the
data model developers.

Cheers :beer:
Pull request:  #947

### PR DESCRIPTION
**Pull request by bettina-gier**
Fixes for datasets used for https://github.com/ESMValGroup/ESMValTool/pull/1914, with gpp bonus as I had them in the same file ;)

-   Closes #946 

***

## Before you get started

-   [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   [x] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   [x] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [x] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   [x] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [ ] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   [x] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

P.S.: Didn't write tests for the fixes as I'm unsure how to - pointers welcome ;)

### CODE REVIEW

**Comment by sloosvel** [comment]
Since the fixes for the CanESM models are the same, maybe they could be imported between models? It's how it's being done in [cesm2-waccm fixes](https://github.com/ESMValGroup/ESMValCore/blob/master/esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py) or in [mpi_esm1_2_xr.py](https://github.com/ESMValGroup/ESMValCore/blob/master/esmvalcore/cmor/_fixes/cmip6/mpi_esm1_2_xr.py). Just to avoid duplicating them.

**Comment by bettina-gier** [comment]
Good call, done!

**Comment by sloosvel** [comment]
There seem to be some codacy errors in the docstrings, but other than that the fixes work well! I couldn't find data for co2 in CanESM5-CanOE but all the others do what they claim to do.

**Comment by bettina-gier** [comment]
I actually don't understand the remaining codacy errors, as there are blank lines and the arguments are described in the docstring, analogous to already existing fixes. (Or I'm just blind)

**Comment by sloosvel** [comment]
I don't see it either. The docstrings look all the same to me, yet some fail and some do not.

**Review by sloosvel — APPROVED** [review]

**Comment by bettina-gier** [comment]
Can we merge this?
Commit failing is not due to this code, and the codacy errors seem nonsensical.

**Review by schlunma — APPROVED** [review]
Code looks fine, fixed data also looks fine :+1:

**Pull request merged**
