### PR TITLE
switched miniconda conda setup hooks for Github Actions workflows

### PR DESCRIPTION
**Pull request by valeriupredoi**
implement solution from #867

### CODE REVIEW

**Comment by nielsdrost** [comment]
@valeriupredoi changes look good to me. I guess we will only know the result when we merge, right?

**Comment by valeriupredoi** [comment]
not just then, I tested with the test branch see eg https://github.com/ESMValGroup/ESMValCore/actions/runs/374464387 - that'll apply to the ESMValTool PR as well :+1:

**Comment by nielsdrost** [comment]
Ok, nice! Perhaps next time do the work on the github-actions2 branch and PR from that to master? Now this branch and the one you tested with seem not to be completely the same.

**Review by nielsdrost — APPROVED** [review]
Thanks @valeriupredoi!

**Comment by valeriupredoi** [comment]
yipers, that branch has a conda build test that we actually have a PR for, apart from that they should identical. Cheers for the review @nielsdrost dude :beer:

**Comment by nielsdrost** [comment]
> yipers, that branch has a conda build test that we actually have a PR for, apart from that they should identical. Cheers for the review @nielsdrost dude

Ah, I see! Is that https://github.com/ESMValGroup/ESMValCore/pull/818? that's yet another branch, right?

**Pull request merged**
