### PR TITLE
Replace os.walk by glob.glob in data finder (only look for data in the specified locations)

### LINKED ISSUE #281: Remove os.walk from datafinder
We are currently use to find data files python`os.walk` function. This means that we search recursively on all folders inside the path constructed from the drs.

I have experimented some problems because of it:

- Defined correctly the rootpath in JASMIN and forgetting to setup the drs led to search in all CMIP5/6 data, meaning that ESMValTool takes ages to fail.

- Experimented some problems in our internal storage when somebody (bad practice, I now) created a nested folder with interpolated data

I don't know if anybody is using the recursivity of `os.walk` to organize its data, but if it is not the case I think we should remove it and replace it with `glob.glob` (sorry @valeriupredoi )

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

With this change, the tool will no longer recursively look into all subdirectories for data. This speeds up finding data in certain cases and promotes a clean data organization.

Closes #281

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] ~Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)~
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by bouweandela** [comment]
- The documentation build on CircleCI is failing because the scipy documentation appears to be offline.
- I suspect the test run is failing because the docker containres have stopped building. We have been approved as members of the Docker Open Source Program, but maybe it takes some time for this to take effect. I have asked Docker about the status.

**Comment by bouweandela** [comment]
The test run was failing because scipy was missing from setup.py and the docker container for testing is a bit outdated.

**Review by jvegasbsc — APPROVED** [review]
Nice! This will avoid lots of trouble when configuring the tool.

**Review by jvegasbsc — CHANGES_REQUESTED** [review]
Tests are failing for me also, but I reckon that my environment is a bit outdated so I reconstructing it to test again.

I approved it earlier because I ran the ESMValTool instead of the ESMValCore tests locally 🤦

**Comment by bouweandela** [comment]
I'll have a look at the tests

**Review by jvegasbsc — APPROVED** [review]
OK. Can you explain why it failed, because I had no clue

**Comment by bouweandela** [comment]
It failed because the tests in tests/sample_data/experimental/test_run_recipe.py try to run a recipe using the sample data from https://github.com/ESMValGroup/ESMValTool_sample_data/, but `'drs'` config-user setting was not set up to use the correct path (it was just searching the entire directory structure for matching files, that's why it worked).

**Pull request merged**
