### PR TITLE
Fix failing CircleCI tests

### LINKED ISSUE #1166: Nightly tests on CircleCI are failing
The `install`, `develop`, and `conda_build` test [failed on CircleCI last night](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/4985/workflows/92577489-0597-4286-9bc7-3e6a0637ebbf). There appear to be two problems:
1) timeouts when creating the conda environment
2) Newer version of mypy with extra dependencies

### PR DESCRIPTION
**Pull request by bouweandela**
## Description

- Increase the timeout for running the `install`, `develop`, and `conda_build` test scenarios on CircleCI
- Add stub libraries required by mypy as development dependencies

Closes #1166 #1168

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by zklaus — APPROVED** [review]

**Comment by zklaus** [comment]
LGTM

**Comment by zklaus** [comment]
Actually going through the checklist, could you tick the boxes and assign a meaningful label? This is important for the changelog.

**Comment by valeriupredoi** [comment]
nice one @bouweandela - I was just pinning mypy as we speak. Also, for Pete's sake, read when you get tagged on GitHub, that avoids work duplication and faster solution delivery (yeah I sound corporate :grin: )

**Comment by valeriupredoi** [comment]
environment still solving very slowly, could you solve at all with the newly added dependencies?

**Comment by bouweandela** [comment]
Sorry for being slow, I'm simply not working enough days a week at the moment to keep up with people tagging me on GitHub. If you need me for anything urgent, just send me an email or Whatsapp.

> environment still solving very slowly, could you solve at all with the newly added dependencies?

Yes, they're only added to setup.py so there should be no change in conda. Not sure what is causing the sudden slow environment.

**Comment by valeriupredoi** [comment]
> Sorry for being slow, I'm simply not working enough days a week at the moment to keep up with people tagging me on GitHub. If you need me for anything urgent, just send me an email or Whatsapp.

nah, just being nagging, man :grin: 

If all fails, I had already tested pinning `mypy<0.900` :+1:

**Pull request merged**
