### PR TITLE
Adapted custom co2s table to match CMIP6 version

### PR DESCRIPTION
**Pull request by schlunma**
This PR fixes the custom `co2s` table to match its CMIP6 version as discussed in #587.

**Tasks**

-   [ ] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [x] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

### CODE REVIEW

**Comment by mattiarighi** [comment]
The tests are failing, but it looks like an internal circleci error.

**Comment by schlunma** [comment]
I think so too, can we restart the test somehow?

**Comment by mattiarighi** [comment]
There is a restart button, but I have no rights to trigger a restart.

**Comment by schlunma** [comment]
Tests are fine now

**Pull request merged**
