### PR TITLE
Add derivation of sea ice extent

### LINKED ISSUE #1693: Sea Ice Extent as a derived variable
**Is your feature request related to a problem? Please describe.**
The sea ice extent is computed by summing `areacello` over the points in which `siconc/sic` (sea_ice_area_fraction) has values > 15%.

It would be useful to be able to compute this quantity as a derived variable and reduce the amount of data that is stored after the preprocessing. The derivation could  return an array of ones, with masked values where the sea ice area fraction  has values < 15%.  This array could later be used in combination with `area_statistics(operator='sum')` in order to obtain the true sea ice extent, since areacello would be used as the weights to compute the weighted sum.

Units of the derived variable should be set to 'm2', since area_statistics does not handle very well the resulting units. 
In summary, with the addition of the derived variable, the sea ice extent could be computed at preprocessor level using a recipe such as:

```yaml
preprocessor:
  preproc:
    # extract_region / extract_shape (in order to obtain regional values)
    area_statistics:
      operator: 'sum'
   # extra time operations if needed
    convert_units:
      units: 10^6 km2 # the units we ultimately use

variables:
  siextent:
    derive: true
    preprocessor: preproc
  
```
Where the derivation would consist of:

```python
        siconc = cubes.extract_cube(Constraint(name='sea_ice_area_fraction'))
        ones = da.ones_like(siconc)
        siextent_data = da.ma.masked_where(siconc.lazy_data()<15, ones)
        siextent = siconc.copy(siextent_data)
        siextent.units = 'm2'
```

**Would you be able to help out?**
Yes

### PR DESCRIPTION
**Pull request by sloosvel**
## Description

This PR allows to compute the sea ice extent as a derived variable in order to reduce the amount of saved data during the preprocessing
Closes #1693 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
~- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available~
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
~- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by sloosvel** [comment]
Hi @dhohn , this is now ready to be reviewed. Do you think you could test the changes?

**Review by dhohn — APPROVED** [review]
Ive made a couple plots which look correct. I also tried a model (ACCESS) that provides both `siconc` and `siconca`, which also works.

**Comment by sloosvel** [comment]
Thanks @dhohn ! 

@ESMValGroup/technical-lead-development-team anyone with time to merge? I can do it if there are no further comments, but since we agreed ond having the merger be different than the reviewer I thought I would ask.

**Comment by bouweandela** [comment]
> anyone with time to merge? 

I would have been happy to do it. Maybe you could wait a bit longer next time, to give people an opportunity to respond to your question?

**Comment by sloosvel** [comment]
ups, will do! sorry

**Pull request merged**
