### PR TITLE
Updated esmf-related pins

### PR DESCRIPTION
**Pull request by schlunma**
## Description

With the new [release](https://github.com/SciTools-incubator/iris-esmf-regrid/releases/tag/v0.10.0) of iris-esmf-regrid we can update some pins in the environment.

See also https://github.com/SciTools-incubator/iris-esmf-regrid/pull/342#issuecomment-2092921514.

***

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
:ok_hand: :beer:

**Comment by valeriupredoi** [comment]
@schlunma I'd argue this would be nice to have in v2.11 if @chrisbillowsMO is not already too fed up with accepting any more bugfixes :beer:

**Comment by valeriupredoi** [comment]
OK we have a problem with the environment for Python 3.9 - they require Python >=3.10 so our envs don't solve https://github.com/ESMValGroup/ESMValCore/actions/runs/9350804150/job/25735049553 - we either retire support for Python 3.9 as per @bouweandela 's https://github.com/ESMValGroup/ESMValCore/issues/2406 now or we don't include this in the release and drop 3.9 the sooner the better - I am leaning towards *not* dropping 3.9 before the release (and hence, not including this in the release)

**Comment by ehogan** [comment]
> OK we have a problem with the environment for Python 3.9 - they require Python >=3.10 so our envs don't solve https://github.com/ESMValGroup/ESMValCore/actions/runs/9350804150/job/25735049553 - we either retire support for Python 3.9 as per @bouweandela 's #2406 now or we don't include this in the release and drop 3.9 the sooner the better - I am leaning towards _not_ dropping 3.9 before the release (and hence, not including this in the release)

Unfortunately, esmf-related pins were updated in ESMValTool via https://github.com/ESMValGroup/ESMValTool/pull/3643 already, which means it's not possible to solve an environment using the latest version of ESMValTool (on `main`) and the ESMValCore release branch, since ESMValTool has `esmpy >=8.6.0` and the ESMValCore release branch has esmpy `!=8.1.0,<8.6.0` 😮

So either we should just include this in the release, or I will need to create an ESMValTool release branch from the commit before https://github.com/ESMValGroup/ESMValTool/pull/3643 (from 3 weeks ago!) and cherry pick everything after that into the release branch 😭

What would be best? 🤔

**Comment by bouweandela** [comment]
How about you create the ESMValTool release branch from `main` and then revert the changes introduced in https://github.com/ESMValGroup/ESMValTool/pull/3643 only in the ESMValTool release branch?

**Comment by bouweandela** [comment]
That would resemble the conda environment that you did all the tests with best, right?

**Comment by valeriupredoi** [comment]
> How about you create the ESMValTool release branch from `main` and then revert the changes introduced in [ESMValGroup/ESMValTool#3643](https://github.com/ESMValGroup/ESMValTool/pull/3643) only in the ESMValTool release branch?

and make sure you don't include the pin in the conda package via `recipe.meta` :+1:

**Comment by schlunma** [comment]
If the change in iris-esmf-regrid is fully backwards-compatible, we could just relax the pin to `esmpy!=8.1.0`, but we still [don't know this yet](https://github.com/SciTools-incubator/iris-esmf-regrid/pull/342#issuecomment-2098438182) 🤷

**Comment by valeriupredoi** [comment]
> If the change in iris-esmf-regrid is fully backwards-compatible, we could just relax the pin to `esmpy!=8.1.0`, but we still [don't know this yet](https://github.com/SciTools-incubator/iris-esmf-regrid/pull/342#issuecomment-2098438182) 🤷

aha! Good catch, Manu! I asked the same q myself - I'd go along the "what's the worst it can happen" line, and stash the pin for now, hopefully they'll give us an answer, and by then NCL have had enough time to support the new ESMPy :crossed_fingers:

**Pull request merged**
