### PR TITLE
Pin `pytest-mypy` to less than 0.10.1

### LINKED ISSUE #1788: Tests failing left, right, and centre on Circle and Github Actions
The new pytest-mypy is causing phenomenal test fails - frankly I've no idea why, I can't understand the standards complaints, if anyone more literate in PEP can, please explain @ESMValGroup/technical-lead-development-team - this PR https://github.com/ESMValGroup/ESMValCore/pull/1787 uses the pin on pytest-mypy (at 0.10.0, 0.10.1 is causing the whole hubbub)

### PR DESCRIPTION
**Pull request by valeriupredoi**
See if it sorts out test issues (I'll edit this PR description if we decide to merge this)
**Edit:** it do

@schlunma makes a good case for this PR to be merged in https://github.com/ESMValGroup/ESMValCore/issues/1788#issuecomment-1310455428

Closes #1788

### CODE REVIEW

**Comment by valeriupredoi** [comment]
OK fellas @schlunma @bouweandela dis ready for a merge :hammer:

**Review by schlunma — APPROVED** [review]
Looks good to me!

Please also open an issue about unpinning mypy after merging https://github.com/ESMValGroup/ESMValCore/pull/1769 so that we don't forget this, this should only be a temporary solution.

@bouweandela please merge if you are happy with this procedure

**Comment by valeriupredoi** [comment]
great cheers Manu - this once merged we need to merge main in https://github.com/ESMValGroup/ESMValCore/pull/1786 which has suddenly become very important :+1:

**Review by zklaus — CHANGES_REQUESTED** [review]
Let's not pin this, and instead follow the guidance at https://github.com/hauntsaninja/no_implicit_optional (which is linked from the error message) and simply set `implicit_optional = True`.

**Comment by zklaus** [comment]
(Of course, better yet, fix our annotations following the same repo guidance, though that is marginally more effort.)

**Comment by bouweandela** [comment]
Thanks for thinking about the potential merge conflicts @schlunma! Let's follow the advice of @zklaus and then I will take care of fixing the affected type hints before the next relase.

**Comment by valeriupredoi** [comment]
OK so I close this then open an implicit ninja PR? :ninja:

**Comment by schlunma** [comment]
Or change it in this PR and change the title? :smile:

**Comment by valeriupredoi** [comment]
following advice from @zklaus I opened https://github.com/ESMValGroup/ESMValCore/pull/1790 and closing this shop

**Comment by valeriupredoi** [comment]
> Or change it in this PR and change the title? smile

naah, too much fuss - plus, it's good to have a cleaner closed PR than mess about with its history :+1:

**Pull request closed without merging**
