### PR TITLE
Fixes for AWI-ESM-1-1-LR (CMIP6, piControl)

### LINKED ISSUE #910: Dataset problem: AWI-ESM-1-1-LR wrong reference year
**Describe the dataset issue**
Many (perhaps all) variables in the `piControl` experiment and the `Amon` mip have the `parent_time_units` attribute set to `days since 0000-01-01 00:00:00`. The 0000 year is not allowed as reference year by `cf_units`.

- Data file has been changed by you in any way (if you answer yes the issue will be void and closed, we are not
supporting custom-made datasets that present problems, it is your resposability to fix those problems): no
- Project (CMIP5/CMIP6/OBS/obs4mips/etc): CMIP6
- Full dataset description (fill out as many as you know, please):
  - dataset: AWI-ESM-1-1-LR
  - experiment: piControl
  - mip: Amon
  - grid: gn
  - variable used: tas (but likely all)
  - data version: v20200212
- Problems encountered (please describe what the actual problems are: e.g. wrong standard name, issue with dimensions): `  
ValueError: zero not allowed as a reference year, does not exist in Julian or Gregorian calendars
`
- Pointer to existing copy of data on ESGF node (it would be very useful if you could provide a physical
fullpath to the file(s) that are causing the problem, e.g. on CEDA Jasmin or DKRZ):
/mnt/lustre02/work/ik1017/CMIP6/data/CMIP6/CMIP/AWI/AWI-ESM-1-1-LR/piControl/r1i1p1f1/Amon/tas/gn/v20200212/tas_Amon_AWI-ESM-1-1-LR_piControl_r1i1p1f1_gn_185501-185512.nc
- Other notes and mentions:  I will write a fix for that

**Assign the right people**
If you are already a member of the ESMValTool GitHub project, please assign Valeriu Predoi (valeriupredoi) and
Klaus Zimmermann (zklaus) to the issue. They will then check the issue raised and propagate it further to the
data model developers.

**Please attach**
  - The recipe that you are trying to run, you can find a copy in the `run` directory in the output directory
  - The `main_log_debug.txt` file, this can also be found in the `run` directory in the output directory
  - Attach a text file with the output of `ncdump -h /path/to/file.nc`

[recipe_test_caseAWI.yml.txt](https://github.com/ESMValGroup/ESMValCore/files/5709478/recipe_test_caseAWI.yml.txt)
[main_log_debug.txt](https://github.com/ESMValGroup/ESMValCore/files/5709479/main_log_debug.txt)

Cheers :beer:

### PR DESCRIPTION
**Pull request by remi-kazeroni**
Before you start, please read our [contribution guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html).

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #910

### CODE REVIEW

**Review by jvegasbsc — APPROVED** [review]
Nice work!

**Review by jvegasbsc — CHANGES_REQUESTED** [review]
Can you please fix the tests?

**Comment by remi-kazeroni** [comment]
> 
> 
> Can you please fix the tests?

Thanks for reviewing. The tests are now fixed.

**Comment by valeriupredoi** [comment]
nice one cheers @remi-kazeroni :beer: @jvegasbsc I am okay with merging this and including it in release even if there's an `AllVars` fix, do you agree?

**Review by valeriupredoi — APPROVED** [review]

**Review by jvegasbsc — APPROVED** [review]

**Pull request merged**
