### PR TITLE
Added warning and automatic fix for no bounds

### PR DESCRIPTION
**Pull request by jvegasbsc**
As discussed in #151

### CODE REVIEW

**Comment by bouweandela** [comment]
Can you please fix the merge conflict?

**Comment by jvegasbsc** [comment]
Done!

**Comment by mattiarighi** [comment]
I would suggest @nperezzanon to test it, since she reported the issue in #151.

**Comment by mattiarighi** [comment]
@nperezzanon can you please test this so it can be merged?

**Comment by bouweandela** [comment]
@mattiarighi Can you have a look at this please? Or maybe @axel-lauer can test, because this is a feature he requested?

**Comment by mattiarighi** [comment]
@axel-lauer any use case for testing this?

**Comment by zklaus** [comment]
Just got aware of this via @jhardenberg's mention in #470. Every time this is actually used it masks a serious data error. What's more, `guess_bounds` is unreliable and *will* lead to wrong bounds for example for staggered grids.

**Comment by jvegasbsc** [comment]
>  Every time this is actually used it masks a serious data error. What's more, guess_bounds is unreliable and will lead to wrong bounds for example for staggered grids.

I agree with you that this can lead to errors, but:

- In regular grids, `guess_bounds` is usually a sound approximation and it does not work in any other case

- We are adding a warning in any case, so users should be aware that something may be not totally correct

- Don't think too much about our computations in staggered grids: i.e we are using the same areacello for our computations on thetao, uo, and vo and we know that it should not be the same, at least for EC-Earth and other NEMO-based models

**Comment by zklaus** [comment]
* `guess_bounds` guesses that the points are in the middle of the cells. If the points are on the faces, edges, or corners of cells, as they can be in staggered, regular grids, it effectively shifts and/or distorts the cells.
* Nobody reads the warnings because you get an impenetrable wall of text
* I am not sure how that relates: In staggered grids the cells are the same also for points that live on faces, edges, and corners, consequently the cell areas *are* the same. Regardless, are you saying somebody is making an error without caring about it so nobody should care about it?

Regarding usability vs compliance, the case doesn't seem so clear. I absolutely think this can be fixed, so high usability from a user point of view, but imho really only on a case by case basis.

**Comment by bouweandela** [comment]
Maybe we can revisit this after #374 is merged, because then we could only apply the guess bounds when using reduced cmor check strictness?

**Pull request merged**
