### PR TITLE
add MO-paths to config file

### LINKED ISSUE #1708: Add Met Office-specific paths to the ESMValTool user configuration file
Add Met Office-specific paths to the ESMValTool user configuration file, e.g. like JASMIN.

### PR DESCRIPTION
**Pull request by mo-tgeddes**
## Description

Adds site-specific paths for the Met Office to the config-user.yml file.

Closes #1708 

Link to documentation:

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [x] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [x] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [x] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [x] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [x] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [x] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [x] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [x] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [x] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Review by ehogan — APPROVED** [review]
Thanks @mo-tgeddes! :)

I'm approving this as the `rootpath`s and `drs`s are correct, but I wonder whether the @ESMValGroup/technical-lead-development-team have an opinion on where the Met Office section should be located within the user configuration file; perhaps under DKRZ so that it matches the order described in the documentation [Pre-installed versions on HPC clusters / other servers](https://docs.esmvaltool.org/en/latest/quickstart/installation.html#pre-installed-versions-on-hpc-clusters-other-servers)?

**Comment by valeriupredoi** [comment]
hey guys, cheers for adding these! This needs a bit of documentation too, as I have explained in https://github.com/ESMValGroup/ESMValCore/issues/1708#issuecomment-1237988853 - could you please add that too?

**Comment by remi-kazeroni** [comment]
> hey guys, cheers for adding these! This needs a bit of documentation too, as I have explained in [#1708 (comment)](https://github.com/ESMValGroup/ESMValCore/issues/1708#issuecomment-1237988853) - could you please add that too?

The MetOffice machine was recently added to our docs in the [list of systems](https://docs.esmvaltool.org/en/latest/quickstart/installation.html#pre-installed-versions-on-hpc-clusters-other-servers) where we have a module, like at CEDA or DKRZ. Is it what you have in mind @valeriupredoi? I'm not so sure our doc should contain info on how to get an account on given machines. At least, I couldn't find that for CEDA and DKRZ. The closest we have is in the [Tutorial](https://esmvalgroup.github.io/ESMValTool_Tutorial/setup.html), I think.

**Comment by valeriupredoi** [comment]
@remi-kazeroni spot on, cheers! That's what I meant indeed, cool - no need to that anymore then. The question about getting access to the MO machine is a bit untouched upon, as it is for the other clusters, good point about including it or not - I would argue we should have at least a pointer to a page where access can be applied for - I believe we instruct the users how to get access to the OBS data on CEDA-JASMIN (via application for membership to the `esmeval` GWS) - where that's located, I can't remember :confused:

**Comment by remi-kazeroni** [comment]
> @remi-kazeroni spot on, cheers! That's what I meant indeed, cool - no need to add that anymore then. The question about getting access to the MO machine is a bit untouched upon, as it is for the other clusters, good point about including it or not - I would argue we should have at least a pointer to a page where access can be applied for

That's a good point @valeriupredoi! Shall we just add a link to this [tutorial setup page](https://esmvalgroup.github.io/ESMValTool_Tutorial/setup.html) that tells users how to get an account (CEDA, DKRZ for now), join compute/data projects, do ssh, use different filesystems, ... ? I feel that our documentation page on installing the Tool is already super long and it may not be good to overload it with details about some clusters.
 
> - I believe we instruct the users how to get access to the OBS data on CEDA-JASMIN (via application for membership to the `esmeval` GWS) - where that's located, I can't remember 😕

I think this never got merged for different reasons 😕 see https://github.com/ESMValGroup/ESMValTool/issues/1072

**Comment by valeriupredoi** [comment]
@remi-kazeroni that is a lovely little page (must admit, first time I see it :grin: ) in the tutorial, props to @SarahAlidoost and @rswamina :beer: Yes, that'd be nice if we added the MO stuff there, if they can be made public, that is.

We need to revive that and https://github.com/ESMValGroup/ESMValTool/pull/2385

**Comment by remi-kazeroni** [comment]
> > @remi-kazeroni that is a lovely little page (must admit, first time I see it 😁 ) in the tutorial, props to @SarahAlidoost and @rswamina 🍺 Yes, that'd be nice if we added the MO stuff there, if they can be made public, that is.
> > We need to revive that and [ESMValGroup/ESMValTool#2385](https://github.com/ESMValGroup/ESMValTool/pull/2385)
> 
> @valeriupredoi should I still add it in this PR? And sorry, I'm a little bit confused, where exactly in the documentation should I put it?

@mo-tgeddes, sorry for bringing up issues not directly relevant to this PR here. I have opened a separate issue for that in https://github.com/ESMValGroup/ESMValTool/issues/2793

I support the idea of ordering the machines based on what's done in the Docs (see [comment](https://github.com/ESMValGroup/ESMValCore/pull/1709#pullrequestreview-1092023423)). I believe this would be enough to merge the PR. Thanks for your work!

**Comment by zklaus** [comment]
As we add more and more machines, I think it's good to keep the order alphabetically. That way, everyone will find their way around. I think that also **is** the order in the documentation, so no disagreement, but that should be the guiding principle.

**Review by remi-kazeroni — APPROVED** [review]
Thanks @mo-tgeddes 👍  Since @ehogan already approved the data paths and the machines are organized in alphabetical order (see [comment](https://github.com/ESMValGroup/ESMValCore/pull/1709#issuecomment-1240700605)), this can be merged. I'll do that tomorrow evening if there are no further comments.

**Pull request merged**
