### PR TITLE
Update CORDEX CMOR tables with valid_max and valid_min

### LINKED ISSUE #1141: CORDEX CMOR tables missing valid_max and valid_min attributes, leading to incorrect preprocessor area operations
I recently developed a recipe involving a region extraction:
```
start_longitude: -5
end_longitude: 30
start_latitude: 42
end_latitude: 52
```
But, when i plotted the data, it was clear that the region extraction wasn't working correctly on the western boundary.
MicrosoftTeams-image

After a bunch of digging, I realised that the issue was that the longitude coord of the original data was defined in the range `[-180, 180]` and the CMOR checker / fixer was not correcting it to `[0, 360]`. The region extraction functions in the preprocessor all assume longitude lives in the range `[0, 360]`, and thus the cropping out of the points beyond 5W was not happening.
The reason for the CMOR checker not fixing the coord was because the default CMOR tables for CORDEX included with ESMValTool don't include the `valid_min` and `valid_max` attributes on the longitude coords, and so all the checks and fixes in https://github.com/ESMValGroup/ESMValCore/blob/b2f7ffc3232f174dd5ebc50ad20b4a02d3517c2c/esmvalcore/cmor/check.py#L617 were skipped.

I've created a branch with a fix for this (by updating the tables). See #1142 

Below is an example of a file from ESGF with the offending longitude data in question. It is not the only CORDEX model to have this issue though. Which does raise the worrying prospect that any recipes people have written to use CORDEX to do for example, area statistics in a region that has parts west of the meridian, have potentially the wrong results for some models with coordinates like this without realising. I only spotted the issue because I produced spatial maps of my data, if I had only been calculating area averages (or other statistics) it wouldn't have been at all obvious that there was any problem.
http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/cordex/output/EUR-11/DMI/MOHC-HadGEM2-ES/historical/r1i1p1/DMI-HIRHAM5/v2/mon/tas/v20190512/tas_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_DMI-HIRHAM5_v2_mon_199101-200012.nc

### PR DESCRIPTION
**Pull request by thomascrocker**
Closes #1141

Add `valid_max` and `valid_min` attributes to longitude entries in CORDEX CMOR tables so that longitude coords are processed correctly by CMOR checker.

One aside, the entries in `CORDEX_grids` had no effect, it was the entries in `CORDEX_mon` that the checker picked up. I'm not sure if this is intended but it was not what I expected.

***

## [Before you get started](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#getting-started)

- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## [Checklist](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#checklist-for-pull-requests)

It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] or [🧪 Scientific][2] review.

[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-review
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-review

- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)
- [ ] [🛠][1] This pull request has a [descriptive title and labels](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-title-and-label)
- [ ] [🛠][1] Code is written according to the [code quality guidelines](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#code-quality)
- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added
- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)
- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date
- [ ] [🛠][1] All [checks below this pull request](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#pull-request-checks) were successful

***

To help with the number pull requests:

- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in this repository

### CODE REVIEW

**Comment by jvegasbsc** [comment]
> One aside, the entries in CORDEX_grids had no effect, it was the entries in CORDEX_mon that the checker picked up. I'm not sure if this is intended but it was not what I expected.

Can you please open an issue detailing this a bit more?

**Review by jvegasbsc — APPROVED** [review]
Looks OK I added a note to the version file so we remember that they are not exactly the referenced commit

**Review by zklaus — CHANGES_REQUESTED** [review]
As discussed in the corresponding issue, #1141, for now I think this is a bad idea. Please don't merge.

**Comment by thomascrocker** [comment]
This PR no longer needed as #245 has fixed.

**Pull request closed without merging**
