### PR TITLE
Fix derived variable ctotal calculation depending on project and standard name

### LINKED ISSUE #617: updated derivation of ctotal for CMIP6 models
**Describe the bug**
The ctotal is derived as the sum of cVeg and cSoil. But, there are differences in definition of these variables in CMIP5 and CMIP6. In order for recipe_carvalhais2014nat.yml to work for CMIP6 models, the derivation needs to be updated.

### PR DESCRIPTION
**Pull request by valeriupredoi**
Before you start, please read [CONTRIBUTING.md](https://github.com/ESMValGroup/ESMValCore/blob/master/CONTRIBUTING.md).

**Tasks**

-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [x] This pull request has a descriptive title that can be used in a changelog
-   [x] Add unit tests
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out why.
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask by commenting.
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
-   [ ] If you make backward incompatible changes to the recipe format, make a new pull request in the [ESMValTool repository](https://github.com/ESMValGroup/ESMValTool) and add the link below

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #617 

**NOTE**: please read [comment](https://github.com/ESMValGroup/ESMValCore/issues/617#issuecomment-616485331) from @koir-su for clarification on why this is needed :beer:

### CODE REVIEW

**Comment by valeriupredoi** [comment]
just fixed the Codacy/Flake issues but now I can't push to remote coz the darn host is not reachable, gitHub sort yer c**p out

**Comment by valeriupredoi** [comment]
hold yer horses, I pushed the code changes to appease the flake gods but they're backlogged somewhere, gitHub is hungover today :beer:

**Comment by valeriupredoi** [comment]
just found this https://github.com/ESMValGroup/ESMValCore/pull/616 - @koir-su please link the issue in the PR next time so we know that it's been resolved in a PR :beer: - up to you to choose which one to go for, this one here has a bit more inclusive test

**Comment by koir-su** [comment]
@valeriupredoi : thanks for the war with the lord today. I thought I had linked the PR with an issue before. Probably, got messed up somewhere.

**Comment by zklaus** [comment]
@koir-su so we're going with this one then? In that case I suggest to close #616 and to make sure that the links between the issue and the pr are up to speed.

**Comment by koir-su** [comment]
@zklaus : Yes. Let's do it that way. I am not confident to do it myself. So, if possible, can you go ahead and close #616 . Thank you.

**Comment by valeriupredoi** [comment]
no worries @koir-su I shall be doing it now :beer:

**Pull request merged**
